exports_files(["__init__.py"])

py_library(
    name = "starkware_utils_time_lib",
    srcs = [
        "fastforward.py",
        "synchronous_executor.py",
        "time.py",
    ],
    visibility = ["//visibility:public"],
)
