#!/usr/bin/env python3

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "../../.."))
from starkware.starknet.compiler.compile import main  # noqa

if __name__ == "__main__":
    sys.exit(main())
