import { Exchange, BaseExchange } from './src/base/Exchange.js';
import PredictionExchange from './src/base/PredictionExchange.js';
import { Precise } from './src/base/Precise.js';
import * as functions from './src/base/functions.js';
import * as errors from './src/base/errors.js';
import type { Int, int, Str, Strings, Num, Bool, IndexType, OrderSide, OrderType, MarketType, SubType, Dict, NullableDict, List, NullableList, Fee, OHLCV, OHLCVC, implicitReturnType, Market, Currency, Dictionary, NestedDictionary, MinMax, FeeInterface, TradingFeeInterface, MarketInterface, Precision, PredictionEvent, PredictionOutcome, PredictionMarket, PredictionSettlement, PredictionFees, PredictionOrder, PredictionTrade, PredictionPosition, PredictionTicker, PredictionOrderBook, PredictionTickers, PredictionTradingFee, PredictionOpenInterest, PredictionOrderRequest, fetchEventsParams, Trade, Order, OrderBook, Ticker, Transaction, Tickers, CurrencyInterface, Balance, BalanceAccount, Account, PartialBalances, Balances, DepositAddress, WithdrawalResponse, FundingRate, FundingRates, Position, BorrowInterest, LeverageTier, LedgerEntry, DepositWithdrawFeeNetwork, DepositWithdrawFee, TransferEntry, CrossBorrowRate, IsolatedBorrowRate, FundingRateHistory, OpenInterest, Liquidation, OrderRequest, CancellationRequest, FundingHistory, MarketMarginModes, MarginMode, Greeks, Conversion, Option, LastPrice, Leverage, MarginModification, Leverages, LastPrices, Currencies, TradingFees, MarginModes, OptionChain, IsolatedBorrowRates, CrossBorrowRates, LeverageTiers, LongShortRatio, OrderBooks, OpenInterests, ConstructorArgs, ADL } from './src/base/types.js';
import { BaseError, ExchangeError, AuthenticationError, PermissionDenied, AccountNotEnabled, AccountSuspended, ArgumentsRequired, BadRequest, BadSymbol, OperationRejected, NoChange, MarginModeAlreadySet, MarketClosed, ManualInteractionNeeded, RestrictedLocation, InsufficientFunds, InvalidAddress, AddressPending, InvalidOrder, OrderNotFound, OrderNotCached, OrderImmediatelyFillable, OrderNotFillable, DuplicateOrderId, ContractUnavailable, NotSupported, InvalidProxySettings, ExchangeClosedByUser, OperationFailed, NetworkError, DDoSProtection, RateLimitExceeded, ExchangeNotAvailable, OnMaintenance, InvalidNonce, ChecksumError, RequestTimeout, BadResponse, NullResponse, CancelPending, UnsubscribeError } from './src/base/errors.js';
declare const version = "4.5.66";
import alpaca from './src/alpaca.js';
import apex from './src/apex.js';
import aster from './src/aster.js';
import backpack from './src/backpack.js';
import bequant from './src/bequant.js';
import bigone from './src/bigone.js';
import binance from './src/binance.js';
import binancecoinm from './src/binancecoinm.js';
import binanceus from './src/binanceus.js';
import binanceusdm from './src/binanceusdm.js';
import bingx from './src/bingx.js';
import bit2c from './src/bit2c.js';
import bitbank from './src/bitbank.js';
import bitbns from './src/bitbns.js';
import bitfinex from './src/bitfinex.js';
import bitflyer from './src/bitflyer.js';
import bitget from './src/bitget.js';
import bithumb from './src/bithumb.js';
import bitmart from './src/bitmart.js';
import bitmex from './src/bitmex.js';
import bitopro from './src/bitopro.js';
import bitrue from './src/bitrue.js';
import bitso from './src/bitso.js';
import bitstamp from './src/bitstamp.js';
import bitteam from './src/bitteam.js';
import bittrade from './src/bittrade.js';
import bitvavo from './src/bitvavo.js';
import blockchaincom from './src/blockchaincom.js';
import blofin from './src/blofin.js';
import btcbox from './src/btcbox.js';
import btcmarkets from './src/btcmarkets.js';
import btcturk from './src/btcturk.js';
import bullish from './src/bullish.js';
import bybit from './src/bybit.js';
import bybiteu from './src/bybiteu.js';
import bydfi from './src/bydfi.js';
import cex from './src/cex.js';
import coinbase from './src/coinbase.js';
import coinbaseexchange from './src/coinbaseexchange.js';
import coinbaseinternational from './src/coinbaseinternational.js';
import coincheck from './src/coincheck.js';
import coinex from './src/coinex.js';
import coinmate from './src/coinmate.js';
import coinone from './src/coinone.js';
import coinsph from './src/coinsph.js';
import coinspot from './src/coinspot.js';
import cryptocom from './src/cryptocom.js';
import cryptomus from './src/cryptomus.js';
import deepcoin from './src/deepcoin.js';
import delta from './src/delta.js';
import deribit from './src/deribit.js';
import derive from './src/derive.js';
import digifinex from './src/digifinex.js';
import dydx from './src/dydx.js';
import exmo from './src/exmo.js';
import extended from './src/extended.js';
import fmfwio from './src/fmfwio.js';
import foxbit from './src/foxbit.js';
import gate from './src/gate.js';
import gateeu from './src/gateeu.js';
import gemini from './src/gemini.js';
import grvt from './src/grvt.js';
import hashkey from './src/hashkey.js';
import hibachi from './src/hibachi.js';
import hitbtc from './src/hitbtc.js';
import hollaex from './src/hollaex.js';
import htx from './src/htx.js';
import hyperliquid from './src/hyperliquid.js';
import independentreserve from './src/independentreserve.js';
import indodax from './src/indodax.js';
import kraken from './src/kraken.js';
import krakenfutures from './src/krakenfutures.js';
import kucoin from './src/kucoin.js';
import kucoineu from './src/kucoineu.js';
import kucoinfutures from './src/kucoinfutures.js';
import latoken from './src/latoken.js';
import lbank from './src/lbank.js';
import lighter from './src/lighter.js';
import luno from './src/luno.js';
import mercado from './src/mercado.js';
import mexc from './src/mexc.js';
import modetrade from './src/modetrade.js';
import mudrex from './src/mudrex.js';
import myokx from './src/myokx.js';
import ndax from './src/ndax.js';
import okx from './src/okx.js';
import okxus from './src/okxus.js';
import onetrading from './src/onetrading.js';
import p2b from './src/p2b.js';
import pacifica from './src/pacifica.js';
import paradex from './src/paradex.js';
import paymium from './src/paymium.js';
import phemex from './src/phemex.js';
import poloniex from './src/poloniex.js';
import tokocrypto from './src/tokocrypto.js';
import toobit from './src/toobit.js';
import upbit from './src/upbit.js';
import weex from './src/weex.js';
import whitebit from './src/whitebit.js';
import woo from './src/woo.js';
import woofipro from './src/woofipro.js';
import xt from './src/xt.js';
import zaif from './src/zaif.js';
import zebpay from './src/zebpay.js';
import alpacaPro from './src/pro/alpaca.js';
import apexPro from './src/pro/apex.js';
import asterPro from './src/pro/aster.js';
import backpackPro from './src/pro/backpack.js';
import bequantPro from './src/pro/bequant.js';
import binancePro from './src/pro/binance.js';
import binancecoinmPro from './src/pro/binancecoinm.js';
import binanceusPro from './src/pro/binanceus.js';
import binanceusdmPro from './src/pro/binanceusdm.js';
import bingxPro from './src/pro/bingx.js';
import bitfinexPro from './src/pro/bitfinex.js';
import bitgetPro from './src/pro/bitget.js';
import bithumbPro from './src/pro/bithumb.js';
import bitmartPro from './src/pro/bitmart.js';
import bitmexPro from './src/pro/bitmex.js';
import bitoproPro from './src/pro/bitopro.js';
import bitruePro from './src/pro/bitrue.js';
import bitstampPro from './src/pro/bitstamp.js';
import bittradePro from './src/pro/bittrade.js';
import bitvavoPro from './src/pro/bitvavo.js';
import blockchaincomPro from './src/pro/blockchaincom.js';
import blofinPro from './src/pro/blofin.js';
import bullishPro from './src/pro/bullish.js';
import bybitPro from './src/pro/bybit.js';
import bybiteuPro from './src/pro/bybiteu.js';
import bydfiPro from './src/pro/bydfi.js';
import cexPro from './src/pro/cex.js';
import coinbasePro from './src/pro/coinbase.js';
import coinbaseexchangePro from './src/pro/coinbaseexchange.js';
import coinbaseinternationalPro from './src/pro/coinbaseinternational.js';
import coincheckPro from './src/pro/coincheck.js';
import coinexPro from './src/pro/coinex.js';
import coinonePro from './src/pro/coinone.js';
import cryptocomPro from './src/pro/cryptocom.js';
import deepcoinPro from './src/pro/deepcoin.js';
import deribitPro from './src/pro/deribit.js';
import derivePro from './src/pro/derive.js';
import dydxPro from './src/pro/dydx.js';
import exmoPro from './src/pro/exmo.js';
import extendedPro from './src/pro/extended.js';
import gatePro from './src/pro/gate.js';
import gateeuPro from './src/pro/gateeu.js';
import geminiPro from './src/pro/gemini.js';
import grvtPro from './src/pro/grvt.js';
import hashkeyPro from './src/pro/hashkey.js';
import hitbtcPro from './src/pro/hitbtc.js';
import hollaexPro from './src/pro/hollaex.js';
import htxPro from './src/pro/htx.js';
import hyperliquidPro from './src/pro/hyperliquid.js';
import independentreservePro from './src/pro/independentreserve.js';
import krakenPro from './src/pro/kraken.js';
import krakenfuturesPro from './src/pro/krakenfutures.js';
import kucoinPro from './src/pro/kucoin.js';
import kucoineuPro from './src/pro/kucoineu.js';
import kucoinfuturesPro from './src/pro/kucoinfutures.js';
import lbankPro from './src/pro/lbank.js';
import lighterPro from './src/pro/lighter.js';
import lunoPro from './src/pro/luno.js';
import mexcPro from './src/pro/mexc.js';
import modetradePro from './src/pro/modetrade.js';
import mudrexPro from './src/pro/mudrex.js';
import myokxPro from './src/pro/myokx.js';
import ndaxPro from './src/pro/ndax.js';
import okxPro from './src/pro/okx.js';
import okxusPro from './src/pro/okxus.js';
import onetradingPro from './src/pro/onetrading.js';
import p2bPro from './src/pro/p2b.js';
import pacificaPro from './src/pro/pacifica.js';
import paradexPro from './src/pro/paradex.js';
import phemexPro from './src/pro/phemex.js';
import poloniexPro from './src/pro/poloniex.js';
import toobitPro from './src/pro/toobit.js';
import upbitPro from './src/pro/upbit.js';
import weexPro from './src/pro/weex.js';
import whitebitPro from './src/pro/whitebit.js';
import wooPro from './src/pro/woo.js';
import woofiproPro from './src/pro/woofipro.js';
import xtPro from './src/pro/xt.js';
import hyperliquidPrediction from './src/prediction/hyperliquid.js';
import kalshiPrediction from './src/prediction/kalshi.js';
import limitlessPrediction from './src/prediction/limitless.js';
import myriadPrediction from './src/prediction/myriad.js';
import polymarketPrediction from './src/prediction/polymarket.js';
declare const exchanges: {
    alpaca: typeof alpaca;
    apex: typeof apex;
    aster: typeof aster;
    backpack: typeof backpack;
    bequant: typeof bequant;
    bigone: typeof bigone;
    binance: typeof binance;
    binancecoinm: typeof binancecoinm;
    binanceus: typeof binanceus;
    binanceusdm: typeof binanceusdm;
    bingx: typeof bingx;
    bit2c: typeof bit2c;
    bitbank: typeof bitbank;
    bitbns: typeof bitbns;
    bitfinex: typeof bitfinex;
    bitflyer: typeof bitflyer;
    bitget: typeof bitget;
    bithumb: typeof bithumb;
    bitmart: typeof bitmart;
    bitmex: typeof bitmex;
    bitopro: typeof bitopro;
    bitrue: typeof bitrue;
    bitso: typeof bitso;
    bitstamp: typeof bitstamp;
    bitteam: typeof bitteam;
    bittrade: typeof bittrade;
    bitvavo: typeof bitvavo;
    blockchaincom: typeof blockchaincom;
    blofin: typeof blofin;
    btcbox: typeof btcbox;
    btcmarkets: typeof btcmarkets;
    btcturk: typeof btcturk;
    bullish: typeof bullish;
    bybit: typeof bybit;
    bybiteu: typeof bybiteu;
    bydfi: typeof bydfi;
    cex: typeof cex;
    coinbase: typeof coinbase;
    coinbaseexchange: typeof coinbaseexchange;
    coinbaseinternational: typeof coinbaseinternational;
    coincheck: typeof coincheck;
    coinex: typeof coinex;
    coinmate: typeof coinmate;
    coinone: typeof coinone;
    coinsph: typeof coinsph;
    coinspot: typeof coinspot;
    cryptocom: typeof cryptocom;
    cryptomus: typeof cryptomus;
    deepcoin: typeof deepcoin;
    delta: typeof delta;
    deribit: typeof deribit;
    derive: typeof derive;
    digifinex: typeof digifinex;
    dydx: typeof dydx;
    exmo: typeof exmo;
    extended: typeof extended;
    fmfwio: typeof fmfwio;
    foxbit: typeof foxbit;
    gate: typeof gate;
    gateeu: typeof gateeu;
    gemini: typeof gemini;
    grvt: typeof grvt;
    hashkey: typeof hashkey;
    hibachi: typeof hibachi;
    hitbtc: typeof hitbtc;
    hollaex: typeof hollaex;
    htx: typeof htx;
    hyperliquid: typeof hyperliquid;
    independentreserve: typeof independentreserve;
    indodax: typeof indodax;
    kraken: typeof kraken;
    krakenfutures: typeof krakenfutures;
    kucoin: typeof kucoin;
    kucoineu: typeof kucoineu;
    kucoinfutures: typeof kucoinfutures;
    latoken: typeof latoken;
    lbank: typeof lbank;
    lighter: typeof lighter;
    luno: typeof luno;
    mercado: typeof mercado;
    mexc: typeof mexc;
    modetrade: typeof modetrade;
    mudrex: typeof mudrex;
    myokx: typeof myokx;
    ndax: typeof ndax;
    okx: typeof okx;
    okxus: typeof okxus;
    onetrading: typeof onetrading;
    p2b: typeof p2b;
    pacifica: typeof pacifica;
    paradex: typeof paradex;
    paymium: typeof paymium;
    phemex: typeof phemex;
    poloniex: typeof poloniex;
    tokocrypto: typeof tokocrypto;
    toobit: typeof toobit;
    upbit: typeof upbit;
    weex: typeof weex;
    whitebit: typeof whitebit;
    woo: typeof woo;
    woofipro: typeof woofipro;
    xt: typeof xt;
    zaif: typeof zaif;
    zebpay: typeof zebpay;
};
declare const pro: {
    alpaca: typeof alpacaPro;
    apex: typeof apexPro;
    aster: typeof asterPro;
    backpack: typeof backpackPro;
    bequant: typeof bequantPro;
    binance: typeof binancePro;
    binancecoinm: typeof binancecoinmPro;
    binanceus: typeof binanceusPro;
    binanceusdm: typeof binanceusdmPro;
    bingx: typeof bingxPro;
    bitfinex: typeof bitfinexPro;
    bitget: typeof bitgetPro;
    bithumb: typeof bithumbPro;
    bitmart: typeof bitmartPro;
    bitmex: typeof bitmexPro;
    bitopro: typeof bitoproPro;
    bitrue: typeof bitruePro;
    bitstamp: typeof bitstampPro;
    bittrade: typeof bittradePro;
    bitvavo: typeof bitvavoPro;
    blockchaincom: typeof blockchaincomPro;
    blofin: typeof blofinPro;
    bullish: typeof bullishPro;
    bybit: typeof bybitPro;
    bybiteu: typeof bybiteuPro;
    bydfi: typeof bydfiPro;
    cex: typeof cexPro;
    coinbase: typeof coinbasePro;
    coinbaseexchange: typeof coinbaseexchangePro;
    coinbaseinternational: typeof coinbaseinternationalPro;
    coincheck: typeof coincheckPro;
    coinex: typeof coinexPro;
    coinone: typeof coinonePro;
    cryptocom: typeof cryptocomPro;
    deepcoin: typeof deepcoinPro;
    deribit: typeof deribitPro;
    derive: typeof derivePro;
    dydx: typeof dydxPro;
    exmo: typeof exmoPro;
    extended: typeof extendedPro;
    gate: typeof gatePro;
    gateeu: typeof gateeuPro;
    gemini: typeof geminiPro;
    grvt: typeof grvtPro;
    hashkey: typeof hashkeyPro;
    hitbtc: typeof hitbtcPro;
    hollaex: typeof hollaexPro;
    htx: typeof htxPro;
    hyperliquid: typeof hyperliquidPro;
    independentreserve: typeof independentreservePro;
    kraken: typeof krakenPro;
    krakenfutures: typeof krakenfuturesPro;
    kucoin: typeof kucoinPro;
    kucoineu: typeof kucoineuPro;
    kucoinfutures: typeof kucoinfuturesPro;
    lbank: typeof lbankPro;
    lighter: typeof lighterPro;
    luno: typeof lunoPro;
    mexc: typeof mexcPro;
    modetrade: typeof modetradePro;
    mudrex: typeof mudrexPro;
    myokx: typeof myokxPro;
    ndax: typeof ndaxPro;
    okx: typeof okxPro;
    okxus: typeof okxusPro;
    onetrading: typeof onetradingPro;
    p2b: typeof p2bPro;
    pacifica: typeof pacificaPro;
    paradex: typeof paradexPro;
    phemex: typeof phemexPro;
    poloniex: typeof poloniexPro;
    toobit: typeof toobitPro;
    upbit: typeof upbitPro;
    weex: typeof weexPro;
    whitebit: typeof whitebitPro;
    woo: typeof wooPro;
    woofipro: typeof woofiproPro;
    xt: typeof xtPro;
};
declare const prediction: {
    hyperliquid: typeof hyperliquidPrediction;
    kalshi: typeof kalshiPrediction;
    limitless: typeof limitlessPrediction;
    myriad: typeof myriadPrediction;
    polymarket: typeof polymarketPrediction;
};
declare const ccxt: {
    version: string;
    Exchange: typeof Exchange;
    BaseExchange: typeof BaseExchange;
    PredictionExchange: typeof PredictionExchange;
    Precise: typeof Precise;
    exchanges: string[];
    pro: {
        alpaca: typeof alpacaPro;
        apex: typeof apexPro;
        aster: typeof asterPro;
        backpack: typeof backpackPro;
        bequant: typeof bequantPro;
        binance: typeof binancePro;
        binancecoinm: typeof binancecoinmPro;
        binanceus: typeof binanceusPro;
        binanceusdm: typeof binanceusdmPro;
        bingx: typeof bingxPro;
        bitfinex: typeof bitfinexPro;
        bitget: typeof bitgetPro;
        bithumb: typeof bithumbPro;
        bitmart: typeof bitmartPro;
        bitmex: typeof bitmexPro;
        bitopro: typeof bitoproPro;
        bitrue: typeof bitruePro;
        bitstamp: typeof bitstampPro;
        bittrade: typeof bittradePro;
        bitvavo: typeof bitvavoPro;
        blockchaincom: typeof blockchaincomPro;
        blofin: typeof blofinPro;
        bullish: typeof bullishPro;
        bybit: typeof bybitPro;
        bybiteu: typeof bybiteuPro;
        bydfi: typeof bydfiPro;
        cex: typeof cexPro;
        coinbase: typeof coinbasePro;
        coinbaseexchange: typeof coinbaseexchangePro;
        coinbaseinternational: typeof coinbaseinternationalPro;
        coincheck: typeof coincheckPro;
        coinex: typeof coinexPro;
        coinone: typeof coinonePro;
        cryptocom: typeof cryptocomPro;
        deepcoin: typeof deepcoinPro;
        deribit: typeof deribitPro;
        derive: typeof derivePro;
        dydx: typeof dydxPro;
        exmo: typeof exmoPro;
        extended: typeof extendedPro;
        gate: typeof gatePro;
        gateeu: typeof gateeuPro;
        gemini: typeof geminiPro;
        grvt: typeof grvtPro;
        hashkey: typeof hashkeyPro;
        hitbtc: typeof hitbtcPro;
        hollaex: typeof hollaexPro;
        htx: typeof htxPro;
        hyperliquid: typeof hyperliquidPro;
        independentreserve: typeof independentreservePro;
        kraken: typeof krakenPro;
        krakenfutures: typeof krakenfuturesPro;
        kucoin: typeof kucoinPro;
        kucoineu: typeof kucoineuPro;
        kucoinfutures: typeof kucoinfuturesPro;
        lbank: typeof lbankPro;
        lighter: typeof lighterPro;
        luno: typeof lunoPro;
        mexc: typeof mexcPro;
        modetrade: typeof modetradePro;
        mudrex: typeof mudrexPro;
        myokx: typeof myokxPro;
        ndax: typeof ndaxPro;
        okx: typeof okxPro;
        okxus: typeof okxusPro;
        onetrading: typeof onetradingPro;
        p2b: typeof p2bPro;
        pacifica: typeof pacificaPro;
        paradex: typeof paradexPro;
        phemex: typeof phemexPro;
        poloniex: typeof poloniexPro;
        toobit: typeof toobitPro;
        upbit: typeof upbitPro;
        weex: typeof weexPro;
        whitebit: typeof whitebitPro;
        woo: typeof wooPro;
        woofipro: typeof woofiproPro;
        xt: typeof xtPro;
    };
    prediction: {
        hyperliquid: typeof hyperliquidPrediction;
        kalshi: typeof kalshiPrediction;
        limitless: typeof limitlessPrediction;
        myriad: typeof myriadPrediction;
        polymarket: typeof polymarketPrediction;
    };
} & {
    alpaca: typeof alpaca;
    apex: typeof apex;
    aster: typeof aster;
    backpack: typeof backpack;
    bequant: typeof bequant;
    bigone: typeof bigone;
    binance: typeof binance;
    binancecoinm: typeof binancecoinm;
    binanceus: typeof binanceus;
    binanceusdm: typeof binanceusdm;
    bingx: typeof bingx;
    bit2c: typeof bit2c;
    bitbank: typeof bitbank;
    bitbns: typeof bitbns;
    bitfinex: typeof bitfinex;
    bitflyer: typeof bitflyer;
    bitget: typeof bitget;
    bithumb: typeof bithumb;
    bitmart: typeof bitmart;
    bitmex: typeof bitmex;
    bitopro: typeof bitopro;
    bitrue: typeof bitrue;
    bitso: typeof bitso;
    bitstamp: typeof bitstamp;
    bitteam: typeof bitteam;
    bittrade: typeof bittrade;
    bitvavo: typeof bitvavo;
    blockchaincom: typeof blockchaincom;
    blofin: typeof blofin;
    btcbox: typeof btcbox;
    btcmarkets: typeof btcmarkets;
    btcturk: typeof btcturk;
    bullish: typeof bullish;
    bybit: typeof bybit;
    bybiteu: typeof bybiteu;
    bydfi: typeof bydfi;
    cex: typeof cex;
    coinbase: typeof coinbase;
    coinbaseexchange: typeof coinbaseexchange;
    coinbaseinternational: typeof coinbaseinternational;
    coincheck: typeof coincheck;
    coinex: typeof coinex;
    coinmate: typeof coinmate;
    coinone: typeof coinone;
    coinsph: typeof coinsph;
    coinspot: typeof coinspot;
    cryptocom: typeof cryptocom;
    cryptomus: typeof cryptomus;
    deepcoin: typeof deepcoin;
    delta: typeof delta;
    deribit: typeof deribit;
    derive: typeof derive;
    digifinex: typeof digifinex;
    dydx: typeof dydx;
    exmo: typeof exmo;
    extended: typeof extended;
    fmfwio: typeof fmfwio;
    foxbit: typeof foxbit;
    gate: typeof gate;
    gateeu: typeof gateeu;
    gemini: typeof gemini;
    grvt: typeof grvt;
    hashkey: typeof hashkey;
    hibachi: typeof hibachi;
    hitbtc: typeof hitbtc;
    hollaex: typeof hollaex;
    htx: typeof htx;
    hyperliquid: typeof hyperliquid;
    independentreserve: typeof independentreserve;
    indodax: typeof indodax;
    kraken: typeof kraken;
    krakenfutures: typeof krakenfutures;
    kucoin: typeof kucoin;
    kucoineu: typeof kucoineu;
    kucoinfutures: typeof kucoinfutures;
    latoken: typeof latoken;
    lbank: typeof lbank;
    lighter: typeof lighter;
    luno: typeof luno;
    mercado: typeof mercado;
    mexc: typeof mexc;
    modetrade: typeof modetrade;
    mudrex: typeof mudrex;
    myokx: typeof myokx;
    ndax: typeof ndax;
    okx: typeof okx;
    okxus: typeof okxus;
    onetrading: typeof onetrading;
    p2b: typeof p2b;
    pacifica: typeof pacifica;
    paradex: typeof paradex;
    paymium: typeof paymium;
    phemex: typeof phemex;
    poloniex: typeof poloniex;
    tokocrypto: typeof tokocrypto;
    toobit: typeof toobit;
    upbit: typeof upbit;
    weex: typeof weex;
    whitebit: typeof whitebit;
    woo: typeof woo;
    woofipro: typeof woofipro;
    xt: typeof xt;
    zaif: typeof zaif;
    zebpay: typeof zebpay;
} & typeof functions & typeof errors;
export { version, Exchange, BaseExchange, PredictionExchange, exchanges, pro, prediction, Precise, functions, errors, BaseError, ExchangeError, AuthenticationError, PermissionDenied, AccountNotEnabled, AccountSuspended, ArgumentsRequired, BadRequest, BadSymbol, OperationRejected, NoChange, MarginModeAlreadySet, MarketClosed, ManualInteractionNeeded, RestrictedLocation, InsufficientFunds, InvalidAddress, AddressPending, InvalidOrder, OrderNotFound, OrderNotCached, OrderImmediatelyFillable, OrderNotFillable, DuplicateOrderId, ContractUnavailable, NotSupported, InvalidProxySettings, ExchangeClosedByUser, OperationFailed, NetworkError, DDoSProtection, RateLimitExceeded, ExchangeNotAvailable, OnMaintenance, InvalidNonce, ChecksumError, RequestTimeout, BadResponse, NullResponse, CancelPending, UnsubscribeError, Int, int, Str, Strings, Num, Bool, IndexType, OrderSide, OrderType, MarketType, SubType, Dict, NullableDict, List, NullableList, Fee, OHLCV, OHLCVC, implicitReturnType, Market, Currency, ConstructorArgs, Dictionary, NestedDictionary, MinMax, FeeInterface, TradingFeeInterface, MarketMarginModes, Precision, MarketInterface, PredictionFees, PredictionEvent, PredictionMarket, PredictionOutcome, PredictionOrder, PredictionTrade, PredictionPosition, PredictionTicker, PredictionOrderBook, PredictionTickers, PredictionTradingFee, PredictionOpenInterest, PredictionSettlement, fetchEventsParams, Trade, Order, OrderBook, OrderBooks, Ticker, Transaction, Tickers, CurrencyInterface, Balance, BalanceAccount, Account, PartialBalances, Balances, DepositAddress, WithdrawalResponse, FundingRate, FundingRates, Position, BorrowInterest, LeverageTier, LedgerEntry, DepositWithdrawFeeNetwork, DepositWithdrawFee, TransferEntry, CrossBorrowRate, IsolatedBorrowRate, FundingRateHistory, OpenInterest, OpenInterests, Liquidation, OrderRequest, PredictionOrderRequest, CancellationRequest, FundingHistory, MarginMode, Greeks, Conversion, Option, LastPrice, Leverage, LongShortRatio, ADL, MarginModification, Leverages, LastPrices, Currencies, TradingFees, MarginModes, OptionChain, IsolatedBorrowRates, CrossBorrowRates, LeverageTiers, alpaca, apex, aster, backpack, bequant, bigone, binance, binancecoinm, binanceus, binanceusdm, bingx, bit2c, bitbank, bitbns, bitfinex, bitflyer, bitget, bithumb, bitmart, bitmex, bitopro, bitrue, bitso, bitstamp, bitteam, bittrade, bitvavo, blockchaincom, blofin, btcbox, btcmarkets, btcturk, bullish, bybit, bybiteu, bydfi, cex, coinbase, coinbaseexchange, coinbaseinternational, coincheck, coinex, coinmate, coinone, coinsph, coinspot, cryptocom, cryptomus, deepcoin, delta, deribit, derive, digifinex, dydx, exmo, extended, fmfwio, foxbit, gate, gateeu, gemini, grvt, hashkey, hibachi, hitbtc, hollaex, htx, hyperliquid, independentreserve, indodax, kraken, krakenfutures, kucoin, kucoineu, kucoinfutures, latoken, lbank, lighter, luno, mercado, mexc, modetrade, mudrex, myokx, ndax, okx, okxus, onetrading, p2b, pacifica, paradex, paymium, phemex, poloniex, tokocrypto, toobit, upbit, weex, whitebit, woo, woofipro, xt, zaif, zebpay, };
export default ccxt;
