package io.github.ccxt;

import java.util.List;

public final class MetaData {
    // metadata info
    // rest only
    public static final List<String> Exchanges = new java.util.ArrayList<String>(java.util.Arrays.asList("aftermath", "alpaca", "apex", "aster", "backpack", "bequant", "bigone", "binance", "binancecoinm", "binanceus", "binanceusdm", "bingx", "bit2c", "bitbank", "bitbns", "bitfinex", "bitflyer", "bitget", "bithumb", "bitmart", "bitmex", "bitopro", "bitrue", "bitso", "bitstamp", "bitteam", "bittrade", "bitvavo", "blockchaincom", "blofin", "btcbox", "btcmarkets", "btcturk", "bullish", "bybit", "bybiteu", "bydfi", "cex", "coinbase", "coinbaseexchange", "coinbaseinternational", "coincheck", "coinex", "coinmate", "coinone", "coinsph", "coinspot", "cryptocom", "cryptomus", "deepcoin", "delta", "deribit", "derive", "digifinex", "dydx", "exmo", "extended", "fmfwio", "foxbit", "gate", "gateeu", "gemini", "grvt", "hashkey", "hibachi", "hitbtc", "hollaex", "htx", "hyperliquid", "independentreserve", "indodax", "kraken", "krakenfutures", "kucoin", "kucoineu", "kucoinfutures", "latoken", "lbank", "lighter", "luno", "mercado", "mexc", "modetrade", "mudrex", "myokx", "ndax", "okx", "okxus", "onetrading", "p2b", "pacifica", "paradex", "paymium", "phemex", "poloniex", "rubin", "tokocrypto", "toobit", "upbit", "weex", "whitebit", "woo", "woofipro", "xt", "zaif", "zebpay"));
    // ws/pro exchanges
    public static final List<String> ProExchanges = new java.util.ArrayList<String>(java.util.Arrays.asList("aftermath", "alpaca", "apex", "aster", "backpack", "bequant", "binance", "binancecoinm", "binanceus", "binanceusdm", "bingx", "bitfinex", "bitget", "bithumb", "bitmart", "bitmex", "bitopro", "bitrue", "bitstamp", "bittrade", "bitvavo", "blockchaincom", "blofin", "bullish", "bybit", "bybiteu", "bydfi", "cex", "coinbase", "coinbaseexchange", "coinbaseinternational", "coincheck", "coinex", "coinone", "cryptocom", "deepcoin", "deribit", "derive", "dydx", "exmo", "extended", "gate", "gateeu", "gemini", "grvt", "hashkey", "hitbtc", "hollaex", "htx", "hyperliquid", "independentreserve", "kraken", "krakenfutures", "kucoin", "kucoineu", "kucoinfutures", "lbank", "lighter", "luno", "mexc", "modetrade", "mudrex", "myokx", "ndax", "okx", "okxus", "onetrading", "p2b", "pacifica", "paradex", "phemex", "poloniex", "rubin", "toobit", "upbit", "weex", "whitebit", "woo", "woofipro", "xt"));
}
