#!/usr/bin/env bash
set -e
echo "APPVEYOR_REPO_BRANCH"
echo $APPVEYOR_REPO_BRANCH

echo "APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH"
echo $APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH

echo "APPVEYOR_PULL_REQUEST_NUMBER"
echo $APPVEYOR_PULL_REQUEST_NUMBER
