#!/bin/sh
echo "Converting .md → .rst..."
pandoc --wrap=preserve --columns=10000 --from=markdown --to=rst --output=python/README.rst README.md
pandoc --wrap=preserve --columns=10000 --from=markdown --to=rst --output=doc/README.rst README.md
pandoc --wrap=preserve --columns=10000 --from=markdown --to=rst --output=doc/FAQ.rst wiki/FAQ.md
pandoc --wrap=preserve --columns=10000 --from=markdown --to=rst --output=doc/manual.rst wiki/Manual.md
pandoc --wrap=preserve --columns=10000 --from=markdown --to=rst --output=doc/install.rst wiki/Install.md
pandoc --wrap=preserve --columns=10000 --from=markdown --to=rst --output=doc/exchanges.rst wiki/Exchange-Markets.md
pandoc --wrap=preserve --columns=10000 --from=markdown --to=rst --output=doc/exchanges-by-country.rst wiki/Exchange-Markets-By-Country.md
echo "Successfully converted .md → .rst"