FROM node:latest

ENV NODE_OPTIONS=--max-old-space-size=3072

RUN apt-get update && apt-get install -y pandoc python-pip python3-pip php
RUN pip install tox requests web3==2.7.0
RUN pip3 install requests aiohttp web3
RUN npm install web3 ethereumjs-util ethereumjs-abi bignumber.js --no-save
RUN apt-get install -y php-curl php-iconv php-mbstring php-bcmath

RUN mkdir -p /app
WORKDIR /app
ADD . /app