import js from '@eslint/js';
import tsParser from '@typescript-eslint/parser';
import tsPlugin from '@typescript-eslint/eslint-plugin';
import jsdocPlugin from 'eslint-plugin-jsdoc';
import unusedImportsPlugin from 'eslint-plugin-unused-imports';
import importPlugin from 'eslint-plugin-import';
import globals from 'globals';

const sharedPlugins = {
    '@typescript-eslint': tsPlugin,
    'unused-imports': unusedImportsPlugin,
    'jsdoc': jsdocPlugin,
    'import': importPlugin,
};

const sharedSettings = {
    'import/resolver': {
        node: {
            extensions: ['.js', '.ts'],
        },
    },
    'import/parsers': {
        '@typescript-eslint/parser': ['.ts', '.js'],
    },
    'jsdoc': {
        tagNamePreference: {
            'function': 'method',
        },
    },
};

const sharedLanguageOptions = {
    parser: tsParser,
    ecmaVersion: 2020,
    sourceType: 'module',
    globals: {
        ...globals.node,
        ...globals.es2021,
        WebAssembly: 'readonly',
    },
};

const mainRules = {
    'unused-imports/no-unused-imports': 'error',
    'no-spaced-func': 'off',
    'import/no-unresolved': 'off',
    'import/named': 'off',
    'strict': 'off',
    'semi': 'error',
    'indent': ['error', 4],
    'init-declarations': 'off',
    'no-undef-init': 'off',
    'comma-dangle': ['error', {
        'arrays': 'always-multiline',
        'objects': 'always-multiline',
        'imports': 'always-multiline',
        'exports': 'always-multiline',
        'functions': 'never',
    }],
    'import/extensions': 'off',
    'brace-style': ['error', '1tbs'],
    'multiline-comment-style': ['error', 'separate-lines'],
    'dot-notation': 'off',
    'quote-props': ['error', 'always'],
    'no-multi-spaces': ['error', { 'ignoreEOLComments': true }],
    'no-whitespace-before-property': 'error',
    'space-before-blocks': ['error', 'always'],
    'space-before-function-paren': ['error', 'always'],
    'func-call-spacing': ['error', 'always'],
    'block-spacing': ['error', 'always'],
    'keyword-spacing': ['error', { 'before': true, 'after': true }],
    'object-curly-spacing': ['error', 'always', { 'objectsInObjects': false }],
    'object-curly-newline': ['error', { 'consistent': true }],
    'space-infix-ops': 'error',
    'space-unary-ops': 'error',
    'space-in-parens': 'error',
    'no-nested-ternary': 'error',
    'eqeqeq': 'error',
    'quotes': ['error', 'single', { 'avoidEscape': true }],
    'no-unused-vars': ['error', { 'argsIgnorePattern': '^(exchange|headers|body|account|info|symbol|price|tag|side|since|name|limit|params|market|timeframe|api|path|code|currency|statusCode|statusText|url|method|response|requestHeaders|requestBody|bidsKey|asksKey|context|config|type|priceKey|amountKey|networkCode|marginMode|subscription|message|client|nonce|orderbook|bookside|deltas|delta|countOrIdKey|amount|fromCurrency|toCurrency|rawCurrency|error|reject|queries|outcome|outcomes|dictionaryOrList|defaultValue|keys|key1|key2|key|allowEmpty|sameTypeOnly|sameSubTypeOnly)', 'caughtErrors': 'none' }],
    'new-parens': 'error',
    'new-cap': ['error', {
        'capIsNewExceptionPattern': '^Future$|^globalThis\\.',
    }],
    'no-var': 'error',
    'prefer-const': ['error', {
        'destructuring': 'any',
        'ignoreReadBeforeAssign': false,
    }],
    'no-warning-comments': ['warn', { 'terms': ['fixme'] }],
    'padded-blocks': ['error', 'never'],
    'lines-between-class-members': ['error', 'always', { 'exceptAfterSingleLine': true }],
    'no-multiple-empty-lines': ['error', { 'max': 1 }],
    'padding-line-between-statements': ['error',
        { 'blankLine': 'never', 'prev': '*', 'next': '*' },
        { 'blankLine': 'always', 'prev': 'import', 'next': '*' },
        { 'blankLine': 'never', 'prev': 'import', 'next': 'import' },
        { 'blankLine': 'always', 'prev': 'directive', 'next': '*' },
        { 'blankLine': 'always', 'prev': '*', 'next': 'cjs-export' },
        { 'blankLine': 'always', 'prev': '*', 'next': 'export' },
        { 'blankLine': 'any', 'prev': 'export', 'next': 'export' },
        { 'blankLine': 'always', 'prev': '*', 'next': 'function' },
    ],
    'prefer-template': 'off',
    'curly': 'error',
    'no-plusplus': 'off',
    'no-restricted-properties': 'off',
    'prefer-destructuring': 'off',
    'class-methods-use-this': 'off',
    'no-param-reassign': 'off',
    'max-len': 'off',
    'no-return-await': 'off',
    'array-bracket-spacing': ['error', 'always'],
    'radix': 'off',
    'camelcase': 'off',
    'no-lonely-if': 'off',
    'no-mixed-operators': 'off',
    'jsdoc/no-types': 'off',
    'no-shadow': ['error', {
        'builtinGlobals': true,
        'hoist': 'all',
        'allow': [],
        'ignoreOnInitialization': false,
    }],
    'no-useless-concat': 'off',
    'no-continue': 'off',
    'no-else-return': 'off',
    'no-unneeded-ternary': 'off',
    'operator-assignment': 'off',
    'no-underscore-dangle': 'off',
    'consistent-return': 'off',
    'no-await-in-loop': 'off',
    'prefer-exponentiation-operator': 'off',
    'jsdoc/check-tag-names': ['error', {
        'definedTags': ['method', 'remarks'],
    }],
    'jsdoc/require-param-description': 'off',
    'jsdoc/reject-any-type': 'off',
    'jsdoc/require-throws-type': 'off',
};

const mainRulesWithoutJsdoc = Object.fromEntries(
    Object.entries(mainRules).filter(([key]) => !key.startsWith('jsdoc/')),
);

const testRules = {
    'semi': ['error', 'always'],
    'no-unused-vars': 'off',
    'quotes': 'off',
    'func-call-spacing': ['error', 'always'],
    'one-var': 'off',
    'indent': ['error', 4],
    'comma-style': 'off',
    'no-multi-spaces': 'off',
    'comma-dangle': 'off',
    'spaced-comment': 'off',
    'camelcase': 'off',
    'padded-blocks': 'off',
    'multiline-comment-style': 'off',
    'curly': 'off',
    'rest-spread-spacing': 'off',
    'no-multiple-empty-lines': 'off',
    'no-undef-init': 'off',
    'no-useless-return': 'off',
    'no-console': 'off',
    'operator-linebreak': 'off',
    'key-spacing': 'off',
    'brace-style': 'off',
    'no-path-concat': 'off',
    'no-use-before-define': 'off',
    'new-cap': 'off',
    'max-classes-per-file': ['error', 2],
    'lines-between-class-members': 'off',
    'padding-line-between-statements': 'off',
    'import/no-extraneous-dependencies': ['error', { 'devDependencies': true }],
    'jsdoc/require-jsdoc': 'off',
    'no-shadow': ['error', {
        'builtinGlobals': true,
        'hoist': 'all',
        'allow': [],
        'ignoreOnInitialization': false,
    }],
};

const wsRules = {
    'semi': 'off',
    'no-unused-vars': 'off',
    'quotes': 'off',
    'quote-props': 'off',
    'func-call-spacing': ['error', 'always'],
    'one-var': 'off',
    'indent': ['warn', 4, { 'ignoredNodes': ['ObjectPattern'] }],
    'comma-style': 'off',
    'no-multi-spaces': 'off',
    'comma-dangle': 'off',
    'spaced-comment': 'off',
    'camelcase': 'off',
    'padded-blocks': 'off',
    'multiline-comment-style': 'off',
    'curly': 'off',
    'rest-spread-spacing': 'off',
    'no-multiple-empty-lines': 'off',
    'no-undef-init': 'off',
    'no-useless-return': 'off',
    'no-console': 'off',
    'operator-linebreak': 'off',
    'key-spacing': 'off',
    'brace-style': 'off',
    'padding-line-between-statements': 'off',
};

const mainSourceFiles = [
    'ts/src/*.ts',
    'ts/src/base/**/*.ts',
    'ts/src/pro/*.ts',
    'ts/src/prediction/*.ts',
];
const mainSourceIgnores = [
    'ts/src/base/functions/**',
    'ts/src/static_dependencies/**',
    'ts/src/pro/bridge/**',
    'ts/src/abstract/**',
    'ts/src/base/ws/**',
];

export default [
    {
        ignores: [
            'build/**',
            'docs/playground/**',
        ],
    },
    {
        ...js.configs.recommended,
        ignores: ['ts/src/base/ws/**'],
    },
    {
        ...jsdocPlugin.configs['flat/recommended-typescript-error'],
        files: mainSourceFiles,
        ignores: mainSourceIgnores,
    },
    {
        files: mainSourceFiles,
        ignores: mainSourceIgnores,
        languageOptions: sharedLanguageOptions,
        plugins: sharedPlugins,
        settings: sharedSettings,
        rules: mainRules,
    },
    {
        files: ['ts/src/test/**/*.ts'],
        languageOptions: sharedLanguageOptions,
        plugins: sharedPlugins,
        settings: sharedSettings,
        rules: testRules,
    },
    {
        files: ['ts/src/pro/test/**/*.ts'],
        languageOptions: sharedLanguageOptions,
        plugins: sharedPlugins,
        settings: sharedSettings,
        rules: testRules,
    },
    {
        files: ['ts/src/base/ws/**/*.ts'],
        languageOptions: {
            parser: tsParser,
            ecmaVersion: 2017,
            sourceType: 'script',
            globals: {
                ...globals.node,
                ...globals.es6,
                ...globals.browser,
            },
        },
        plugins: sharedPlugins,
        settings: sharedSettings,
        rules: wsRules,
    },
    {
        files: ['cli/ts/**/*.ts'],
        languageOptions: sharedLanguageOptions,
        plugins: sharedPlugins,
        settings: sharedSettings,
        rules: {
            ...mainRulesWithoutJsdoc,
            'no-use-before-define': 'off',
            'lines-between-class-members': 'error',
            'padding-line-between-statements': ['error',
                { 'blankLine': 'always', 'prev': 'import', 'next': '*' },
                { 'blankLine': 'never', 'prev': 'import', 'next': 'import' },
                { 'blankLine': 'always', 'prev': 'directive', 'next': '*' },
                { 'blankLine': 'always', 'prev': '*', 'next': 'cjs-export' },
                { 'blankLine': 'always', 'prev': '*', 'next': 'export' },
                { 'blankLine': 'any', 'prev': 'export', 'next': 'export' },
                { 'blankLine': 'always', 'prev': '*', 'next': 'function' },
            ],
        },
    },
    {
        files: ['examples/ts/**/*.ts'],
        languageOptions: sharedLanguageOptions,
        plugins: sharedPlugins,
        settings: sharedSettings,
        rules: {
            ...mainRulesWithoutJsdoc,
            'no-console': 'off',
            'import/no-named-as-default-member': 'off',
            'init-declarations': 'error',
            'new-cap': 'off',
            'no-multiple-empty-lines': ['error', { 'max': 2 }],
            'no-shadow': 'off',
            'no-use-before-define': ['error', {
                'functions': false,
                'classes': true,
                'variables': true,
                'allowNamedExports': false,
            }],
            'padding-line-between-statements': ['warn',
                { 'blankLine': 'always', 'prev': 'directive', 'next': '*' },
                { 'blankLine': 'always', 'prev': '*', 'next': 'cjs-export' },
                { 'blankLine': 'always', 'prev': '*', 'next': 'export' },
                { 'blankLine': 'always', 'prev': '*', 'next': 'function' },
            ],
        },
    },
];
