#!/bin/sh

text_align_center() {
    columns=80
    printf "%*s\n" $(((${#1} + $columns) / 2)) "$1"
}

echo ""
text_align_center "---------------------------------------------------"
echo ""
text_align_center "Alternatively, you can contribute in crypto directly:"
echo ""
text_align_center "ETH 0xa7c2b18b7c8b86984560cad3b1bc3224b388ded0"
text_align_center "BTC 33RmVRfhK2WZVQR1R83h2e9yXoqRNDvJva        "
text_align_center "BCH 1GN9p233TvNcNQFthCgfiHUnj5JRKEc2Ze        "
text_align_center "LTC LbT8mkAqQBphc4yxLXEDgYDfEax74et3bP        "
echo ""
text_align_center "---------------------------------------------------"
echo ""
text_align_center "Thank you!"
echo ""
