'use strict';

console.log ('                                                                 ')
console.log ('              ---------------------------------------------------')
console.log ('                                                                 ')
console.log ('                     You can contribute in crypto directly:      ')
console.log ('                                                                 ')
console.log ('                 ETH 0xa7c2b18b7c8b86984560cad3b1bc3224b388ded0  ')
console.log ('                 BTC 33RmVRfhK2WZVQR1R83h2e9yXoqRNDvJva          ')
console.log ('                 BCH 1GN9p233TvNcNQFthCgfiHUnj5JRKEc2Ze          ')
console.log ('                 LTC LbT8mkAqQBphc4yxLXEDgYDfEax74et3bP          ')
console.log ('                                                                 ')
console.log ('              ---------------------------------------------------')
console.log ('                                                                 ')
console.log ('                                   Thank you!                    ')
console.log ('                                                                 ')