/**
 * Auto-generated by SBE (Simple Binary Encoding)
 * Schema: com.okx.sbe
 * DO NOT EDIT
 */

export interface Asks {
  pxMantissa: bigint;
  szMantissa: bigint;
  ordCount: number;
}

export interface Bids {
  pxMantissa: bigint;
  szMantissa: bigint;
  ordCount: number;
}

export interface BooksL2TbtChannelEvent {
  instIdCode: bigint;
  tsUs: bigint;
  outTime: bigint;
  seqId: bigint;
  prevSeqId: bigint;
  pxExponent: number;
  szExponent: number;
  asks: Asks[];
  bids: Bids[];
}

export class BooksL2TbtChannelEventDecoder {
  private static readonly BLOCK_LENGTH = 42;
  private static readonly TEMPLATE_ID = 1001;
  private static readonly SCHEMA_ID = 1;
  private static readonly SCHEMA_VERSION = 0;

  private readonly littleEndian: boolean;

  constructor(byteOrder: 'little' | 'big' = 'little') {
    this.littleEndian = byteOrder === 'little';
  }

  decode(buffer: ArrayBuffer, offset: number = 0): BooksL2TbtChannelEvent {
    const view = new DataView(buffer);
    let pos = offset;

    const instIdCode = view.getBigInt64(pos, this.littleEndian);
    pos += 8;

    const tsUs = view.getBigInt64(pos, this.littleEndian);
    pos += 8;

    const outTime = view.getBigInt64(pos, this.littleEndian);
    pos += 8;

    const seqId = view.getBigInt64(pos, this.littleEndian);
    pos += 8;

    const prevSeqId = view.getBigInt64(pos, this.littleEndian);
    pos += 8;

    const pxExponent = view.getInt8(pos);
    pos += 1;

    const szExponent = view.getInt8(pos);
    pos += 1;

    // Skip to end of block for forward compatibility
    pos = offset + BooksL2TbtChannelEventDecoder.BLOCK_LENGTH;

    const asks = this.decodeAsksGroup(view, pos);
    pos = asks.nextOffset;

    const bids = this.decodeBidsGroup(view, pos);
    pos = bids.nextOffset;

    return {
      instIdCode: instIdCode,
      tsUs: tsUs,
      outTime: outTime,
      seqId: seqId,
      prevSeqId: prevSeqId,
      pxExponent: pxExponent,
      szExponent: szExponent,
      asks: asks.items,
      bids: bids.items
    };
  }
  private decodeAsksGroup(view: DataView, offset: number): { items: Asks[], nextOffset: number } {
    let pos = offset;

    const blockLength = view.getUint16(pos, this.littleEndian);
    pos += 2;
    const numInGroup = view.getUint16(pos, this.littleEndian);
    pos += 2;

    const items: Asks[] = [];

    for (let i = 0; i < numInGroup; i++) {
      const itemStart = pos;

      const pxMantissa = view.getBigInt64(pos, this.littleEndian);
      pos += 8;

      const szMantissa = view.getBigInt64(pos, this.littleEndian);
      pos += 8;

      const ordCount = view.getInt32(pos, this.littleEndian);
      pos += 4;

      // Skip to next block for forward compatibility
      pos = itemStart + blockLength;

      items.push({
        pxMantissa: pxMantissa,
        szMantissa: szMantissa,
        ordCount: ordCount
      });
    }

    return { items, nextOffset: pos };
  }
  private decodeBidsGroup(view: DataView, offset: number): { items: Bids[], nextOffset: number } {
    let pos = offset;

    const blockLength = view.getUint16(pos, this.littleEndian);
    pos += 2;
    const numInGroup = view.getUint16(pos, this.littleEndian);
    pos += 2;

    const items: Bids[] = [];

    for (let i = 0; i < numInGroup; i++) {
      const itemStart = pos;

      const pxMantissa = view.getBigInt64(pos, this.littleEndian);
      pos += 8;

      const szMantissa = view.getBigInt64(pos, this.littleEndian);
      pos += 8;

      const ordCount = view.getInt32(pos, this.littleEndian);
      pos += 4;

      // Skip to next block for forward compatibility
      pos = itemStart + blockLength;

      items.push({
        pxMantissa: pxMantissa,
        szMantissa: szMantissa,
        ordCount: ordCount
      });
    }

    return { items, nextOffset: pos };
  }

  static getBlockLength(): number {
    return BooksL2TbtChannelEventDecoder.BLOCK_LENGTH;
  }

  static getTemplateId(): number {
    return BooksL2TbtChannelEventDecoder.TEMPLATE_ID;
  }

  static getSchemaId(): number {
    return BooksL2TbtChannelEventDecoder.SCHEMA_ID;
  }

  static getSchemaVersion(): number {
    return BooksL2TbtChannelEventDecoder.SCHEMA_VERSION;
  }
}
