// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package io.github.ccxt.api;
import io.github.ccxt.Exchange;

public class BitoproApi extends Exchange
{

    public BitoproApi () {
        super();
    }

    public BitoproApi (Object options) {
        super(options);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetOrderBookPair (Object... optionalArgs)
    {
        return this.callAsync ("publicGetOrderBookPair", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetTickers (Object... optionalArgs)
    {
        return this.callAsync ("publicGetTickers", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetTickersPair (Object... optionalArgs)
    {
        return this.callAsync ("publicGetTickersPair", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetTradesPair (Object... optionalArgs)
    {
        return this.callAsync ("publicGetTradesPair", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetProvisioningCurrencies (Object... optionalArgs)
    {
        return this.callAsync ("publicGetProvisioningCurrencies", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetProvisioningTradingPairs (Object... optionalArgs)
    {
        return this.callAsync ("publicGetProvisioningTradingPairs", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetProvisioningLimitationsAndFees (Object... optionalArgs)
    {
        return this.callAsync ("publicGetProvisioningLimitationsAndFees", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetTradingHistoryPair (Object... optionalArgs)
    {
        return this.callAsync ("publicGetTradingHistoryPair", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetPriceOtcCurrency (Object... optionalArgs)
    {
        return this.callAsync ("publicGetPriceOtcCurrency", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetAccountsBalance (Object... optionalArgs)
    {
        return this.callAsync ("privateGetAccountsBalance", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetOrdersHistory (Object... optionalArgs)
    {
        return this.callAsync ("privateGetOrdersHistory", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetOrdersAllPair (Object... optionalArgs)
    {
        return this.callAsync ("privateGetOrdersAllPair", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetOrdersTradesPair (Object... optionalArgs)
    {
        return this.callAsync ("privateGetOrdersTradesPair", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetOrdersPairOrderId (Object... optionalArgs)
    {
        return this.callAsync ("privateGetOrdersPairOrderId", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetWalletWithdrawCurrencySerial (Object... optionalArgs)
    {
        return this.callAsync ("privateGetWalletWithdrawCurrencySerial", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetWalletWithdrawCurrencyIdId (Object... optionalArgs)
    {
        return this.callAsync ("privateGetWalletWithdrawCurrencyIdId", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetWalletDepositHistoryCurrency (Object... optionalArgs)
    {
        return this.callAsync ("privateGetWalletDepositHistoryCurrency", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetWalletWithdrawHistoryCurrency (Object... optionalArgs)
    {
        return this.callAsync ("privateGetWalletWithdrawHistoryCurrency", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetOrdersOpen (Object... optionalArgs)
    {
        return this.callAsync ("privateGetOrdersOpen", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privatePostOrdersPair (Object... optionalArgs)
    {
        return this.callAsync ("privatePostOrdersPair", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privatePostOrdersBatch (Object... optionalArgs)
    {
        return this.callAsync ("privatePostOrdersBatch", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privatePostWalletWithdrawCurrency (Object... optionalArgs)
    {
        return this.callAsync ("privatePostWalletWithdrawCurrency", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privatePutOrders (Object... optionalArgs)
    {
        return this.callAsync ("privatePutOrders", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateDeleteOrdersPairId (Object... optionalArgs)
    {
        return this.callAsync ("privateDeleteOrdersPairId", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateDeleteOrdersAll (Object... optionalArgs)
    {
        return this.callAsync ("privateDeleteOrdersAll", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateDeleteOrdersPair (Object... optionalArgs)
    {
        return this.callAsync ("privateDeleteOrdersPair", optionalArgs);
    }

}