// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package io.github.ccxt.api;
import io.github.ccxt.Exchange;

public class ZaifApi extends Exchange
{

    public ZaifApi () {
        super();
    }

    public ZaifApi (Object options) {
        super(options);
    }

    /**
     * Calls the publicGetDepthPair endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public java.util.concurrent.CompletableFuture<java.util.Map<String, Object>>  publicGetDepthPair (Object... optionalArgs)
    {
        return this.callAsync ("publicGetDepthPair", optionalArgs);
    }

    /**
     * Calls the publicGetCurrenciesPair endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON array
     */
    public java.util.concurrent.CompletableFuture<java.util.List<Object>>  publicGetCurrenciesPair (Object... optionalArgs)
    {
        return this.callAsync ("publicGetCurrenciesPair", optionalArgs);
    }

    /**
     * Calls the publicGetCurrenciesAll endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON array
     */
    public java.util.concurrent.CompletableFuture<java.util.List<Object>>  publicGetCurrenciesAll (Object... optionalArgs)
    {
        return this.callAsync ("publicGetCurrenciesAll", optionalArgs);
    }

    /**
     * Calls the publicGetCurrencyPairsPair endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON array
     */
    public java.util.concurrent.CompletableFuture<java.util.List<Object>>  publicGetCurrencyPairsPair (Object... optionalArgs)
    {
        return this.callAsync ("publicGetCurrencyPairsPair", optionalArgs);
    }

    /**
     * Calls the publicGetCurrencyPairsAll endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON array
     */
    public java.util.concurrent.CompletableFuture<java.util.List<Object>>  publicGetCurrencyPairsAll (Object... optionalArgs)
    {
        return this.callAsync ("publicGetCurrencyPairsAll", optionalArgs);
    }

    /**
     * Calls the publicGetLastPricePair endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public java.util.concurrent.CompletableFuture<java.util.Map<String, Object>>  publicGetLastPricePair (Object... optionalArgs)
    {
        return this.callAsync ("publicGetLastPricePair", optionalArgs);
    }

    /**
     * Calls the publicGetTickerPair endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public java.util.concurrent.CompletableFuture<java.util.Map<String, Object>>  publicGetTickerPair (Object... optionalArgs)
    {
        return this.callAsync ("publicGetTickerPair", optionalArgs);
    }

    /**
     * Calls the publicGetTradesPair endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON array
     */
    public java.util.concurrent.CompletableFuture<java.util.List<Object>>  publicGetTradesPair (Object... optionalArgs)
    {
        return this.callAsync ("publicGetTradesPair", optionalArgs);
    }

    /**
     * Calls the privatePostActiveOrders endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public java.util.concurrent.CompletableFuture<java.util.Map<String, Object>>  privatePostActiveOrders (Object... optionalArgs)
    {
        return this.callAsync ("privatePostActiveOrders", optionalArgs);
    }

    /**
     * Calls the privatePostCancelOrder endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public java.util.concurrent.CompletableFuture<java.util.Map<String, Object>>  privatePostCancelOrder (Object... optionalArgs)
    {
        return this.callAsync ("privatePostCancelOrder", optionalArgs);
    }

    /**
     * Calls the privatePostDepositHistory endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public java.util.concurrent.CompletableFuture<java.util.Map<String, Object>>  privatePostDepositHistory (Object... optionalArgs)
    {
        return this.callAsync ("privatePostDepositHistory", optionalArgs);
    }

    /**
     * Calls the privatePostGetIdInfo endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public java.util.concurrent.CompletableFuture<java.util.Map<String, Object>>  privatePostGetIdInfo (Object... optionalArgs)
    {
        return this.callAsync ("privatePostGetIdInfo", optionalArgs);
    }

    /**
     * Calls the privatePostGetInfo endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public java.util.concurrent.CompletableFuture<java.util.Map<String, Object>>  privatePostGetInfo (Object... optionalArgs)
    {
        return this.callAsync ("privatePostGetInfo", optionalArgs);
    }

    /**
     * Calls the privatePostGetInfo2 endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public java.util.concurrent.CompletableFuture<java.util.Map<String, Object>>  privatePostGetInfo2 (Object... optionalArgs)
    {
        return this.callAsync ("privatePostGetInfo2", optionalArgs);
    }

    /**
     * Calls the privatePostGetPersonalInfo endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public java.util.concurrent.CompletableFuture<java.util.Map<String, Object>>  privatePostGetPersonalInfo (Object... optionalArgs)
    {
        return this.callAsync ("privatePostGetPersonalInfo", optionalArgs);
    }

    /**
     * Calls the privatePostTrade endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public java.util.concurrent.CompletableFuture<java.util.Map<String, Object>>  privatePostTrade (Object... optionalArgs)
    {
        return this.callAsync ("privatePostTrade", optionalArgs);
    }

    /**
     * Calls the privatePostTradeHistory endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public java.util.concurrent.CompletableFuture<java.util.Map<String, Object>>  privatePostTradeHistory (Object... optionalArgs)
    {
        return this.callAsync ("privatePostTradeHistory", optionalArgs);
    }

    /**
     * Calls the privatePostWithdraw endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public java.util.concurrent.CompletableFuture<java.util.Map<String, Object>>  privatePostWithdraw (Object... optionalArgs)
    {
        return this.callAsync ("privatePostWithdraw", optionalArgs);
    }

    /**
     * Calls the privatePostWithdrawHistory endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public java.util.concurrent.CompletableFuture<java.util.Map<String, Object>>  privatePostWithdrawHistory (Object... optionalArgs)
    {
        return this.callAsync ("privatePostWithdrawHistory", optionalArgs);
    }

    /**
     * Calls the ecapiPostCreateInvoice endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public java.util.concurrent.CompletableFuture<java.util.Map<String, Object>>  ecapiPostCreateInvoice (Object... optionalArgs)
    {
        return this.callAsync ("ecapiPostCreateInvoice", optionalArgs);
    }

    /**
     * Calls the ecapiPostGetInvoice endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public java.util.concurrent.CompletableFuture<java.util.Map<String, Object>>  ecapiPostGetInvoice (Object... optionalArgs)
    {
        return this.callAsync ("ecapiPostGetInvoice", optionalArgs);
    }

    /**
     * Calls the ecapiPostGetInvoiceIdsByOrderNumber endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public java.util.concurrent.CompletableFuture<java.util.Map<String, Object>>  ecapiPostGetInvoiceIdsByOrderNumber (Object... optionalArgs)
    {
        return this.callAsync ("ecapiPostGetInvoiceIdsByOrderNumber", optionalArgs);
    }

    /**
     * Calls the ecapiPostCancelInvoice endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public java.util.concurrent.CompletableFuture<java.util.Map<String, Object>>  ecapiPostCancelInvoice (Object... optionalArgs)
    {
        return this.callAsync ("ecapiPostCancelInvoice", optionalArgs);
    }

    /**
     * Calls the tlapiPostGetPositions endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public java.util.concurrent.CompletableFuture<java.util.Map<String, Object>>  tlapiPostGetPositions (Object... optionalArgs)
    {
        return this.callAsync ("tlapiPostGetPositions", optionalArgs);
    }

    /**
     * Calls the tlapiPostPositionHistory endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public java.util.concurrent.CompletableFuture<java.util.Map<String, Object>>  tlapiPostPositionHistory (Object... optionalArgs)
    {
        return this.callAsync ("tlapiPostPositionHistory", optionalArgs);
    }

    /**
     * Calls the tlapiPostActivePositions endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public java.util.concurrent.CompletableFuture<java.util.Map<String, Object>>  tlapiPostActivePositions (Object... optionalArgs)
    {
        return this.callAsync ("tlapiPostActivePositions", optionalArgs);
    }

    /**
     * Calls the tlapiPostCreatePosition endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public java.util.concurrent.CompletableFuture<java.util.Map<String, Object>>  tlapiPostCreatePosition (Object... optionalArgs)
    {
        return this.callAsync ("tlapiPostCreatePosition", optionalArgs);
    }

    /**
     * Calls the tlapiPostChangePosition endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public java.util.concurrent.CompletableFuture<java.util.Map<String, Object>>  tlapiPostChangePosition (Object... optionalArgs)
    {
        return this.callAsync ("tlapiPostChangePosition", optionalArgs);
    }

    /**
     * Calls the tlapiPostCancelPosition endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public java.util.concurrent.CompletableFuture<java.util.Map<String, Object>>  tlapiPostCancelPosition (Object... optionalArgs)
    {
        return this.callAsync ("tlapiPostCancelPosition", optionalArgs);
    }

    /**
     * Calls the fapiGetGroupsGroupId endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON array
     */
    public java.util.concurrent.CompletableFuture<java.util.List<Object>>  fapiGetGroupsGroupId (Object... optionalArgs)
    {
        return this.callAsync ("fapiGetGroupsGroupId", optionalArgs);
    }

    /**
     * Calls the fapiGetLastPriceGroupIdPair endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public java.util.concurrent.CompletableFuture<java.util.Map<String, Object>>  fapiGetLastPriceGroupIdPair (Object... optionalArgs)
    {
        return this.callAsync ("fapiGetLastPriceGroupIdPair", optionalArgs);
    }

    /**
     * Calls the fapiGetTickerGroupIdPair endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public java.util.concurrent.CompletableFuture<java.util.Map<String, Object>>  fapiGetTickerGroupIdPair (Object... optionalArgs)
    {
        return this.callAsync ("fapiGetTickerGroupIdPair", optionalArgs);
    }

    /**
     * Calls the fapiGetTradesGroupIdPair endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON array
     */
    public java.util.concurrent.CompletableFuture<java.util.List<Object>>  fapiGetTradesGroupIdPair (Object... optionalArgs)
    {
        return this.callAsync ("fapiGetTradesGroupIdPair", optionalArgs);
    }

    /**
     * Calls the fapiGetDepthGroupIdPair endpoint.
     *
     * @param optionalArgs the request parameters
     * @return a JSON object
     */
    public java.util.concurrent.CompletableFuture<java.util.Map<String, Object>>  fapiGetDepthGroupIdPair (Object... optionalArgs)
    {
        return this.callAsync ("fapiGetDepthGroupIdPair", optionalArgs);
    }

}