require 'ccxt/version'
require 'ccxt/base/exchange'

module Ccxt
  @exchanges = [
    "ccxt_1btcxe",
    "acx",
    "allcoin",
    "anxpro",
    "anybits",
    "bcex",
    "bequant",
    "bibox",
    "bigone",
    "binance",
    "binanceje",
    "bit2c",
    "bitbank",
    "bitbay",
    "bitfinex",
    "bitfinex2",
    "bitflyer",
    "bitforex",
    "bithumb",
    "bitibu",
    "bitkk",
    "bitlish",
    "bitmarket",
    "bitmex",
    "bitsane",
    "bitso",
    "bitstamp",
    "bitstamp1",
    "bittrex",
    "bitz",
    "bl3p",
    "bleutrade",
    "braziliex",
    "btcalpha",
    "btcbox",
    "btcchina",
    "btcexchange",
    "btcmarkets",
    "btctradeim",
    "btctradeua",
    "btcturk",
    "buda",
    "bxinth",
    "ccex",
    "cex",
    "chbtc",
    "chilebit",
    "cobinhood",
    "coinbase",
    "coinbaseprime",
    "coinbasepro",
    "coincheck",
    "coinegg",
    "coinex",
    "coinexchange",
    "coinfalcon",
    "coinfloor",
    "coingi",
    "coinmarketcap",
    "coinmate",
    "coinnest",
    "coinone",
    "coinspot",
    "cointiger",
    "coolcoin",
    "coss",
    "crex24",
    "crypton",
    "cryptopia",
    "deribit",
    "dsx",
    "ethfinex",
    "exmo",
    "exx",
    "fcoin",
    "fcoinjp",
    "flowbtc",
    "foxbit",
    "fybse",
    "fybsg",
    "gateio",
    "gdax",
    "gemini",
    "getbtc",
    "hadax",
    "hitbtc",
    "hitbtc2",
    "huobipro",
    "huobiru",
    "ice3x",
    "independentreserve",
    "indodax",
    "itbit",
    "jubi",
    "kkex",
    "kraken",
    "kucoin",
    "kucoin2",
    "kuna",
    "lakebtc",
    "lbank",
    "liqui",
    "liquid",
    "livecoin",
    "luno",
    "lykke",
    "mandala",
    "mercado",
    "mixcoins",
    "negociecoins",
    "nova",
    "okcoincny",
    "okcoinusd",
    "okex",
    "paymium",
    "poloniex",
    "quadrigacx",
    "rightbtc",
    "southxchange",
    "stronghold",
    "surbitcoin",
    "theocean",
    "therock",
    "tidebit",
    "tidex",
    "uex",
    "upbit",
    "urdubit",
    "vaultoro",
    "vbtc",
    "virwox",
    "xbtce",
    "yobit",
    "zaif",
    "zb"
  ].each do |exchange|
    require "ccxt/#{exchange}"

    define_singleton_method exchange do |*args|
      self[exchange].new *args
    end
  end.freeze

  def self.exchanges
    @exchanges
  end

  def self.[](key)
    if Ccxt.exchanges.include? key
      class_name = key.split('_').collect(&:capitalize).join
      return const_get class_name
    else
      return nil
    end
  end
end
