import { implicitReturnType } from '../base/types.js'
import { Exchange as _Exchange } from '../base/Exchange.js'

export default abstract class Exchange extends _Exchange {
    abstract publicSpotGetCommonSymbols (params?: {}): Promise<implicitReturnType>;
    abstract publicSpotGetCommonCurrencys (params?: {}): Promise<implicitReturnType>;
    abstract publicSpotGetCommonTimestamp (params?: {}): Promise<implicitReturnType>;
    abstract publicSpotGetQKline (params?: {}): Promise<implicitReturnType>;
    abstract publicSpotGetQTickers (params?: {}): Promise<implicitReturnType>;
    abstract publicSpotGetQTickerPrice (params?: {}): Promise<implicitReturnType>;
    abstract publicSpotGetQDepth (params?: {}): Promise<implicitReturnType>;
    abstract publicSpotGetQDeals (params?: {}): Promise<implicitReturnType>;
    abstract publicSwapGetMarketCandle (params?: {}): Promise<implicitReturnType>;
    abstract publicSwapGetMarketDeals (params?: {}): Promise<implicitReturnType>;
    abstract publicSwapGetMarketDepth (params?: {}): Promise<implicitReturnType>;
    abstract publicSwapGetMarketFundingRate (params?: {}): Promise<implicitReturnType>;
    abstract publicSwapGetMarketIndex (params?: {}): Promise<implicitReturnType>;
    abstract publicSwapGetMarketRiskLimit (params?: {}): Promise<implicitReturnType>;
    abstract publicSwapGetMarketSymbols (params?: {}): Promise<implicitReturnType>;
    abstract publicSwapGetMarketTickerPrice (params?: {}): Promise<implicitReturnType>;
    abstract publicSwapGetMarketTickers (params?: {}): Promise<implicitReturnType>;
    abstract publicSwapGetServerPing (params?: {}): Promise<implicitReturnType>;
    abstract privateSpotGetUApiInfo (params?: {}): Promise<implicitReturnType>;
    abstract privateSpotGetUAccountBalance (params?: {}): Promise<implicitReturnType>;
    abstract privateSpotGetUWalletAddress (params?: {}): Promise<implicitReturnType>;
    abstract privateSpotGetUWalletDepositRecord (params?: {}): Promise<implicitReturnType>;
    abstract privateSpotGetUWalletWithdrawRecord (params?: {}): Promise<implicitReturnType>;
    abstract privateSpotGetUOrderOpenOrders (params?: {}): Promise<implicitReturnType>;
    abstract privateSpotGetUOrderOpenOrderDetail (params?: {}): Promise<implicitReturnType>;
    abstract privateSpotGetUOrderHistoryOrders (params?: {}): Promise<implicitReturnType>;
    abstract privateSpotPostUAccountTransfer (params?: {}): Promise<implicitReturnType>;
    abstract privateSpotPostUWalletWithdraw (params?: {}): Promise<implicitReturnType>;
    abstract privateSpotPostUOrderCreate (params?: {}): Promise<implicitReturnType>;
    abstract privateSpotPostUOrderCancel (params?: {}): Promise<implicitReturnType>;
    abstract privateSpotPostUOrderBatchCreate (params?: {}): Promise<implicitReturnType>;
    abstract privateSpotPostUOrderBatchCancel (params?: {}): Promise<implicitReturnType>;
    abstract privateSwapGetAccountBalance (params?: {}): Promise<implicitReturnType>;
    abstract privateSwapGetAccountBalanceRecord (params?: {}): Promise<implicitReturnType>;
    abstract privateSwapGetAccountOrder (params?: {}): Promise<implicitReturnType>;
    abstract privateSwapGetAccountOrderForced (params?: {}): Promise<implicitReturnType>;
    abstract privateSwapGetAccountPosition (params?: {}): Promise<implicitReturnType>;
    abstract privateSwapGetEntrustFinished (params?: {}): Promise<implicitReturnType>;
    abstract privateSwapGetEntrustUnFinish (params?: {}): Promise<implicitReturnType>;
    abstract privateSwapGetOrderFinished (params?: {}): Promise<implicitReturnType>;
    abstract privateSwapGetOrderFinishedInfo (params?: {}): Promise<implicitReturnType>;
    abstract privateSwapGetOrderUnFinish (params?: {}): Promise<implicitReturnType>;
    abstract privateSwapGetPositionInfo (params?: {}): Promise<implicitReturnType>;
    abstract privateSwapPostAccountSetLeverage (params?: {}): Promise<implicitReturnType>;
    abstract privateSwapPostEntrustAdd (params?: {}): Promise<implicitReturnType>;
    abstract privateSwapPostEntrustCancel (params?: {}): Promise<implicitReturnType>;
    abstract privateSwapPostOrderBatchCancel (params?: {}): Promise<implicitReturnType>;
    abstract privateSwapPostOrderBatchOpen (params?: {}): Promise<implicitReturnType>;
    abstract privateSwapPostOrderCancel (params?: {}): Promise<implicitReturnType>;
    abstract privateSwapPostOrderClose (params?: {}): Promise<implicitReturnType>;
    abstract privateSwapPostOrderCloseAll (params?: {}): Promise<implicitReturnType>;
    abstract privateSwapPostOrderOpen (params?: {}): Promise<implicitReturnType>;
    abstract privateSwapPostPositionSetSpSl (params?: {}): Promise<implicitReturnType>;
    abstract privateSwapPostPositionUpdate (params?: {}): Promise<implicitReturnType>;
}