import * as functions from './functions.js';
import { AuthenticationError, DDoSProtection, ExchangeError, ExchangeNotAvailable, RateLimitExceeded, RequestTimeout } from "./errors.js";
import WsClient from './ws/WsClient.js';
import { Future } from './ws/Future.js';
import { CountedOrderBook, IndexedOrderBook, OrderBook as WsOrderBook } from './ws/OrderBook.js';
import { Balance, Balances, Currency, DepositAddressResponse, Dictionary, IndexType, Int, Market, MinMax, OHLCV, OHLCVC, Order, OrderBook, OrderSide, OrderType, Position, Ticker, Trade } from './types.js';
export { Fee, Market, Position, Ticker, Trade } from './types.js';
/**
 * @class Exchange
 */
export default class Exchange {
    hash: (request: import("../static_dependencies/noble-hashes/utils.js").Input, hash: {
        (message: import("../static_dependencies/noble-hashes/utils.js").Input): Uint8Array;
        outputLen: number;
        blockLen: number;
        create(): import("../static_dependencies/noble-hashes/utils.js").Hash<import("../static_dependencies/noble-hashes/utils.js").Hash<any>>;
    }, digest?: "binary" | "hex" | "base64") => any;
    hmac: (request: import("../static_dependencies/noble-hashes/utils.js").Input, secret: import("../static_dependencies/noble-hashes/utils.js").Input, hash: {
        (message: import("../static_dependencies/noble-hashes/utils.js").Input): Uint8Array;
        outputLen: number;
        blockLen: number;
        create(): import("../static_dependencies/noble-hashes/utils.js").Hash<import("../static_dependencies/noble-hashes/utils.js").Hash<any>>;
    }, digest?: "binary" | "hex" | "base64") => any;
    AbortError: any;
    accounts: any;
    accountsById: any;
    agent: any;
    aggregate: typeof functions.aggregate;
    api: any;
    apiKey: string;
    arrayConcat: (a: any, b: any) => any;
    balance: {};
    base16ToBinary: (str: string) => Uint8Array;
    base58ToBinary: (str: string) => Uint8Array;
    base64ToBinary: (str: string) => Uint8Array;
    base64ToString: (string: any) => string;
    baseCurrencies: any;
    binaryConcat: typeof import("../static_dependencies/noble-curves/abstract/utils.js").concatBytes;
    binaryConcatArray: (arr: any) => Uint8Array;
    binaryToBase16: (data: Uint8Array) => string;
    binaryToBase58: (data: Uint8Array) => string;
    binaryToBase64: (data: Uint8Array) => string;
    capitalize: (s: string) => string;
    clients: {};
    clone: (x: any) => any;
    codes: any;
    commonCurrencies: any;
    crc32: typeof functions.crc32;
    currencies: Dictionary<Currency>;
    currencies_by_id: any;
    decimalToPrecision: (x: any, roundingMode: any, numPrecisionDigits: any, countingMode?: number, paddingMode?: number) => any;
    decode: (data: Uint8Array) => string;
    deepExtend: (...xs: any[]) => any;
    enableLastHttpResponse: boolean;
    enableLastJsonResponse: boolean;
    enableLastResponseHeaders: boolean;
    enableRateLimit: boolean;
    encode: (str: string) => Uint8Array;
    exceptions: {};
    extend: (...args: any[]) => any;
    extractParams: (string: any) => any[];
    fees: object;
    FetchError: any;
    fetchImplementation: any;
    filterBy: (x: any, k: any, value?: any, out?: any[]) => any[];
    flatten: (x: any, out?: any[]) => any[];
    groupBy: (x: any, k: any, out?: {}) => {};
    handleContentTypeApplicationZip: boolean;
    has: Dictionary<boolean | 'emulated'>;
    headers: any;
    hostname: string;
    http_proxy: string;
    http_proxy_callback: any;
    httpExceptions: any;
    httpProxy: string;
    httpProxyCallback: any;
    https_proxy: string;
    https_proxy_callback: any;
    httpsProxy: string;
    httpsProxyCallback: any;
    id: string;
    ids: string[];
    implodeParams: (string: any, params: any) => any;
    inArray: (needle: any, haystack: any) => any;
    indexBy: (x: any, k: any, out?: {}) => {};
    isArray: (needle: any, haystack: any) => any;
    isEmpty: (object: any) => boolean;
    isJsonEncodedObject: (object: any) => boolean;
    isNode: boolean;
    iso8601: (timestamp: any) => string;
    json: (data: any, params?: any) => string;
    keys: {
        (o: object): string[];
        (o: {}): string[];
    };
    keysort: (x: any, out?: {}) => {};
    last_http_response: any;
    last_json_response: any;
    last_response_headers: any;
    lastRestRequestTimestamp: number;
    limits: {
        amount?: MinMax;
        cost?: MinMax;
        leverage?: MinMax;
        price?: MinMax;
    };
    login: string;
    markets: Dictionary<any>;
    markets_by_id: Dictionary<any>;
    marketsByAltname: any;
    marketsLoading: any;
    merge: (target: any, ...args: any[]) => any;
    microseconds: () => number;
    milliseconds: () => number;
    minFundingAddressLength: number;
    myTrades: any;
    name: string;
    newUpdates: boolean;
    now: () => number;
    number: NumberConstructor;
    numberToBE: (n: number, padding: number) => Uint8Array;
    numberToLE: (n: number, padding: number) => Uint8Array;
    numberToString: typeof functions.numberToString;
    ohlcvs: any;
    omit: (x: any, ...args: any[]) => any;
    omitZero: typeof functions.omitZero;
    options: {
        [key: string]: any;
    };
    orderbooks: {};
    ordered: (x: any) => any;
    orders: any;
    origin: string;
    paddingMode: any;
    parse8601: (x: any) => number;
    parseDate: (x: any) => number;
    parseTimeframe: (timeframe: string) => number;
    password: string;
    positions: {};
    precision: {
        amount: number | undefined;
        price: number | undefined;
    };
    precisionFromString: typeof functions.precisionFromString;
    precisionMode: number;
    privateKey: string;
    proxy: any;
    proxy_url: string;
    proxy_url_callback: any;
    proxyUrl: string;
    proxyUrlCallback: any;
    quoteCurrencies: any;
    quoteJsonNumbers: boolean;
    rateLimit: number;
    rawencode: (object: any) => string;
    reduceFees: boolean;
    reloadingMarkets: any;
    requiredCredentials: {
        apiKey: boolean;
        login: boolean;
        password: boolean;
        privateKey: boolean;
        secret: boolean;
        token: boolean;
        twofa: boolean;
        uid: boolean;
        walletAddress: boolean;
    };
    requiresEddsa: boolean;
    requiresWeb3: boolean;
    safeFloat2: (o: any, k1: string | number, k2: string | number, $default?: number) => number;
    safeFloat: (o: any, k: string | number, $default?: number) => number;
    safeFloatN: (o: any, k: (string | number)[], $default?: number) => number;
    safeInteger2: (o: any, k1: string | number, k2: string | number, $default?: number) => number;
    safeInteger: (o: any, k: string | number, $default?: number) => number;
    safeIntegerN: (o: any, k: (string | number)[], $default?: number) => number;
    safeIntegerProduct2: (o: any, k1: string | number, k2: string | number, $factor: number, $default?: number) => number;
    safeIntegerProduct: (o: any, k: string | number, $factor: number, $default?: number) => number;
    safeIntegerProductN: (o: any, k: (string | number)[], $factor: number, $default?: number) => number;
    safeString2: (o: any, k1: string | number, k2: string | number, $default?: string) => string;
    safeString: (o: any, k: string | number, $default?: string) => string;
    safeStringLower2: (o: any, k1: string | number, k2: string | number, $default?: string) => string;
    safeStringLower: (o: any, k: string | number, $default?: string) => string;
    safeStringLowerN: (o: any, k: (string | number)[], $default?: string) => string;
    safeStringN: (o: any, k: (string | number)[], $default?: string) => string;
    safeStringUpper2: (o: any, k1: string | number, k2: string | number, $default?: string) => string;
    safeStringUpper: (o: any, k: string | number, $default?: string) => string;
    safeStringUpperN: (o: any, k: (string | number)[], $default?: string) => string;
    safeTimestamp2: (o: any, k1: string | number, k2: string | number, $default?: any) => number;
    safeTimestamp: (o: any, k: string | number, $default?: number) => number;
    safeTimestampN: (o: any, k: (string | number)[], $default?: number) => number;
    safeValue2: (o: any, k1: string | number, k2: string | number, $default?: any) => any;
    safeValue: (o: any, k: string | number, $default?: any) => any;
    safeValueN: (o: any, k: (string | number)[], $default?: any) => any;
    seconds: () => number;
    secret: string;
    socks_proxy: string;
    socks_proxy_callback: any;
    socksProxy: string;
    socksProxyCallback: any;
    sortBy2: (array: any, key1: any, key2: any, descending?: boolean, direction?: number) => any;
    sortBy: (array: any, key: any, descending?: boolean, direction?: number) => any;
    stablePairs: {};
    status: any;
    streaming: {};
    stringToBase64: (string: any) => string;
    strip: (s: string) => string;
    substituteCommonCurrencyCodes: boolean;
    sum: (...xs: any[]) => any;
    symbols: string[];
    targetAccount: any;
    throttler: any;
    tickers: {};
    timeframes: Dictionary<number | string>;
    timeout: number;
    toArray: (object: any) => unknown[];
    token: string;
    tokenBucket: any;
    trades: any;
    transactions: {};
    twofa: any;
    uid: string;
    unCamelCase: (s: string) => string;
    unique: (x: any) => any[];
    urlencode: (object: any) => string;
    urlencodeNested: (object: any) => string;
    urlencodeWithArrayRepeat: (object: any) => string;
    userAgents: any;
    uuid16: (a?: any) => string;
    uuid22: (a?: any) => string;
    uuid: (a?: any) => string;
    uuidv1: () => string;
    validateClientSsl: boolean;
    validateServerSsl: boolean;
    values: (x: any) => any[];
    verbose: boolean;
    version: string;
    vwap: typeof functions.vwap;
    walletAddress: string;
    ymd: (timestamp: any, infix: any, fullYear?: boolean) => string;
    ymdhms: (timestamp: any, infix?: string) => string;
    yymmdd: (timestamp: any, infix?: string) => string;
    yyyymmdd: (timestamp: any, infix?: string) => string;
    urls: {
        api?: string | Dictionary<string>;
        api_management?: string;
        doc?: string[];
        fees?: string;
        logo?: string;
        referral?: string;
        test?: string | Dictionary<string>;
        www?: string;
    };
    user_agent: {
        'User-Agent': string;
    } | false;
    userAgent: {
        'User-Agent': string;
    } | false;
    describe(): {
        alias: boolean;
        api: any;
        certified: boolean;
        commonCurrencies: {
            BCC: string;
            BCHSV: string;
            XBT: string;
        };
        countries: any;
        currencies: {};
        enableRateLimit: boolean;
        exceptions: any;
        fees: {
            funding: {
                deposit: {};
                percentage: any;
                tierBased: any;
                withdraw: {};
            };
            trading: {
                maker: any;
                percentage: any;
                taker: any;
                tierBased: any;
            };
        };
        has: {
            addMargin: any;
            cancelAllOrders: any;
            cancelAllOrdersWs: any;
            cancelOrder: boolean;
            cancelOrders: any;
            cancelOrdersWs: any;
            cancelOrderWs: any;
            CORS: any;
            createDepositAddress: any;
            createLimitOrder: boolean;
            createMarketOrder: boolean;
            createOrder: boolean;
            createOrderWs: any;
            createPostOnlyOrder: any;
            createReduceOnlyOrder: any;
            createStopLimitOrder: any;
            createStopMarketOrder: any;
            createStopOrder: any;
            editOrder: string;
            editOrderWs: any;
            fetchAccounts: any;
            fetchBalance: boolean;
            fetchBalanceWs: any;
            fetchBidsAsks: any;
            fetchBorrowInterest: any;
            fetchBorrowRate: any;
            fetchBorrowRateHistory: any;
            fetchBorrowRates: any;
            fetchBorrowRatesPerSymbol: any;
            fetchCanceledOrders: any;
            fetchClosedOrder: any;
            fetchClosedOrders: any;
            fetchCurrencies: string;
            fetchDeposit: any;
            fetchDepositAddress: any;
            fetchDepositAddresses: any;
            fetchDepositAddressesByNetwork: any;
            fetchDeposits: any;
            fetchDepositsWithdrawals: any;
            fetchFundingHistory: any;
            fetchFundingRate: any;
            fetchFundingRateHistory: any;
            fetchFundingRates: any;
            fetchIndexOHLCV: any;
            fetchL2OrderBook: boolean;
            fetchLastPrices: any;
            fetchLedger: any;
            fetchLedgerEntry: any;
            fetchLeverageTiers: any;
            fetchMarketLeverageTiers: any;
            fetchMarkets: boolean;
            fetchMarkOHLCV: any;
            fetchMyTrades: any;
            fetchOHLCV: any;
            fetchOpenInterest: any;
            fetchOpenInterestHistory: any;
            fetchOpenOrder: any;
            fetchOpenOrders: any;
            fetchOpenOrdersWs: any;
            fetchOrder: any;
            fetchOrderBook: boolean;
            fetchOrderBooks: any;
            fetchOrders: any;
            fetchOrderTrades: any;
            fetchOrderWs: any;
            fetchPermissions: any;
            fetchPosition: any;
            fetchPositions: any;
            fetchPositionsBySymbol: any;
            fetchPositionsRisk: any;
            fetchPremiumIndexOHLCV: any;
            fetchStatus: string;
            fetchTicker: boolean;
            fetchTickers: any;
            fetchTime: any;
            fetchTrades: boolean;
            fetchTradesWs: any;
            fetchTradingFee: any;
            fetchTradingFees: any;
            fetchTradingLimits: any;
            fetchTransactionFee: any;
            fetchTransactionFees: any;
            fetchTransactions: any;
            fetchTransfers: any;
            fetchWithdrawAddresses: any;
            fetchWithdrawal: any;
            fetchWithdrawals: any;
            future: any;
            margin: any;
            option: any;
            privateAPI: boolean;
            publicAPI: boolean;
            reduceMargin: any;
            setLeverage: any;
            setMargin: any;
            setMarginMode: any;
            setPositionMode: any;
            signIn: any;
            spot: any;
            swap: any;
            transfer: any;
            watchBalance: any;
            watchMyTrades: any;
            watchOHLCV: any;
            watchOHLCVForSymbols: any;
            watchOrderBook: any;
            watchOrderBookForSymbols: any;
            watchOrders: any;
            watchTicker: any;
            watchTickers: any;
            watchTrades: any;
            watchTradesForSymbols: any;
            withdraw: any;
        };
        httpExceptions: {
            '400': typeof ExchangeNotAvailable;
            '401': typeof AuthenticationError;
            '403': typeof ExchangeNotAvailable;
            '404': typeof ExchangeNotAvailable;
            '405': typeof ExchangeNotAvailable;
            '407': typeof AuthenticationError;
            '408': typeof RequestTimeout;
            '409': typeof ExchangeNotAvailable;
            '410': typeof ExchangeNotAvailable;
            '418': typeof DDoSProtection;
            '422': typeof ExchangeError;
            '429': typeof RateLimitExceeded;
            '451': typeof ExchangeNotAvailable;
            '500': typeof ExchangeNotAvailable;
            '501': typeof ExchangeNotAvailable;
            '502': typeof ExchangeNotAvailable;
            '503': typeof ExchangeNotAvailable;
            '504': typeof RequestTimeout;
            '511': typeof AuthenticationError;
            '520': typeof ExchangeNotAvailable;
            '521': typeof ExchangeNotAvailable;
            '522': typeof ExchangeNotAvailable;
            '525': typeof ExchangeNotAvailable;
            '526': typeof ExchangeNotAvailable;
            '530': typeof ExchangeNotAvailable;
        };
        id: any;
        limits: {
            amount: {
                min: any;
                max: any;
            };
            cost: {
                min: any;
                max: any;
            };
            leverage: {
                min: any;
                max: any;
            };
            price: {
                min: any;
                max: any;
            };
        };
        markets: any;
        name: any;
        paddingMode: number;
        precisionMode: number;
        pro: boolean;
        rateLimit: number;
        requiredCredentials: {
            apiKey: boolean;
            login: boolean;
            password: boolean;
            privateKey: boolean;
            secret: boolean;
            token: boolean;
            twofa: boolean;
            uid: boolean;
            walletAddress: boolean;
        };
        status: {
            eta: any;
            status: string;
            updated: any;
            url: any;
        };
        timeframes: any;
        urls: {
            api: any;
            doc: any;
            fees: any;
            logo: any;
            www: any;
        };
    };
    constructor(userConfig?: {});
    afterConstruct(): void;
    arraySlice(array: any, first: any, second?: any): any;
    checkAddress(address: any): any;
    checkOrderArguments(market: any, type: any, side: any, amount: any, price: any, params: any): void;
    checkProxySettings(url: any, method: any, headers: any, body: any): string[];
    checkRequiredDependencies(): void;
    checkRequiredVersion(requiredVersion: any, error?: boolean): boolean;
    client(url: any): WsClient;
    close(): Promise<any[]>;
    convertToBigInt(value: string): bigint;
    countedOrderBook(snapshot?: {}, depth?: number): CountedOrderBook;
    createDepositAddress(code: string, params?: {}): Promise<DepositAddressResponse>;
    createNetworksByIdObject(): void;
    defineRestApi(api: any, methodName: any, paths?: any[]): void;
    defineRestApiEndpoint(methodName: any, uppercaseMethod: any, lowercaseMethod: any, camelcaseMethod: any, path: any, paths: any, config?: {}): void;
    delay(timeout: any, method: any, ...args: any[]): void;
    encodeURIComponent(...args: any[]): string;
    fetch(url: any, method?: string, headers?: any, body?: any): Promise<any>;
    fetchAccounts(params?: {}): Promise<any>;
    fetchBorrowRates(params?: {}): Promise<any>;
    fetchCurrencies(params?: {}): Promise<unknown>;
    fetchDepositAddresses(codes?: string[], params?: {}): Promise<any>;
    fetchFundingRates(symbols?: string[], params?: {}): Promise<any>;
    fetchLeverageTiers(symbols?: string[], params?: {}): Promise<any>;
    fetchMarkets(params?: {}): Promise<Market[]>;
    fetchOrderBook(symbol: string, limit?: Int, params?: {}): Promise<OrderBook>;
    fetchRestOrderBookSafe(symbol: any, limit?: any, params?: {}): Promise<OrderBook>;
    fetchTime(params?: {}): Promise<number>;
    fetchTrades(symbol: string, since?: Int, limit?: Int, params?: {}): Promise<Trade[]>;
    fetchTradesWs(symbol: string, since?: Int, limit?: Int, params?: {}): Promise<Trade[]>;
    fetchTradingLimits(symbols?: string[], params?: {}): Promise<any>;
    filterByLimit(array: object[], limit?: Int, key?: IndexType): any;
    filterBySinceLimit(array: object[], since?: Int, limit?: Int, key?: IndexType, tail?: boolean): any;
    filterByValueSinceLimit(array: object[], field: IndexType, value?: any, since?: Int, limit?: Int, key?: string, tail?: boolean): any;
    findMessageHashes(client: any, element: string): string[];
    findTimeframe(timeframe: any, timeframes?: any): string;
    getCacheIndex(orderbook: any, deltas: any): number;
    getProperty(obj: any, property: any, defaultValue?: any): any;
    getResponseHeaders(response: any): {};
    handleDelta(bookside: any, delta: any): void;
    handleDeltas(orderbook: any, deltas: any): void;
    handleHttpStatusCode(code: any, reason: any, url: any, method: any, body: any): void;
    handleMessage(client: any, message: any): void;
    handleRestResponse(response: any, url: any, method?: string, requestHeaders?: any, requestBody?: any): any;
    indexedOrderBook(snapshot?: {}, depth?: number): IndexedOrderBook;
    initRestRateLimiter(): void;
    loadMarkets(reload?: boolean, params?: {}): Promise<Dictionary<Market>>;
    loadMarketsHelper(reload?: boolean, params?: {}): Promise<Dictionary<any>>;
    loadOrderBook(client: any, messageHash: any, symbol: any, limit?: any, params?: {}): Promise<void>;
    log(...args: any[]): void;
    onClose(client: any, error: any): void;
    onConnected(client: any, message?: any): void;
    onError(client: any, error: any): void;
    onJsonResponse(responseBody: any): any;
    onRestResponse(statusCode: any, statusText: any, url: any, method: any, responseHeaders: any, responseBody: any, requestHeaders: any, requestBody: any): any;
    orderBook(snapshot?: {}, depth?: number): WsOrderBook;
    parseAccount(account: any): void;
    parseBorrowInterest(info: any, market?: any): void;
    parseDepositAddress(depositAddress: any, currency?: any): void;
    parseFundingRateHistory(info: any, market?: any): void;
    parseJson(jsonString: any): any;
    parseLedgerEntry(item: any, currency?: any): void;
    parseMarketLeverageTiers(info: any, market?: any): void;
    parseNumber(value: any, d?: number): number;
    parseOrder(order: any, market?: any): Order;
    parsePosition(position: any, market?: any): void;
    parseTicker(ticker: object, market?: any): Ticker;
    parseToInt(number: any): number;
    parseTrade(trade: object, market?: any): Trade;
    parseTransaction(transaction: any, currency?: any): void;
    parseTransfer(transfer: any, currency?: any): void;
    parseWsOHLCV(ohlcv: any, market?: any): any;
    parseWsOrder(order: any, market?: any): Order;
    parseWsOrderTrade(trade: any, market?: any): Trade;
    parseWsTrade(trade: any, market?: any): Trade;
    remove0xPrefix(hexData: any): any;
    setLeverage(leverage: any, symbol?: string, params?: {}): Promise<any>;
    setSandboxMode(enabled: any): void;
    sign(path: any, api?: any, method?: string, params?: {}, headers?: any, body?: any): {};
    spawn(method: any, ...args: any[]): Future;
    throttle(cost?: any): any;
    transfer(code: string, amount: any, fromAccount: any, toAccount: any, params?: {}): Promise<any>;
    valueIsDefined(value: any): boolean;
    watch(url: any, messageHash: any, message?: any, subscribeHash?: any, subscription?: any): any;
    watchOHLCVForSymbols(symbolsAndTimeframes: string[][], since?: Int, limit?: Int, params?: {}): Promise<Dictionary<Dictionary<OHLCV[]>>>;
    watchOrderBook(symbol: string, limit?: Int, params?: {}): Promise<OrderBook>;
    watchOrderBookForSymbols(symbols: string[], limit?: Int, params?: {}): Promise<OrderBook>;
    watchTrades(symbol: string, since?: Int, limit?: Int, params?: {}): Promise<Trade[]>;
    watchTradesForSymbols(symbols: string[], since?: Int, limit?: Int, params?: {}): Promise<Trade[]>;
    withdraw(code: string, amount: any, address: any, tag?: any, params?: {}): Promise<any>;
    getDefaultOptions(): {
        defaultNetworkCodeReplacements: {
            ETH: {
                ERC20: string;
            };
            TRX: {
                TRC20: string;
            };
            CRO: {
                CRC20: string;
            };
        };
    };
    safeLedgerEntry(entry: object, currency?: object): {
        id: string;
        timestamp: number;
        datetime: string;
        direction: string;
        account: string;
        referenceId: string;
        referenceAccount: string;
        type: string;
        currency: any;
        amount: number;
        before: number;
        after: number;
        status: string;
        fee: any;
        info: object;
    };
    safeCurrencyStructure(currency: object): any;
    setMarkets(markets: any, currencies?: any): Dictionary<any>;
    safeBalance(balance: object): Balances;
    safeOrder(order: object, market?: object): Order;
    parseOrders(orders: object, market?: object, since?: Int, limit?: Int, params?: {}): Order[];
    calculateFee(symbol: string, type: string, side: string, amount: number, price: number, takerOrMaker?: string, params?: {}): {
        cost: number;
        currency: any;
        rate: number;
        type: string;
    };
    safeTrade(trade: object, market?: object): Trade;
    invertFlatStringDictionary(dict: any): {};
    reduceFeesByCurrency(fees: any): any[];
    safeTicker(ticker: object, market?: any): Ticker;
    fetchOHLCV(symbol: string, timeframe?: string, since?: Int, limit?: Int, params?: {}): Promise<OHLCV[]>;
    watchOHLCV(symbol: string, timeframe?: string, since?: Int, limit?: Int, params?: {}): Promise<OHLCV[]>;
    convertTradingViewToOHLCV(ohlcvs: any, timestamp?: string, open?: string, high?: string, low?: string, close?: string, volume?: string, ms?: boolean): any[];
    convertOHLCVToTradingView(ohlcvs: any, timestamp?: string, open?: string, high?: string, low?: string, close?: string, volume?: string, ms?: boolean): {};
    fetchWebEndpoint(method: any, endpointMethod: any, returnAsJson: any, startRegex?: any, endRegex?: any): Promise<any>;
    marketIds(symbols: any): any;
    marketSymbols(symbols: any, type?: string, allowEmpty?: boolean): any;
    marketCodes(codes: any): any;
    parseBidsAsks(bidasks: any, priceKey?: IndexType, amountKey?: IndexType): any[];
    fetchL2OrderBook(symbol: string, limit?: Int, params?: {}): Promise<any>;
    filterBySymbol(objects: any, symbol?: string): any;
    parseOHLCV(ohlcv: any, market?: any): any;
    networkCodeToId(networkCode: any, currencyCode?: any): string;
    networkIdToCode(networkId: any, currencyCode?: any): string;
    handleNetworkCodeAndParams(params: any): any[];
    defaultNetworkCode(currencyCode: any): any;
    selectNetworkCodeFromUnifiedNetworks(currencyCode: any, networkCode: any, indexedNetworkEntries: any): any;
    selectNetworkIdFromRawNetworks(currencyCode: any, networkCode: any, indexedNetworkEntries: any): any;
    selectNetworkKeyFromNetworks(currencyCode: any, networkCode: any, indexedNetworkEntries: any, isIndexedByUnifiedNetworkCode?: boolean): any;
    safeNumber2(dictionary: any, key1: any, key2: any, d?: any): number;
    parseOrderBook(orderbook: object, symbol: string, timestamp?: number, bidsKey?: string, asksKey?: string, priceKey?: IndexType, amountKey?: IndexType): OrderBook;
    parseOHLCVs(ohlcvs: object[], market?: any, timeframe?: string, since?: Int, limit?: Int): OHLCV[];
    parseLeverageTiers(response: any, symbols?: string[], marketIdKey?: any): {};
    loadTradingLimits(symbols?: string[], reload?: boolean, params?: {}): Promise<Dictionary<any>>;
    safePosition(position: any): Position;
    parsePositions(positions: any, symbols?: string[], params?: {}): Position[];
    parseAccounts(accounts: any, params?: {}): any[];
    parseTrades(trades: any, market?: object, since?: Int, limit?: Int, params?: {}): Trade[];
    parseTransactions(transactions: any, currency?: object, since?: Int, limit?: Int, params?: {}): any;
    parseTransfers(transfers: any, currency?: object, since?: Int, limit?: Int, params?: {}): any;
    parseLedger(data: any, currency?: object, since?: Int, limit?: Int, params?: {}): any;
    nonce(): number;
    setHeaders(headers: any): any;
    marketId(symbol: string): string;
    symbol(symbol: string): string;
    resolvePath(path: any, params: any): any[];
    filterByArray(objects: any, key: IndexType, values?: any, indexed?: boolean): any;
    fetch2(path: any, api?: any, method?: string, params?: {}, headers?: any, body?: any, config?: {}): Promise<any>;
    request(path: any, api?: any, method?: string, params?: {}, headers?: any, body?: any, config?: {}): Promise<any>;
    loadAccounts(reload?: boolean, params?: {}): Promise<any>;
    buildOHLCVC(trades: Trade[], timeframe?: string, since?: number, limit?: number): OHLCVC[];
    parseTradingViewOHLCV(ohlcvs: any, market?: any, timeframe?: string, since?: Int, limit?: Int): OHLCV[];
    editLimitBuyOrder(id: any, symbol: any, amount: any, price?: any, params?: {}): Promise<Order>;
    editLimitSellOrder(id: any, symbol: any, amount: any, price?: any, params?: {}): Promise<Order>;
    editLimitOrder(id: any, symbol: any, side: any, amount: any, price?: any, params?: {}): Promise<Order>;
    editOrder(id: string, symbol: any, type: any, side: any, amount?: any, price?: any, params?: {}): Promise<Order>;
    editOrderWs(id: string, symbol: string, type: OrderType, side: OrderSide, amount: number, price?: number, params?: {}): Promise<Order>;
    fetchPermissions(params?: {}): Promise<void>;
    fetchPosition(symbol: string, params?: {}): Promise<Position>;
    fetchPositionsBySymbol(symbol: string, params?: {}): Promise<Position[]>;
    fetchPositions(symbols?: string[], params?: {}): Promise<Position[]>;
    fetchPositionsRisk(symbols?: string[], params?: {}): Promise<Position[]>;
    fetchBidsAsks(symbols?: string[], params?: {}): Promise<Dictionary<Ticker>>;
    parseBidAsk(bidask: any, priceKey?: IndexType, amountKey?: IndexType): number[];
    safeCurrency(currencyId?: string, currency?: any): any;
    safeMarket(marketId?: any, market?: any, delimiter?: any, marketType?: any): any;
    checkRequiredCredentials(error?: boolean): boolean;
    oath(): string;
    fetchBalance(params?: {}): Promise<Balances>;
    fetchBalanceWs(params?: {}): Promise<Balances>;
    parseBalance(response: any): Balances;
    watchBalance(params?: {}): Promise<Balances>;
    fetchPartialBalance(part: any, params?: {}): Promise<Balance>;
    fetchFreeBalance(params?: {}): Promise<Balance>;
    fetchUsedBalance(params?: {}): Promise<Balance>;
    fetchTotalBalance(params?: {}): Promise<Balance>;
    fetchStatus(params?: {}): Promise<any>;
    fetchFundingFee(code: string, params?: {}): Promise<any>;
    fetchFundingFees(codes?: string[], params?: {}): Promise<any>;
    fetchTransactionFee(code: string, params?: {}): Promise<any>;
    fetchTransactionFees(codes?: string[], params?: {}): Promise<any>;
    fetchDepositWithdrawFees(codes?: string[], params?: {}): Promise<any>;
    fetchDepositWithdrawFee(code: string, params?: {}): Promise<any>;
    getSupportedMapping(key: any, mapping?: {}): any;
    fetchBorrowRate(code: string, params?: {}): Promise<any>;
    handleOptionAndParams(params: any, methodName: any, optionName: any, defaultValue?: any): any[];
    handleOption(methodName: any, optionName: any, defaultValue?: any): any;
    handleMarketTypeAndParams(methodName: any, market?: any, params?: {}): any;
    handleSubTypeAndParams(methodName: any, market?: any, params?: {}, defaultValue?: any): any[];
    handleMarginModeAndParams(methodName: any, params?: {}, defaultValue?: any): any[];
    throwExactlyMatchedException(exact: any, string: any, message: any): void;
    throwBroadlyMatchedException(broad: any, string: any, message: any): void;
    findBroadlyMatchedKey(broad: any, string: any): string;
    handleErrors(statusCode: any, statusText: any, url: any, method: any, responseHeaders: any, responseBody: any, response: any, requestHeaders: any, requestBody: any): any;
    calculateRateLimiterCost(api: any, method: any, path: any, params: any, config?: {}): any;
    fetchTicker(symbol: string, params?: {}): Promise<Ticker>;
    watchTicker(symbol: string, params?: {}): Promise<Ticker>;
    fetchTickers(symbols?: string[], params?: {}): Promise<Dictionary<Ticker>>;
    watchTickers(symbols?: string[], params?: {}): Promise<Dictionary<Ticker>>;
    fetchOrder(id: string, symbol?: string, params?: {}): Promise<Order>;
    fetchOrderWs(id: string, symbol?: string, params?: {}): Promise<Order>;
    fetchOrderStatus(id: string, symbol?: string, params?: {}): Promise<string>;
    fetchUnifiedOrder(order: any, params?: {}): Promise<Order>;
    createOrder(symbol: string, type: OrderType, side: OrderSide, amount: any, price?: any, params?: {}): Promise<Order>;
    createOrderWs(symbol: string, type: OrderType, side: OrderSide, amount: number, price?: number, params?: {}): Promise<Order>;
    cancelOrder(id: string, symbol?: string, params?: {}): Promise<any>;
    cancelOrderWs(id: string, symbol?: string, params?: {}): Promise<any>;
    cancelOrdersWs(ids: string[], symbol?: string, params?: {}): Promise<any>;
    cancelAllOrders(symbol?: string, params?: {}): Promise<any>;
    cancelAllOrdersWs(symbol?: string, params?: {}): Promise<any>;
    cancelUnifiedOrder(order: any, params?: {}): Promise<any>;
    fetchOrders(symbol?: string, since?: Int, limit?: Int, params?: {}): Promise<Order[]>;
    fetchOrderTrades(id: string, symbol?: string, since?: Int, limit?: Int, params?: {}): Promise<Trade[]>;
    watchOrders(symbol?: string, since?: Int, limit?: Int, params?: {}): Promise<Order[]>;
    fetchOpenOrders(symbol?: string, since?: Int, limit?: Int, params?: {}): Promise<Order[]>;
    fetchOpenOrdersWs(symbol?: string, since?: Int, limit?: Int, params?: {}): Promise<Order[]>;
    fetchClosedOrders(symbol?: string, since?: Int, limit?: Int, params?: {}): Promise<Order[]>;
    fetchMyTrades(symbol?: string, since?: Int, limit?: Int, params?: {}): Promise<Trade[]>;
    fetchMyTradesWs(symbol?: string, since?: Int, limit?: Int, params?: {}): Promise<Trade[]>;
    watchMyTrades(symbol?: string, since?: Int, limit?: Int, params?: {}): Promise<Trade[]>;
    fetchOHLCVWs(symbol: string, timeframe?: string, since?: Int, limit?: Int, params?: {}): Promise<OHLCV[]>;
    fetchDepositsWithdrawals(code?: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    fetchDeposits(symbol?: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    fetchWithdrawals(symbol?: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    fetchOpenInterest(symbol: string, params?: {}): Promise<any>;
    parseLastPrice(price: any, market?: any): any;
    fetchDepositAddress(code: string, params?: {}): Promise<any>;
    account(): Balance;
    commonCurrencyCode(currency: string): string;
    currency(code: any): any;
    market(symbol: string): any;
    handleWithdrawTagAndParams(tag: any, params: any): any;
    createLimitOrder(symbol: string, side: OrderSide, amount: any, price: any, params?: {}): Promise<Order>;
    createMarketOrder(symbol: string, side: OrderSide, amount: any, price?: any, params?: {}): Promise<Order>;
    createLimitBuyOrder(symbol: string, amount: any, price: any, params?: {}): Promise<Order>;
    createLimitSellOrder(symbol: string, amount: any, price: any, params?: {}): Promise<Order>;
    createMarketBuyOrder(symbol: string, amount: any, params?: {}): Promise<Order>;
    createMarketSellOrder(symbol: string, amount: any, params?: {}): Promise<Order>;
    costToPrecision(symbol: string, cost: any): any;
    priceToPrecision(symbol: string, price: any): string;
    amountToPrecision(symbol: string, amount: any): any;
    feeToPrecision(symbol: string, fee: any): any;
    currencyToPrecision(code: string, fee: any, networkCode?: any): any;
    forceString(value: any): any;
    isTickPrecision(): boolean;
    isDecimalPrecision(): boolean;
    isSignificantPrecision(): boolean;
    safeNumber(obj: object, key: IndexType, defaultNumber?: number): number;
    safeNumberN(obj: object, arr: IndexType[], defaultNumber?: number): number;
    parsePrecision(precision?: string): string;
    loadTimeDifference(params?: {}): Promise<any>;
    implodeHostname(url: string): any;
    fetchMarketLeverageTiers(symbol: string, params?: {}): Promise<any>;
    createPostOnlyOrder(symbol: string, type: OrderType, side: OrderSide, amount: any, price: any, params?: {}): Promise<Order>;
    createReduceOnlyOrder(symbol: string, type: OrderType, side: OrderSide, amount: any, price: any, params?: {}): Promise<Order>;
    createStopOrder(symbol: string, type: OrderType, side: OrderSide, amount: any, price?: any, stopPrice?: any, params?: {}): Promise<Order>;
    createStopLimitOrder(symbol: string, side: OrderSide, amount: any, price: any, stopPrice: any, params?: {}): Promise<Order>;
    createStopMarketOrder(symbol: string, side: OrderSide, amount: any, stopPrice: any, params?: {}): Promise<Order>;
    safeCurrencyCode(currencyId?: string, currency?: any): any;
    filterBySymbolSinceLimit(array: any, symbol?: string, since?: Int, limit?: Int, tail?: boolean): any;
    filterByCurrencySinceLimit(array: any, code?: any, since?: Int, limit?: Int, tail?: boolean): any;
    parseLastPrices(pricesData: any, symbols?: string[], params?: {}): any;
    parseTickers(tickers: any, symbols?: string[], params?: {}): Dictionary<Ticker>;
    parseDepositAddresses(addresses: any, codes?: string[], indexed?: boolean, params?: {}): {};
    parseBorrowInterests(response: any, market?: any): any[];
    parseFundingRateHistories(response: any, market?: any, since?: Int, limit?: Int): any;
    safeSymbol(marketId: any, market?: any, delimiter?: any, marketType?: any): any;
    parseFundingRate(contract: string, market?: any): void;
    parseFundingRates(response: any, market?: any): {};
    isTriggerOrder(params: any): any[];
    isPostOnly(isMarketOrder: boolean, exchangeSpecificParam: any, params?: {}): boolean;
    handlePostOnly(isMarketOrder: boolean, exchangeSpecificPostOnlyOption: boolean, params?: any): any[];
    fetchLastPrices(symbols?: string[], params?: {}): Promise<void>;
    fetchTradingFees(params?: {}): Promise<any>;
    fetchTradingFee(symbol: string, params?: {}): Promise<any>;
    parseOpenInterest(interest: any, market?: any): any;
    parseOpenInterests(response: any, market?: any, since?: Int, limit?: Int): any;
    fetchFundingRate(symbol: string, params?: {}): Promise<any>;
    fetchMarkOHLCV(symbol: any, timeframe?: string, since?: Int, limit?: Int, params?: {}): Promise<OHLCV[]>;
    fetchIndexOHLCV(symbol: string, timeframe?: string, since?: Int, limit?: Int, params?: {}): Promise<OHLCV[]>;
    fetchPremiumIndexOHLCV(symbol: string, timeframe?: string, since?: Int, limit?: Int, params?: {}): Promise<OHLCV[]>;
    handleTimeInForce(params?: {}): string;
    convertTypeToAccount(account: any): any;
    checkRequiredArgument(methodName: any, argument: any, argumentName: any, options?: any[]): void;
    checkRequiredMarginArgument(methodName: string, symbol: string, marginMode: string): void;
    checkRequiredSymbol(methodName: string, symbol: string): void;
    parseDepositWithdrawFees(response: any, codes?: string[], currencyIdKey?: any): any;
    parseDepositWithdrawFee(fee: any, currency?: any): any;
    depositWithdrawFee(info: any): any;
    assignDefaultDepositWithdrawFees(fee: any, currency?: any): any;
    parseIncome(info: any, market?: any): void;
    parseIncomes(incomes: any, market?: any, since?: Int, limit?: Int): any;
    getMarketFromSymbols(symbols?: string[]): any;
    parseWsOHLCVs(ohlcvs: object[], market?: any, timeframe?: string, since?: Int, limit?: Int): any[];
    fetchTransactions(code?: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    filterByArrayPositions(objects: any, key: IndexType, values?: any, indexed?: boolean): Position[];
    resolvePromiseIfMessagehashMatches(client: any, prefix: string, symbol: string, data: any): void;
    resolveMultipleOHLCV(client: any, prefix: string, symbol: string, timeframe: string, data: any): void;
    createOHLCVObject(symbol: string, timeframe: string, data: any): Dictionary<Dictionary<OHLCV[]>>;
}
export { Exchange, };
