import { Str, Int } from './types.js';
declare class Precise {
    decimals: number;
    integer: bigint;
    base: undefined;
    constructor(number: bigint | string, decimals?: Int);
    mul(other: Precise): Precise;
    div(other: Precise, precision?: number): Precise;
    add(other: Precise): Precise;
    mod(other: Precise): Precise;
    sub(other: Precise): Precise;
    abs(): Precise;
    neg(): Precise;
    or(other: Precise): Precise;
    min(other: Precise): Precise;
    max(other: Precise): Precise;
    gt(other: Precise): boolean;
    ge(other: Precise): boolean;
    lt(other: Precise): boolean;
    le(other: Precise): boolean;
    reduce(): this | undefined;
    equals(other: any): boolean;
    toString(): string;
    static stringMul(string1: Str, string2: Str): string | undefined;
    static stringDiv(string1: Str, string2: Str, precision?: number): string | undefined;
    static stringAdd(string1: Str, string2: Str): string | undefined;
    static stringSub(string1: Str, string2: Str): string | undefined;
    static stringAbs(string: Str): string | undefined;
    static stringNeg(string: Str): string | undefined;
    static stringMod(string1: Str, string2: Str): string | undefined;
    static stringOr(string1: Str, string2: Str): string | undefined;
    static stringEquals(string1: Str, string2: Str): boolean;
    static stringEq(string1: Str, string2: Str): boolean;
    static stringMin(string1: Str, string2: Str): string | undefined;
    static stringMax(string1: Str, string2: Str): string | undefined;
    static stringGt(string1: Str, string2: Str): boolean;
    static stringGe(string1: Str, string2: Str): boolean;
    static stringLt(string1: Str, string2: Str): boolean;
    static stringLe(string1: Str, string2: Str): boolean;
}
export default Precise;
export { Precise };
