declare class Precise {
    decimals: any;
    integer: any;
    base: any;
    constructor(number: any, decimals?: any);
    mul(other: any): Precise;
    div(other: any, precision?: number): Precise;
    add(other: any): Precise;
    mod(other: any): Precise;
    sub(other: any): Precise;
    abs(): Precise;
    neg(): Precise;
    min(other: any): any;
    max(other: any): any;
    gt(other: any): boolean;
    ge(other: any): boolean;
    lt(other: any): any;
    le(other: any): any;
    reduce(): this;
    equals(other: any): boolean;
    toString(): string;
    static stringMul(string1: any, string2: any): string;
    static stringDiv(string1: any, string2: any, precision?: number): string;
    static stringAdd(string1: any, string2: any): any;
    static stringSub(string1: any, string2: any): string;
    static stringAbs(string: any): string;
    static stringNeg(string: any): string;
    static stringMod(string1: any, string2: any): string;
    static stringEquals(string1: any, string2: any): boolean;
    static stringEq(string1: any, string2: any): boolean;
    static stringMin(string1: any, string2: any): any;
    static stringMax(string1: any, string2: any): any;
    static stringGt(string1: any, string2: any): boolean;
    static stringGe(string1: any, string2: any): boolean;
    static stringLt(string1: any, string2: any): any;
    static stringLe(string1: any, string2: any): any;
}
export default Precise;
export { Precise };
