package(default_visibility = ["//visibility:public"])

py_library(
    name = "starkware_contracts_utils_lib",
    srcs = [
        "utils.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
    ],
)
