# Group: base_utils — generic collection / string helpers from
# `ts/src/base/functions/generic.ts` and `string.ts`.
include("../base/test.aggregate.jl")
include("../base/test.arrayConcat.jl")
include("../base/test.arraysConcat.jl")
include("../base/test.capitalize.jl")
include("../base/test.clone.jl")
include("../base/test.deepExtend.jl")
include("../base/test.extend.jl")
include("../base/test.filterBy.jl")
include("../base/test.groupBy.jl")
include("../base/test.inArray.jl")
include("../base/test.indexBy.jl")
include("../base/test.isEmpty.jl")
include("../base/test.keysort.jl")
include("../base/test.omit.jl")
include("../base/test.removeRepeatedElementsFromArray.jl")
include("../base/test.sort.jl")
include("../base/test.sortBy.jl")
include("../base/test.strip.jl")
include("../base/test.sum.jl")
include("../base/test.toArray.jl")
include("../base/test.unique.jl")

@testset "base_utils" begin
    testAggregate()
    testArrayConcat()
    testArraysConcat()
    testCapitalize()
    testClone()
    testDeepExtend()
    testExtend()
    testFilterBy()
    testGroupBy()
    testInArray()
    testIndexBy()
    testIsEmpty()
    testKeysort()
    testOmit()
    testRemoveRepeatedElementsFromArray()
    testSort()
    testSortBy()
    testStrip()
    testSum()
    testToArray()
    testUnique()
end
