name: New Issue
description: Report bugs here
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Ensure :
        - Your issue is directly related to ccxt
        - You have already searched for similar issues
        - Your local CCXT version is up to date (check the [latest available version](https://github.com/ccxt/ccxt/blob/master/package.json#L3) )
        - Read the [Manual](https://github.com/ccxt/ccxt/wiki/Manual), especially sections: `Exchange Properties`, `Rate Limit`, `Authentication`, `API keys`, as the subject might already be described there.
        - Read the [FAQ](https://github.com/ccxt/ccxt/wiki/FAQ) for most frequently asked questions
        - Read the [Troubleshooting](https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting) section of the manual and followed troubleshooting steps

        ## Please provide:
        - Set `exchange.verbose = true` property before calling exchange functions
        - minimal, reproducible example/code
        - surround your code and verbose output with triple backticks:
          ````markdown
          ```
          your codes or output
          ```
        - Do not include keys & credentials.

  - type: input
    id: operating-system
    attributes:
      label: Operating System
    validations:
      required: false

  - type: dropdown
    id: language
    attributes:
      multiple: true
      label: Programming Language
      options:
        - JavaScript
        - Python
        - PHP
        - C#
        - GO
    validations:
      required: false

  - type: input
    id: ccxt-version
    attributes:
      label: CCXT Version
    validations:
      required: false

  - type: textarea
    attributes:
      label: Description
    validations:
      required: false
