name: New Issue
description: Report bugs here
labels: []
assignees: []
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have already searched across existing issues
          required: true
        - label: I have read the documentation
          required: false

  - type: markdown
    attributes:
      value: |
        ## Ensure :
        - Read the [FAQ](https://github.com/ccxt/ccxt/wiki/FAQ) or search for the specific subject in the [Manual](https://github.com/ccxt/ccxt/wiki/Manual) (eg: `Exchange Properties`, `Rate Limit`, `Authentication`, `API keys`, etc).
        - Read the [Troubleshooting](https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting) to better understand your issue.

        ## Please provide:
        - Set `exchange.verbose = true` property before calling exchange functions
        - minimal, reproducible example/code
        - surround your code and verbose output with triple backticks:
          ````markdown
          ```
          your codes or output
          ```

  - type: input
    id: operating-system
    attributes:
      label: Operating System
    validations:
      required: false

  - type: dropdown
    id: language
    attributes:
      multiple: true
      label: Programming Language
      options:
        - JavaScript
        - Python
        - PHP
        - C#
        - GO
    validations:
      required: false

  - type: input
    id: ccxt-version
    attributes:
      label: CCXT Version
    validations:
      required: false

  - type: textarea
    attributes:
      label: Description
      description: (Do not expose your API keys)
    validations:
      required: true
