name: New Issue
description: Report bugs here
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Ensure :
        - This question is directly related to ccxt
        - Your local CCXT version is up to date (view the latest available version [here](https://github.com/ccxt/ccxt/blob/master/package.json#L3) )
        - You have already searched for similar issues
        - Read the [Manual](https://github.com/ccxt/ccxt/wiki/Manual), especally sections: `Exchange Properties`, `Rate Limit`, `Authentication`, `API keys`, as the subject might already be described there.
        - Read the [FAQ](https://github.com/ccxt/ccxt/wiki/FAQ) for most frequently asked questions
        - Read the [Troubleshooting](https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting) section of the manual and followed troubleshooting steps & [How to submit a good issue](https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue)

        ---

  - type: input
    id: operating-system
    attributes:
      label: Operating System
    validations:
      required: false

  - type: dropdown
    id: language
    attributes:
      multiple: true
      label: Programming Languages
      description: Which language are you using?
      options:
        - JavaScript
        - Python
        - PHP
    validations:
      required: false

  - type: input
    id: ccxt-version
    attributes:
      label: CCXT Version
    validations:
      required: false

  - type: textarea
    attributes:
      label: Description
      description: Describe the issue that you're having precisely. Include clear steps for how to reproduce the issue.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Code
      description: Don't post your API keys or secret keys!
      value: |
        ```
          

        ```
    validations:
      required: false
