// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package ccxt

func (this *DeribitCore) PublicGetAuth(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetAuth", args...)
}

func (this *DeribitCore) PublicGetExchangeToken(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetExchangeToken", args...)
}

func (this *DeribitCore) PublicGetForkToken(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetForkToken", args...)
}

func (this *DeribitCore) PublicGetSetHeartbeat(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetSetHeartbeat", args...)
}

func (this *DeribitCore) PublicGetDisableHeartbeat(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetDisableHeartbeat", args...)
}

func (this *DeribitCore) PublicGetGetTime(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetGetTime", args...)
}

func (this *DeribitCore) PublicGetHello(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetHello", args...)
}

func (this *DeribitCore) PublicGetStatus(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetStatus", args...)
}

func (this *DeribitCore) PublicGetTest(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetTest", args...)
}

func (this *DeribitCore) PublicGetSubscribe(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetSubscribe", args...)
}

func (this *DeribitCore) PublicGetUnsubscribe(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetUnsubscribe", args...)
}

func (this *DeribitCore) PublicGetUnsubscribeAll(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetUnsubscribeAll", args...)
}

func (this *DeribitCore) PublicGetGetAnnouncements(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetGetAnnouncements", args...)
}

func (this *DeribitCore) PublicGetGetBookSummaryByCurrency(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetGetBookSummaryByCurrency", args...)
}

func (this *DeribitCore) PublicGetGetBookSummaryByInstrument(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetGetBookSummaryByInstrument", args...)
}

func (this *DeribitCore) PublicGetGetContractSize(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetGetContractSize", args...)
}

func (this *DeribitCore) PublicGetGetCurrencies(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetGetCurrencies", args...)
}

func (this *DeribitCore) PublicGetGetDeliveryPrices(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetGetDeliveryPrices", args...)
}

func (this *DeribitCore) PublicGetGetFundingChartData(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetGetFundingChartData", args...)
}

func (this *DeribitCore) PublicGetGetFundingRateHistory(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetGetFundingRateHistory", args...)
}

func (this *DeribitCore) PublicGetGetFundingRateValue(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetGetFundingRateValue", args...)
}

func (this *DeribitCore) PublicGetGetHistoricalVolatility(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetGetHistoricalVolatility", args...)
}

func (this *DeribitCore) PublicGetGetIndex(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetGetIndex", args...)
}

func (this *DeribitCore) PublicGetGetIndexPrice(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetGetIndexPrice", args...)
}

func (this *DeribitCore) PublicGetGetIndexPriceNames(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetGetIndexPriceNames", args...)
}

func (this *DeribitCore) PublicGetGetInstrument(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetGetInstrument", args...)
}

func (this *DeribitCore) PublicGetGetInstruments(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetGetInstruments", args...)
}

func (this *DeribitCore) PublicGetGetLastSettlementsByCurrency(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetGetLastSettlementsByCurrency", args...)
}

func (this *DeribitCore) PublicGetGetLastSettlementsByInstrument(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetGetLastSettlementsByInstrument", args...)
}

func (this *DeribitCore) PublicGetGetLastTradesByCurrency(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetGetLastTradesByCurrency", args...)
}

func (this *DeribitCore) PublicGetGetLastTradesByCurrencyAndTime(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetGetLastTradesByCurrencyAndTime", args...)
}

func (this *DeribitCore) PublicGetGetLastTradesByInstrument(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetGetLastTradesByInstrument", args...)
}

func (this *DeribitCore) PublicGetGetLastTradesByInstrumentAndTime(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetGetLastTradesByInstrumentAndTime", args...)
}

func (this *DeribitCore) PublicGetGetMarkPriceHistory(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetGetMarkPriceHistory", args...)
}

func (this *DeribitCore) PublicGetGetOrderBook(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetGetOrderBook", args...)
}

func (this *DeribitCore) PublicGetGetTradeVolumes(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetGetTradeVolumes", args...)
}

func (this *DeribitCore) PublicGetGetTradingviewChartData(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetGetTradingviewChartData", args...)
}

func (this *DeribitCore) PublicGetGetVolatilityIndexData(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetGetVolatilityIndexData", args...)
}

func (this *DeribitCore) PublicGetTicker(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("publicGetTicker", args...)
}

func (this *DeribitCore) PrivateGetLogout(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetLogout", args...)
}

func (this *DeribitCore) PrivateGetEnableCancelOnDisconnect(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetEnableCancelOnDisconnect", args...)
}

func (this *DeribitCore) PrivateGetDisableCancelOnDisconnect(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetDisableCancelOnDisconnect", args...)
}

func (this *DeribitCore) PrivateGetGetCancelOnDisconnect(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetGetCancelOnDisconnect", args...)
}

func (this *DeribitCore) PrivateGetSubscribe(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetSubscribe", args...)
}

func (this *DeribitCore) PrivateGetUnsubscribe(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetUnsubscribe", args...)
}

func (this *DeribitCore) PrivateGetUnsubscribeAll(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetUnsubscribeAll", args...)
}

func (this *DeribitCore) PrivateGetChangeApiKeyName(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetChangeApiKeyName", args...)
}

func (this *DeribitCore) PrivateGetChangeScopeInApiKey(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetChangeScopeInApiKey", args...)
}

func (this *DeribitCore) PrivateGetChangeSubaccountName(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetChangeSubaccountName", args...)
}

func (this *DeribitCore) PrivateGetCreateApiKey(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetCreateApiKey", args...)
}

func (this *DeribitCore) PrivateGetCreateSubaccount(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetCreateSubaccount", args...)
}

func (this *DeribitCore) PrivateGetDisableApiKey(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetDisableApiKey", args...)
}

func (this *DeribitCore) PrivateGetDisableTfaForSubaccount(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetDisableTfaForSubaccount", args...)
}

func (this *DeribitCore) PrivateGetEnableAffiliateProgram(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetEnableAffiliateProgram", args...)
}

func (this *DeribitCore) PrivateGetEnableApiKey(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetEnableApiKey", args...)
}

func (this *DeribitCore) PrivateGetGetAccessLog(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetGetAccessLog", args...)
}

func (this *DeribitCore) PrivateGetGetAccountSummary(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetGetAccountSummary", args...)
}

func (this *DeribitCore) PrivateGetGetAccountSummaries(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetGetAccountSummaries", args...)
}

func (this *DeribitCore) PrivateGetGetAffiliateProgramInfo(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetGetAffiliateProgramInfo", args...)
}

func (this *DeribitCore) PrivateGetGetEmailLanguage(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetGetEmailLanguage", args...)
}

func (this *DeribitCore) PrivateGetGetNewAnnouncements(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetGetNewAnnouncements", args...)
}

func (this *DeribitCore) PrivateGetGetPortfolioMargins(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetGetPortfolioMargins", args...)
}

func (this *DeribitCore) PrivateGetGetPosition(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetGetPosition", args...)
}

func (this *DeribitCore) PrivateGetGetPositions(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetGetPositions", args...)
}

func (this *DeribitCore) PrivateGetGetSubaccounts(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetGetSubaccounts", args...)
}

func (this *DeribitCore) PrivateGetGetSubaccountsDetails(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetGetSubaccountsDetails", args...)
}

func (this *DeribitCore) PrivateGetGetTransactionLog(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetGetTransactionLog", args...)
}

func (this *DeribitCore) PrivateGetListApiKeys(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetListApiKeys", args...)
}

func (this *DeribitCore) PrivateGetRemoveApiKey(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetRemoveApiKey", args...)
}

func (this *DeribitCore) PrivateGetRemoveSubaccount(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetRemoveSubaccount", args...)
}

func (this *DeribitCore) PrivateGetResetApiKey(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetResetApiKey", args...)
}

func (this *DeribitCore) PrivateGetSetAnnouncementAsRead(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetSetAnnouncementAsRead", args...)
}

func (this *DeribitCore) PrivateGetSetApiKeyAsDefault(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetSetApiKeyAsDefault", args...)
}

func (this *DeribitCore) PrivateGetSetEmailForSubaccount(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetSetEmailForSubaccount", args...)
}

func (this *DeribitCore) PrivateGetSetEmailLanguage(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetSetEmailLanguage", args...)
}

func (this *DeribitCore) PrivateGetSetPasswordForSubaccount(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetSetPasswordForSubaccount", args...)
}

func (this *DeribitCore) PrivateGetToggleNotificationsFromSubaccount(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetToggleNotificationsFromSubaccount", args...)
}

func (this *DeribitCore) PrivateGetToggleSubaccountLogin(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetToggleSubaccountLogin", args...)
}

func (this *DeribitCore) PrivateGetExecuteBlockTrade(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetExecuteBlockTrade", args...)
}

func (this *DeribitCore) PrivateGetGetBlockTrade(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetGetBlockTrade", args...)
}

func (this *DeribitCore) PrivateGetGetLastBlockTradesByCurrency(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetGetLastBlockTradesByCurrency", args...)
}

func (this *DeribitCore) PrivateGetInvalidateBlockTradeSignature(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetInvalidateBlockTradeSignature", args...)
}

func (this *DeribitCore) PrivateGetVerifyBlockTrade(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetVerifyBlockTrade", args...)
}

func (this *DeribitCore) PrivateGetBuy(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetBuy", args...)
}

func (this *DeribitCore) PrivateGetSell(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetSell", args...)
}

func (this *DeribitCore) PrivateGetEdit(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetEdit", args...)
}

func (this *DeribitCore) PrivateGetEditByLabel(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetEditByLabel", args...)
}

func (this *DeribitCore) PrivateGetCancel(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetCancel", args...)
}

func (this *DeribitCore) PrivateGetCancelAll(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetCancelAll", args...)
}

func (this *DeribitCore) PrivateGetCancelAllByCurrency(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetCancelAllByCurrency", args...)
}

func (this *DeribitCore) PrivateGetCancelAllByInstrument(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetCancelAllByInstrument", args...)
}

func (this *DeribitCore) PrivateGetCancelByLabel(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetCancelByLabel", args...)
}

func (this *DeribitCore) PrivateGetClosePosition(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetClosePosition", args...)
}

func (this *DeribitCore) PrivateGetGetMargins(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetGetMargins", args...)
}

func (this *DeribitCore) PrivateGetGetMmpConfig(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetGetMmpConfig", args...)
}

func (this *DeribitCore) PrivateGetGetOpenOrdersByCurrency(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetGetOpenOrdersByCurrency", args...)
}

func (this *DeribitCore) PrivateGetGetOpenOrdersByInstrument(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetGetOpenOrdersByInstrument", args...)
}

func (this *DeribitCore) PrivateGetGetOrderHistoryByCurrency(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetGetOrderHistoryByCurrency", args...)
}

func (this *DeribitCore) PrivateGetGetOrderHistoryByInstrument(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetGetOrderHistoryByInstrument", args...)
}

func (this *DeribitCore) PrivateGetGetOrderMarginByIds(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetGetOrderMarginByIds", args...)
}

func (this *DeribitCore) PrivateGetGetOrderState(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetGetOrderState", args...)
}

func (this *DeribitCore) PrivateGetGetStopOrderHistory(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetGetStopOrderHistory", args...)
}

func (this *DeribitCore) PrivateGetGetTriggerOrderHistory(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetGetTriggerOrderHistory", args...)
}

func (this *DeribitCore) PrivateGetGetUserTradesByCurrency(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetGetUserTradesByCurrency", args...)
}

func (this *DeribitCore) PrivateGetGetUserTradesByCurrencyAndTime(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetGetUserTradesByCurrencyAndTime", args...)
}

func (this *DeribitCore) PrivateGetGetUserTradesByInstrument(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetGetUserTradesByInstrument", args...)
}

func (this *DeribitCore) PrivateGetGetUserTradesByInstrumentAndTime(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetGetUserTradesByInstrumentAndTime", args...)
}

func (this *DeribitCore) PrivateGetGetUserTradesByOrder(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetGetUserTradesByOrder", args...)
}

func (this *DeribitCore) PrivateGetResetMmp(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetResetMmp", args...)
}

func (this *DeribitCore) PrivateGetSetMmpConfig(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetSetMmpConfig", args...)
}

func (this *DeribitCore) PrivateGetGetSettlementHistoryByInstrument(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetGetSettlementHistoryByInstrument", args...)
}

func (this *DeribitCore) PrivateGetGetSettlementHistoryByCurrency(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetGetSettlementHistoryByCurrency", args...)
}

func (this *DeribitCore) PrivateGetCancelTransferById(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetCancelTransferById", args...)
}

func (this *DeribitCore) PrivateGetCancelWithdrawal(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetCancelWithdrawal", args...)
}

func (this *DeribitCore) PrivateGetCreateDepositAddress(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetCreateDepositAddress", args...)
}

func (this *DeribitCore) PrivateGetGetCurrentDepositAddress(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetGetCurrentDepositAddress", args...)
}

func (this *DeribitCore) PrivateGetGetDeposits(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetGetDeposits", args...)
}

func (this *DeribitCore) PrivateGetGetTransfers(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetGetTransfers", args...)
}

func (this *DeribitCore) PrivateGetGetWithdrawals(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetGetWithdrawals", args...)
}

func (this *DeribitCore) PrivateGetSubmitTransferToSubaccount(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetSubmitTransferToSubaccount", args...)
}

func (this *DeribitCore) PrivateGetSubmitTransferToUser(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetSubmitTransferToUser", args...)
}

func (this *DeribitCore) PrivateGetWithdraw(args ...interface{}) <-chan interface{} {
	return this.callEndpointAsync("privateGetWithdraw", args...)
}
