package(default_visibility = ["//visibility:public"])

py_library(
    name = "starknet_api_utils_lib",
    srcs = [
        "api_utils.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//src/starkware/cairo/lang:cairo_constants_lib",
    ],
)
