package base
import "github.com/ccxt/ccxt/go/v4"

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


    func TestWatchMyTrades(exchange ccxt.ICoreExchange, skippedProperties any, symbol any) <- chan any {
                ch := make(chan any)
                go func() any {
                    defer close(ch)
                    defer ReturnPanicError(ch)
                        var method any = "watchMyTrades"
                var now any = exchange.Milliseconds()
                var ends any = Add(now, 15000)
                for IsLessThan(now, ends) {
                    var success any = true
                    var response any = nil
                    
                        {
                             func() (ret_ any) {
                    		    defer func() {
                                    if e := recover(); e != nil {
                                        if e == "break" {
                                            return
                                        }
                                        ret_ = func() any {
                                            // catch block:
                                                        if !IsTrue(IsTemporaryFailure(e)) {
                                    panic(e)
                                }
                                now = exchange.Milliseconds()
                                // continue;
                                success = false
                                            return nil
                                        }()
                                    }
                                }()
                    		    // try block:
                                            
                        response = (UnWrapType(<-exchange.WatchMyTrades(symbol)))
                                    PanicOnError(response)
                    		    return nil
                    	    }()
                        
                            }
                    if IsTrue(IsEqual(success, true)) {
                        AssertNonEmtpyArray(exchange, skippedProperties, method, response, symbol)
                        now = exchange.Milliseconds()
                        for i := 0; IsLessThan(i, GetArrayLength(response)); i++ {
                            TestTrade(exchange, skippedProperties, method, GetValue(response, i), symbol, now)
                        }
                        AssertTimestampOrder(exchange, method, symbol, response)
                    }
                }
            
                ch <- true
                return nil
            
                }()
                return ch
            }
