// Example prompts for the assistant's empty state. /api/prompts samples a few
// server-side so this list never reaches the client bundle.
export const PROMPTS: string[] = [
  "Fetch the BTC/USDT ticker on binance and print the last price",
  "Fetch the ETH/USDT order book on kraken and print the top 5 bids",
  "Load all markets on okx and print how many symbols exist",
  "Fetch 1h OHLCV candles for SOL/USDT on bybit",
  "Fetch the last 50 public trades for BTC/USD on bitstamp",
  "Fetch all tickers on kucoin and print the top 10 by volume",
  "Fetch the exchange status and server time from binance",
  "Fetch currencies on gate and list the ones with deposits disabled",
  "Print the bid ask spread for XRP/USDT on mexc",
  "Fetch the L2 order book for DOGE/USDT on bitget",
  "Fetch daily candles for BTC/USDT on htx for the last 30 days",
  "Fetch trading fees for ETH/USDT on binance",
  "Fetch last prices for a list of symbols on bybit",
  "List every USDT spot market on poloniex",
  "Fetch the ticker for BTC/EUR on bitfinex and show the volume",
  "Compute the mid price from the order book on coinbase",
  "Fetch 5m candles for ADA/USDT on bingx and print the closes",
  "Fetch order book depth of 100 levels for BTC/USDT on whitebit",
  "Print the 24h percentage change for the top movers on binance",
  "Fetch markets on deribit and list all option symbols",
  "Fetch the server time on upbit and compare it with local time",
  "Fetch tickers for three symbols at once on okx",
  "Fetch recent trades on bithumb and compute the buy sell ratio",
  "Fetch weekly candles for ETH/BTC on kraken",
  "List all active swap markets on phemex",
  "Fetch the ticker for BTC/USDT on lbank and print the vwap",
  "Fetch the order book on coinex and compute the total bid volume",
  "Fetch OHLCV for BTC/USDT on cryptocom in the 15m timeframe",
  "Print the top 20 symbols by quote volume on gate",
  "Fetch currencies on kucoin and print the available deposit networks",
  "Check the exchange status on bybit and print the maintenance message",
  "Fetch trades for SOL/USDT on woo and print the last trade price",
  "Build a simple ascii chart from OHLCV closes on binance",
  "Fetch the ticker for BTC/USDT on xt and print bid and ask",
  "Fetch all markets on blofin and count linear versus inverse",
  "Fetch the order book for ETH/USDT on htx with limit 20",
  "Fetch 1m candles for BTC/USDT on binance and print the last candle",
  "Fetch tickers on bitfinex and sort them by percentage change",
  "Fetch the trading fee schedule for all markets on kraken",
  "Print the number of markets per type on okx",
  "Fetch OHLCV for BTC/USD on coinbaseexchange in the 1d timeframe",
  "Fetch the ticker for TON/USDT on bitget and show the high and low",
  "Fetch order books for five symbols on mexc in a loop",
  "Fetch the last price of every BTC market on binance",
  "Fetch trades for ETH/USDT on bybit since one hour ago",
  "Fetch a ticker on paradex and print the mark price",
  "Print all timeframes supported by fetchOHLCV on kucoin",
  "Fetch the withdrawal fee for USDT on gate",
  "Fetch markets on upbit and list all KRW pairs",
  "Fetch a ticker on hyperliquid and print the funding info",
  "Compute the order book imbalance for BTC/USDT on binance",
  "Fetch OHLCV for DOGE/USDT on lbank and compute a 20 period SMA",
  "Fetch the last trade price for every symbol on coinone",
  "Fetch the server time on bitstamp and print it as iso8601",
  "Fetch the order book for BTC/USDT on apex and print the top ask",
  "Fetch my spot balance on binance and print the non zero assets",
  "Create a limit buy order for 0.01 BTC/USDT on kraken",
  "Create a market sell order for 10 XRP on kucoin",
  "Cancel an order by id on okx and print the result",
  "Cancel all open orders for BTC/USDT on bybit",
  "Edit the price of an existing limit order on binance",
  "Fetch a single order by id and print its status on gate",
  "Fetch all open orders on mexc and print their symbols",
  "Fetch closed orders for ETH/USDT on bitget",
  "Fetch canceled orders on kucoin for the last week",
  "Fetch my trades for BTC/USDT on coinbase and sum the fees",
  "Fetch the trades belonging to one order on kraken",
  "Fetch all deposits on binance and print the pending ones",
  "Fetch withdrawal history on htx and print the tx ids",
  "Withdraw USDT from kucoin to an address on the TRC20 network",
  "Fetch the deposit address for BTC on bitfinex",
  "Create a new deposit address for USDT on coinex",
  "Transfer USDT from spot to futures on binance",
  "Fetch the account ledger on okx for the last 24 hours",
  "Fetch all accounts and their ids on coinbase",
  "Create a post only limit order on bybit",
  "Create a reduce only sell order on binanceusdm",
  "Create a stop loss order for BTC/USDT on phemex",
  "Create a trailing percent order on bybit",
  "Create a trailing amount order on binance",
  "Place a limit buy with take profit and stop loss on okx",
  "Create multiple orders in one call on gate",
  "Test an order without actually sending it on binance",
  "Fetch balance on kraken and print free versus used amounts",
  "Fetch my open orders across all symbols on bitstamp",
  "Create an OCO order for BTC/USDT on binance",
  "Cancel all orders then verify none remain on phemex",
  "Compute the total portfolio value in USDT on binance",
  "Fetch deposits and withdrawals and merge them into one list",
  "Create a limit order then cancel it after five seconds on bitget",
  "Fetch the order history for the last month on kucoin",
  "Withdraw ETH from one exchange to another automatically",
  "Fetch my trading fee tier on binance",
  "Fetch the ledger and keep only the fee entries on okx",
  "Create a market buy using a quote amount on binance",
  "Fetch the balance of a sub account on bybit",
  "Fetch open orders and cancel the oldest one on mexc",
  "Create a limit sell above the current price on cryptocom",
  "Fetch closed orders and compute the realized pnl on bybit",
  "Fetch all deposit addresses by network on kucoin",
  "Set leverage to 10x for BTC/USDT on binanceusdm",
  "Set the margin mode to isolated for ETH/USDT on bybit",
  "Fetch all open positions on okx and print the unrealized pnl",
  "Fetch a single position for the BTC/USDT swap on bitget",
  "Fetch the current funding rate for BTC/USDT on binanceusdm",
  "Fetch funding rate history for ETH/USDT on bybit",
  "Fetch my funding payment history on okx",
  "Fetch open interest for the BTC/USDT perpetual on bingx",
  "Fetch the mark price and index price for BTC/USDT on binanceusdm",
  "Fetch leverage tiers for BTC/USDT on bybit",
  "Fetch the borrow rate for USDT on binance margin",
  "Borrow USDT and then repay it on okx margin",
  "Fetch recent liquidations for BTC/USDT on bybit",
  "Fetch settlement history for expired options on deribit",
  "Print the contract size and whether BTC/USD is linear or inverse",
  "Open and then close a perpetual position on krakenfutures",
  "Create a swap order with 5x leverage on phemex",
  "Fetch positions for all symbols on hyperliquid",
  "Fetch the funding interval for BTC/USDT on gate",
  "Fetch option markets and their greeks on deribit",
  "Set leverage and margin mode before placing an order on bitget",
  "Close an open position with a reduce only market order on bybit",
  "Fetch the maintenance margin rate for BTC/USDT on delta",
  "Fetch the liquidation price of my position on binanceusdm",
  "Fetch the perpetual balance on phemex",
  "Fetch coin margined futures positions on binancecoinm",
  "Fetch OHLCV of the mark price for BTC/USDT on binanceusdm",
  "Place a stop order on kucoinfutures",
  "Do a margin loan buy sell and repay cycle on kraken",
  "Fetch open interest history for ETH/USDT on okx",
  "Watch the BTC/USDT ticker on binance and print each update",
  "Watch tickers for several symbols at once on okx",
  "Watch the ETH/USDT order book on bybit and print the best bid",
  "Watch 1m OHLCV candles for BTC/USDT on kucoin",
  "Watch live trades for SOL/USDT on gate",
  "Watch my balance updates on binance",
  "Watch my orders and log every status change on okx",
  "Watch my trades in real time on bybit",
  "Watch positions continuously on binanceusdm",
  "Watch bids and asks for BTC/USDT on binance",
  "Unwatch the order book after ten updates on bybit",
  "Watch order books for five symbols at once on kucoin",
  "Watch trades for many symbols using watchTradesForSymbols on okx",
  "Reconnect automatically when the websocket drops on binance",
  "Close the exchange cleanly after watching tickers on gate",
  "Fetch a balance snapshot and then watch balance updates on binance",
  "Watch OHLCV for many symbols continuously on binance",
  "Watch the order book on coinbase and print the spread live",
  "Stream trades from three exchanges at the same time",
  "Watch tickers on bitget and write each update to a csv",
  "Watch the order book and detect large walls on bybit",
  "Watch orders and cancel any that stay open too long on okx",
  "Watch ticker and ohlcv on bitmex at the same time",
  "Watch only new trades and skip the initial snapshot on binance",
  "Watch positions for specific symbols on bybit",
  "Watch the order book on deribit for an option symbol",
  "Compare watchTicker latency versus fetchTicker on binance",
  "Watch trades on cryptocom and aggregate them into 1m bars",
  "Watch balance on gate and alert when USDT drops",
  "Handle a graceful shutdown while watching order books on okx",
  "Watch many streams from one exchange in parallel on binance",
  "Watch the BTC/USDT order book on hyperliquid",
  "Watch tickers on upbit and print the top gainer every second",
  "Watch my orders on kucoinfutures and print the fills",
  "Watch bids and asks for multiple symbols on bybit",
  "Fetch events on polymarket and print the first ten titles",
  "Search polymarket events by keyword and print their ids",
  "Fetch an event on polymarket and then fetch its ticker",
  "List the active markets on polymarket with their outcomes",
  "Fetch the order book for a kalshi event market",
  "Fetch events on kalshi and print only the open ones",
  "Compare the implied probability of yes and no on polymarket",
  "Fetch trades for a polymarket market and print the sizes",
  "Fetch the outcome token symbols for a polymarket event",
  "Fetch a kalshi ticker and print the yes bid and ask",
  "Fetch polymarket events by tag and show their volume",
  "Print the implied odds for a kalshi election market",
  "Fetch OHLCV history for a polymarket outcome token",
  "Compare the same event on polymarket and kalshi",
  "Fetch kalshi trades and compute the average price",
  "Fetch events on limitless and print the active ones",
  "Fetch prediction market tickers on myriad",
  "Fetch a hyperliquid prediction event and its outcome symbols",
  "Compare the BTC/USDT price across binance bybit and okx",
  "Find the cheapest venue to buy ETH right now",
  "Build a spread scanner across five exchanges",
  "Print a cross exchange arbitrage table for BTC/USDT",
  "Find the symbols common to kraken and coinbase",
  "Compare taker fees on binance kucoin and gate",
  "Compare the exchange.has capabilities of bybit and okx",
  "Rank exchanges by 24h BTC volume",
  "Fetch tickers from many exchanges concurrently with Promise.all",
  "Fetch one order book from three exchanges and compare the depth",
  "Print which exchanges support fetchOHLCV for BTC/USDT",
  "Compare funding rates for BTC perpetuals across three venues",
  "Instantiate every ccxt exchange at once and count them",
  "Search all exchanges for a given symbol",
  "Fetch balances from binance kucoin and okx in parallel",
  "Find the widest bid ask spread among ten exchanges",
  "Compare BTC/USDT candles from binance and bybit side by side",
  "Detect price divergence between htx and mexc for ETH/USDT",
  "List the exchanges that support withdrawals for USDT",
  "Compare withdrawal fees for BTC across four exchanges",
  "Fetch OHLCV from many exchanges continuously and merge them",
  "Build a triangular arbitrage check on binance",
  "List exchanges by country and print their ids",
  "Compare the spot and perpetual price of BTC on bitget",
  "Aggregate order books from three exchanges into one book",
  "Page through OHLCV with since until you reach today on binance",
  "Fetch a full year of daily candles for BTC/USDT on kraken",
  "Paginate fetchMyTrades by id on binance",
  "Fetch trades since a given timestamp on bitfinex",
  "Use parse8601 to turn a date string into a since value",
  "Print an iso8601 timestamp for every candle on okx",
  "Fetch the first available OHLCV timestamp on binance",
  "Loop fetchClosedOrders until there are no more results on kucoin",
  "Fetch one month of 1m candles in chunks on bybit",
  "Paginate the order history by page number on okx",
  "Fetch all trades between two dates on poloniex",
  "Fetch OHLCV with since and limit and save it to csv",
  "Validate that paginated OHLCV has no gaps on gate",
  "Fetch my trades page by page on coinbaseexchange",
  "Fetch funding rate history for the last 90 days on bybit",
  "Wrap a fetchTicker call in try catch for NetworkError and ExchangeError",
  "Retry on RateLimitExceeded with exponential backoff on binance",
  "Enable the built in rate limiter and poll tickers on kucoin",
  "Set a custom timeout of 30 seconds on okx",
  "Retry a failed createOrder up to three times on bybit",
  "Handle InsufficientFunds when placing an order on kraken",
  "Catch OrderNotFound when canceling an order on gate",
  "Switch binance into sandbox mode and place a test order",
  "Route all requests through an http proxy on binance",
  "Turn on verbose mode and inspect the raw request on okx",
  "Check exchange.has before calling fetchOHLCV on any exchange",
  "Handle ExchangeNotAvailable and fall back to another venue",
  "Print the rate limit and adjust it for kucoin",
  "Use a rolling window rate limiter on binance",
  "Catch AuthenticationError and print a helpful message",
  "Load api keys from environment variables safely",
  "Use the bybit testnet endpoints for a paper trade",
  "Add a custom user agent and headers to okx requests",
  "Rotate through several proxies for public requests",
  "Measure request round trip time and log the slow calls",
  "Use amountToPrecision and priceToPrecision before creating an order",
  "Print the minimum order amount and cost for BTC/USDT on binance",
  "Print the base and quote currency of every market on kraken",
  "Convert a unified symbol into an exchange market id on okx",
  "List all deposit networks for USDT on binance",
  "Fetch a convert quote between USDT and BTC on binance",
  "Print the price and amount precision for ETH/USDT on gate",
  "Look up market limits and reject an order that is too small",
  "Map currency codes to their chains on kucoin",
  "Print the market info object for BTC/USDT on bybit",
  "Round an order amount down to the exchange step size",
  "Print the taker and maker fee from market info on mexc",
  "Cache loadMarkets to a file and reuse it later",
];

// Guards against an edit silently dropping entries — this module is server-only.
if (PROMPTS.length !== 256) throw new Error(`prompts: expected 256, got ${PROMPTS.length}`);
