from ccxt.base.types import Entry


class ImplicitAPI:
    public_get_openapi_time = publicGetOpenapiTime = Entry('openapi/time', 'public', 'GET', {'cost': 1})
    public_get_openapi_symbol = publicGetOpenapiSymbol = Entry('openapi/symbol', 'public', 'GET', {'cost': 1})
    public_get_openapi_quote_depth = publicGetOpenapiQuoteDepth = Entry('openapi/quote/depth', 'public', 'GET', {'cost': 1})
    public_get_openapi_quote_trades = publicGetOpenapiQuoteTrades = Entry('openapi/quote/trades', 'public', 'GET', {'cost': 1})
    public_get_openapi_quote_ticker = publicGetOpenapiQuoteTicker = Entry('openapi/quote/ticker', 'public', 'GET', {'cost': 1})
    public_get_openapi_quote_klines = publicGetOpenapiQuoteKlines = Entry('openapi/quote/klines', 'public', 'GET', {'cost': 1})
    public_get_openapi_contract_fundingrate = publicGetOpenapiContractFundingRate = Entry('openapi/contract/fundingRate', 'public', 'GET', {'cost': 1})
    public_get_openapi_contract_fundingrate_history = publicGetOpenapiContractFundingRateHistory = Entry('openapi/contract/fundingRate/history', 'public', 'GET', {'cost': 1})
    public_get_openapi_quote_openinterest = publicGetOpenapiQuoteOpenInterest = Entry('openapi/quote/openInterest', 'public', 'GET', {'cost': 1})
    public_get_openapi_quote_indexprice = publicGetOpenapiQuoteIndexPrice = Entry('openapi/quote/indexPrice', 'public', 'GET', {'cost': 1})
    public_get_openapi_quote_markprice = publicGetOpenapiQuoteMarkPrice = Entry('openapi/quote/markPrice', 'public', 'GET', {'cost': 1})
    public_get_openapi_quote_risklimit = publicGetOpenapiQuoteRiskLimit = Entry('openapi/quote/riskLimit', 'public', 'GET', {'cost': 1})
    public_get_openapi_quote_insurance = publicGetOpenapiQuoteInsurance = Entry('openapi/quote/insurance', 'public', 'GET', {'cost': 1})
    public_get_openapi_quote_liquidationorders = publicGetOpenapiQuoteLiquidationOrders = Entry('openapi/quote/liquidationOrders', 'public', 'GET', {'cost': 1})
    private_get_openapi_contract_account = privateGetOpenapiContractAccount = Entry('openapi/contract/account', 'private', 'GET', {'cost': 1})
    private_get_openapi_contract_order = privateGetOpenapiContractOrder = Entry('openapi/contract/order', 'private', 'GET', {'cost': 1})
    private_get_openapi_contract_order_history = privateGetOpenapiContractOrderHistory = Entry('openapi/contract/order/history', 'private', 'GET', {'cost': 1})
    private_get_openapi_contract_mytrades = privateGetOpenapiContractMyTrades = Entry('openapi/contract/myTrades', 'private', 'GET', {'cost': 1})
    private_get_openapi_contract_positions = privateGetOpenapiContractPositions = Entry('openapi/contract/positions', 'private', 'GET', {'cost': 1})
    private_get_openapi_contract_position_history = privateGetOpenapiContractPositionHistory = Entry('openapi/contract/position/history', 'private', 'GET', {'cost': 1})
    private_get_openapi_contract_asset = privateGetOpenapiContractAsset = Entry('openapi/contract/asset', 'private', 'GET', {'cost': 1})
    private_get_openapi_contract_transfer = privateGetOpenapiContractTransfer = Entry('openapi/contract/transfer', 'private', 'GET', {'cost': 1})
    private_get_openapi_contract_income = privateGetOpenapiContractIncome = Entry('openapi/contract/income', 'private', 'GET', {'cost': 1})
    private_get_openapi_contract_leverage = privateGetOpenapiContractLeverage = Entry('openapi/contract/leverage', 'private', 'GET', {'cost': 1})
    private_get_openapi_contract_forceorders = privateGetOpenapiContractForceOrders = Entry('openapi/contract/forceOrders', 'private', 'GET', {'cost': 1})
    private_get_openapi_contract_adlquantile = privateGetOpenapiContractAdlQuantile = Entry('openapi/contract/adlQuantile', 'private', 'GET', {'cost': 1})
    private_post_openapi_contract_order = privatePostOpenapiContractOrder = Entry('openapi/contract/order', 'private', 'POST', {'cost': 1})
    private_post_openapi_contract_batchorders = privatePostOpenapiContractBatchOrders = Entry('openapi/contract/batchOrders', 'private', 'POST', {'cost': 1})
    private_post_openapi_contract_leverage = privatePostOpenapiContractLeverage = Entry('openapi/contract/leverage', 'private', 'POST', {'cost': 1})
    private_post_openapi_contract_position_margin = privatePostOpenapiContractPositionMargin = Entry('openapi/contract/position/margin', 'private', 'POST', {'cost': 1})
    private_post_openapi_contract_position_risklimit = privatePostOpenapiContractPositionRiskLimit = Entry('openapi/contract/position/riskLimit', 'private', 'POST', {'cost': 1})
    private_post_openapi_contract_openorders = privatePostOpenapiContractOpenOrders = Entry('openapi/contract/openOrders', 'private', 'POST', {'cost': 1})
    private_post_openapi_contract_historyorders = privatePostOpenapiContractHistoryOrders = Entry('openapi/contract/historyOrders', 'private', 'POST', {'cost': 1})
    private_delete_openapi_contract_order_cancel = privateDeleteOpenapiContractOrderCancel = Entry('openapi/contract/order/cancel', 'private', 'DELETE', {'cost': 1})
    private_delete_openapi_contract_batchorders = privateDeleteOpenapiContractBatchOrders = Entry('openapi/contract/batchOrders', 'private', 'DELETE', {'cost': 1})
    private_delete_openapi_contract_allopenorders = privateDeleteOpenapiContractAllOpenOrders = Entry('openapi/contract/allOpenOrders', 'private', 'DELETE', {'cost': 1})
