from ccxt.base.types import Entry
from typing import Any as PythonAny, Dict, List

_List = List[PythonAny]
_Dict = Dict[str, PythonAny]

class ImplicitAPI:
    public_get_api_v1_assets = publicGetApiV1Assets = Entry[_List]('api/v1/assets', 'public', 'GET', {'cost': 1})
    public_get_api_v1_collateral = publicGetApiV1Collateral = Entry[_List]('api/v1/collateral', 'public', 'GET', {'cost': 1})
    public_get_api_v1_borrowlend_markets = publicGetApiV1BorrowLendMarkets = Entry[_List]('api/v1/borrowLend/markets', 'public', 'GET', {'cost': 1})
    public_get_api_v1_borrowlend_markets_history = publicGetApiV1BorrowLendMarketsHistory = Entry[_List]('api/v1/borrowLend/markets/history', 'public', 'GET', {'cost': 1})
    public_get_api_v1_markets = publicGetApiV1Markets = Entry[_List]('api/v1/markets', 'public', 'GET', {'cost': 1})
    public_get_api_v1_market = publicGetApiV1Market = Entry[_Dict]('api/v1/market', 'public', 'GET', {'cost': 1})
    public_get_api_v1_ticker = publicGetApiV1Ticker = Entry[_Dict]('api/v1/ticker', 'public', 'GET', {'cost': 1})
    public_get_api_v1_tickers = publicGetApiV1Tickers = Entry[_List]('api/v1/tickers', 'public', 'GET', {'cost': 1})
    public_get_api_v1_depth = publicGetApiV1Depth = Entry[_Dict]('api/v1/depth', 'public', 'GET', {'cost': 1})
    public_get_api_v1_klines = publicGetApiV1Klines = Entry[_List]('api/v1/klines', 'public', 'GET', {'cost': 1})
    public_get_api_v1_markprices = publicGetApiV1MarkPrices = Entry[_List]('api/v1/markPrices', 'public', 'GET', {'cost': 1})
    public_get_api_v1_openinterest = publicGetApiV1OpenInterest = Entry[_List]('api/v1/openInterest', 'public', 'GET', {'cost': 1})
    public_get_api_v1_fundingrates = publicGetApiV1FundingRates = Entry[_List]('api/v1/fundingRates', 'public', 'GET', {'cost': 1})
    public_get_api_v1_status = publicGetApiV1Status = Entry[_Dict]('api/v1/status', 'public', 'GET', {'cost': 1})
    public_get_api_v1_ping = publicGetApiV1Ping = Entry[str]('api/v1/ping', 'public', 'GET', {'cost': 1})
    public_get_api_v1_time = publicGetApiV1Time = Entry[_List]('api/v1/time', 'public', 'GET', {'cost': 1})
    public_get_api_v1_wallets = publicGetApiV1Wallets = Entry[_List]('api/v1/wallets', 'public', 'GET', {'cost': 1})
    public_get_api_v1_trades = publicGetApiV1Trades = Entry[_List]('api/v1/trades', 'public', 'GET', {'cost': 1})
    public_get_api_v1_trades_history = publicGetApiV1TradesHistory = Entry[_List]('api/v1/trades/history', 'public', 'GET', {'cost': 1})
    private_get_api_v1_account = privateGetApiV1Account = Entry[_Dict]('api/v1/account', 'private', 'GET', {'cost': 1})
    private_get_api_v1_account_limits_borrow = privateGetApiV1AccountLimitsBorrow = Entry[_Dict]('api/v1/account/limits/borrow', 'private', 'GET', {'cost': 1})
    private_get_api_v1_account_limits_order = privateGetApiV1AccountLimitsOrder = Entry[_Dict]('api/v1/account/limits/order', 'private', 'GET', {'cost': 1})
    private_get_api_v1_account_limits_withdrawal = privateGetApiV1AccountLimitsWithdrawal = Entry[_Dict]('api/v1/account/limits/withdrawal', 'private', 'GET', {'cost': 1})
    private_get_api_v1_borrowlend_positions = privateGetApiV1BorrowLendPositions = Entry[_List]('api/v1/borrowLend/positions', 'private', 'GET', {'cost': 1})
    private_get_api_v1_capital = privateGetApiV1Capital = Entry[_Dict]('api/v1/capital', 'private', 'GET', {'cost': 1})
    private_get_api_v1_capital_collateral = privateGetApiV1CapitalCollateral = Entry[_Dict]('api/v1/capital/collateral', 'private', 'GET', {'cost': 1})
    private_get_wapi_v1_capital_deposits = privateGetWapiV1CapitalDeposits = Entry[_List]('wapi/v1/capital/deposits', 'private', 'GET', {'cost': 1})
    private_get_wapi_v1_capital_deposit_address = privateGetWapiV1CapitalDepositAddress = Entry[_Dict]('wapi/v1/capital/deposit/address', 'private', 'GET', {'cost': 1})
    private_get_wapi_v1_capital_withdrawals = privateGetWapiV1CapitalWithdrawals = Entry[_List]('wapi/v1/capital/withdrawals', 'private', 'GET', {'cost': 1})
    private_get_api_v1_position = privateGetApiV1Position = Entry[_List]('api/v1/position', 'private', 'GET', {'cost': 1})
    private_get_wapi_v1_history_borrowlend = privateGetWapiV1HistoryBorrowLend = Entry[_List]('wapi/v1/history/borrowLend', 'private', 'GET', {'cost': 1})
    private_get_wapi_v1_history_interest = privateGetWapiV1HistoryInterest = Entry[_List]('wapi/v1/history/interest', 'private', 'GET', {'cost': 1})
    private_get_wapi_v1_history_borrowlend_positions = privateGetWapiV1HistoryBorrowLendPositions = Entry[_List]('wapi/v1/history/borrowLend/positions', 'private', 'GET', {'cost': 1})
    private_get_wapi_v1_history_dust = privateGetWapiV1HistoryDust = Entry[_List]('wapi/v1/history/dust', 'private', 'GET', {'cost': 1})
    private_get_wapi_v1_history_fills = privateGetWapiV1HistoryFills = Entry[_List]('wapi/v1/history/fills', 'private', 'GET', {'cost': 1})
    private_get_wapi_v1_history_funding = privateGetWapiV1HistoryFunding = Entry[_List]('wapi/v1/history/funding', 'private', 'GET', {'cost': 1})
    private_get_wapi_v1_history_orders = privateGetWapiV1HistoryOrders = Entry[_List]('wapi/v1/history/orders', 'private', 'GET', {'cost': 1})
    private_get_wapi_v1_history_rfq = privateGetWapiV1HistoryRfq = Entry[_List]('wapi/v1/history/rfq', 'private', 'GET', {'cost': 1})
    private_get_wapi_v1_history_quote = privateGetWapiV1HistoryQuote = Entry[_List]('wapi/v1/history/quote', 'private', 'GET', {'cost': 1})
    private_get_wapi_v1_history_settlement = privateGetWapiV1HistorySettlement = Entry[_List]('wapi/v1/history/settlement', 'private', 'GET', {'cost': 1})
    private_get_wapi_v1_history_strategies = privateGetWapiV1HistoryStrategies = Entry[_List]('wapi/v1/history/strategies', 'private', 'GET', {'cost': 1})
    private_get_api_v1_order = privateGetApiV1Order = Entry[_Dict]('api/v1/order', 'private', 'GET', {'cost': 1})
    private_get_api_v1_orders = privateGetApiV1Orders = Entry[_List]('api/v1/orders', 'private', 'GET', {'cost': 1})
    private_post_api_v1_account_convertdust = privatePostApiV1AccountConvertDust = Entry[_Dict]('api/v1/account/convertDust', 'private', 'POST', {'cost': 1})
    private_post_api_v1_borrowlend = privatePostApiV1BorrowLend = Entry[_Dict]('api/v1/borrowLend', 'private', 'POST', {'cost': 1})
    private_post_wapi_v1_capital_withdrawals = privatePostWapiV1CapitalWithdrawals = Entry[_Dict]('wapi/v1/capital/withdrawals', 'private', 'POST', {'cost': 1})
    private_post_api_v1_order = privatePostApiV1Order = Entry[_Dict]('api/v1/order', 'private', 'POST', {'cost': 1})
    private_post_api_v1_orders = privatePostApiV1Orders = Entry[_List]('api/v1/orders', 'private', 'POST', {'cost': 1})
    private_post_api_v1_rfq = privatePostApiV1Rfq = Entry[_Dict]('api/v1/rfq', 'private', 'POST', {'cost': 1})
    private_post_api_v1_rfq_accept = privatePostApiV1RfqAccept = Entry[_Dict]('api/v1/rfq/accept', 'private', 'POST', {'cost': 1})
    private_post_api_v1_rfq_refresh = privatePostApiV1RfqRefresh = Entry[_Dict]('api/v1/rfq/refresh', 'private', 'POST', {'cost': 1})
    private_post_api_v1_rfq_cancel = privatePostApiV1RfqCancel = Entry[_Dict]('api/v1/rfq/cancel', 'private', 'POST', {'cost': 1})
    private_post_api_v1_rfq_quote = privatePostApiV1RfqQuote = Entry[_Dict]('api/v1/rfq/quote', 'private', 'POST', {'cost': 1})
    private_delete_api_v1_order = privateDeleteApiV1Order = Entry[_Dict]('api/v1/order', 'private', 'DELETE', {'cost': 1})
    private_delete_api_v1_orders = privateDeleteApiV1Orders = Entry[_List]('api/v1/orders', 'private', 'DELETE', {'cost': 1})
    private_patch_api_v1_account = privatePatchApiV1Account = Entry[_Dict]('api/v1/account', 'private', 'PATCH', {'cost': 1})
