from ccxt.base.types import Entry


class ImplicitAPI:
    public_get_ping = publicGetPing = Entry('ping', 'public', 'GET', {'cost': 1})
    public_get_asset_pairs = publicGetAssetPairs = Entry('asset_pairs', 'public', 'GET', {'cost': 1})
    public_get_asset_pairs_asset_pair_name_depth = publicGetAssetPairsAssetPairNameDepth = Entry('asset_pairs/{asset_pair_name}/depth', 'public', 'GET', {'cost': 1})
    public_get_asset_pairs_asset_pair_name_trades = publicGetAssetPairsAssetPairNameTrades = Entry('asset_pairs/{asset_pair_name}/trades', 'public', 'GET', {'cost': 1})
    public_get_asset_pairs_asset_pair_name_ticker = publicGetAssetPairsAssetPairNameTicker = Entry('asset_pairs/{asset_pair_name}/ticker', 'public', 'GET', {'cost': 1})
    public_get_asset_pairs_asset_pair_name_candles = publicGetAssetPairsAssetPairNameCandles = Entry('asset_pairs/{asset_pair_name}/candles', 'public', 'GET', {'cost': 1})
    public_get_asset_pairs_tickers = publicGetAssetPairsTickers = Entry('asset_pairs/tickers', 'public', 'GET', {'cost': 1})
    private_get_accounts = privateGetAccounts = Entry('accounts', 'private', 'GET', {'cost': 1})
    private_get_fund_accounts = privateGetFundAccounts = Entry('fund/accounts', 'private', 'GET', {'cost': 1})
    private_get_assets_asset_symbol_address = privateGetAssetsAssetSymbolAddress = Entry('assets/{asset_symbol}/address', 'private', 'GET', {'cost': 1})
    private_get_orders = privateGetOrders = Entry('orders', 'private', 'GET', {'cost': 1})
    private_get_orders_id = privateGetOrdersId = Entry('orders/{id}', 'private', 'GET', {'cost': 1})
    private_get_orders_multi = privateGetOrdersMulti = Entry('orders/multi', 'private', 'GET', {'cost': 1})
    private_get_trades = privateGetTrades = Entry('trades', 'private', 'GET', {'cost': 1})
    private_get_withdrawals = privateGetWithdrawals = Entry('withdrawals', 'private', 'GET', {'cost': 1})
    private_get_deposits = privateGetDeposits = Entry('deposits', 'private', 'GET', {'cost': 1})
    private_post_orders = privatePostOrders = Entry('orders', 'private', 'POST', {'cost': 1})
    private_post_orders_id_cancel = privatePostOrdersIdCancel = Entry('orders/{id}/cancel', 'private', 'POST', {'cost': 1})
    private_post_orders_cancel = privatePostOrdersCancel = Entry('orders/cancel', 'private', 'POST', {'cost': 1})
    private_post_withdrawals = privatePostWithdrawals = Entry('withdrawals', 'private', 'POST', {'cost': 1})
    private_post_transfer = privatePostTransfer = Entry('transfer', 'private', 'POST', {'cost': 1})
    contractpublic_get_symbols = contractPublicGetSymbols = Entry('symbols', 'contractPublic', 'GET', {'cost': 1})
    contractpublic_get_instruments = contractPublicGetInstruments = Entry('instruments', 'contractPublic', 'GET', {'cost': 1})
    contractpublic_get_depth_symbol_snapshot = contractPublicGetDepthSymbolSnapshot = Entry('depth@{symbol}/snapshot', 'contractPublic', 'GET', {'cost': 1})
    contractpublic_get_instruments_difference = contractPublicGetInstrumentsDifference = Entry('instruments/difference', 'contractPublic', 'GET', {'cost': 1})
    contractpublic_get_instruments_prices = contractPublicGetInstrumentsPrices = Entry('instruments/prices', 'contractPublic', 'GET', {'cost': 1})
    contractprivate_get_accounts = contractPrivateGetAccounts = Entry('accounts', 'contractPrivate', 'GET', {'cost': 1})
    contractprivate_get_orders_id = contractPrivateGetOrdersId = Entry('orders/{id}', 'contractPrivate', 'GET', {'cost': 1})
    contractprivate_get_orders = contractPrivateGetOrders = Entry('orders', 'contractPrivate', 'GET', {'cost': 1})
    contractprivate_get_orders_opening = contractPrivateGetOrdersOpening = Entry('orders/opening', 'contractPrivate', 'GET', {'cost': 1})
    contractprivate_get_orders_count = contractPrivateGetOrdersCount = Entry('orders/count', 'contractPrivate', 'GET', {'cost': 1})
    contractprivate_get_orders_opening_count = contractPrivateGetOrdersOpeningCount = Entry('orders/opening/count', 'contractPrivate', 'GET', {'cost': 1})
    contractprivate_get_trades = contractPrivateGetTrades = Entry('trades', 'contractPrivate', 'GET', {'cost': 1})
    contractprivate_get_trades_count = contractPrivateGetTradesCount = Entry('trades/count', 'contractPrivate', 'GET', {'cost': 1})
    contractprivate_post_orders = contractPrivatePostOrders = Entry('orders', 'contractPrivate', 'POST', {'cost': 1})
    contractprivate_post_orders_batch = contractPrivatePostOrdersBatch = Entry('orders/batch', 'contractPrivate', 'POST', {'cost': 1})
    contractprivate_put_positions_symbol_margin = contractPrivatePutPositionsSymbolMargin = Entry('positions/{symbol}/margin', 'contractPrivate', 'PUT', {'cost': 1})
    contractprivate_put_positions_symbol_risk_limit = contractPrivatePutPositionsSymbolRiskLimit = Entry('positions/{symbol}/risk-limit', 'contractPrivate', 'PUT', {'cost': 1})
    contractprivate_delete_orders_id = contractPrivateDeleteOrdersId = Entry('orders/{id}', 'contractPrivate', 'DELETE', {'cost': 1})
    contractprivate_delete_orders_batch = contractPrivateDeleteOrdersBatch = Entry('orders/batch', 'contractPrivate', 'DELETE', {'cost': 1})
    webexchange_get_v3_assets = webExchangeGetV3Assets = Entry('v3/assets', 'webExchange', 'GET', {'cost': 1})
