from ccxt.base.types import Entry
from typing import Any as PythonAny, Dict, List

_List = List[PythonAny]
_Dict = Dict[str, PythonAny]

class ImplicitAPI:
    www_get_order_fetchmarkets = wwwGetOrderFetchMarkets = Entry[_List]('order/fetchMarkets', 'www', 'GET', {'cost': 1})
    www_get_order_fetchtickers = wwwGetOrderFetchTickers = Entry[_Dict]('order/fetchTickers', 'www', 'GET', {'cost': 1})
    www_get_order_fetchorderbook = wwwGetOrderFetchOrderbook = Entry[_Dict]('order/fetchOrderbook', 'www', 'GET', {'cost': 1})
    www_get_order_gettickerwithvolume = wwwGetOrderGetTickerWithVolume = Entry[_Dict]('order/getTickerWithVolume', 'www', 'GET', {'cost': 1})
    www_get_exchangedata_ohlc = wwwGetExchangeDataOhlc = Entry[_List]('exchangeData/ohlc', 'www', 'GET', {'cost': 1})
    www_get_exchangedata_orderbook = wwwGetExchangeDataOrderBook = Entry[_Dict]('exchangeData/orderBook', 'www', 'GET', {'cost': 1})
    www_get_exchangedata_tradedetails = wwwGetExchangeDataTradedetails = Entry[_List]('exchangeData/tradedetails', 'www', 'GET', {'cost': 1})
    v1_get_platform_status = v1GetPlatformStatus = Entry[_Dict]('platform/status', 'v1', 'GET', {'cost': 1})
    v1_get_tickers = v1GetTickers = Entry[_Dict]('tickers', 'v1', 'GET', {'cost': 1})
    v1_get_orderbook_sell_symbol = v1GetOrderbookSellSymbol = Entry[_Dict]('orderbook/sell/{symbol}', 'v1', 'GET', {'cost': 1})
    v1_get_orderbook_buy_symbol = v1GetOrderbookBuySymbol = Entry[_Dict]('orderbook/buy/{symbol}', 'v1', 'GET', {'cost': 1})
    v1_post_currentcoinbalance_everything = v1PostCurrentCoinBalanceEVERYTHING = Entry[_Dict]('currentCoinBalance/EVERYTHING', 'v1', 'POST', {'cost': 1})
    v1_post_getapiusagestatus_usage = v1PostGetApiUsageStatusUSAGE = Entry[_Dict]('getApiUsageStatus/USAGE', 'v1', 'POST', {'cost': 1})
    v1_post_getordersockettoken_usage = v1PostGetOrderSocketTokenUSAGE = Entry[_Dict]('getOrderSocketToken/USAGE', 'v1', 'POST', {'cost': 1})
    v1_post_currentcoinbalance_symbol = v1PostCurrentCoinBalanceSymbol = Entry[_Dict]('currentCoinBalance/{symbol}', 'v1', 'POST', {'cost': 1})
    v1_post_orderstatus_symbol = v1PostOrderStatusSymbol = Entry[_Dict]('orderStatus/{symbol}', 'v1', 'POST', {'cost': 1})
    v1_post_deposithistory_symbol = v1PostDepositHistorySymbol = Entry[_Dict]('depositHistory/{symbol}', 'v1', 'POST', {'cost': 1})
    v1_post_withdrawhistory_symbol = v1PostWithdrawHistorySymbol = Entry[_Dict]('withdrawHistory/{symbol}', 'v1', 'POST', {'cost': 1})
    v1_post_withdrawhistoryall_symbol = v1PostWithdrawHistoryAllSymbol = Entry[_Dict]('withdrawHistoryAll/{symbol}', 'v1', 'POST', {'cost': 1})
    v1_post_deposithistoryall_symbol = v1PostDepositHistoryAllSymbol = Entry[_Dict]('depositHistoryAll/{symbol}', 'v1', 'POST', {'cost': 1})
    v1_post_listopenorders_symbol = v1PostListOpenOrdersSymbol = Entry[_Dict]('listOpenOrders/{symbol}', 'v1', 'POST', {'cost': 1})
    v1_post_listopenstoporders_symbol = v1PostListOpenStopOrdersSymbol = Entry[_Dict]('listOpenStopOrders/{symbol}', 'v1', 'POST', {'cost': 1})
    v1_post_getcoinaddress_symbol = v1PostGetCoinAddressSymbol = Entry[_Dict]('getCoinAddress/{symbol}', 'v1', 'POST', {'cost': 1})
    v1_post_placesellorder_symbol = v1PostPlaceSellOrderSymbol = Entry[_Dict]('placeSellOrder/{symbol}', 'v1', 'POST', {'cost': 1})
    v1_post_placebuyorder_symbol = v1PostPlaceBuyOrderSymbol = Entry[_Dict]('placeBuyOrder/{symbol}', 'v1', 'POST', {'cost': 1})
    v1_post_buystoploss_symbol = v1PostBuyStopLossSymbol = Entry[_Dict]('buyStopLoss/{symbol}', 'v1', 'POST', {'cost': 1})
    v1_post_sellstoploss_symbol = v1PostSellStopLossSymbol = Entry[_Dict]('sellStopLoss/{symbol}', 'v1', 'POST', {'cost': 1})
    v1_post_cancelorder_symbol = v1PostCancelOrderSymbol = Entry[_Dict]('cancelOrder/{symbol}', 'v1', 'POST', {'cost': 1})
    v1_post_cancelstoplossorder_symbol = v1PostCancelStopLossOrderSymbol = Entry[_Dict]('cancelStopLossOrder/{symbol}', 'v1', 'POST', {'cost': 1})
    v1_post_listexecutedorders_symbol = v1PostListExecutedOrdersSymbol = Entry[_Dict]('listExecutedOrders/{symbol}', 'v1', 'POST', {'cost': 1})
    v1_post_placemarketorder_symbol = v1PostPlaceMarketOrderSymbol = Entry[_Dict]('placeMarketOrder/{symbol}', 'v1', 'POST', {'cost': 1})
    v1_post_placemarketorderqnty_symbol = v1PostPlaceMarketOrderQntySymbol = Entry[_Dict]('placeMarketOrderQnty/{symbol}', 'v1', 'POST', {'cost': 1})
    v2_post_orders = v2PostOrders = Entry[_Dict]('orders', 'v2', 'POST', {'cost': 1})
    v2_post_cancel = v2PostCancel = Entry[_Dict]('cancel', 'v2', 'POST', {'cost': 1})
    v2_post_getordersnew = v2PostGetordersnew = Entry[_Dict]('getordersnew', 'v2', 'POST', {'cost': 1})
    v2_post_marginorders = v2PostMarginOrders = Entry[_Dict]('marginOrders', 'v2', 'POST', {'cost': 1})
