from ccxt.base.types import Entry
from typing import Any as PythonAny, Dict, List

_List = List[PythonAny]
_Dict = Dict[str, PythonAny]

class ImplicitAPI:
    public_get_getmarkets_usa = publicGetGetmarketsUsa = Entry[_List]('getmarkets/usa', 'public', 'GET', {'cost': 1})
    public_get_getmarkets_eu = publicGetGetmarketsEu = Entry[_List]('getmarkets/eu', 'public', 'GET', {'cost': 1})
    public_get_getmarkets = publicGetGetmarkets = Entry[_List]('getmarkets', 'public', 'GET', {'cost': 1})
    public_get_getboard = publicGetGetboard = Entry[_Dict]('getboard', 'public', 'GET', {'cost': 1})
    public_get_getticker = publicGetGetticker = Entry[_Dict]('getticker', 'public', 'GET', {'cost': 1})
    public_get_getexecutions = publicGetGetexecutions = Entry[_List]('getexecutions', 'public', 'GET', {'cost': 1})
    public_get_gethealth = publicGetGethealth = Entry[_Dict]('gethealth', 'public', 'GET', {'cost': 1})
    public_get_getboardstate = publicGetGetboardstate = Entry[_Dict]('getboardstate', 'public', 'GET', {'cost': 1})
    public_get_getchats = publicGetGetchats = Entry[_List]('getchats', 'public', 'GET', {'cost': 1})
    public_get_getfundingrate = publicGetGetfundingrate = Entry[_Dict]('getfundingrate', 'public', 'GET', {'cost': 1})
    private_get_getpermissions = privateGetGetpermissions = Entry[_List]('getpermissions', 'private', 'GET', {'cost': 1})
    private_get_getbalance = privateGetGetbalance = Entry[_Dict]('getbalance', 'private', 'GET', {'cost': 1})
    private_get_getbalancehistory = privateGetGetbalancehistory = Entry[_List]('getbalancehistory', 'private', 'GET', {'cost': 1})
    private_get_getcollateral = privateGetGetcollateral = Entry[_Dict]('getcollateral', 'private', 'GET', {'cost': 1})
    private_get_getcollateralhistory = privateGetGetcollateralhistory = Entry[_List]('getcollateralhistory', 'private', 'GET', {'cost': 1})
    private_get_getcollateralaccounts = privateGetGetcollateralaccounts = Entry[_List]('getcollateralaccounts', 'private', 'GET', {'cost': 1})
    private_get_getaddresses = privateGetGetaddresses = Entry[_List]('getaddresses', 'private', 'GET', {'cost': 1})
    private_get_getcoinins = privateGetGetcoinins = Entry[_List]('getcoinins', 'private', 'GET', {'cost': 1})
    private_get_getcoinouts = privateGetGetcoinouts = Entry[_List]('getcoinouts', 'private', 'GET', {'cost': 1})
    private_get_getbankaccounts = privateGetGetbankaccounts = Entry[_List]('getbankaccounts', 'private', 'GET', {'cost': 1})
    private_get_getdeposits = privateGetGetdeposits = Entry[_List]('getdeposits', 'private', 'GET', {'cost': 1})
    private_get_getwithdrawals = privateGetGetwithdrawals = Entry[_List]('getwithdrawals', 'private', 'GET', {'cost': 1})
    private_get_getchildorders = privateGetGetchildorders = Entry[_List]('getchildorders', 'private', 'GET', {'cost': 1})
    private_get_getparentorders = privateGetGetparentorders = Entry[_List]('getparentorders', 'private', 'GET', {'cost': 1})
    private_get_getparentorder = privateGetGetparentorder = Entry[_Dict]('getparentorder', 'private', 'GET', {'cost': 1})
    private_get_getexecutions = privateGetGetexecutions = Entry[_List]('getexecutions', 'private', 'GET', {'cost': 1})
    private_get_getpositions = privateGetGetpositions = Entry[_List]('getpositions', 'private', 'GET', {'cost': 1})
    private_get_gettradingcommission = privateGetGettradingcommission = Entry[_Dict]('gettradingcommission', 'private', 'GET', {'cost': 1})
    private_post_sendcoin = privatePostSendcoin = Entry[_Dict]('sendcoin', 'private', 'POST', {'cost': 1})
    private_post_withdraw = privatePostWithdraw = Entry[_Dict]('withdraw', 'private', 'POST', {'cost': 1})
    private_post_sendchildorder = privatePostSendchildorder = Entry[_Dict]('sendchildorder', 'private', 'POST', {'cost': 1})
    private_post_cancelchildorder = privatePostCancelchildorder = Entry[_Dict]('cancelchildorder', 'private', 'POST', {'cost': 1})
    private_post_sendparentorder = privatePostSendparentorder = Entry[_Dict]('sendparentorder', 'private', 'POST', {'cost': 1})
    private_post_cancelparentorder = privatePostCancelparentorder = Entry[_Dict]('cancelparentorder', 'private', 'POST', {'cost': 1})
    private_post_cancelallchildorders = privatePostCancelallchildorders = Entry[_Dict]('cancelallchildorders', 'private', 'POST', {'cost': 1})
