from ccxt.base.types import Entry
_Dict = dict[str, object]
_List = list[object]


class ImplicitAPI:
    public_get_public_ticker_all_quoteid = publicGetPublicTickerALLQuoteId = Entry[_Dict]('public/ticker/ALL_{quoteId}', 'public', 'GET', {'cost': 1})
    public_get_public_ticker_baseid_quoteid = publicGetPublicTickerBaseIdQuoteId = Entry[_Dict]('public/ticker/{baseId}_{quoteId}', 'public', 'GET', {'cost': 1})
    public_get_public_orderbook_all_quoteid = publicGetPublicOrderbookALLQuoteId = Entry[_Dict]('public/orderbook/ALL_{quoteId}', 'public', 'GET', {'cost': 1})
    public_get_public_orderbook_baseid_quoteid = publicGetPublicOrderbookBaseIdQuoteId = Entry[_Dict]('public/orderbook/{baseId}_{quoteId}', 'public', 'GET', {'cost': 1})
    public_get_public_transaction_history_baseid_quoteid = publicGetPublicTransactionHistoryBaseIdQuoteId = Entry[_Dict]('public/transaction_history/{baseId}_{quoteId}', 'public', 'GET', {'cost': 1})
    public_get_public_network_info = publicGetPublicNetworkInfo = Entry[_Dict]('public/network-info', 'public', 'GET', {'cost': 1})
    public_get_public_assetsstatus_multichain_all = publicGetPublicAssetsstatusMultichainALL = Entry[_Dict]('public/assetsstatus/multichain/ALL', 'public', 'GET', {'cost': 1})
    public_get_public_assetsstatus_multichain_currency = publicGetPublicAssetsstatusMultichainCurrency = Entry[_Dict]('public/assetsstatus/multichain/{currency}', 'public', 'GET', {'cost': 1})
    public_get_public_withdraw_minimum_all = publicGetPublicWithdrawMinimumALL = Entry[_Dict]('public/withdraw/minimum/ALL', 'public', 'GET', {'cost': 1})
    public_get_public_withdraw_minimum_currency = publicGetPublicWithdrawMinimumCurrency = Entry[_Dict]('public/withdraw/minimum/{currency}', 'public', 'GET', {'cost': 1})
    public_get_public_assetsstatus_all = publicGetPublicAssetsstatusALL = Entry[_Dict]('public/assetsstatus/ALL', 'public', 'GET', {'cost': 1})
    public_get_public_assetsstatus_baseid = publicGetPublicAssetsstatusBaseId = Entry[_Dict]('public/assetsstatus/{baseId}', 'public', 'GET', {'cost': 1})
    public_get_public_candlestick_baseid_quoteid_interval = publicGetPublicCandlestickBaseIdQuoteIdInterval = Entry[_Dict]('public/candlestick/{baseId}_{quoteId}/{interval}', 'public', 'GET', {'cost': 1})
    public_get_v1_market_all = publicGetV1MarketAll = Entry[_List]('v1/market/all', 'public', 'GET', {'cost': 1})
    public_get_v1_candles_minutes_unit = publicGetV1CandlesMinutesUnit = Entry[_List]('v1/candles/minutes/{unit}', 'public', 'GET', {'cost': 1})
    public_get_v1_candles_days = publicGetV1CandlesDays = Entry[_List]('v1/candles/days', 'public', 'GET', {'cost': 1})
    public_get_v1_candles_weeks = publicGetV1CandlesWeeks = Entry[_List]('v1/candles/weeks', 'public', 'GET', {'cost': 1})
    public_get_v1_candles_months = publicGetV1CandlesMonths = Entry[_List]('v1/candles/months', 'public', 'GET', {'cost': 1})
    public_get_v1_trades_ticks = publicGetV1TradesTicks = Entry[_List]('v1/trades/ticks', 'public', 'GET', {'cost': 1})
    public_get_v1_ticker = publicGetV1Ticker = Entry[_List]('v1/ticker', 'public', 'GET', {'cost': 1})
    public_get_v1_orderbook = publicGetV1Orderbook = Entry[_List]('v1/orderbook', 'public', 'GET', {'cost': 1})
    public_get_v1_market_virtual_asset_warning = publicGetV1MarketVirtualAssetWarning = Entry[_Dict | _List]('v1/market/virtual_asset_warning', 'public', 'GET', {'cost': 1})
    public_get_v1_notices = publicGetV1Notices = Entry[_Dict | _List]('v1/notices', 'public', 'GET', {'cost': 1})
    public_get_v2_fee_inout_currency = publicGetV2FeeInoutCurrency = Entry[_Dict]('v2/fee/inout/{currency}', 'public', 'GET', {'cost': 1})
    private_get_v1_accounts = privateGetV1Accounts = Entry[_List]('v1/accounts', 'private', 'GET', {'cost': 1})
    private_get_v1_orders_chance = privateGetV1OrdersChance = Entry[_Dict]('v1/orders/chance', 'private', 'GET', {'cost': 1})
    private_get_v1_order = privateGetV1Order = Entry[_Dict]('v1/order', 'private', 'GET', {'cost': 1})
    private_get_v1_orders = privateGetV1Orders = Entry[_List]('v1/orders', 'private', 'GET', {'cost': 1})
    private_get_v1_twap = privateGetV1Twap = Entry[_Dict]('v1/twap', 'private', 'GET', {'cost': 1})
    private_get_v1_withdraws = privateGetV1Withdraws = Entry[_List]('v1/withdraws', 'private', 'GET', {'cost': 1})
    private_get_v1_withdraws_krw = privateGetV1WithdrawsKrw = Entry[_List]('v1/withdraws/krw', 'private', 'GET', {'cost': 1})
    private_get_v1_withdraw = privateGetV1Withdraw = Entry[_Dict]('v1/withdraw', 'private', 'GET', {'cost': 1})
    private_get_v1_withdraws_chance = privateGetV1WithdrawsChance = Entry[_Dict]('v1/withdraws/chance', 'private', 'GET', {'cost': 1})
    private_get_v1_withdraws_coin_addresses = privateGetV1WithdrawsCoinAddresses = Entry[_List]('v1/withdraws/coin_addresses', 'private', 'GET', {'cost': 1})
    private_get_v1_deposits = privateGetV1Deposits = Entry[_List]('v1/deposits', 'private', 'GET', {'cost': 1})
    private_get_v1_deposits_krw = privateGetV1DepositsKrw = Entry[_List]('v1/deposits/krw', 'private', 'GET', {'cost': 1})
    private_get_v1_deposit = privateGetV1Deposit = Entry[_Dict]('v1/deposit', 'private', 'GET', {'cost': 1})
    private_get_v1_deposits_coin_addresses = privateGetV1DepositsCoinAddresses = Entry[_List]('v1/deposits/coin_addresses', 'private', 'GET', {'cost': 1})
    private_get_v1_deposits_coin_address = privateGetV1DepositsCoinAddress = Entry[_Dict]('v1/deposits/coin_address', 'private', 'GET', {'cost': 1})
    private_get_v1_status_wallet = privateGetV1StatusWallet = Entry[_Dict | _List]('v1/status/wallet', 'private', 'GET', {'cost': 1})
    private_get_v1_api_keys = privateGetV1ApiKeys = Entry[_Dict | _List]('v1/api_keys', 'private', 'GET', {'cost': 1})
    private_post_info_account = privatePostInfoAccount = Entry[_Dict]('info/account', 'private', 'POST', {'cost': 1})
    private_post_info_balance = privatePostInfoBalance = Entry[_Dict]('info/balance', 'private', 'POST', {'cost': 1})
    private_post_info_wallet_address = privatePostInfoWalletAddress = Entry[_Dict]('info/wallet_address', 'private', 'POST', {'cost': 1})
    private_post_info_ticker = privatePostInfoTicker = Entry[_Dict]('info/ticker', 'private', 'POST', {'cost': 1})
    private_post_info_orders = privatePostInfoOrders = Entry[_Dict]('info/orders', 'private', 'POST', {'cost': 1})
    private_post_info_user_transactions = privatePostInfoUserTransactions = Entry[_Dict]('info/user_transactions', 'private', 'POST', {'cost': 1})
    private_post_info_order_detail = privatePostInfoOrderDetail = Entry[_Dict]('info/order_detail', 'private', 'POST', {'cost': 1})
    private_post_trade_place = privatePostTradePlace = Entry[_Dict]('trade/place', 'private', 'POST', {'cost': 5})
    private_post_trade_cancel = privatePostTradeCancel = Entry[_Dict]('trade/cancel', 'private', 'POST', {'cost': 5})
    private_post_trade_btc_withdrawal = privatePostTradeBtcWithdrawal = Entry[_Dict]('trade/btc_withdrawal', 'private', 'POST', {'cost': 1})
    private_post_trade_krw_deposit = privatePostTradeKrwDeposit = Entry[_Dict]('trade/krw_deposit', 'private', 'POST', {'cost': 1})
    private_post_trade_krw_withdrawal = privatePostTradeKrwWithdrawal = Entry[_Dict]('trade/krw_withdrawal', 'private', 'POST', {'cost': 1})
    private_post_trade_market_buy = privatePostTradeMarketBuy = Entry[_Dict]('trade/market_buy', 'private', 'POST', {'cost': 1})
    private_post_trade_market_sell = privatePostTradeMarketSell = Entry[_Dict]('trade/market_sell', 'private', 'POST', {'cost': 1})
    private_post_trade_stop_limit = privatePostTradeStopLimit = Entry[_Dict]('trade/stop_limit', 'private', 'POST', {'cost': 1})
    private_post_v2_orders = privatePostV2Orders = Entry[_Dict]('v2/orders', 'private', 'POST', {'cost': 1})
    private_post_v2_orders_batch = privatePostV2OrdersBatch = Entry[_Dict]('v2/orders/batch', 'private', 'POST', {'cost': 6})
    private_post_v2_orders_cancel = privatePostV2OrdersCancel = Entry[_Dict]('v2/orders/cancel', 'private', 'POST', {'cost': 6})
    private_post_v1_twap = privatePostV1Twap = Entry[_Dict]('v1/twap', 'private', 'POST', {'cost': 1})
    private_post_v1_withdraws_coin = privatePostV1WithdrawsCoin = Entry[_Dict]('v1/withdraws/coin', 'private', 'POST', {'cost': 1})
    private_post_v1_withdraws_krw = privatePostV1WithdrawsKrw = Entry[_Dict]('v1/withdraws/krw', 'private', 'POST', {'cost': 1})
    private_post_v1_deposits_generate_coin_address = privatePostV1DepositsGenerateCoinAddress = Entry[_Dict]('v1/deposits/generate_coin_address', 'private', 'POST', {'cost': 1})
    private_post_v1_deposits_krw = privatePostV1DepositsKrw = Entry[_Dict]('v1/deposits/krw', 'private', 'POST', {'cost': 1})
    private_delete_v2_order = privateDeleteV2Order = Entry[_Dict]('v2/order', 'private', 'DELETE', {'cost': 1})
    private_delete_v1_twap = privateDeleteV1Twap = Entry[_Dict]('v1/twap', 'private', 'DELETE', {'cost': 1})
    private_delete_v1_withdraws_coin = privateDeleteV1WithdrawsCoin = Entry[_Dict]('v1/withdraws/coin', 'private', 'DELETE', {'cost': 1})
