from ccxt.base.types import Entry
from typing import Any as PythonAny, Dict, List, Union

_Dict = Dict[str, PythonAny]
_List = List[PythonAny]

class ImplicitAPI:
    spot_kline_public_get_public_json = spotKlinePublicGetPublicJson = Entry[_Dict]('public.json', ['spot', 'kline', 'public'], 'GET', {'cost': 0.24})
    spot_kline_public_get_public_currency_json = spotKlinePublicGetPublicCurrencyJson = Entry[_Dict]('public{currency}.json', ['spot', 'kline', 'public'], 'GET', {'cost': 0.24})
    spot_v1_public_get_ping = spotV1PublicGetPing = Entry[_Dict]('ping', ['spot', 'v1', 'public'], 'GET', {'cost': 0.24})
    spot_v1_public_get_time = spotV1PublicGetTime = Entry[_Dict]('time', ['spot', 'v1', 'public'], 'GET', {'cost': 0.24})
    spot_v1_public_get_exchangeinfo = spotV1PublicGetExchangeInfo = Entry[_Dict]('exchangeInfo', ['spot', 'v1', 'public'], 'GET', {'cost': 0.24})
    spot_v1_public_get_depth = spotV1PublicGetDepth = Entry[_Dict]('depth', ['spot', 'v1', 'public'], 'GET', {'cost': 1, 'byLimit': [[100, 0.24], [500, 1.2], [1000, 2.4]]})
    spot_v1_public_get_trades = spotV1PublicGetTrades = Entry[_List]('trades', ['spot', 'v1', 'public'], 'GET', {'cost': 0.24})
    spot_v1_public_get_historicaltrades = spotV1PublicGetHistoricalTrades = Entry[_List]('historicalTrades', ['spot', 'v1', 'public'], 'GET', {'cost': 1.2})
    spot_v1_public_get_aggtrades = spotV1PublicGetAggTrades = Entry[_List]('aggTrades', ['spot', 'v1', 'public'], 'GET', {'cost': 0.24})
    spot_v1_public_get_ticker_24hr = spotV1PublicGetTicker24hr = Entry[_List]('ticker/24hr', ['spot', 'v1', 'public'], 'GET', {'cost': 0.24, 'noSymbol': 9.6})
    spot_v1_public_get_ticker_price = spotV1PublicGetTickerPrice = Entry[_Dict]('ticker/price', ['spot', 'v1', 'public'], 'GET', {'cost': 0.24})
    spot_v1_public_get_ticker_bookticker = spotV1PublicGetTickerBookTicker = Entry[_Dict]('ticker/bookTicker', ['spot', 'v1', 'public'], 'GET', {'cost': 0.24})
    spot_v1_public_get_market_kline = spotV1PublicGetMarketKline = Entry[_Dict]('market/kline', ['spot', 'v1', 'public'], 'GET', {'cost': 0.24})
    spot_v1_private_get_order = spotV1PrivateGetOrder = Entry[_Dict]('order', ['spot', 'v1', 'private'], 'GET', {'cost': 5})
    spot_v1_private_get_openorders = spotV1PrivateGetOpenOrders = Entry[_Dict]('openOrders', ['spot', 'v1', 'private'], 'GET', {'cost': 5})
    spot_v1_private_get_allorders = spotV1PrivateGetAllOrders = Entry[_List]('allOrders', ['spot', 'v1', 'private'], 'GET', {'cost': 25})
    spot_v1_private_get_account = spotV1PrivateGetAccount = Entry[_Dict]('account', ['spot', 'v1', 'private'], 'GET', {'cost': 25})
    spot_v1_private_get_mytrades = spotV1PrivateGetMyTrades = Entry[_List]('myTrades', ['spot', 'v1', 'private'], 'GET', {'cost': 25})
    spot_v1_private_get_etf_net_value_symbol = spotV1PrivateGetEtfNetValueSymbol = Entry[_Dict]('etf/net-value/{symbol}', ['spot', 'v1', 'private'], 'GET', {'cost': 0.24})
    spot_v1_private_get_withdraw_history = spotV1PrivateGetWithdrawHistory = Entry[_Dict]('withdraw/history', ['spot', 'v1', 'private'], 'GET', {'cost': 120})
    spot_v1_private_get_deposit_history = spotV1PrivateGetDepositHistory = Entry[_Dict]('deposit/history', ['spot', 'v1', 'private'], 'GET', {'cost': 120})
    spot_v1_private_post_order = spotV1PrivatePostOrder = Entry[_Dict]('order', ['spot', 'v1', 'private'], 'POST', {'cost': 5})
    spot_v1_private_post_withdraw_commit = spotV1PrivatePostWithdrawCommit = Entry[_Dict]('withdraw/commit', ['spot', 'v1', 'private'], 'POST', {'cost': 120})
    spot_v1_private_delete_order = spotV1PrivateDeleteOrder = Entry[_Dict]('order', ['spot', 'v1', 'private'], 'DELETE', {'cost': 5})
    spot_v2_private_get_mytrades = spotV2PrivateGetMyTrades = Entry[_Dict]('myTrades', ['spot', 'v2', 'private'], 'GET', {'cost': 1.2})
    fapi_v1_public_get_ping = fapiV1PublicGetPing = Entry[_Dict]('ping', ['fapi', 'v1', 'public'], 'GET', {'cost': 0.24})
    fapi_v1_public_get_time = fapiV1PublicGetTime = Entry[_Dict]('time', ['fapi', 'v1', 'public'], 'GET', {'cost': 0.24})
    fapi_v1_public_get_contracts = fapiV1PublicGetContracts = Entry[_List]('contracts', ['fapi', 'v1', 'public'], 'GET', {'cost': 0.24})
    fapi_v1_public_get_depth = fapiV1PublicGetDepth = Entry[_Dict]('depth', ['fapi', 'v1', 'public'], 'GET', {'cost': 0.24})
    fapi_v1_public_get_ticker = fapiV1PublicGetTicker = Entry[Union[_Dict, _List]]('ticker', ['fapi', 'v1', 'public'], 'GET', {'cost': 0.24})
    fapi_v1_public_get_klines = fapiV1PublicGetKlines = Entry[_List]('klines', ['fapi', 'v1', 'public'], 'GET', {'cost': 0.24})
    fapi_v2_private_get_mytrades = fapiV2PrivateGetMyTrades = Entry[_Dict]('myTrades', ['fapi', 'v2', 'private'], 'GET', {'cost': 5})
    fapi_v2_private_get_openorders = fapiV2PrivateGetOpenOrders = Entry[_Dict]('openOrders', ['fapi', 'v2', 'private'], 'GET', {'cost': 5})
    fapi_v2_private_get_order = fapiV2PrivateGetOrder = Entry[_Dict]('order', ['fapi', 'v2', 'private'], 'GET', {'cost': 5})
    fapi_v2_private_get_account = fapiV2PrivateGetAccount = Entry[_Dict]('account', ['fapi', 'v2', 'private'], 'GET', {'cost': 5})
    fapi_v2_private_get_leveragebracket = fapiV2PrivateGetLeverageBracket = Entry[_Dict]('leverageBracket', ['fapi', 'v2', 'private'], 'GET', {'cost': 5})
    fapi_v2_private_get_commissionrate = fapiV2PrivateGetCommissionRate = Entry[_Dict]('commissionRate', ['fapi', 'v2', 'private'], 'GET', {'cost': 5})
    fapi_v2_private_get_futures_transfer_history = fapiV2PrivateGetFuturesTransferHistory = Entry[_Dict]('futures_transfer_history', ['fapi', 'v2', 'private'], 'GET', {'cost': 5})
    fapi_v2_private_get_forceordershistory = fapiV2PrivateGetForceOrdersHistory = Entry[_Dict]('forceOrdersHistory', ['fapi', 'v2', 'private'], 'GET', {'cost': 5})
    fapi_v2_private_post_positionmargin = fapiV2PrivatePostPositionMargin = Entry[_Dict]('positionMargin', ['fapi', 'v2', 'private'], 'POST', {'cost': 5})
    fapi_v2_private_post_level_edit = fapiV2PrivatePostLevelEdit = Entry[_Dict]('level_edit', ['fapi', 'v2', 'private'], 'POST', {'cost': 5})
    fapi_v2_private_post_cancel = fapiV2PrivatePostCancel = Entry[_Dict]('cancel', ['fapi', 'v2', 'private'], 'POST', {'cost': 5})
    fapi_v2_private_post_order = fapiV2PrivatePostOrder = Entry[_Dict]('order', ['fapi', 'v2', 'private'], 'POST', {'cost': 25})
    fapi_v2_private_post_allopenorders = fapiV2PrivatePostAllOpenOrders = Entry[_Dict]('allOpenOrders', ['fapi', 'v2', 'private'], 'POST', {'cost': 5})
    fapi_v2_private_post_futures_transfer = fapiV2PrivatePostFuturesTransfer = Entry[_Dict]('futures_transfer', ['fapi', 'v2', 'private'], 'POST', {'cost': 5})
    dapi_v1_public_get_ping = dapiV1PublicGetPing = Entry[_Dict]('ping', ['dapi', 'v1', 'public'], 'GET', {'cost': 0.24})
    dapi_v1_public_get_time = dapiV1PublicGetTime = Entry[_Dict]('time', ['dapi', 'v1', 'public'], 'GET', {'cost': 0.24})
    dapi_v1_public_get_contracts = dapiV1PublicGetContracts = Entry[_List]('contracts', ['dapi', 'v1', 'public'], 'GET', {'cost': 0.24})
    dapi_v1_public_get_depth = dapiV1PublicGetDepth = Entry[_Dict]('depth', ['dapi', 'v1', 'public'], 'GET', {'cost': 0.24})
    dapi_v1_public_get_ticker = dapiV1PublicGetTicker = Entry[_List]('ticker', ['dapi', 'v1', 'public'], 'GET', {'cost': 0.24})
    dapi_v1_public_get_klines = dapiV1PublicGetKlines = Entry[_Dict]('klines', ['dapi', 'v1', 'public'], 'GET', {'cost': 0.24})
    dapi_v2_private_get_mytrades = dapiV2PrivateGetMyTrades = Entry[_Dict]('myTrades', ['dapi', 'v2', 'private'], 'GET', {'cost': 5})
    dapi_v2_private_get_openorders = dapiV2PrivateGetOpenOrders = Entry[_Dict]('openOrders', ['dapi', 'v2', 'private'], 'GET', {'cost': 5})
    dapi_v2_private_get_order = dapiV2PrivateGetOrder = Entry[_Dict]('order', ['dapi', 'v2', 'private'], 'GET', {'cost': 5})
    dapi_v2_private_get_account = dapiV2PrivateGetAccount = Entry[_Dict]('account', ['dapi', 'v2', 'private'], 'GET', {'cost': 5})
    dapi_v2_private_get_leveragebracket = dapiV2PrivateGetLeverageBracket = Entry[_Dict]('leverageBracket', ['dapi', 'v2', 'private'], 'GET', {'cost': 5})
    dapi_v2_private_get_commissionrate = dapiV2PrivateGetCommissionRate = Entry[_Dict]('commissionRate', ['dapi', 'v2', 'private'], 'GET', {'cost': 5})
    dapi_v2_private_get_futures_transfer_history = dapiV2PrivateGetFuturesTransferHistory = Entry[_Dict]('futures_transfer_history', ['dapi', 'v2', 'private'], 'GET', {'cost': 5})
    dapi_v2_private_get_forceordershistory = dapiV2PrivateGetForceOrdersHistory = Entry[_Dict]('forceOrdersHistory', ['dapi', 'v2', 'private'], 'GET', {'cost': 5})
    dapi_v2_private_post_positionmargin = dapiV2PrivatePostPositionMargin = Entry[_Dict]('positionMargin', ['dapi', 'v2', 'private'], 'POST', {'cost': 5})
    dapi_v2_private_post_level_edit = dapiV2PrivatePostLevelEdit = Entry[_Dict]('level_edit', ['dapi', 'v2', 'private'], 'POST', {'cost': 5})
    dapi_v2_private_post_cancel = dapiV2PrivatePostCancel = Entry[_Dict]('cancel', ['dapi', 'v2', 'private'], 'POST', {'cost': 5})
    dapi_v2_private_post_order = dapiV2PrivatePostOrder = Entry[_Dict]('order', ['dapi', 'v2', 'private'], 'POST', {'cost': 5})
    dapi_v2_private_post_allopenorders = dapiV2PrivatePostAllOpenOrders = Entry[_Dict]('allOpenOrders', ['dapi', 'v2', 'private'], 'POST', {'cost': 5})
    dapi_v2_private_post_futures_transfer = dapiV2PrivatePostFuturesTransfer = Entry[_Dict]('futures_transfer', ['dapi', 'v2', 'private'], 'POST', {'cost': 5})
    open_v1_private_post_poseidon_api_v1_listenkey = openV1PrivatePostPoseidonApiV1ListenKey = Entry[_Dict]('poseidon/api/v1/listenKey', ['open', 'v1', 'private'], 'POST', {'cost': 1})
    open_v1_private_put_poseidon_api_v1_listenkey_listenkey = openV1PrivatePutPoseidonApiV1ListenKeyListenKey = Entry[_Dict]('poseidon/api/v1/listenKey/{listenKey}', ['open', 'v1', 'private'], 'PUT', {'cost': 1})
    open_v1_private_delete_poseidon_api_v1_listenkey_listenkey = openV1PrivateDeletePoseidonApiV1ListenKeyListenKey = Entry[_Dict]('poseidon/api/v1/listenKey/{listenKey}', ['open', 'v1', 'private'], 'DELETE', {'cost': 1})
