from ccxt.base.types import Entry
from typing import Any as PythonAny, Dict, List

_List = List[PythonAny]
_Dict = Dict[str, PythonAny]

class ImplicitAPI:
    public_get_markets = publicGetMarkets = Entry[_List]('markets', 'public', 'GET', {'cost': 1})
    public_get_markets_marketid_ticker = publicGetMarketsMarketIdTicker = Entry[_Dict]('markets/{marketId}/ticker', 'public', 'GET', {'cost': 1})
    public_get_markets_marketid_trades = publicGetMarketsMarketIdTrades = Entry[_List]('markets/{marketId}/trades', 'public', 'GET', {'cost': 1})
    public_get_markets_marketid_orderbook = publicGetMarketsMarketIdOrderbook = Entry[_Dict]('markets/{marketId}/orderbook', 'public', 'GET', {'cost': 1})
    public_get_markets_marketid_candles = publicGetMarketsMarketIdCandles = Entry[_List]('markets/{marketId}/candles', 'public', 'GET', {'cost': 1})
    public_get_markets_tickers = publicGetMarketsTickers = Entry[_List]('markets/tickers', 'public', 'GET', {'cost': 1})
    public_get_markets_orderbooks = publicGetMarketsOrderbooks = Entry[_List]('markets/orderbooks', 'public', 'GET', {'cost': 1})
    public_get_time = publicGetTime = Entry[_Dict]('time', 'public', 'GET', {'cost': 1})
    private_get_orders = privateGetOrders = Entry[_List]('orders', 'private', 'GET', {'cost': 1})
    private_get_orders_id = privateGetOrdersId = Entry[_Dict]('orders/{id}', 'private', 'GET', {'cost': 1})
    private_get_batchorders_ids = privateGetBatchordersIds = Entry[_Dict]('batchorders/{ids}', 'private', 'GET', {'cost': 1})
    private_get_trades = privateGetTrades = Entry[_List]('trades', 'private', 'GET', {'cost': 1})
    private_get_trades_id = privateGetTradesId = Entry[_Dict]('trades/{id}', 'private', 'GET', {'cost': 1})
    private_get_withdrawals = privateGetWithdrawals = Entry[_List]('withdrawals', 'private', 'GET', {'cost': 1})
    private_get_withdrawals_id = privateGetWithdrawalsId = Entry[_Dict]('withdrawals/{id}', 'private', 'GET', {'cost': 1})
    private_get_deposits = privateGetDeposits = Entry[_List]('deposits', 'private', 'GET', {'cost': 1})
    private_get_deposits_id = privateGetDepositsId = Entry[_Dict]('deposits/{id}', 'private', 'GET', {'cost': 1})
    private_get_transfers = privateGetTransfers = Entry[_List]('transfers', 'private', 'GET', {'cost': 1})
    private_get_transfers_id = privateGetTransfersId = Entry[_Dict]('transfers/{id}', 'private', 'GET', {'cost': 1})
    private_get_addresses = privateGetAddresses = Entry[_Dict]('addresses', 'private', 'GET', {'cost': 1})
    private_get_withdrawal_fees = privateGetWithdrawalFees = Entry[_List]('withdrawal-fees', 'private', 'GET', {'cost': 1})
    private_get_assets = privateGetAssets = Entry[_List]('assets', 'private', 'GET', {'cost': 1})
    private_get_accounts_me_trading_fees = privateGetAccountsMeTradingFees = Entry[_Dict]('accounts/me/trading-fees', 'private', 'GET', {'cost': 1})
    private_get_accounts_me_withdrawal_limits = privateGetAccountsMeWithdrawalLimits = Entry[_List]('accounts/me/withdrawal-limits', 'private', 'GET', {'cost': 1})
    private_get_accounts_me_balances = privateGetAccountsMeBalances = Entry[_Dict]('accounts/me/balances', 'private', 'GET', {'cost': 1})
    private_get_accounts_me_transactions = privateGetAccountsMeTransactions = Entry[_List]('accounts/me/transactions', 'private', 'GET', {'cost': 1})
    private_get_reports_id = privateGetReportsId = Entry[_Dict]('reports/{id}', 'private', 'GET', {'cost': 1})
    private_post_orders = privatePostOrders = Entry[_Dict]('orders', 'private', 'POST', {'cost': 1})
    private_post_batchorders = privatePostBatchorders = Entry[_Dict]('batchorders', 'private', 'POST', {'cost': 1})
    private_post_withdrawals = privatePostWithdrawals = Entry[_Dict]('withdrawals', 'private', 'POST', {'cost': 1})
    private_post_reports = privatePostReports = Entry[_Dict]('reports', 'private', 'POST', {'cost': 1})
    private_delete_orders = privateDeleteOrders = Entry[_List]('orders', 'private', 'DELETE', {'cost': 1})
    private_delete_orders_id = privateDeleteOrdersId = Entry[_Dict]('orders/{id}', 'private', 'DELETE', {'cost': 1})
    private_delete_batchorders_ids = privateDeleteBatchordersIds = Entry[_Dict]('batchorders/{ids}', 'private', 'DELETE', {'cost': 1})
    private_put_orders_id = privatePutOrdersId = Entry[_Dict]('orders/{id}', 'private', 'PUT', {'cost': 1})
