from ccxt.base.types import Entry
_List = list[object]
_Dict = dict[str, object]


class ImplicitAPI:
    public_get_spot_api_v3_3_market_summary = publicGetSpotApiV33MarketSummary = Entry[_List]('spot/api/v3.3/market_summary', 'public', 'GET', {'cost': 5})
    public_get_spot_api_v3_3_ohlcv = publicGetSpotApiV33Ohlcv = Entry[_List]('spot/api/v3.3/ohlcv', 'public', 'GET', {'cost': 5})
    public_get_spot_api_v3_3_price = publicGetSpotApiV33Price = Entry[_Dict | _List]('spot/api/v3.3/price', 'public', 'GET', {'cost': 5})
    public_get_spot_api_v3_3_orderbook = publicGetSpotApiV33Orderbook = Entry[_Dict | _List]('spot/api/v3.3/orderbook', 'public', 'GET', {'cost': 5})
    public_get_spot_api_v3_3_orderbook_l2 = publicGetSpotApiV33OrderbookL2 = Entry[_Dict | _List]('spot/api/v3.3/orderbook/L2', 'public', 'GET', {'cost': 5})
    public_get_spot_api_v3_3_trades = publicGetSpotApiV33Trades = Entry[_List]('spot/api/v3.3/trades', 'public', 'GET', {'cost': 5})
    public_get_spot_api_v3_3_time = publicGetSpotApiV33Time = Entry[_Dict | _List]('spot/api/v3.3/time', 'public', 'GET', {'cost': 5})
    public_get_futures_api_v2_3_market_summary = publicGetFuturesApiV23MarketSummary = Entry[_List]('futures/api/v2.3/market_summary', 'public', 'GET', {'cost': 5})
    public_get_futures_api_v2_3_ohlcv = publicGetFuturesApiV23Ohlcv = Entry[_List]('futures/api/v2.3/ohlcv', 'public', 'GET', {'cost': 5})
    public_get_futures_api_v2_3_price = publicGetFuturesApiV23Price = Entry[_Dict | _List]('futures/api/v2.3/price', 'public', 'GET', {'cost': 5})
    public_get_futures_api_v2_3_orderbook = publicGetFuturesApiV23Orderbook = Entry[_Dict | _List]('futures/api/v2.3/orderbook', 'public', 'GET', {'cost': 5})
    public_get_futures_api_v2_3_orderbook_l2 = publicGetFuturesApiV23OrderbookL2 = Entry[_Dict | _List]('futures/api/v2.3/orderbook/L2', 'public', 'GET', {'cost': 5})
    public_get_futures_api_v2_3_trades = publicGetFuturesApiV23Trades = Entry[_List]('futures/api/v2.3/trades', 'public', 'GET', {'cost': 5})
    public_get_futures_api_v2_3_funding_history = publicGetFuturesApiV23FundingHistory = Entry[_Dict | _List]('futures/api/v2.3/funding_history', 'public', 'GET', {'cost': 5})
    public_get_futures_api_v2_3_market_risk_limit = publicGetFuturesApiV23MarketRiskLimit = Entry[_Dict | _List]('futures/api/v2.3/market/risk_limit', 'public', 'GET', {'cost': 5})
    public_get_spot_api_v3_2_availablecurrencynetworks = publicGetSpotApiV32AvailableCurrencyNetworks = Entry[_Dict | _List]('spot/api/v3.2/availableCurrencyNetworks', 'public', 'GET', {'cost': 15})
    public_get_spot_api_v3_2_exchangerate = publicGetSpotApiV32ExchangeRate = Entry[_Dict | _List]('spot/api/v3.2/exchangeRate', 'public', 'GET', {'cost': 15})
    public_get_public_api_wallet_v1_crypto_networks = publicGetPublicApiWalletV1CryptoNetworks = Entry[_Dict | _List]('public-api/wallet/v1/crypto/networks', 'public', 'GET', {'cost': 15})
    public_get_public_api_wallet_v1_assets_exchangerate = publicGetPublicApiWalletV1AssetsExchangeRate = Entry[_Dict | _List]('public-api/wallet/v1/assets/exchangeRate', 'public', 'GET', {'cost': 15})
    public_get_public_api_market_v1_markets = publicGetPublicApiMarketV1Markets = Entry[_Dict]('public-api/market/v1/markets', 'public', 'GET', {'cost': 3})
    public_get_public_api_market_v1_exchangeinfo = publicGetPublicApiMarketV1ExchangeInfo = Entry[_Dict | _List]('public-api/market/v1/exchangeInfo', 'public', 'GET', {'cost': 3})
    public_get_public_api_market_v1_orderbook = publicGetPublicApiMarketV1Orderbook = Entry[_Dict]('public-api/market/v1/orderbook', 'public', 'GET', {'cost': 3})
    public_get_public_api_market_v1_trades = publicGetPublicApiMarketV1Trades = Entry[_Dict]('public-api/market/v1/trades', 'public', 'GET', {'cost': 3})
    public_get_public_api_market_v1_klines = publicGetPublicApiMarketV1Klines = Entry[_Dict]('public-api/market/v1/klines', 'public', 'GET', {'cost': 3})
    public_get_public_api_market_v1_ticker_24hr = publicGetPublicApiMarketV1Ticker24hr = Entry[_Dict]('public-api/market/v1/ticker/24hr', 'public', 'GET', {'cost': 3})
    public_get_public_api_market_v1_ticker_price = publicGetPublicApiMarketV1TickerPrice = Entry[_Dict | _List]('public-api/market/v1/ticker/price', 'public', 'GET', {'cost': 3})
    public_get_public_api_market_v1_ticker_indices = publicGetPublicApiMarketV1TickerIndices = Entry[_Dict | _List]('public-api/market/v1/ticker/indices', 'public', 'GET', {'cost': 3})
    public_get_public_api_market_v1_ticker_l1 = publicGetPublicApiMarketV1TickerL1 = Entry[_Dict | _List]('public-api/market/v1/ticker/l1', 'public', 'GET', {'cost': 3})
    public_get_public_api_market_v1_recentfundinghistory = publicGetPublicApiMarketV1RecentFundingHistory = Entry[_Dict]('public-api/market/v1/recentFundingHistory', 'public', 'GET', {'cost': 3})
    public_get_public_api_market_v1_risklimits = publicGetPublicApiMarketV1RiskLimits = Entry[_Dict]('public-api/market/v1/riskLimits', 'public', 'GET', {'cost': 3})
    public_get_public_api_wallet_v1_crypto_list = publicGetPublicApiWalletV1CryptoList = Entry[_Dict | _List]('public-api/wallet/v1/crypto/list', 'public', 'GET', {'cost': 15})
    public_get_public_api_otc_v1_markets = publicGetPublicApiOtcV1Markets = Entry[_Dict | _List]('public-api/otc/v1/markets', 'public', 'GET', {'cost': 1})
    private_get_spot_api_v3_3_order = privateGetSpotApiV33Order = Entry[_Dict | _List]('spot/api/v3.3/order', 'private', 'GET', {'cost': 1})
    private_get_spot_api_v3_3_user_open_orders = privateGetSpotApiV33UserOpenOrders = Entry[_Dict | _List]('spot/api/v3.3/user/open_orders', 'private', 'GET', {'cost': 5})
    private_get_spot_api_v3_3_user_trade_history = privateGetSpotApiV33UserTradeHistory = Entry[_List]('spot/api/v3.3/user/trade_history', 'private', 'GET', {'cost': 5})
    private_get_spot_api_v3_3_user_fees = privateGetSpotApiV33UserFees = Entry[_List]('spot/api/v3.3/user/fees', 'private', 'GET', {'cost': 5})
    private_get_spot_api_v3_3_invest_products = privateGetSpotApiV33InvestProducts = Entry[_Dict | _List]('spot/api/v3.3/invest/products', 'private', 'GET', {'cost': 5})
    private_get_spot_api_v3_3_invest_orders = privateGetSpotApiV33InvestOrders = Entry[_Dict | _List]('spot/api/v3.3/invest/orders', 'private', 'GET', {'cost': 5})
    private_get_spot_api_v3_3_invest_history = privateGetSpotApiV33InvestHistory = Entry[_Dict | _List]('spot/api/v3.3/invest/history', 'private', 'GET', {'cost': 5})
    private_get_futures_api_v2_3_order = privateGetFuturesApiV23Order = Entry[_Dict | _List]('futures/api/v2.3/order', 'private', 'GET', {'cost': 1})
    private_get_futures_api_v2_3_user_open_orders = privateGetFuturesApiV23UserOpenOrders = Entry[_Dict | _List]('futures/api/v2.3/user/open_orders', 'private', 'GET', {'cost': 1})
    private_get_futures_api_v2_3_user_trade_history = privateGetFuturesApiV23UserTradeHistory = Entry[_List]('futures/api/v2.3/user/trade_history', 'private', 'GET', {'cost': 5})
    private_get_futures_api_v2_3_user_positions = privateGetFuturesApiV23UserPositions = Entry[_List]('futures/api/v2.3/user/positions', 'private', 'GET', {'cost': 5})
    private_get_futures_api_v2_3_risk_limit = privateGetFuturesApiV23RiskLimit = Entry[_Dict | _List]('futures/api/v2.3/risk_limit', 'private', 'GET', {'cost': 5})
    private_get_futures_api_v2_3_leverage = privateGetFuturesApiV23Leverage = Entry[_Dict | _List]('futures/api/v2.3/leverage', 'private', 'GET', {'cost': 5})
    private_get_futures_api_v2_3_user_fees = privateGetFuturesApiV23UserFees = Entry[_List]('futures/api/v2.3/user/fees', 'private', 'GET', {'cost': 5})
    private_get_futures_api_v2_3_position_mode = privateGetFuturesApiV23PositionMode = Entry[_List]('futures/api/v2.3/position_mode', 'private', 'GET', {'cost': 5})
    private_get_futures_api_v2_3_user_margin_setting = privateGetFuturesApiV23UserMarginSetting = Entry[_Dict | _List]('futures/api/v2.3/user/margin_setting', 'private', 'GET', {'cost': 5})
    private_get_futures_api_v2_3_user_wallet = privateGetFuturesApiV23UserWallet = Entry[_List]('futures/api/v2.3/user/wallet', 'private', 'GET', {'cost': 5})
    private_get_futures_api_v2_3_user_wallet_history = privateGetFuturesApiV23UserWalletHistory = Entry[_Dict | _List]('futures/api/v2.3/user/wallet_history', 'private', 'GET', {'cost': 5})
    private_get_futures_api_v2_3_user_unifiedwallet_margin = privateGetFuturesApiV23UserUnifiedWalletMargin = Entry[_Dict | _List]('futures/api/v2.3/user/unifiedWallet/margin', 'private', 'GET', {'cost': 5})
    private_get_futures_api_v2_3_user_margin = privateGetFuturesApiV23UserMargin = Entry[_Dict | _List]('futures/api/v2.3/user/margin', 'private', 'GET', {'cost': 5})
    private_get_otc_api_v1_getmarket = privateGetOtcApiV1GetMarket = Entry[_Dict | _List]('otc/api/v1/getMarket', 'private', 'GET', {'cost': 1})
    private_get_spot_api_v3_2_user_wallet = privateGetSpotApiV32UserWallet = Entry[_List]('spot/api/v3.2/user/wallet', 'private', 'GET', {'cost': 15})
    private_get_spot_api_v3_2_user_wallet_history = privateGetSpotApiV32UserWalletHistory = Entry[_List]('spot/api/v3.2/user/wallet_history', 'private', 'GET', {'cost': 15})
    private_get_spot_api_v3_3_user_wallet_address = privateGetSpotApiV33UserWalletAddress = Entry[_Dict | _List]('spot/api/v3.3/user/wallet/address', 'private', 'GET', {'cost': 15})
    private_get_spot_api_v3_2_availablecurrencies = privateGetSpotApiV32AvailableCurrencies = Entry[_Dict | _List]('spot/api/v3.2/availableCurrencies', 'private', 'GET', {'cost': 15})
    private_get_spot_api_v3_2_subaccount_wallet_history = privateGetSpotApiV32SubaccountWalletHistory = Entry[_Dict | _List]('spot/api/v3.2/subaccount/wallet/history', 'private', 'GET', {'cost': 15})
    private_get_spot_api_v4_trade_orders = privateGetSpotApiV4TradeOrders = Entry[_List]('spot/api/v4/trade/orders', 'private', 'GET', {'cost': 5})
    private_get_spot_api_v4_trade_order = privateGetSpotApiV4TradeOrder = Entry[_Dict]('spot/api/v4/trade/order', 'private', 'GET', {'cost': 5})
    private_get_spot_api_v4_trade_trade_history = privateGetSpotApiV4TradeTradeHistory = Entry[_Dict | _List]('spot/api/v4/trade/trade_history', 'private', 'GET', {'cost': 5})
    private_get_spot_api_v4_trade_fees = privateGetSpotApiV4TradeFees = Entry[_List]('spot/api/v4/trade/fees', 'private', 'GET', {'cost': 5})
    private_get_futures_api_v3_trade_orders = privateGetFuturesApiV3TradeOrders = Entry[_List]('futures/api/v3/trade/orders', 'private', 'GET', {'cost': 5})
    private_get_futures_api_v3_trade_risk_limit = privateGetFuturesApiV3TradeRiskLimit = Entry[_Dict | _List]('futures/api/v3/trade/risk_limit', 'private', 'GET', {'cost': 5})
    private_get_futures_api_v3_trade_position_mode = privateGetFuturesApiV3TradePositionMode = Entry[_List]('futures/api/v3/trade/position_mode', 'private', 'GET', {'cost': 5})
    private_get_futures_api_v3_trade_leverage = privateGetFuturesApiV3TradeLeverage = Entry[_List]('futures/api/v3/trade/leverage', 'private', 'GET', {'cost': 5})
    private_get_futures_api_v3_trade_trade_history = privateGetFuturesApiV3TradeTradeHistory = Entry[_List]('futures/api/v3/trade/trade_history', 'private', 'GET', {'cost': 5})
    private_get_futures_api_v3_trade_positions = privateGetFuturesApiV3TradePositions = Entry[_List]('futures/api/v3/trade/positions', 'private', 'GET', {'cost': 5})
    private_get_futures_api_v3_trade_margin_setting = privateGetFuturesApiV3TradeMarginSetting = Entry[_Dict | _List]('futures/api/v3/trade/margin_setting', 'private', 'GET', {'cost': 5})
    private_get_public_api_wallet_v1_assets = privateGetPublicApiWalletV1Assets = Entry[_Dict | _List]('public-api/wallet/v1/assets', 'private', 'GET', {'cost': 15})
    private_get_public_api_wallet_v1_user_assets = privateGetPublicApiWalletV1UserAssets = Entry[_Dict]('public-api/wallet/v1/user/assets', 'private', 'GET', {'cost': 15})
    private_get_public_api_wallet_v1_user_wallethistory = privateGetPublicApiWalletV1UserWalletHistory = Entry[_Dict | _List]('public-api/wallet/v1/user/walletHistory', 'private', 'GET', {'cost': 15})
    private_get_public_api_wallet_v1_user_crypto_address = privateGetPublicApiWalletV1UserCryptoAddress = Entry[_Dict | _List]('public-api/wallet/v1/user/crypto/address', 'private', 'GET', {'cost': 15})
    private_get_public_api_otc_v1_quotes = privateGetPublicApiOtcV1Quotes = Entry[_Dict | _List]('public-api/otc/v1/quotes', 'private', 'GET', {'cost': 1})
    private_post_spot_api_v3_3_order = privatePostSpotApiV33Order = Entry[_Dict | _List]('spot/api/v3.3/order', 'private', 'POST', {'cost': 1})
    private_post_spot_api_v3_3_order_peg = privatePostSpotApiV33OrderPeg = Entry[_Dict | _List]('spot/api/v3.3/order/peg', 'private', 'POST', {'cost': 1})
    private_post_spot_api_v3_3_order_cancelallafter = privatePostSpotApiV33OrderCancelAllAfter = Entry[_Dict]('spot/api/v3.3/order/cancelAllAfter', 'private', 'POST', {'cost': 1})
    private_post_spot_api_v3_3_invest_deposit = privatePostSpotApiV33InvestDeposit = Entry[_Dict | _List]('spot/api/v3.3/invest/deposit', 'private', 'POST', {'cost': 5})
    private_post_spot_api_v3_3_invest_renew = privatePostSpotApiV33InvestRenew = Entry[_Dict | _List]('spot/api/v3.3/invest/renew', 'private', 'POST', {'cost': 5})
    private_post_spot_api_v3_3_invest_redeem = privatePostSpotApiV33InvestRedeem = Entry[_Dict | _List]('spot/api/v3.3/invest/redeem', 'private', 'POST', {'cost': 5})
    private_post_futures_api_v2_3_order = privatePostFuturesApiV23Order = Entry[_Dict | _List]('futures/api/v2.3/order', 'private', 'POST', {'cost': 1})
    private_post_futures_api_v2_3_order_peg = privatePostFuturesApiV23OrderPeg = Entry[_Dict | _List]('futures/api/v2.3/order/peg', 'private', 'POST', {'cost': 1})
    private_post_futures_api_v2_3_order_cancelallafter = privatePostFuturesApiV23OrderCancelAllAfter = Entry[_Dict]('futures/api/v2.3/order/cancelAllAfter', 'private', 'POST', {'cost': 1})
    private_post_futures_api_v2_3_order_close_position = privatePostFuturesApiV23OrderClosePosition = Entry[_Dict | _List]('futures/api/v2.3/order/close_position', 'private', 'POST', {'cost': 1})
    private_post_futures_api_v2_3_risk_limit = privatePostFuturesApiV23RiskLimit = Entry[_Dict | _List]('futures/api/v2.3/risk_limit', 'private', 'POST', {'cost': 5})
    private_post_futures_api_v2_3_leverage = privatePostFuturesApiV23Leverage = Entry[_Dict | _List]('futures/api/v2.3/leverage', 'private', 'POST', {'cost': 5})
    private_post_futures_api_v2_3_settle_in = privatePostFuturesApiV23SettleIn = Entry[_Dict | _List]('futures/api/v2.3/settle_in', 'private', 'POST', {'cost': 5})
    private_post_futures_api_v2_3_order_bind_tpsl = privatePostFuturesApiV23OrderBindTpsl = Entry[_Dict | _List]('futures/api/v2.3/order/bind/tpsl', 'private', 'POST', {'cost': 1})
    private_post_futures_api_v2_3_position_mode = privatePostFuturesApiV23PositionMode = Entry[_Dict]('futures/api/v2.3/position_mode', 'private', 'POST', {'cost': 5})
    private_post_futures_api_v2_3_user_wallet_transfer = privatePostFuturesApiV23UserWalletTransfer = Entry[_Dict | _List]('futures/api/v2.3/user/wallet/transfer', 'private', 'POST', {'cost': 5})
    private_post_futures_api_v2_3_subaccount_wallet_transfer = privatePostFuturesApiV23SubaccountWalletTransfer = Entry[_Dict | _List]('futures/api/v2.3/subaccount/wallet/transfer', 'private', 'POST', {'cost': 5})
    private_post_otc_api_v1_quote = privatePostOtcApiV1Quote = Entry[_Dict | _List]('otc/api/v1/quote', 'private', 'POST', {'cost': 1})
    private_post_otc_api_v1_accept_quoteid = privatePostOtcApiV1AcceptQuoteId = Entry[_Dict | _List]('otc/api/v1/accept/{quoteId}', 'private', 'POST', {'cost': 1})
    private_post_otc_api_v1_reject_quoteid = privatePostOtcApiV1RejectQuoteId = Entry[_Dict | _List]('otc/api/v1/reject/{quoteId}', 'private', 'POST', {'cost': 1})
    private_post_otc_api_v1_queryorder_quoteid = privatePostOtcApiV1QueryOrderQuoteId = Entry[_Dict | _List]('otc/api/v1/queryOrder/{quoteId}', 'private', 'POST', {'cost': 1})
    private_post_spot_api_v3_3_user_wallet_address = privatePostSpotApiV33UserWalletAddress = Entry[_Dict | _List]('spot/api/v3.3/user/wallet/address', 'private', 'POST', {'cost': 15})
    private_post_spot_api_v3_3_user_wallet_withdraw = privatePostSpotApiV33UserWalletWithdraw = Entry[_Dict | _List]('spot/api/v3.3/user/wallet/withdraw', 'private', 'POST', {'cost': 15})
    private_post_spot_api_v3_2_user_wallet_convert = privatePostSpotApiV32UserWalletConvert = Entry[_Dict | _List]('spot/api/v3.2/user/wallet/convert', 'private', 'POST', {'cost': 15})
    private_post_spot_api_v3_3_user_wallet_transfer = privatePostSpotApiV33UserWalletTransfer = Entry[_Dict | _List]('spot/api/v3.3/user/wallet/transfer', 'private', 'POST', {'cost': 15})
    private_post_spot_api_v4_trade_orders = privatePostSpotApiV4TradeOrders = Entry[_List]('spot/api/v4/trade/orders', 'private', 'POST', {'cost': 1})
    private_post_spot_api_v4_trade_orders_cancel_all_after = privatePostSpotApiV4TradeOrdersCancelAllAfter = Entry[_Dict]('spot/api/v4/trade/orders/cancel_all_after', 'private', 'POST', {'cost': 1})
    private_post_spot_api_v4_trade_orders_algo = privatePostSpotApiV4TradeOrdersAlgo = Entry[_List]('spot/api/v4/trade/orders/algo', 'private', 'POST', {'cost': 1})
    private_post_futures_api_v3_trade_orders = privatePostFuturesApiV3TradeOrders = Entry[_Dict]('futures/api/v3/trade/orders', 'private', 'POST', {'cost': 1})
    private_post_futures_api_v3_trade_orders_cancel_all_after = privatePostFuturesApiV3TradeOrdersCancelAllAfter = Entry[_Dict]('futures/api/v3/trade/orders/cancel_all_after', 'private', 'POST', {'cost': 1})
    private_post_futures_api_v3_trade_orders_algo = privatePostFuturesApiV3TradeOrdersAlgo = Entry[_Dict]('futures/api/v3/trade/orders/algo', 'private', 'POST', {'cost': 1})
    private_post_futures_api_v3_trade_settle_in = privatePostFuturesApiV3TradeSettleIn = Entry[_Dict | _List]('futures/api/v3/trade/settle_in', 'private', 'POST', {'cost': 5})
    private_post_futures_api_v3_trade_risk_limit = privatePostFuturesApiV3TradeRiskLimit = Entry[_Dict | _List]('futures/api/v3/trade/risk_limit', 'private', 'POST', {'cost': 5})
    private_post_futures_api_v3_trade_positions_tpsl = privatePostFuturesApiV3TradePositionsTpsl = Entry[_Dict | _List]('futures/api/v3/trade/positions/tpsl', 'private', 'POST', {'cost': 1})
    private_post_futures_api_v3_trade_position_mode = privatePostFuturesApiV3TradePositionMode = Entry[_Dict]('futures/api/v3/trade/position_mode', 'private', 'POST', {'cost': 1})
    private_post_futures_api_v3_trade_leverage = privatePostFuturesApiV3TradeLeverage = Entry[_Dict]('futures/api/v3/trade/leverage', 'private', 'POST', {'cost': 1})
    private_post_public_api_wallet_v1_user_crypto_address = privatePostPublicApiWalletV1UserCryptoAddress = Entry[_Dict | _List]('public-api/wallet/v1/user/crypto/address', 'private', 'POST', {'cost': 15})
    private_post_public_api_wallet_v1_user_crypto_withdraw = privatePostPublicApiWalletV1UserCryptoWithdraw = Entry[_Dict | _List]('public-api/wallet/v1/user/crypto/withdraw', 'private', 'POST', {'cost': 15})
    private_post_public_api_wallet_v1_user_assets_sendto = privatePostPublicApiWalletV1UserAssetsSendTo = Entry[_Dict | _List]('public-api/wallet/v1/user/assets/sendTo', 'private', 'POST', {'cost': 15})
    private_post_public_api_wallet_v1_user_assets_convert = privatePostPublicApiWalletV1UserAssetsConvert = Entry[_Dict | _List]('public-api/wallet/v1/user/assets/convert', 'private', 'POST', {'cost': 15})
    private_post_public_api_otc_v1_quotes = privatePostPublicApiOtcV1Quotes = Entry[_Dict | _List]('public-api/otc/v1/quotes', 'private', 'POST', {'cost': 1})
    private_post_public_api_otc_v1_quotes_accept = privatePostPublicApiOtcV1QuotesAccept = Entry[_Dict | _List]('public-api/otc/v1/quotes/accept', 'private', 'POST', {'cost': 1})
    private_put_spot_api_v3_3_order = privatePutSpotApiV33Order = Entry[_Dict | _List]('spot/api/v3.3/order', 'private', 'PUT', {'cost': 1})
    private_put_futures_api_v2_3_order = privatePutFuturesApiV23Order = Entry[_Dict | _List]('futures/api/v2.3/order', 'private', 'PUT', {'cost': 1})
    private_put_spot_api_v4_trade_orders = privatePutSpotApiV4TradeOrders = Entry[_List]('spot/api/v4/trade/orders', 'private', 'PUT', {'cost': 1})
    private_put_futures_api_v3_trade_orders = privatePutFuturesApiV3TradeOrders = Entry[_List]('futures/api/v3/trade/orders', 'private', 'PUT', {'cost': 1})
    private_delete_spot_api_v3_3_order = privateDeleteSpotApiV33Order = Entry[_Dict | _List]('spot/api/v3.3/order', 'private', 'DELETE', {'cost': 1})
    private_delete_futures_api_v2_3_order = privateDeleteFuturesApiV23Order = Entry[_Dict | _List]('futures/api/v2.3/order', 'private', 'DELETE', {'cost': 1})
    private_delete_spot_api_v3_3_user_wallet_address = privateDeleteSpotApiV33UserWalletAddress = Entry[_Dict | _List]('spot/api/v3.3/user/wallet/address', 'private', 'DELETE', {'cost': 15})
    private_delete_spot_api_v4_trade_orders = privateDeleteSpotApiV4TradeOrders = Entry[_List]('spot/api/v4/trade/orders', 'private', 'DELETE', {'cost': 1})
    private_delete_spot_api_v4_trade_orders_all = privateDeleteSpotApiV4TradeOrdersAll = Entry[_List]('spot/api/v4/trade/orders/all', 'private', 'DELETE', {'cost': 1})
    private_delete_futures_api_v3_trade_orders = privateDeleteFuturesApiV3TradeOrders = Entry[_List]('futures/api/v3/trade/orders', 'private', 'DELETE', {'cost': 1})
    private_delete_futures_api_v3_trade_positions = privateDeleteFuturesApiV3TradePositions = Entry[_Dict | _List]('futures/api/v3/trade/positions', 'private', 'DELETE', {'cost': 1})
    private_delete_public_api_wallet_v1_user_crypto_address = privateDeletePublicApiWalletV1UserCryptoAddress = Entry[_Dict | _List]('public-api/wallet/v1/user/crypto/address', 'private', 'DELETE', {'cost': 15})
