from ccxt.base.types import Entry


class ImplicitAPI:
    public_get_exchange_orders_rate = publicGetExchangeOrdersRate = Entry('exchange/orders/rate', 'public', 'GET', {'cost': 1})
    public_get_exchange_status = publicGetExchangeStatus = Entry('exchange_status', 'public', 'GET', {'cost': 1})
    public_get_order_books = publicGetOrderBooks = Entry('order_books', 'public', 'GET', {'cost': 1})
    public_get_rate_pair = publicGetRatePair = Entry('rate/{pair}', 'public', 'GET', {'cost': 1})
    public_get_ticker = publicGetTicker = Entry('ticker', 'public', 'GET', {'cost': 1})
    public_get_trades = publicGetTrades = Entry('trades', 'public', 'GET', {'cost': 1})
    private_get_accounts = privateGetAccounts = Entry('accounts', 'private', 'GET', {'cost': 1})
    private_get_accounts_balance = privateGetAccountsBalance = Entry('accounts/balance', 'private', 'GET', {'cost': 1})
    private_get_accounts_leverage_balance = privateGetAccountsLeverageBalance = Entry('accounts/leverage_balance', 'private', 'GET', {'cost': 1})
    private_get_bank_accounts = privateGetBankAccounts = Entry('bank_accounts', 'private', 'GET', {'cost': 1})
    private_get_deposit_money = privateGetDepositMoney = Entry('deposit_money', 'private', 'GET', {'cost': 1})
    private_get_exchange_orders_id = privateGetExchangeOrdersId = Entry('exchange/orders/{id}', 'private', 'GET', {'cost': 1})
    private_get_exchange_orders_opens = privateGetExchangeOrdersOpens = Entry('exchange/orders/opens', 'private', 'GET', {'cost': 1})
    private_get_exchange_orders_cancel_status = privateGetExchangeOrdersCancelStatus = Entry('exchange/orders/cancel_status', 'private', 'GET', {'cost': 1})
    private_get_exchange_orders_transactions = privateGetExchangeOrdersTransactions = Entry('exchange/orders/transactions', 'private', 'GET', {'cost': 1})
    private_get_exchange_orders_transactions_pagination = privateGetExchangeOrdersTransactionsPagination = Entry('exchange/orders/transactions_pagination', 'private', 'GET', {'cost': 1})
    private_get_exchange_leverage_positions = privateGetExchangeLeveragePositions = Entry('exchange/leverage/positions', 'private', 'GET', {'cost': 1})
    private_get_lending_borrows_matches = privateGetLendingBorrowsMatches = Entry('lending/borrows/matches', 'private', 'GET', {'cost': 1})
    private_get_send_money = privateGetSendMoney = Entry('send_money', 'private', 'GET', {'cost': 1})
    private_get_withdraws = privateGetWithdraws = Entry('withdraws', 'private', 'GET', {'cost': 1})
    private_post_bank_accounts = privatePostBankAccounts = Entry('bank_accounts', 'private', 'POST', {'cost': 1})
    private_post_deposit_money_id_fast = privatePostDepositMoneyIdFast = Entry('deposit_money/{id}/fast', 'private', 'POST', {'cost': 1})
    private_post_exchange_orders = privatePostExchangeOrders = Entry('exchange/orders', 'private', 'POST', {'cost': 1})
    private_post_exchange_transfers_to_leverage = privatePostExchangeTransfersToLeverage = Entry('exchange/transfers/to_leverage', 'private', 'POST', {'cost': 1})
    private_post_exchange_transfers_from_leverage = privatePostExchangeTransfersFromLeverage = Entry('exchange/transfers/from_leverage', 'private', 'POST', {'cost': 1})
    private_post_lending_borrows = privatePostLendingBorrows = Entry('lending/borrows', 'private', 'POST', {'cost': 1})
    private_post_lending_borrows_id_repay = privatePostLendingBorrowsIdRepay = Entry('lending/borrows/{id}/repay', 'private', 'POST', {'cost': 1})
    private_post_send_money = privatePostSendMoney = Entry('send_money', 'private', 'POST', {'cost': 1})
    private_post_withdraws = privatePostWithdraws = Entry('withdraws', 'private', 'POST', {'cost': 1})
    private_delete_bank_accounts_id = privateDeleteBankAccountsId = Entry('bank_accounts/{id}', 'private', 'DELETE', {'cost': 1})
    private_delete_exchange_orders_id = privateDeleteExchangeOrdersId = Entry('exchange/orders/{id}', 'private', 'DELETE', {'cost': 1})
    private_delete_withdraws_id = privateDeleteWithdrawsId = Entry('withdraws/{id}', 'private', 'DELETE', {'cost': 1})
