from ccxt.base.types import Entry
from typing import Any as PythonAny, Dict

_Dict = Dict[str, PythonAny]

class ImplicitAPI:
    public_get_orderbook = publicGetOrderBook = Entry[_Dict]('orderBook', 'public', 'GET', {'cost': 1})
    public_get_ticker = publicGetTicker = Entry[_Dict]('ticker', 'public', 'GET', {'cost': 1})
    public_get_tickerall = publicGetTickerAll = Entry[_Dict]('tickerAll', 'public', 'GET', {'cost': 1})
    public_get_products = publicGetProducts = Entry[_Dict]('products', 'public', 'GET', {'cost': 1})
    public_get_transactions = publicGetTransactions = Entry[_Dict]('transactions', 'public', 'GET', {'cost': 1})
    public_get_tradingpairs = publicGetTradingPairs = Entry[_Dict]('tradingPairs', 'public', 'GET', {'cost': 1})
    public_get_system_time = publicGetSystemTime = Entry[_Dict]('system/time', 'public', 'GET', {'cost': 1})
    private_post_currencies = privatePostCurrencies = Entry[_Dict]('currencies', 'private', 'POST', {'cost': 1})
    private_post_balances = privatePostBalances = Entry[_Dict]('balances', 'private', 'POST', {'cost': 1})
    private_post_bitcoincashwithdrawal = privatePostBitcoinCashWithdrawal = Entry[_Dict]('bitcoinCashWithdrawal', 'private', 'POST', {'cost': 1})
    private_post_bitcoincashdepositaddresses = privatePostBitcoinCashDepositAddresses = Entry[_Dict]('bitcoinCashDepositAddresses', 'private', 'POST', {'cost': 1})
    private_post_bitcoindepositaddresses = privatePostBitcoinDepositAddresses = Entry[_Dict]('bitcoinDepositAddresses', 'private', 'POST', {'cost': 1})
    private_post_bitcoinwithdrawal = privatePostBitcoinWithdrawal = Entry[_Dict]('bitcoinWithdrawal', 'private', 'POST', {'cost': 1})
    private_post_bitcoinwithdrawalfees = privatePostBitcoinWithdrawalFees = Entry[_Dict]('bitcoinWithdrawalFees', 'private', 'POST', {'cost': 1})
    private_post_buyinstant = privatePostBuyInstant = Entry[_Dict]('buyInstant', 'private', 'POST', {'cost': 1})
    private_post_buylimit = privatePostBuyLimit = Entry[_Dict]('buyLimit', 'private', 'POST', {'cost': 1})
    private_post_cancelorder = privatePostCancelOrder = Entry[_Dict]('cancelOrder', 'private', 'POST', {'cost': 1})
    private_post_cancelorderwithinfo = privatePostCancelOrderWithInfo = Entry[_Dict]('cancelOrderWithInfo', 'private', 'POST', {'cost': 1})
    private_post_createvoucher = privatePostCreateVoucher = Entry[_Dict]('createVoucher', 'private', 'POST', {'cost': 1})
    private_post_dashdepositaddresses = privatePostDashDepositAddresses = Entry[_Dict]('dashDepositAddresses', 'private', 'POST', {'cost': 1})
    private_post_dashwithdrawal = privatePostDashWithdrawal = Entry[_Dict]('dashWithdrawal', 'private', 'POST', {'cost': 1})
    private_post_ethereumwithdrawal = privatePostEthereumWithdrawal = Entry[_Dict]('ethereumWithdrawal', 'private', 'POST', {'cost': 1})
    private_post_ethereumdepositaddresses = privatePostEthereumDepositAddresses = Entry[_Dict]('ethereumDepositAddresses', 'private', 'POST', {'cost': 1})
    private_post_litecoinwithdrawal = privatePostLitecoinWithdrawal = Entry[_Dict]('litecoinWithdrawal', 'private', 'POST', {'cost': 1})
    private_post_litecoindepositaddresses = privatePostLitecoinDepositAddresses = Entry[_Dict]('litecoinDepositAddresses', 'private', 'POST', {'cost': 1})
    private_post_openorders = privatePostOpenOrders = Entry[_Dict]('openOrders', 'private', 'POST', {'cost': 1})
    private_post_order = privatePostOrder = Entry[_Dict]('order', 'private', 'POST', {'cost': 1})
    private_post_orderhistory = privatePostOrderHistory = Entry[_Dict]('orderHistory', 'private', 'POST', {'cost': 1})
    private_post_orderbyid = privatePostOrderById = Entry[_Dict]('orderById', 'private', 'POST', {'cost': 1})
    private_post_pusherauth = privatePostPusherAuth = Entry[_Dict]('pusherAuth', 'private', 'POST', {'cost': 1})
    private_post_redeemvoucher = privatePostRedeemVoucher = Entry[_Dict]('redeemVoucher', 'private', 'POST', {'cost': 1})
    private_post_replacebybuylimit = privatePostReplaceByBuyLimit = Entry[_Dict]('replaceByBuyLimit', 'private', 'POST', {'cost': 1})
    private_post_replacebybuyinstant = privatePostReplaceByBuyInstant = Entry[_Dict]('replaceByBuyInstant', 'private', 'POST', {'cost': 1})
    private_post_replacebyselllimit = privatePostReplaceBySellLimit = Entry[_Dict]('replaceBySellLimit', 'private', 'POST', {'cost': 1})
    private_post_replacebysellinstant = privatePostReplaceBySellInstant = Entry[_Dict]('replaceBySellInstant', 'private', 'POST', {'cost': 1})
    private_post_rippledepositaddresses = privatePostRippleDepositAddresses = Entry[_Dict]('rippleDepositAddresses', 'private', 'POST', {'cost': 1})
    private_post_ripplewithdrawal = privatePostRippleWithdrawal = Entry[_Dict]('rippleWithdrawal', 'private', 'POST', {'cost': 1})
    private_post_sellinstant = privatePostSellInstant = Entry[_Dict]('sellInstant', 'private', 'POST', {'cost': 1})
    private_post_selllimit = privatePostSellLimit = Entry[_Dict]('sellLimit', 'private', 'POST', {'cost': 1})
    private_post_transactionhistory = privatePostTransactionHistory = Entry[_Dict]('transactionHistory', 'private', 'POST', {'cost': 1})
    private_post_traderfees = privatePostTraderFees = Entry[_Dict]('traderFees', 'private', 'POST', {'cost': 1})
    private_post_tradehistory = privatePostTradeHistory = Entry[_Dict]('tradeHistory', 'private', 'POST', {'cost': 1})
    private_post_transfer = privatePostTransfer = Entry[_Dict]('transfer', 'private', 'POST', {'cost': 1})
    private_post_transferhistory = privatePostTransferHistory = Entry[_Dict]('transferHistory', 'private', 'POST', {'cost': 1})
    private_post_unconfirmedbitcoindeposits = privatePostUnconfirmedBitcoinDeposits = Entry[_Dict]('unconfirmedBitcoinDeposits', 'private', 'POST', {'cost': 1})
    private_post_unconfirmedbitcoincashdeposits = privatePostUnconfirmedBitcoinCashDeposits = Entry[_Dict]('unconfirmedBitcoinCashDeposits', 'private', 'POST', {'cost': 1})
    private_post_unconfirmeddashdeposits = privatePostUnconfirmedDashDeposits = Entry[_Dict]('unconfirmedDashDeposits', 'private', 'POST', {'cost': 1})
    private_post_unconfirmedethereumdeposits = privatePostUnconfirmedEthereumDeposits = Entry[_Dict]('unconfirmedEthereumDeposits', 'private', 'POST', {'cost': 1})
    private_post_unconfirmedlitecoindeposits = privatePostUnconfirmedLitecoinDeposits = Entry[_Dict]('unconfirmedLitecoinDeposits', 'private', 'POST', {'cost': 1})
    private_post_unconfirmedrippledeposits = privatePostUnconfirmedRippleDeposits = Entry[_Dict]('unconfirmedRippleDeposits', 'private', 'POST', {'cost': 1})
    private_post_cancelallopenorders = privatePostCancelAllOpenOrders = Entry[_Dict]('cancelAllOpenOrders', 'private', 'POST', {'cost': 1})
    private_post_withdrawvirtualcurrency = privatePostWithdrawVirtualCurrency = Entry[_Dict]('withdrawVirtualCurrency', 'private', 'POST', {'cost': 1})
    private_post_virtualcurrencydepositaddresses = privatePostVirtualCurrencyDepositAddresses = Entry[_Dict]('virtualCurrencyDepositAddresses', 'private', 'POST', {'cost': 1})
    private_post_unconfirmedvirtualcurrencydeposits = privatePostUnconfirmedVirtualCurrencyDeposits = Entry[_Dict]('unconfirmedVirtualCurrencyDeposits', 'private', 'POST', {'cost': 1})
    private_post_adawithdrawal = privatePostAdaWithdrawal = Entry[_Dict]('adaWithdrawal', 'private', 'POST', {'cost': 1})
    private_post_adadepositaddresses = privatePostAdaDepositAddresses = Entry[_Dict]('adaDepositAddresses', 'private', 'POST', {'cost': 1})
    private_post_unconfirmedadadeposits = privatePostUnconfirmedAdaDeposits = Entry[_Dict]('unconfirmedAdaDeposits', 'private', 'POST', {'cost': 1})
    private_post_solwithdrawal = privatePostSolWithdrawal = Entry[_Dict]('solWithdrawal', 'private', 'POST', {'cost': 1})
    private_post_soldepositaddresses = privatePostSolDepositAddresses = Entry[_Dict]('solDepositAddresses', 'private', 'POST', {'cost': 1})
    private_post_unconfirmedsoldeposits = privatePostUnconfirmedSolDeposits = Entry[_Dict]('unconfirmedSolDeposits', 'private', 'POST', {'cost': 1})
    private_post_bankwirewithdrawal = privatePostBankWireWithdrawal = Entry[_Dict]('bankWireWithdrawal', 'private', 'POST', {'cost': 1})
