from ccxt.base.types import Entry
_List = list[object]
_Dict = dict[str, object]


class ImplicitAPI:
    v1_public_get_assets = v1PublicGetAssets = Entry[_List]('assets', ['v1', 'public'], 'GET', {'cost': 1})
    v1_public_get_assets_assets = v1PublicGetAssetsAssets = Entry[_Dict]('assets/{assets}', ['v1', 'public'], 'GET', {'cost': 1})
    v1_public_get_assets_asset_networks = v1PublicGetAssetsAssetNetworks = Entry[_List]('assets/{asset}/networks', ['v1', 'public'], 'GET', {'cost': 1})
    v1_public_get_instruments = v1PublicGetInstruments = Entry[_List]('instruments', ['v1', 'public'], 'GET', {'cost': 1})
    v1_public_get_instruments_instrument = v1PublicGetInstrumentsInstrument = Entry[_Dict]('instruments/{instrument}', ['v1', 'public'], 'GET', {'cost': 1})
    v1_public_get_instruments_instrument_quote = v1PublicGetInstrumentsInstrumentQuote = Entry[_Dict]('instruments/{instrument}/quote', ['v1', 'public'], 'GET', {'cost': 1})
    v1_public_get_instruments_instrument_funding = v1PublicGetInstrumentsInstrumentFunding = Entry[_Dict]('instruments/{instrument}/funding', ['v1', 'public'], 'GET', {'cost': 1})
    v1_public_get_instruments_instrument_candles = v1PublicGetInstrumentsInstrumentCandles = Entry[_Dict]('instruments/{instrument}/candles', ['v1', 'public'], 'GET', {'cost': 1})
    v1_public_get_instruments_volumes_daily = v1PublicGetInstrumentsVolumesDaily = Entry[_Dict]('instruments/volumes/daily', ['v1', 'public'], 'GET', {'cost': 1})
    v1_public_get_position_offsets = v1PublicGetPositionOffsets = Entry[_Dict]('position-offsets', ['v1', 'public'], 'GET', {'cost': 1})
    v1_public_get_fee_rate_tiers = v1PublicGetFeeRateTiers = Entry[_List]('fee-rate-tiers', ['v1', 'public'], 'GET', {'cost': 1})
    v1_private_get_address_book = v1PrivateGetAddressBook = Entry[_List]('address-book', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_orders = v1PrivateGetOrders = Entry[_Dict]('orders', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_orders_id = v1PrivateGetOrdersId = Entry[_Dict]('orders/{id}', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_index_index_composition = v1PrivateGetIndexIndexComposition = Entry[_Dict]('index/{index}/composition', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_index_index_composition_history = v1PrivateGetIndexIndexCompositionHistory = Entry[_Dict]('index/{index}/composition-history', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_index_index_price = v1PrivateGetIndexIndexPrice = Entry[_Dict]('index/{index}/price', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_index_index_candles = v1PrivateGetIndexIndexCandles = Entry[_Dict]('index/{index}/candles', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_portfolios = v1PrivateGetPortfolios = Entry[_List]('portfolios', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_portfolios_portfolio = v1PrivateGetPortfoliosPortfolio = Entry[_Dict]('portfolios/{portfolio}', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_portfolios_portfolio_detail = v1PrivateGetPortfoliosPortfolioDetail = Entry[_Dict]('portfolios/{portfolio}/detail', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_portfolios_portfolio_summary = v1PrivateGetPortfoliosPortfolioSummary = Entry[_Dict]('portfolios/{portfolio}/summary', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_portfolios_portfolio_balances = v1PrivateGetPortfoliosPortfolioBalances = Entry[_List]('portfolios/{portfolio}/balances', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_portfolios_portfolio_balances_asset = v1PrivateGetPortfoliosPortfolioBalancesAsset = Entry[_Dict]('portfolios/{portfolio}/balances/{asset}', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_portfolios_portfolio_positions = v1PrivateGetPortfoliosPortfolioPositions = Entry[_List]('portfolios/{portfolio}/positions', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_portfolios_portfolio_positions_instrument = v1PrivateGetPortfoliosPortfolioPositionsInstrument = Entry[_Dict]('portfolios/{portfolio}/positions/{instrument}', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_portfolios_portfolio_position_limits = v1PrivateGetPortfoliosPortfolioPositionLimits = Entry[_Dict]('portfolios/{portfolio}/position-limits', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_portfolios_portfolio_position_limits_positions = v1PrivateGetPortfoliosPortfolioPositionLimitsPositions = Entry[_List]('portfolios/{portfolio}/position-limits/positions', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_portfolios_portfolio_position_limits_positions_instrument = v1PrivateGetPortfoliosPortfolioPositionLimitsPositionsInstrument = Entry[_Dict]('portfolios/{portfolio}/position-limits/positions/{instrument}', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_portfolios_fills = v1PrivateGetPortfoliosFills = Entry[_Dict]('portfolios/fills', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_portfolios_portfolio_fills = v1PrivateGetPortfoliosPortfolioFills = Entry[_Dict]('portfolios/{portfolio}/fills', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_portfolios_fee_rates = v1PrivateGetPortfoliosFeeRates = Entry[_List]('portfolios/fee-rates', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_portfolios_portfolio_loans = v1PrivateGetPortfoliosPortfolioLoans = Entry[_List]('portfolios/{portfolio}/loans', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_portfolios_portfolio_loans_asset = v1PrivateGetPortfoliosPortfolioLoansAsset = Entry[_Dict]('portfolios/{portfolio}/loans/{asset}', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_portfolios_portfolio_loans_asset_availability = v1PrivateGetPortfoliosPortfolioLoansAssetAvailability = Entry[_Dict]('portfolios/{portfolio}/loans/{asset}/availability', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_portfolios_portfolio_margin_call_status = v1PrivateGetPortfoliosPortfolioMarginCallStatus = Entry[_Dict]('portfolios/{portfolio}/margin-call-status', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_transfers = v1PrivateGetTransfers = Entry[_Dict]('transfers', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_transfers_transfer_uuid = v1PrivateGetTransfersTransferUuid = Entry[_Dict]('transfers/{transfer_uuid}', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_transfers_withdraw_portfolio_asset_counterparty_withdrawal_limit = v1PrivateGetTransfersWithdrawPortfolioAssetCounterpartyWithdrawalLimit = Entry[_Dict]('transfers/withdraw/{portfolio}/{asset}/counterparty-withdrawal-limit', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_post_orders = v1PrivatePostOrders = Entry[_Dict]('orders', ['v1', 'private'], 'POST', {'cost': 1})
    v1_private_post_portfolios = v1PrivatePostPortfolios = Entry[_Dict]('portfolios', ['v1', 'private'], 'POST', {'cost': 1})
    v1_private_post_portfolios_margin = v1PrivatePostPortfoliosMargin = Entry[_Dict]('portfolios/margin', ['v1', 'private'], 'POST', {'cost': 1})
    v1_private_post_portfolios_portfolio_cross_collateral_enabled = v1PrivatePostPortfoliosPortfolioCrossCollateralEnabled = Entry[_Dict]('portfolios/{portfolio}/cross-collateral-enabled', ['v1', 'private'], 'POST', {'cost': 1})
    v1_private_post_portfolios_portfolio_auto_margin_enabled = v1PrivatePostPortfoliosPortfolioAutoMarginEnabled = Entry[_Dict]('portfolios/{portfolio}/auto-margin-enabled', ['v1', 'private'], 'POST', {'cost': 1})
    v1_private_post_portfolios_portfolio_loans_asset = v1PrivatePostPortfoliosPortfolioLoansAsset = Entry[_Dict]('portfolios/{portfolio}/loans/{asset}', ['v1', 'private'], 'POST', {'cost': 1})
    v1_private_post_portfolios_portfolio_loans_asset_preview = v1PrivatePostPortfoliosPortfolioLoansAssetPreview = Entry[_Dict]('portfolios/{portfolio}/loans/{asset}/preview', ['v1', 'private'], 'POST', {'cost': 1})
    v1_private_post_portfolios_transfer = v1PrivatePostPortfoliosTransfer = Entry[_Dict]('portfolios/transfer', ['v1', 'private'], 'POST', {'cost': 1})
    v1_private_post_portfolios_transfer_position = v1PrivatePostPortfoliosTransferPosition = Entry[_Dict]('portfolios/transfer-position', ['v1', 'private'], 'POST', {'cost': 1})
    v1_private_post_transfers_withdraw = v1PrivatePostTransfersWithdraw = Entry[_Dict]('transfers/withdraw', ['v1', 'private'], 'POST', {'cost': 1})
    v1_private_post_transfers_address = v1PrivatePostTransfersAddress = Entry[_Dict]('transfers/address', ['v1', 'private'], 'POST', {'cost': 1})
    v1_private_post_transfers_create_counterparty_id = v1PrivatePostTransfersCreateCounterpartyId = Entry[_Dict]('transfers/create-counterparty-id', ['v1', 'private'], 'POST', {'cost': 1})
    v1_private_post_transfers_validate_counterparty_id = v1PrivatePostTransfersValidateCounterpartyId = Entry[_Dict]('transfers/validate-counterparty-id', ['v1', 'private'], 'POST', {'cost': 1})
    v1_private_post_transfers_withdraw_counterparty = v1PrivatePostTransfersWithdrawCounterparty = Entry[_Dict]('transfers/withdraw/counterparty', ['v1', 'private'], 'POST', {'cost': 1})
    v1_private_put_orders_id = v1PrivatePutOrdersId = Entry[_Dict]('orders/{id}', ['v1', 'private'], 'PUT', {'cost': 1})
    v1_private_put_portfolios_portfolio = v1PrivatePutPortfoliosPortfolio = Entry[_Dict]('portfolios/{portfolio}', ['v1', 'private'], 'PUT', {'cost': 1})
    v1_private_delete_orders = v1PrivateDeleteOrders = Entry[_List]('orders', ['v1', 'private'], 'DELETE', {'cost': 1})
    v1_private_delete_orders_id = v1PrivateDeleteOrdersId = Entry[_Dict]('orders/{id}', ['v1', 'private'], 'DELETE', {'cost': 1})
    v1_private_patch_portfolios_portfolio = v1PrivatePatchPortfoliosPortfolio = Entry[_Dict]('portfolios/{portfolio}', ['v1', 'private'], 'PATCH', {'cost': 1})
