from ccxt.base.types import Entry
from typing import Any as PythonAny, Dict

_Dict = Dict[str, PythonAny]

class ImplicitAPI:
    public_get_deepcoin_market_books = publicGetDeepcoinMarketBooks = Entry[_Dict]('deepcoin/market/books', 'public', 'GET', {'cost': 1})
    public_get_deepcoin_market_candles = publicGetDeepcoinMarketCandles = Entry[_Dict]('deepcoin/market/candles', 'public', 'GET', {'cost': 1})
    public_get_deepcoin_market_instruments = publicGetDeepcoinMarketInstruments = Entry[_Dict]('deepcoin/market/instruments', 'public', 'GET', {'cost': 1})
    public_get_deepcoin_market_tickers = publicGetDeepcoinMarketTickers = Entry[_Dict]('deepcoin/market/tickers', 'public', 'GET', {'cost': 1})
    public_get_deepcoin_market_index_candles = publicGetDeepcoinMarketIndexCandles = Entry[_Dict]('deepcoin/market/index-candles', 'public', 'GET', {'cost': 1})
    public_get_deepcoin_market_trades = publicGetDeepcoinMarketTrades = Entry[_Dict]('deepcoin/market/trades', 'public', 'GET', {'cost': 1})
    public_get_deepcoin_market_mark_price_candles = publicGetDeepcoinMarketMarkPriceCandles = Entry[_Dict]('deepcoin/market/mark-price-candles', 'public', 'GET', {'cost': 1})
    public_get_deepcoin_market_step_margin = publicGetDeepcoinMarketStepMargin = Entry[_Dict]('deepcoin/market/step-margin', 'public', 'GET', {'cost': 5})
    public_get_deepcoin_trade_funding_rate = publicGetDeepcoinTradeFundingRate = Entry[_Dict]('deepcoin/trade/funding-rate', 'public', 'GET', {'cost': 5})
    public_get_deepcoin_trade_fund_rate_current_funding_rate = publicGetDeepcoinTradeFundRateCurrentFundingRate = Entry[_Dict]('deepcoin/trade/fund-rate/current-funding-rate', 'public', 'GET', {'cost': 5})
    public_get_deepcoin_trade_fund_rate_history = publicGetDeepcoinTradeFundRateHistory = Entry[_Dict]('deepcoin/trade/fund-rate/history', 'public', 'GET', {'cost': 5})
    private_get_deepcoin_account_balances = privateGetDeepcoinAccountBalances = Entry[_Dict]('deepcoin/account/balances', 'private', 'GET', {'cost': 5})
    private_get_deepcoin_account_bills = privateGetDeepcoinAccountBills = Entry[_Dict]('deepcoin/account/bills', 'private', 'GET', {'cost': 5})
    private_get_deepcoin_account_positions = privateGetDeepcoinAccountPositions = Entry[_Dict]('deepcoin/account/positions', 'private', 'GET', {'cost': 5})
    private_get_deepcoin_trade_fills = privateGetDeepcoinTradeFills = Entry[_Dict]('deepcoin/trade/fills', 'private', 'GET', {'cost': 5})
    private_get_deepcoin_trade_orderbyid = privateGetDeepcoinTradeOrderByID = Entry[_Dict]('deepcoin/trade/orderByID', 'private', 'GET', {'cost': 5})
    private_get_deepcoin_trade_finishorderbyid = privateGetDeepcoinTradeFinishOrderByID = Entry[_Dict]('deepcoin/trade/finishOrderByID', 'private', 'GET', {'cost': 5})
    private_get_deepcoin_trade_orders_history = privateGetDeepcoinTradeOrdersHistory = Entry[_Dict]('deepcoin/trade/orders-history', 'private', 'GET', {'cost': 5})
    private_get_deepcoin_trade_v2_orders_pending = privateGetDeepcoinTradeV2OrdersPending = Entry[_Dict]('deepcoin/trade/v2/orders-pending', 'private', 'GET', {'cost': 5})
    private_get_deepcoin_trade_trigger_orders_pending = privateGetDeepcoinTradeTriggerOrdersPending = Entry[_Dict]('deepcoin/trade/trigger-orders-pending', 'private', 'GET', {'cost': 5})
    private_get_deepcoin_trade_trigger_orders_history = privateGetDeepcoinTradeTriggerOrdersHistory = Entry[_Dict]('deepcoin/trade/trigger-orders-history', 'private', 'GET', {'cost': 5})
    private_get_deepcoin_copytrading_support_contracts = privateGetDeepcoinCopytradingSupportContracts = Entry[_Dict]('deepcoin/copytrading/support-contracts', 'private', 'GET', {'cost': 5})
    private_get_deepcoin_copytrading_leader_position = privateGetDeepcoinCopytradingLeaderPosition = Entry[_Dict]('deepcoin/copytrading/leader-position', 'private', 'GET', {'cost': 5})
    private_get_deepcoin_copytrading_estimate_profit = privateGetDeepcoinCopytradingEstimateProfit = Entry[_Dict]('deepcoin/copytrading/estimate-profit', 'private', 'GET', {'cost': 5})
    private_get_deepcoin_copytrading_history_profit = privateGetDeepcoinCopytradingHistoryProfit = Entry[_Dict]('deepcoin/copytrading/history-profit', 'private', 'GET', {'cost': 5})
    private_get_deepcoin_copytrading_follower_rank = privateGetDeepcoinCopytradingFollowerRank = Entry[_Dict]('deepcoin/copytrading/follower-rank', 'private', 'GET', {'cost': 5})
    private_get_deepcoin_internal_transfer_support = privateGetDeepcoinInternalTransferSupport = Entry[_Dict]('deepcoin/internal-transfer/support', 'private', 'GET', {'cost': 5})
    private_get_deepcoin_internal_transfer_history_order = privateGetDeepcoinInternalTransferHistoryOrder = Entry[_Dict]('deepcoin/internal-transfer/history-order', 'private', 'GET', {'cost': 5})
    private_get_deepcoin_rebate_config = privateGetDeepcoinRebateConfig = Entry[_Dict]('deepcoin/rebate/config', 'private', 'GET', {'cost': 5})
    private_get_deepcoin_agents_users = privateGetDeepcoinAgentsUsers = Entry[_Dict]('deepcoin/agents/users', 'private', 'GET', {'cost': 5})
    private_get_deepcoin_agents_users_rebate_list = privateGetDeepcoinAgentsUsersRebateList = Entry[_Dict]('deepcoin/agents/users/rebate-list', 'private', 'GET', {'cost': 5})
    private_get_deepcoin_agents_users_rebates = privateGetDeepcoinAgentsUsersRebates = Entry[_Dict]('deepcoin/agents/users/rebates', 'private', 'GET', {'cost': 5})
    private_get_deepcoin_asset_deposit_list = privateGetDeepcoinAssetDepositList = Entry[_Dict]('deepcoin/asset/deposit-list', 'private', 'GET', {'cost': 5})
    private_get_deepcoin_asset_withdraw_list = privateGetDeepcoinAssetWithdrawList = Entry[_Dict]('deepcoin/asset/withdraw-list', 'private', 'GET', {'cost': 5})
    private_get_deepcoin_asset_recharge_chain_list = privateGetDeepcoinAssetRechargeChainList = Entry[_Dict]('deepcoin/asset/recharge-chain-list', 'private', 'GET', {'cost': 5})
    private_get_deepcoin_listenkey_acquire = privateGetDeepcoinListenkeyAcquire = Entry[_Dict]('deepcoin/listenkey/acquire', 'private', 'GET', {'cost': 5})
    private_get_deepcoin_listenkey_extend = privateGetDeepcoinListenkeyExtend = Entry[_Dict]('deepcoin/listenkey/extend', 'private', 'GET', {'cost': 5})
    private_post_deepcoin_account_set_leverage = privatePostDeepcoinAccountSetLeverage = Entry[_Dict]('deepcoin/account/set-leverage', 'private', 'POST', {'cost': 5})
    private_post_deepcoin_trade_order = privatePostDeepcoinTradeOrder = Entry[_Dict]('deepcoin/trade/order', 'private', 'POST', {'cost': 5})
    private_post_deepcoin_trade_replace_order = privatePostDeepcoinTradeReplaceOrder = Entry[_Dict]('deepcoin/trade/replace-order', 'private', 'POST', {'cost': 5})
    private_post_deepcoin_trade_cancel_order = privatePostDeepcoinTradeCancelOrder = Entry[_Dict]('deepcoin/trade/cancel-order', 'private', 'POST', {'cost': 5})
    private_post_deepcoin_trade_batch_cancel_order = privatePostDeepcoinTradeBatchCancelOrder = Entry[_Dict]('deepcoin/trade/batch-cancel-order', 'private', 'POST', {'cost': 5})
    private_post_deepcoin_trade_cancel_trigger_order = privatePostDeepcoinTradeCancelTriggerOrder = Entry[_Dict]('deepcoin/trade/cancel-trigger-order', 'private', 'POST', {'cost': 0.16666666666666666})
    private_post_deepcoin_trade_swap_cancel_all = privatePostDeepcoinTradeSwapCancelAll = Entry[_Dict]('deepcoin/trade/swap/cancel-all', 'private', 'POST', {'cost': 5})
    private_post_deepcoin_trade_trigger_order = privatePostDeepcoinTradeTriggerOrder = Entry[_Dict]('deepcoin/trade/trigger-order', 'private', 'POST', {'cost': 5})
    private_post_deepcoin_trade_batch_close_position = privatePostDeepcoinTradeBatchClosePosition = Entry[_Dict]('deepcoin/trade/batch-close-position', 'private', 'POST', {'cost': 5})
    private_post_deepcoin_trade_replace_order_sltp = privatePostDeepcoinTradeReplaceOrderSltp = Entry[_Dict]('deepcoin/trade/replace-order-sltp', 'private', 'POST', {'cost': 5})
    private_post_deepcoin_trade_close_position_by_ids = privatePostDeepcoinTradeClosePositionByIds = Entry[_Dict]('deepcoin/trade/close-position-by-ids', 'private', 'POST', {'cost': 5})
    private_post_deepcoin_copytrading_leader_settings = privatePostDeepcoinCopytradingLeaderSettings = Entry[_Dict]('deepcoin/copytrading/leader-settings', 'private', 'POST', {'cost': 5})
    private_post_deepcoin_copytrading_set_contracts = privatePostDeepcoinCopytradingSetContracts = Entry[_Dict]('deepcoin/copytrading/set-contracts', 'private', 'POST', {'cost': 5})
    private_post_deepcoin_internal_transfer = privatePostDeepcoinInternalTransfer = Entry[_Dict]('deepcoin/internal-transfer', 'private', 'POST', {'cost': 5})
    private_post_deepcoin_rebate_config = privatePostDeepcoinRebateConfig = Entry[_Dict]('deepcoin/rebate/config', 'private', 'POST', {'cost': 5})
    private_post_deepcoin_asset_transfer = privatePostDeepcoinAssetTransfer = Entry[_Dict]('deepcoin/asset/transfer', 'private', 'POST', {'cost': 5})
