from ccxt.base.types import Entry
from typing import Any as PythonAny, Dict, List

_Dict = Dict[str, PythonAny]
_List = List[PythonAny]

class ImplicitAPI:
    public_get_assets = publicGetAssets = Entry[_Dict]('assets', 'public', 'GET', {'cost': 1})
    public_get_indices = publicGetIndices = Entry[_Dict]('indices', 'public', 'GET', {'cost': 1})
    public_get_products = publicGetProducts = Entry[_Dict]('products', 'public', 'GET', {'cost': 1})
    public_get_products_symbol = publicGetProductsSymbol = Entry[_Dict]('products/{symbol}', 'public', 'GET', {'cost': 1})
    public_get_tickers = publicGetTickers = Entry[_Dict]('tickers', 'public', 'GET', {'cost': 1})
    public_get_tickers_symbol = publicGetTickersSymbol = Entry[_Dict]('tickers/{symbol}', 'public', 'GET', {'cost': 1})
    public_get_l2orderbook_symbol = publicGetL2orderbookSymbol = Entry[_Dict]('l2orderbook/{symbol}', 'public', 'GET', {'cost': 1})
    public_get_trades_symbol = publicGetTradesSymbol = Entry[_Dict]('trades/{symbol}', 'public', 'GET', {'cost': 1})
    public_get_stats = publicGetStats = Entry[_List]('stats', 'public', 'GET', {'cost': 1})
    public_get_history_candles = publicGetHistoryCandles = Entry[_Dict]('history/candles', 'public', 'GET', {'cost': 1})
    public_get_history_sparklines = publicGetHistorySparklines = Entry[_Dict]('history/sparklines', 'public', 'GET', {'cost': 1})
    public_get_settings = publicGetSettings = Entry[_Dict]('settings', 'public', 'GET', {'cost': 1})
    private_get_orders = privateGetOrders = Entry[_Dict]('orders', 'private', 'GET', {'cost': 1})
    private_get_orders_order_id = privateGetOrdersOrderId = Entry[_Dict]('orders/{order_id}', 'private', 'GET', {'cost': 1})
    private_get_orders_client_order_id_client_oid = privateGetOrdersClientOrderIdClientOid = Entry[_Dict]('orders/client_order_id/{client_oid}', 'private', 'GET', {'cost': 1})
    private_get_products_product_id_orders_leverage = privateGetProductsProductIdOrdersLeverage = Entry[_Dict]('products/{product_id}/orders/leverage', 'private', 'GET', {'cost': 1})
    private_get_positions_margined = privateGetPositionsMargined = Entry[_Dict]('positions/margined', 'private', 'GET', {'cost': 1})
    private_get_positions = privateGetPositions = Entry[_Dict]('positions', 'private', 'GET', {'cost': 1})
    private_get_orders_history = privateGetOrdersHistory = Entry[_Dict]('orders/history', 'private', 'GET', {'cost': 1})
    private_get_fills = privateGetFills = Entry[_Dict]('fills', 'private', 'GET', {'cost': 1})
    private_get_fills_history_download_csv = privateGetFillsHistoryDownloadCsv = Entry[_Dict]('fills/history/download/csv', 'private', 'GET', {'cost': 1})
    private_get_wallet_balances = privateGetWalletBalances = Entry[_Dict]('wallet/balances', 'private', 'GET', {'cost': 1})
    private_get_wallet_transactions = privateGetWalletTransactions = Entry[_Dict]('wallet/transactions', 'private', 'GET', {'cost': 1})
    private_get_wallet_transactions_download = privateGetWalletTransactionsDownload = Entry[_Dict]('wallet/transactions/download', 'private', 'GET', {'cost': 1})
    private_get_wallets_sub_accounts_transfer_history = privateGetWalletsSubAccountsTransferHistory = Entry[_Dict]('wallets/sub_accounts_transfer_history', 'private', 'GET', {'cost': 1})
    private_get_users_trading_preferences = privateGetUsersTradingPreferences = Entry[_Dict]('users/trading_preferences', 'private', 'GET', {'cost': 1})
    private_get_sub_accounts = privateGetSubAccounts = Entry[_Dict]('sub_accounts', 'private', 'GET', {'cost': 1})
    private_get_profile = privateGetProfile = Entry[_Dict]('profile', 'private', 'GET', {'cost': 1})
    private_get_rate_limits_quota = privateGetRateLimitsQuota = Entry[_Dict]('rate_limits/quota', 'private', 'GET', {'cost': 1})
    private_get_heartbeat = privateGetHeartbeat = Entry[_Dict]('heartbeat', 'private', 'GET', {'cost': 1})
    private_get_deposits_address = privateGetDepositsAddress = Entry[_Dict]('deposits/address', 'private', 'GET', {'cost': 1})
    private_post_orders = privatePostOrders = Entry[_Dict]('orders', 'private', 'POST', {'cost': 1})
    private_post_orders_bracket = privatePostOrdersBracket = Entry[_Dict]('orders/bracket', 'private', 'POST', {'cost': 1})
    private_post_orders_batch = privatePostOrdersBatch = Entry[_Dict]('orders/batch', 'private', 'POST', {'cost': 1})
    private_post_products_product_id_orders_leverage = privatePostProductsProductIdOrdersLeverage = Entry[_Dict]('products/{product_id}/orders/leverage', 'private', 'POST', {'cost': 1})
    private_post_positions_change_margin = privatePostPositionsChangeMargin = Entry[_Dict]('positions/change_margin', 'private', 'POST', {'cost': 1})
    private_post_positions_close_all = privatePostPositionsCloseAll = Entry[_Dict]('positions/close_all', 'private', 'POST', {'cost': 1})
    private_post_wallets_sub_account_balance_transfer = privatePostWalletsSubAccountBalanceTransfer = Entry[_Dict]('wallets/sub_account_balance_transfer', 'private', 'POST', {'cost': 1})
    private_post_heartbeat_create = privatePostHeartbeatCreate = Entry[_Dict]('heartbeat/create', 'private', 'POST', {'cost': 1})
    private_post_heartbeat = privatePostHeartbeat = Entry[_Dict]('heartbeat', 'private', 'POST', {'cost': 1})
    private_post_orders_cancel_after = privatePostOrdersCancelAfter = Entry[_Dict]('orders/cancel_after', 'private', 'POST', {'cost': 1})
    private_post_orders_leverage = privatePostOrdersLeverage = Entry[_Dict]('orders/leverage', 'private', 'POST', {'cost': 1})
    private_put_orders = privatePutOrders = Entry[_Dict]('orders', 'private', 'PUT', {'cost': 1})
    private_put_orders_bracket = privatePutOrdersBracket = Entry[_Dict]('orders/bracket', 'private', 'PUT', {'cost': 1})
    private_put_orders_batch = privatePutOrdersBatch = Entry[_Dict]('orders/batch', 'private', 'PUT', {'cost': 1})
    private_put_positions_auto_topup = privatePutPositionsAutoTopup = Entry[_Dict]('positions/auto_topup', 'private', 'PUT', {'cost': 1})
    private_put_users_update_mmp = privatePutUsersUpdateMmp = Entry[_Dict]('users/update_mmp', 'private', 'PUT', {'cost': 1})
    private_put_users_reset_mmp = privatePutUsersResetMmp = Entry[_Dict]('users/reset_mmp', 'private', 'PUT', {'cost': 1})
    private_put_users_margin_mode = privatePutUsersMarginMode = Entry[_Dict]('users/margin_mode', 'private', 'PUT', {'cost': 1})
    private_delete_orders = privateDeleteOrders = Entry[_Dict]('orders', 'private', 'DELETE', {'cost': 1})
    private_delete_orders_all = privateDeleteOrdersAll = Entry[_Dict]('orders/all', 'private', 'DELETE', {'cost': 1})
    private_delete_orders_batch = privateDeleteOrdersBatch = Entry[_Dict]('orders/batch', 'private', 'DELETE', {'cost': 1})
