from ccxt.base.types import Entry
from typing import Any as PythonAny, Dict, List

_Dict = Dict[str, PythonAny]
_List = List[PythonAny]

class ImplicitAPI:
    indexer_get_addresses_address = indexerGetAddressesAddress = Entry[_Dict]('addresses/{address}', 'indexer', 'GET', {'cost': 1})
    indexer_get_addresses_address_parentsubaccountnumber_number = indexerGetAddressesAddressParentSubaccountNumberNumber = Entry[_Dict]('addresses/{address}/parentSubaccountNumber/{number}', 'indexer', 'GET', {'cost': 1})
    indexer_get_addresses_address_subaccountnumber_subaccountnumber = indexerGetAddressesAddressSubaccountNumberSubaccountNumber = Entry[_Dict]('addresses/{address}/subaccountNumber/{subaccountNumber}', 'indexer', 'GET', {'cost': 1})
    indexer_get_assetpositions = indexerGetAssetPositions = Entry[_Dict]('assetPositions', 'indexer', 'GET', {'cost': 1})
    indexer_get_assetpositions_parentsubaccountnumber = indexerGetAssetPositionsParentSubaccountNumber = Entry[_Dict]('assetPositions/parentSubaccountNumber', 'indexer', 'GET', {'cost': 1})
    indexer_get_candles_perpetualmarkets_market = indexerGetCandlesPerpetualMarketsMarket = Entry[_Dict]('candles/perpetualMarkets/{market}', 'indexer', 'GET', {'cost': 1})
    indexer_get_compliance_screen_address = indexerGetComplianceScreenAddress = Entry[_Dict]('compliance/screen/{address}', 'indexer', 'GET', {'cost': 1})
    indexer_get_fills = indexerGetFills = Entry[_Dict]('fills', 'indexer', 'GET', {'cost': 1})
    indexer_get_fills_parentsubaccountnumber = indexerGetFillsParentSubaccountNumber = Entry[_Dict]('fills/parentSubaccountNumber', 'indexer', 'GET', {'cost': 1})
    indexer_get_fundingpayments = indexerGetFundingPayments = Entry[_Dict]('fundingPayments', 'indexer', 'GET', {'cost': 1})
    indexer_get_fundingpayments_parentsubaccount = indexerGetFundingPaymentsParentSubaccount = Entry[_Dict]('fundingPayments/parentSubaccount', 'indexer', 'GET', {'cost': 1})
    indexer_get_height = indexerGetHeight = Entry[_Dict]('height', 'indexer', 'GET', {'cost': 0.1})
    indexer_get_historical_pnl = indexerGetHistoricalPnl = Entry[_Dict]('historical-pnl', 'indexer', 'GET', {'cost': 1})
    indexer_get_historical_pnl_parentsubaccountnumber = indexerGetHistoricalPnlParentSubaccountNumber = Entry[_Dict]('historical-pnl/parentSubaccountNumber', 'indexer', 'GET', {'cost': 1})
    indexer_get_historicalblocktradingrewards_address = indexerGetHistoricalBlockTradingRewardsAddress = Entry[_Dict]('historicalBlockTradingRewards/{address}', 'indexer', 'GET', {'cost': 1})
    indexer_get_historicalfunding_market = indexerGetHistoricalFundingMarket = Entry[_Dict]('historicalFunding/{market}', 'indexer', 'GET', {'cost': 1})
    indexer_get_historicaltradingrewardaggregations_address = indexerGetHistoricalTradingRewardAggregationsAddress = Entry[_Dict]('historicalTradingRewardAggregations/{address}', 'indexer', 'GET', {'cost': 1})
    indexer_get_orderbooks_perpetualmarket_market = indexerGetOrderbooksPerpetualMarketMarket = Entry[_Dict]('orderbooks/perpetualMarket/{market}', 'indexer', 'GET', {'cost': 1})
    indexer_get_orders = indexerGetOrders = Entry[_List]('orders', 'indexer', 'GET', {'cost': 1})
    indexer_get_orders_parentsubaccountnumber = indexerGetOrdersParentSubaccountNumber = Entry[_Dict]('orders/parentSubaccountNumber', 'indexer', 'GET', {'cost': 1})
    indexer_get_orders_orderid = indexerGetOrdersOrderId = Entry[_Dict]('orders/{orderId}', 'indexer', 'GET', {'cost': 1})
    indexer_get_perpetualmarkets = indexerGetPerpetualMarkets = Entry[_Dict]('perpetualMarkets', 'indexer', 'GET', {'cost': 1})
    indexer_get_perpetualpositions = indexerGetPerpetualPositions = Entry[_Dict]('perpetualPositions', 'indexer', 'GET', {'cost': 1})
    indexer_get_perpetualpositions_parentsubaccountnumber = indexerGetPerpetualPositionsParentSubaccountNumber = Entry[_Dict]('perpetualPositions/parentSubaccountNumber', 'indexer', 'GET', {'cost': 1})
    indexer_get_screen = indexerGetScreen = Entry[_Dict]('screen', 'indexer', 'GET', {'cost': 1})
    indexer_get_sparklines = indexerGetSparklines = Entry[_Dict]('sparklines', 'indexer', 'GET', {'cost': 1})
    indexer_get_time = indexerGetTime = Entry[_Dict]('time', 'indexer', 'GET', {'cost': 1})
    indexer_get_trades_perpetualmarket_market = indexerGetTradesPerpetualMarketMarket = Entry[_Dict]('trades/perpetualMarket/{market}', 'indexer', 'GET', {'cost': 1})
    indexer_get_transfers = indexerGetTransfers = Entry[_Dict]('transfers', 'indexer', 'GET', {'cost': 1})
    indexer_get_transfers_between = indexerGetTransfersBetween = Entry[_Dict]('transfers/between', 'indexer', 'GET', {'cost': 1})
    indexer_get_transfers_parentsubaccountnumber = indexerGetTransfersParentSubaccountNumber = Entry[_Dict]('transfers/parentSubaccountNumber', 'indexer', 'GET', {'cost': 1})
    indexer_get_vault_v1_megavault_historicalpnl = indexerGetVaultV1MegavaultHistoricalPnl = Entry[_Dict]('vault/v1/megavault/historicalPnl', 'indexer', 'GET', {'cost': 1})
    indexer_get_vault_v1_megavault_positions = indexerGetVaultV1MegavaultPositions = Entry[_Dict]('vault/v1/megavault/positions', 'indexer', 'GET', {'cost': 1})
    indexer_get_vault_v1_vaults_historicalpnl = indexerGetVaultV1VaultsHistoricalPnl = Entry[_Dict]('vault/v1/vaults/historicalPnl', 'indexer', 'GET', {'cost': 1})
    indexer_get_perpetualmarketsparklines = indexerGetPerpetualMarketSparklines = Entry[_Dict]('perpetualMarketSparklines', 'indexer', 'GET', {'cost': 1})
    indexer_get_perpetualmarkets_ticker = indexerGetPerpetualMarketsTicker = Entry[_Dict]('perpetualMarkets/{ticker}', 'indexer', 'GET', {'cost': 1})
    indexer_get_perpetualmarkets_ticker_orderbook = indexerGetPerpetualMarketsTickerOrderbook = Entry[_Dict]('perpetualMarkets/{ticker}/orderbook', 'indexer', 'GET', {'cost': 1})
    indexer_get_trades_perpetualmarket_ticker = indexerGetTradesPerpetualMarketTicker = Entry[_Dict]('trades/perpetualMarket/{ticker}', 'indexer', 'GET', {'cost': 1})
    indexer_get_historicalfunding_ticker = indexerGetHistoricalFundingTicker = Entry[_Dict]('historicalFunding/{ticker}', 'indexer', 'GET', {'cost': 1})
    indexer_get_candles_ticker_resolution = indexerGetCandlesTickerResolution = Entry[_Dict]('candles/{ticker}/{resolution}', 'indexer', 'GET', {'cost': 1})
    indexer_get_addresses_address_subaccounts = indexerGetAddressesAddressSubaccounts = Entry[_Dict]('addresses/{address}/subaccounts', 'indexer', 'GET', {'cost': 1})
    indexer_get_addresses_address_subaccountnumber_subaccountnumber_assetpositions = indexerGetAddressesAddressSubaccountNumberSubaccountNumberAssetPositions = Entry[_Dict]('addresses/{address}/subaccountNumber/{subaccountNumber}/assetPositions', 'indexer', 'GET', {'cost': 1})
    indexer_get_addresses_address_subaccountnumber_subaccountnumber_perpetualpositions = indexerGetAddressesAddressSubaccountNumberSubaccountNumberPerpetualPositions = Entry[_Dict]('addresses/{address}/subaccountNumber/{subaccountNumber}/perpetualPositions', 'indexer', 'GET', {'cost': 1})
    indexer_get_addresses_address_subaccountnumber_subaccountnumber_orders = indexerGetAddressesAddressSubaccountNumberSubaccountNumberOrders = Entry[_Dict]('addresses/{address}/subaccountNumber/{subaccountNumber}/orders', 'indexer', 'GET', {'cost': 1})
    indexer_get_fills_parentsubaccount = indexerGetFillsParentSubaccount = Entry[_Dict]('fills/parentSubaccount', 'indexer', 'GET', {'cost': 1})
    indexer_get_historical_pnl_parentsubaccount = indexerGetHistoricalPnlParentSubaccount = Entry[_Dict]('historical-pnl/parentSubaccount', 'indexer', 'GET', {'cost': 1})
    noderpc_get_abci_info = nodeRpcGetAbciInfo = Entry[_Dict]('abci_info', 'nodeRpc', 'GET', {'cost': 1})
    noderpc_get_block = nodeRpcGetBlock = Entry[_Dict]('block', 'nodeRpc', 'GET', {'cost': 1})
    noderpc_get_broadcast_tx_async = nodeRpcGetBroadcastTxAsync = Entry[_Dict]('broadcast_tx_async', 'nodeRpc', 'GET', {'cost': 1})
    noderpc_get_broadcast_tx_sync = nodeRpcGetBroadcastTxSync = Entry[_Dict]('broadcast_tx_sync', 'nodeRpc', 'GET', {'cost': 1})
    noderpc_get_tx = nodeRpcGetTx = Entry[_Dict]('tx', 'nodeRpc', 'GET', {'cost': 1})
    noderest_get_cosmos_auth_v1beta1_account_info_dydxaddress = nodeRestGetCosmosAuthV1beta1AccountInfoDydxAddress = Entry[_Dict]('cosmos/auth/v1beta1/account_info/{dydxAddress}', 'nodeRest', 'GET', {'cost': 1})
    noderest_post_cosmos_tx_v1beta1_encode = nodeRestPostCosmosTxV1beta1Encode = Entry[_Dict]('cosmos/tx/v1beta1/encode', 'nodeRest', 'POST', {'cost': 1})
    noderest_post_cosmos_tx_v1beta1_simulate = nodeRestPostCosmosTxV1beta1Simulate = Entry[_Dict]('cosmos/tx/v1beta1/simulate', 'nodeRest', 'POST', {'cost': 1})
