from ccxt.base.types import Entry
from typing import Any as PythonAny, Dict, List, Union

_Dict = Dict[str, PythonAny]
_List = List[PythonAny]

class ImplicitAPI:
    web_get_ctrl_feesandlimits = webGetCtrlFeesAndLimits = Entry[_Dict]('ctrl/feesAndLimits', 'web', 'GET', {'cost': 1})
    web_get_en_docs_fees = webGetEnDocsFees = Entry[_Dict]('en/docs/fees', 'web', 'GET', {'cost': 1})
    public_get_currency = publicGetCurrency = Entry[_List]('currency', 'public', 'GET', {'cost': 1})
    public_get_currency_list_extended = publicGetCurrencyListExtended = Entry[_List]('currency/list/extended', 'public', 'GET', {'cost': 1})
    public_get_order_book = publicGetOrderBook = Entry[_Dict]('order_book', 'public', 'GET', {'cost': 1})
    public_get_pair_settings = publicGetPairSettings = Entry[_Dict]('pair_settings', 'public', 'GET', {'cost': 1})
    public_get_ticker = publicGetTicker = Entry[_Dict]('ticker', 'public', 'GET', {'cost': 1})
    public_get_trades = publicGetTrades = Entry[_Dict]('trades', 'public', 'GET', {'cost': 1})
    public_get_candles_history = publicGetCandlesHistory = Entry[_Dict]('candles_history', 'public', 'GET', {'cost': 1})
    public_get_required_amount = publicGetRequiredAmount = Entry[_Dict]('required_amount', 'public', 'GET', {'cost': 1})
    public_get_payments_providers_crypto_list = publicGetPaymentsProvidersCryptoList = Entry[Union[_Dict, _List]]('payments/providers/crypto/list', 'public', 'GET', {'cost': 1})
    private_post_user_info = privatePostUserInfo = Entry[_Dict]('user_info', 'private', 'POST', {'cost': 1})
    private_post_order_create = privatePostOrderCreate = Entry[_Dict]('order_create', 'private', 'POST', {'cost': 1})
    private_post_order_cancel = privatePostOrderCancel = Entry[_Dict]('order_cancel', 'private', 'POST', {'cost': 1})
    private_post_stop_market_order_create = privatePostStopMarketOrderCreate = Entry[_Dict]('stop_market_order_create', 'private', 'POST', {'cost': 1})
    private_post_stop_market_order_cancel = privatePostStopMarketOrderCancel = Entry[_Dict]('stop_market_order_cancel', 'private', 'POST', {'cost': 1})
    private_post_user_open_orders = privatePostUserOpenOrders = Entry[_Dict]('user_open_orders', 'private', 'POST', {'cost': 1})
    private_post_user_trades = privatePostUserTrades = Entry[_Dict]('user_trades', 'private', 'POST', {'cost': 1})
    private_post_user_cancelled_orders = privatePostUserCancelledOrders = Entry[_List]('user_cancelled_orders', 'private', 'POST', {'cost': 1})
    private_post_order_trades = privatePostOrderTrades = Entry[_Dict]('order_trades', 'private', 'POST', {'cost': 1})
    private_post_deposit_address = privatePostDepositAddress = Entry[_Dict]('deposit_address', 'private', 'POST', {'cost': 1})
    private_post_withdraw_crypt = privatePostWithdrawCrypt = Entry[_Dict]('withdraw_crypt', 'private', 'POST', {'cost': 1})
    private_post_withdraw_get_txid = privatePostWithdrawGetTxid = Entry[_Dict]('withdraw_get_txid', 'private', 'POST', {'cost': 1})
    private_post_excode_create = privatePostExcodeCreate = Entry[_Dict]('excode_create', 'private', 'POST', {'cost': 1})
    private_post_excode_load = privatePostExcodeLoad = Entry[_Dict]('excode_load', 'private', 'POST', {'cost': 1})
    private_post_code_check = privatePostCodeCheck = Entry[_Dict]('code_check', 'private', 'POST', {'cost': 1})
    private_post_wallet_history = privatePostWalletHistory = Entry[_Dict]('wallet_history', 'private', 'POST', {'cost': 1})
    private_post_wallet_operations = privatePostWalletOperations = Entry[_Dict]('wallet_operations', 'private', 'POST', {'cost': 1})
    private_post_margin_user_order_create = privatePostMarginUserOrderCreate = Entry[_Dict]('margin/user/order/create', 'private', 'POST', {'cost': 1})
    private_post_margin_user_order_update = privatePostMarginUserOrderUpdate = Entry[_Dict]('margin/user/order/update', 'private', 'POST', {'cost': 1})
    private_post_margin_user_order_cancel = privatePostMarginUserOrderCancel = Entry[_Dict]('margin/user/order/cancel', 'private', 'POST', {'cost': 1})
    private_post_margin_user_position_close = privatePostMarginUserPositionClose = Entry[_Dict]('margin/user/position/close', 'private', 'POST', {'cost': 1})
    private_post_margin_user_position_margin_add = privatePostMarginUserPositionMarginAdd = Entry[_Dict]('margin/user/position/margin_add', 'private', 'POST', {'cost': 1})
    private_post_margin_user_position_margin_remove = privatePostMarginUserPositionMarginRemove = Entry[_Dict]('margin/user/position/margin_remove', 'private', 'POST', {'cost': 1})
    private_post_margin_currency_list = privatePostMarginCurrencyList = Entry[_Dict]('margin/currency/list', 'private', 'POST', {'cost': 1})
    private_post_margin_pair_list = privatePostMarginPairList = Entry[_Dict]('margin/pair/list', 'private', 'POST', {'cost': 1})
    private_post_margin_settings = privatePostMarginSettings = Entry[_Dict]('margin/settings', 'private', 'POST', {'cost': 1})
    private_post_margin_funding_list = privatePostMarginFundingList = Entry[_Dict]('margin/funding/list', 'private', 'POST', {'cost': 1})
    private_post_margin_user_info = privatePostMarginUserInfo = Entry[_Dict]('margin/user/info', 'private', 'POST', {'cost': 1})
    private_post_margin_user_order_list = privatePostMarginUserOrderList = Entry[_Dict]('margin/user/order/list', 'private', 'POST', {'cost': 1})
    private_post_margin_user_order_history = privatePostMarginUserOrderHistory = Entry[_Dict]('margin/user/order/history', 'private', 'POST', {'cost': 1})
    private_post_margin_user_order_trades = privatePostMarginUserOrderTrades = Entry[_Dict]('margin/user/order/trades', 'private', 'POST', {'cost': 1})
    private_post_margin_user_order_max_quantity = privatePostMarginUserOrderMaxQuantity = Entry[_Dict]('margin/user/order/max_quantity', 'private', 'POST', {'cost': 1})
    private_post_margin_user_position_list = privatePostMarginUserPositionList = Entry[_Dict]('margin/user/position/list', 'private', 'POST', {'cost': 1})
    private_post_margin_user_position_margin_remove_info = privatePostMarginUserPositionMarginRemoveInfo = Entry[_Dict]('margin/user/position/margin_remove_info', 'private', 'POST', {'cost': 1})
    private_post_margin_user_position_margin_add_info = privatePostMarginUserPositionMarginAddInfo = Entry[_Dict]('margin/user/position/margin_add_info', 'private', 'POST', {'cost': 1})
    private_post_margin_user_wallet_list = privatePostMarginUserWalletList = Entry[_Dict]('margin/user/wallet/list', 'private', 'POST', {'cost': 1})
    private_post_margin_user_wallet_history = privatePostMarginUserWalletHistory = Entry[_Dict]('margin/user/wallet/history', 'private', 'POST', {'cost': 1})
    private_post_margin_user_trade_list = privatePostMarginUserTradeList = Entry[_Dict]('margin/user/trade/list', 'private', 'POST', {'cost': 1})
    private_post_margin_trades = privatePostMarginTrades = Entry[_Dict]('margin/trades', 'private', 'POST', {'cost': 1})
    private_post_margin_liquidation_feed = privatePostMarginLiquidationFeed = Entry[_Dict]('margin/liquidation/feed', 'private', 'POST', {'cost': 1})
