from ccxt.base.types import Entry
from typing import Any as PythonAny, Dict, List

_Dict = Dict[str, PythonAny]
_List = List[PythonAny]

class ImplicitAPI:
    v1_public_get_info_markets = v1PublicGetInfoMarkets = Entry[_Dict]('info/markets', ['v1', 'public'], 'GET', {'cost': 1})
    v1_public_get_info_assets = v1PublicGetInfoAssets = Entry[_Dict]('info/assets', ['v1', 'public'], 'GET', {'cost': 1})
    v1_public_get_info_assets_asset_price = v1PublicGetInfoAssetsAssetPrice = Entry[_Dict]('info/assets/{asset}/price', ['v1', 'public'], 'GET', {'cost': 1})
    v1_public_get_info_markets_market_stats = v1PublicGetInfoMarketsMarketStats = Entry[_Dict]('info/markets/{market}/stats', ['v1', 'public'], 'GET', {'cost': 1})
    v1_public_get_info_markets_market_orderbook = v1PublicGetInfoMarketsMarketOrderbook = Entry[_Dict]('info/markets/{market}/orderbook', ['v1', 'public'], 'GET', {'cost': 1})
    v1_public_get_info_markets_market_trades = v1PublicGetInfoMarketsMarketTrades = Entry[_Dict]('info/markets/{market}/trades', ['v1', 'public'], 'GET', {'cost': 1})
    v1_public_get_info_candles_market_candletype = v1PublicGetInfoCandlesMarketCandleType = Entry[_Dict]('info/candles/{market}/{candleType}', ['v1', 'public'], 'GET', {'cost': 1})
    v1_public_get_info_market_funding = v1PublicGetInfoMarketFunding = Entry[_Dict]('info/{market}/funding', ['v1', 'public'], 'GET', {'cost': 1})
    v1_public_get_info_market_open_interests = v1PublicGetInfoMarketOpenInterests = Entry[_Dict]('info/{market}/open-interests', ['v1', 'public'], 'GET', {'cost': 1})
    v1_public_get_info_builder_dashboard = v1PublicGetInfoBuilderDashboard = Entry[_Dict]('info/builder/dashboard', ['v1', 'public'], 'GET', {'cost': 1})
    v1_private_get_user_accounts = v1PrivateGetUserAccounts = Entry[_Dict]('user/accounts', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_user_account_info = v1PrivateGetUserAccountInfo = Entry[_Dict]('user/account/info', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_user_balance = v1PrivateGetUserBalance = Entry[_Dict]('user/balance', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_user_spot_balances = v1PrivateGetUserSpotBalances = Entry[_Dict]('user/spot/balances', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_user_assetoperations = v1PrivateGetUserAssetOperations = Entry[_Dict]('user/assetOperations', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_user_positions = v1PrivateGetUserPositions = Entry[_Dict]('user/positions', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_user_positions_history = v1PrivateGetUserPositionsHistory = Entry[_Dict]('user/positions/history', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_user_orders = v1PrivateGetUserOrders = Entry[_Dict]('user/orders', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_user_orders_history = v1PrivateGetUserOrdersHistory = Entry[_Dict]('user/orders/history', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_user_orders_id = v1PrivateGetUserOrdersId = Entry[_Dict]('user/orders/{id}', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_user_orders_external_externalid = v1PrivateGetUserOrdersExternalExternalId = Entry[_Dict]('user/orders/external/{externalId}', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_user_trades = v1PrivateGetUserTrades = Entry[_Dict]('user/trades', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_user_funding_history = v1PrivateGetUserFundingHistory = Entry[_Dict]('user/funding/history', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_user_rebates_stats = v1PrivateGetUserRebatesStats = Entry[_Dict]('user/rebates/stats', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_user_leverage = v1PrivateGetUserLeverage = Entry[_Dict]('user/leverage', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_user_fees = v1PrivateGetUserFees = Entry[_Dict]('user/fees', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_user_bridge_config = v1PrivateGetUserBridgeConfig = Entry[_Dict]('user/bridge/config', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_user_bridge_quote = v1PrivateGetUserBridgeQuote = Entry[_Dict]('user/bridge/quote', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_user_affiliate = v1PrivateGetUserAffiliate = Entry[_Dict]('user/affiliate', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_user_referrals_status = v1PrivateGetUserReferralsStatus = Entry[_Dict]('user/referrals/status', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_user_referrals_links = v1PrivateGetUserReferralsLinks = Entry[_List]('user/referrals/links', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_user_referrals_dashboard = v1PrivateGetUserReferralsDashboard = Entry[_Dict]('user/referrals/dashboard', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_user_rewards_earned = v1PrivateGetUserRewardsEarned = Entry[_Dict]('user/rewards/earned', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_user_rewards_leaderboard_stats = v1PrivateGetUserRewardsLeaderboardStats = Entry[_Dict]('user/rewards/leaderboard/stats', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_portfolio_charts_equities = v1PrivateGetPortfolioChartsEquities = Entry[_Dict]('portfolio/charts/equities', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_portfolio_charts_pnl = v1PrivateGetPortfolioChartsPnl = Entry[_Dict]('portfolio/charts/pnl', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_vault_public_performance = v1PrivateGetVaultPublicPerformance = Entry[_Dict]('vault/public/performance', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_vault_public_summary = v1PrivateGetVaultPublicSummary = Entry[_Dict]('vault/public/summary', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_get_builder_trades = v1PrivateGetBuilderTrades = Entry[_Dict]('builder/trades', ['v1', 'private'], 'GET', {'cost': 1})
    v1_private_post_user_order = v1PrivatePostUserOrder = Entry[_Dict]('user/order', ['v1', 'private'], 'POST', {'cost': 1})
    v1_private_post_user_order_masscancel = v1PrivatePostUserOrderMassCancel = Entry[_Dict]('user/order/massCancel', ['v1', 'private'], 'POST', {'cost': 1})
    v1_private_post_user_deadmanswitch = v1PrivatePostUserDeadmanswitch = Entry[str]('user/deadmanswitch', ['v1', 'private'], 'POST', {'cost': 1})
    v1_private_post_user_bridge_quote = v1PrivatePostUserBridgeQuote = Entry[_Dict]('user/bridge/quote', ['v1', 'private'], 'POST', {'cost': 1})
    v1_private_post_user_withdrawal = v1PrivatePostUserWithdrawal = Entry[_Dict]('user/withdrawal', ['v1', 'private'], 'POST', {'cost': 1})
    v1_private_post_user_transfer = v1PrivatePostUserTransfer = Entry[_Dict]('user/transfer', ['v1', 'private'], 'POST', {'cost': 1})
    v1_private_post_user_referrals_use = v1PrivatePostUserReferralsUse = Entry[_Dict]('user/referrals/use', ['v1', 'private'], 'POST', {'cost': 1})
    v1_private_post_user_referrals = v1PrivatePostUserReferrals = Entry[_Dict]('user/referrals', ['v1', 'private'], 'POST', {'cost': 1})
    v1_private_put_user_referrals = v1PrivatePutUserReferrals = Entry[_Dict]('user/referrals', ['v1', 'private'], 'PUT', {'cost': 1})
    v1_private_patch_user_leverage = v1PrivatePatchUserLeverage = Entry[_Dict]('user/leverage', ['v1', 'private'], 'PATCH', {'cost': 1})
    v1_private_delete_user_order_id = v1PrivateDeleteUserOrderId = Entry[_Dict]('user/order/{id}', ['v1', 'private'], 'DELETE', {'cost': 1})
    v1_private_delete_user_order = v1PrivateDeleteUserOrder = Entry[_Dict]('user/order', ['v1', 'private'], 'DELETE', {'cost': 1})
