from ccxt.base.types import Entry
from typing import Any as PythonAny, Dict

_Dict = Dict[str, PythonAny]

class ImplicitAPI:
    v2public_get_reference_currencies = v2PublicGetReferenceCurrencies = Entry[_Dict]('reference/currencies', 'v2Public', 'GET', {'cost': 1})
    v2public_get_market_status = v2PublicGetMarketStatus = Entry[_Dict]('market-status', 'v2Public', 'GET', {'cost': 1})
    v2private_get_account_ledger = v2PrivateGetAccountLedger = Entry[_Dict]('account/ledger', 'v2Private', 'GET', {'cost': 1})
    v2private_get_account_withdraw_quota = v2PrivateGetAccountWithdrawQuota = Entry[_Dict]('account/withdraw/quota', 'v2Private', 'GET', {'cost': 1})
    v2private_get_account_withdraw_address = v2PrivateGetAccountWithdrawAddress = Entry[_Dict]('account/withdraw/address', 'v2Private', 'GET', {'cost': 1})
    v2private_get_account_deposit_address = v2PrivateGetAccountDepositAddress = Entry[_Dict]('account/deposit/address', 'v2Private', 'GET', {'cost': 1})
    v2private_get_account_repayment = v2PrivateGetAccountRepayment = Entry[_Dict]('account/repayment', 'v2Private', 'GET', {'cost': 5})
    v2private_get_reference_transact_fee_rate = v2PrivateGetReferenceTransactFeeRate = Entry[_Dict]('reference/transact-fee-rate', 'v2Private', 'GET', {'cost': 1})
    v2private_get_account_asset_valuation = v2PrivateGetAccountAssetValuation = Entry[_Dict]('account/asset-valuation', 'v2Private', 'GET', {'cost': 0.2})
    v2private_get_point_account = v2PrivateGetPointAccount = Entry[_Dict]('point/account', 'v2Private', 'GET', {'cost': 5})
    v2private_get_sub_user_user_list = v2PrivateGetSubUserUserList = Entry[_Dict]('sub-user/user-list', 'v2Private', 'GET', {'cost': 1})
    v2private_get_sub_user_user_state = v2PrivateGetSubUserUserState = Entry[_Dict]('sub-user/user-state', 'v2Private', 'GET', {'cost': 1})
    v2private_get_sub_user_account_list = v2PrivateGetSubUserAccountList = Entry[_Dict]('sub-user/account-list', 'v2Private', 'GET', {'cost': 1})
    v2private_get_sub_user_deposit_address = v2PrivateGetSubUserDepositAddress = Entry[_Dict]('sub-user/deposit-address', 'v2Private', 'GET', {'cost': 1})
    v2private_get_sub_user_query_deposit = v2PrivateGetSubUserQueryDeposit = Entry[_Dict]('sub-user/query-deposit', 'v2Private', 'GET', {'cost': 1})
    v2private_get_user_api_key = v2PrivateGetUserApiKey = Entry[_Dict]('user/api-key', 'v2Private', 'GET', {'cost': 1})
    v2private_get_user_uid = v2PrivateGetUserUid = Entry[_Dict]('user/uid', 'v2Private', 'GET', {'cost': 1})
    v2private_get_algo_orders_opening = v2PrivateGetAlgoOrdersOpening = Entry[_Dict]('algo-orders/opening', 'v2Private', 'GET', {'cost': 1})
    v2private_get_algo_orders_history = v2PrivateGetAlgoOrdersHistory = Entry[_Dict]('algo-orders/history', 'v2Private', 'GET', {'cost': 1})
    v2private_get_algo_orders_specific = v2PrivateGetAlgoOrdersSpecific = Entry[_Dict]('algo-orders/specific', 'v2Private', 'GET', {'cost': 1})
    v2private_get_c2c_offers = v2PrivateGetC2cOffers = Entry[_Dict]('c2c/offers', 'v2Private', 'GET', {'cost': 1})
    v2private_get_c2c_offer = v2PrivateGetC2cOffer = Entry[_Dict]('c2c/offer', 'v2Private', 'GET', {'cost': 1})
    v2private_get_c2c_transactions = v2PrivateGetC2cTransactions = Entry[_Dict]('c2c/transactions', 'v2Private', 'GET', {'cost': 1})
    v2private_get_c2c_repayment = v2PrivateGetC2cRepayment = Entry[_Dict]('c2c/repayment', 'v2Private', 'GET', {'cost': 1})
    v2private_get_c2c_account = v2PrivateGetC2cAccount = Entry[_Dict]('c2c/account', 'v2Private', 'GET', {'cost': 1})
    v2private_get_etp_reference = v2PrivateGetEtpReference = Entry[_Dict]('etp/reference', 'v2Private', 'GET', {'cost': 1})
    v2private_get_etp_transactions = v2PrivateGetEtpTransactions = Entry[_Dict]('etp/transactions', 'v2Private', 'GET', {'cost': 5})
    v2private_get_etp_transaction = v2PrivateGetEtpTransaction = Entry[_Dict]('etp/transaction', 'v2Private', 'GET', {'cost': 5})
    v2private_get_etp_rebalance = v2PrivateGetEtpRebalance = Entry[_Dict]('etp/rebalance', 'v2Private', 'GET', {'cost': 1})
    v2private_get_etp_limit = v2PrivateGetEtpLimit = Entry[_Dict]('etp/limit', 'v2Private', 'GET', {'cost': 1})
    v2private_post_account_transfer = v2PrivatePostAccountTransfer = Entry[_Dict]('account/transfer', 'v2Private', 'POST', {'cost': 1})
    v2private_post_account_repayment = v2PrivatePostAccountRepayment = Entry[_Dict]('account/repayment', 'v2Private', 'POST', {'cost': 5})
    v2private_post_point_transfer = v2PrivatePostPointTransfer = Entry[_Dict]('point/transfer', 'v2Private', 'POST', {'cost': 5})
    v2private_post_sub_user_management = v2PrivatePostSubUserManagement = Entry[_Dict]('sub-user/management', 'v2Private', 'POST', {'cost': 1})
    v2private_post_sub_user_creation = v2PrivatePostSubUserCreation = Entry[_Dict]('sub-user/creation', 'v2Private', 'POST', {'cost': 1})
    v2private_post_sub_user_tradable_market = v2PrivatePostSubUserTradableMarket = Entry[_Dict]('sub-user/tradable-market', 'v2Private', 'POST', {'cost': 1})
    v2private_post_sub_user_transferability = v2PrivatePostSubUserTransferability = Entry[_Dict]('sub-user/transferability', 'v2Private', 'POST', {'cost': 1})
    v2private_post_sub_user_api_key_generation = v2PrivatePostSubUserApiKeyGeneration = Entry[_Dict]('sub-user/api-key-generation', 'v2Private', 'POST', {'cost': 1})
    v2private_post_sub_user_api_key_modification = v2PrivatePostSubUserApiKeyModification = Entry[_Dict]('sub-user/api-key-modification', 'v2Private', 'POST', {'cost': 1})
    v2private_post_sub_user_api_key_deletion = v2PrivatePostSubUserApiKeyDeletion = Entry[_Dict]('sub-user/api-key-deletion', 'v2Private', 'POST', {'cost': 1})
    v2private_post_sub_user_deduct_mode = v2PrivatePostSubUserDeductMode = Entry[_Dict]('sub-user/deduct-mode', 'v2Private', 'POST', {'cost': 1})
    v2private_post_algo_orders = v2PrivatePostAlgoOrders = Entry[_Dict]('algo-orders', 'v2Private', 'POST', {'cost': 1})
    v2private_post_algo_orders_cancel_all_after = v2PrivatePostAlgoOrdersCancelAllAfter = Entry[_Dict]('algo-orders/cancel-all-after', 'v2Private', 'POST', {'cost': 1})
    v2private_post_algo_orders_cancellation = v2PrivatePostAlgoOrdersCancellation = Entry[_Dict]('algo-orders/cancellation', 'v2Private', 'POST', {'cost': 1})
    v2private_post_c2c_offer = v2PrivatePostC2cOffer = Entry[_Dict]('c2c/offer', 'v2Private', 'POST', {'cost': 1})
    v2private_post_c2c_cancellation = v2PrivatePostC2cCancellation = Entry[_Dict]('c2c/cancellation', 'v2Private', 'POST', {'cost': 1})
    v2private_post_c2c_cancel_all = v2PrivatePostC2cCancelAll = Entry[_Dict]('c2c/cancel-all', 'v2Private', 'POST', {'cost': 1})
    v2private_post_c2c_repayment = v2PrivatePostC2cRepayment = Entry[_Dict]('c2c/repayment', 'v2Private', 'POST', {'cost': 1})
    v2private_post_c2c_transfer = v2PrivatePostC2cTransfer = Entry[_Dict]('c2c/transfer', 'v2Private', 'POST', {'cost': 1})
    v2private_post_etp_creation = v2PrivatePostEtpCreation = Entry[_Dict]('etp/creation', 'v2Private', 'POST', {'cost': 5})
    v2private_post_etp_redemption = v2PrivatePostEtpRedemption = Entry[_Dict]('etp/redemption', 'v2Private', 'POST', {'cost': 5})
    v2private_post_etp_transactid_cancel = v2PrivatePostEtpTransactIdCancel = Entry[_Dict]('etp/{transactId}/cancel', 'v2Private', 'POST', {'cost': 10})
    v2private_post_etp_batch_cancel = v2PrivatePostEtpBatchCancel = Entry[_Dict]('etp/batch-cancel', 'v2Private', 'POST', {'cost': 50})
    public_get_common_symbols = publicGetCommonSymbols = Entry[_Dict]('common/symbols', 'public', 'GET', {'cost': 1})
    public_get_common_currencys = publicGetCommonCurrencys = Entry[_Dict]('common/currencys', 'public', 'GET', {'cost': 1})
    public_get_common_timestamp = publicGetCommonTimestamp = Entry[_Dict]('common/timestamp', 'public', 'GET', {'cost': 1})
    public_get_common_exchange = publicGetCommonExchange = Entry[_Dict]('common/exchange', 'public', 'GET', {'cost': 1})
    public_get_settings_currencys = publicGetSettingsCurrencys = Entry[_Dict]('settings/currencys', 'public', 'GET', {'cost': 1})
    private_get_account_accounts = privateGetAccountAccounts = Entry[_Dict]('account/accounts', 'private', 'GET', {'cost': 0.2})
    private_get_account_accounts_id_balance = privateGetAccountAccountsIdBalance = Entry[_Dict]('account/accounts/{id}/balance', 'private', 'GET', {'cost': 0.2})
    private_get_account_accounts_sub_uid = privateGetAccountAccountsSubUid = Entry[_Dict]('account/accounts/{sub-uid}', 'private', 'GET', {'cost': 1})
    private_get_account_history = privateGetAccountHistory = Entry[_Dict]('account/history', 'private', 'GET', {'cost': 4})
    private_get_cross_margin_loan_info = privateGetCrossMarginLoanInfo = Entry[_Dict]('cross-margin/loan-info', 'private', 'GET', {'cost': 1})
    private_get_margin_loan_info = privateGetMarginLoanInfo = Entry[_Dict]('margin/loan-info', 'private', 'GET', {'cost': 1})
    private_get_fee_fee_rate_get = privateGetFeeFeeRateGet = Entry[_Dict]('fee/fee-rate/get', 'private', 'GET', {'cost': 1})
    private_get_order_openorders = privateGetOrderOpenOrders = Entry[_Dict]('order/openOrders', 'private', 'GET', {'cost': 0.4})
    private_get_order_orders = privateGetOrderOrders = Entry[_Dict]('order/orders', 'private', 'GET', {'cost': 0.4})
    private_get_order_orders_id = privateGetOrderOrdersId = Entry[_Dict]('order/orders/{id}', 'private', 'GET', {'cost': 0.4})
    private_get_order_orders_id_matchresults = privateGetOrderOrdersIdMatchresults = Entry[_Dict]('order/orders/{id}/matchresults', 'private', 'GET', {'cost': 0.4})
    private_get_order_orders_getclientorder = privateGetOrderOrdersGetClientOrder = Entry[_Dict]('order/orders/getClientOrder', 'private', 'GET', {'cost': 0.4})
    private_get_order_history = privateGetOrderHistory = Entry[_Dict]('order/history', 'private', 'GET', {'cost': 1})
    private_get_order_matchresults = privateGetOrderMatchresults = Entry[_Dict]('order/matchresults', 'private', 'GET', {'cost': 1})
    private_get_query_deposit_withdraw = privateGetQueryDepositWithdraw = Entry[_Dict]('query/deposit-withdraw', 'private', 'GET', {'cost': 1})
    private_get_margin_loan_orders = privateGetMarginLoanOrders = Entry[_Dict]('margin/loan-orders', 'private', 'GET', {'cost': 0.2})
    private_get_margin_accounts_balance = privateGetMarginAccountsBalance = Entry[_Dict]('margin/accounts/balance', 'private', 'GET', {'cost': 0.2})
    private_get_cross_margin_loan_orders = privateGetCrossMarginLoanOrders = Entry[_Dict]('cross-margin/loan-orders', 'private', 'GET', {'cost': 1})
    private_get_cross_margin_accounts_balance = privateGetCrossMarginAccountsBalance = Entry[_Dict]('cross-margin/accounts/balance', 'private', 'GET', {'cost': 1})
    private_get_points_actions = privateGetPointsActions = Entry[_Dict]('points/actions', 'private', 'GET', {'cost': 1})
    private_get_points_orders = privateGetPointsOrders = Entry[_Dict]('points/orders', 'private', 'GET', {'cost': 1})
    private_get_subuser_aggregate_balance = privateGetSubuserAggregateBalance = Entry[_Dict]('subuser/aggregate-balance', 'private', 'GET', {'cost': 10})
    private_get_stable_coin_exchange_rate = privateGetStableCoinExchangeRate = Entry[_Dict]('stable-coin/exchange_rate', 'private', 'GET', {'cost': 1})
    private_get_stable_coin_quote = privateGetStableCoinQuote = Entry[_Dict]('stable-coin/quote', 'private', 'GET', {'cost': 1})
    private_post_account_transfer = privatePostAccountTransfer = Entry[_Dict]('account/transfer', 'private', 'POST', {'cost': 1})
    private_post_futures_transfer = privatePostFuturesTransfer = Entry[_Dict]('futures/transfer', 'private', 'POST', {'cost': 1})
    private_post_order_batch_orders = privatePostOrderBatchOrders = Entry[_Dict]('order/batch-orders', 'private', 'POST', {'cost': 0.4})
    private_post_order_orders_place = privatePostOrderOrdersPlace = Entry[_Dict]('order/orders/place', 'private', 'POST', {'cost': 0.2})
    private_post_order_orders_submitcancelclientorder = privatePostOrderOrdersSubmitCancelClientOrder = Entry[_Dict]('order/orders/submitCancelClientOrder', 'private', 'POST', {'cost': 0.2})
    private_post_order_orders_batchcancelopenorders = privatePostOrderOrdersBatchCancelOpenOrders = Entry[_Dict]('order/orders/batchCancelOpenOrders', 'private', 'POST', {'cost': 0.4})
    private_post_order_orders_id_submitcancel = privatePostOrderOrdersIdSubmitcancel = Entry[_Dict]('order/orders/{id}/submitcancel', 'private', 'POST', {'cost': 0.2})
    private_post_order_orders_batchcancel = privatePostOrderOrdersBatchcancel = Entry[_Dict]('order/orders/batchcancel', 'private', 'POST', {'cost': 0.4})
    private_post_dw_withdraw_api_create = privatePostDwWithdrawApiCreate = Entry[_Dict]('dw/withdraw/api/create', 'private', 'POST', {'cost': 1})
    private_post_dw_withdraw_virtual_id_cancel = privatePostDwWithdrawVirtualIdCancel = Entry[_Dict]('dw/withdraw-virtual/{id}/cancel', 'private', 'POST', {'cost': 1})
    private_post_dw_transfer_in_margin = privatePostDwTransferInMargin = Entry[_Dict]('dw/transfer-in/margin', 'private', 'POST', {'cost': 10})
    private_post_dw_transfer_out_margin = privatePostDwTransferOutMargin = Entry[_Dict]('dw/transfer-out/margin', 'private', 'POST', {'cost': 10})
    private_post_margin_orders = privatePostMarginOrders = Entry[_Dict]('margin/orders', 'private', 'POST', {'cost': 10})
    private_post_margin_orders_id_repay = privatePostMarginOrdersIdRepay = Entry[_Dict]('margin/orders/{id}/repay', 'private', 'POST', {'cost': 10})
    private_post_cross_margin_transfer_in = privatePostCrossMarginTransferIn = Entry[_Dict]('cross-margin/transfer-in', 'private', 'POST', {'cost': 1})
    private_post_cross_margin_transfer_out = privatePostCrossMarginTransferOut = Entry[_Dict]('cross-margin/transfer-out', 'private', 'POST', {'cost': 1})
    private_post_cross_margin_orders = privatePostCrossMarginOrders = Entry[_Dict]('cross-margin/orders', 'private', 'POST', {'cost': 1})
    private_post_cross_margin_orders_id_repay = privatePostCrossMarginOrdersIdRepay = Entry[_Dict]('cross-margin/orders/{id}/repay', 'private', 'POST', {'cost': 1})
    private_post_stable_coin_exchange = privatePostStableCoinExchange = Entry[_Dict]('stable-coin/exchange', 'private', 'POST', {'cost': 1})
    private_post_subuser_transfer = privatePostSubuserTransfer = Entry[_Dict]('subuser/transfer', 'private', 'POST', {'cost': 10})
    status_public_spot_get_api_v2_summary_json = statusPublicSpotGetApiV2SummaryJson = Entry[_Dict]('api/v2/summary.json', ['status', 'public', 'spot'], 'GET', {'cost': 1})
    status_public_future_inverse_get_api_v2_summary_json = statusPublicFutureInverseGetApiV2SummaryJson = Entry[_Dict]('api/v2/summary.json', ['status', 'public', 'future', 'inverse'], 'GET', {'cost': 1})
    status_public_future_linear_get_api_v2_summary_json = statusPublicFutureLinearGetApiV2SummaryJson = Entry[_Dict]('api/v2/summary.json', ['status', 'public', 'future', 'linear'], 'GET', {'cost': 1})
    status_public_swap_inverse_get_api_v2_summary_json = statusPublicSwapInverseGetApiV2SummaryJson = Entry[_Dict]('api/v2/summary.json', ['status', 'public', 'swap', 'inverse'], 'GET', {'cost': 1})
    status_public_swap_linear_get_api_v2_summary_json = statusPublicSwapLinearGetApiV2SummaryJson = Entry[_Dict]('api/v2/summary.json', ['status', 'public', 'swap', 'linear'], 'GET', {'cost': 1})
    spot_public_get_v2_market_status = spotPublicGetV2MarketStatus = Entry[_Dict]('v2/market-status', ['spot', 'public'], 'GET', {'cost': 1})
    spot_public_get_v1_common_symbols = spotPublicGetV1CommonSymbols = Entry[_Dict]('v1/common/symbols', ['spot', 'public'], 'GET', {'cost': 1})
    spot_public_get_v1_common_currencys = spotPublicGetV1CommonCurrencys = Entry[_Dict]('v1/common/currencys', ['spot', 'public'], 'GET', {'cost': 1})
    spot_public_get_v2_settings_common_currencies = spotPublicGetV2SettingsCommonCurrencies = Entry[_Dict]('v2/settings/common/currencies', ['spot', 'public'], 'GET', {'cost': 1})
    spot_public_get_v2_reference_currencies = spotPublicGetV2ReferenceCurrencies = Entry[_Dict]('v2/reference/currencies', ['spot', 'public'], 'GET', {'cost': 1})
    spot_public_get_v1_common_timestamp = spotPublicGetV1CommonTimestamp = Entry[_Dict]('v1/common/timestamp', ['spot', 'public'], 'GET', {'cost': 1})
    spot_public_get_v1_common_exchange = spotPublicGetV1CommonExchange = Entry[_Dict]('v1/common/exchange', ['spot', 'public'], 'GET', {'cost': 1})
    spot_public_get_v1_settings_common_chains = spotPublicGetV1SettingsCommonChains = Entry[_Dict]('v1/settings/common/chains', ['spot', 'public'], 'GET', {'cost': 1})
    spot_public_get_v1_settings_common_currencys = spotPublicGetV1SettingsCommonCurrencys = Entry[_Dict]('v1/settings/common/currencys', ['spot', 'public'], 'GET', {'cost': 1})
    spot_public_get_v1_settings_common_symbols = spotPublicGetV1SettingsCommonSymbols = Entry[_Dict]('v1/settings/common/symbols', ['spot', 'public'], 'GET', {'cost': 1})
    spot_public_get_v2_settings_common_symbols = spotPublicGetV2SettingsCommonSymbols = Entry[_Dict]('v2/settings/common/symbols', ['spot', 'public'], 'GET', {'cost': 1})
    spot_public_get_v1_settings_common_market_symbols = spotPublicGetV1SettingsCommonMarketSymbols = Entry[_Dict]('v1/settings/common/market-symbols', ['spot', 'public'], 'GET', {'cost': 1})
    spot_public_get_market_history_candles = spotPublicGetMarketHistoryCandles = Entry[_Dict]('market/history/candles', ['spot', 'public'], 'GET', {'cost': 1})
    spot_public_get_market_history_kline = spotPublicGetMarketHistoryKline = Entry[_Dict]('market/history/kline', ['spot', 'public'], 'GET', {'cost': 1})
    spot_public_get_market_detail_merged = spotPublicGetMarketDetailMerged = Entry[_Dict]('market/detail/merged', ['spot', 'public'], 'GET', {'cost': 1})
    spot_public_get_market_tickers = spotPublicGetMarketTickers = Entry[_Dict]('market/tickers', ['spot', 'public'], 'GET', {'cost': 1})
    spot_public_get_market_detail = spotPublicGetMarketDetail = Entry[_Dict]('market/detail', ['spot', 'public'], 'GET', {'cost': 1})
    spot_public_get_market_depth = spotPublicGetMarketDepth = Entry[_Dict]('market/depth', ['spot', 'public'], 'GET', {'cost': 1})
    spot_public_get_market_trade = spotPublicGetMarketTrade = Entry[_Dict]('market/trade', ['spot', 'public'], 'GET', {'cost': 1})
    spot_public_get_market_history_trade = spotPublicGetMarketHistoryTrade = Entry[_Dict]('market/history/trade', ['spot', 'public'], 'GET', {'cost': 1})
    spot_public_get_market_etp = spotPublicGetMarketEtp = Entry[_Dict]('market/etp', ['spot', 'public'], 'GET', {'cost': 1})
    spot_public_get_v2_etp_reference = spotPublicGetV2EtpReference = Entry[_Dict]('v2/etp/reference', ['spot', 'public'], 'GET', {'cost': 1})
    spot_public_get_v2_etp_rebalance = spotPublicGetV2EtpRebalance = Entry[_Dict]('v2/etp/rebalance', ['spot', 'public'], 'GET', {'cost': 1})
    spot_private_get_v1_account_accounts = spotPrivateGetV1AccountAccounts = Entry[_Dict]('v1/account/accounts', ['spot', 'private'], 'GET', {'cost': 0.2})
    spot_private_get_v1_account_accounts_account_id_balance = spotPrivateGetV1AccountAccountsAccountIdBalance = Entry[_Dict]('v1/account/accounts/{account-id}/balance', ['spot', 'private'], 'GET', {'cost': 0.2})
    spot_private_get_v2_account_valuation = spotPrivateGetV2AccountValuation = Entry[_Dict]('v2/account/valuation', ['spot', 'private'], 'GET', {'cost': 1})
    spot_private_get_v2_account_asset_valuation = spotPrivateGetV2AccountAssetValuation = Entry[_Dict]('v2/account/asset-valuation', ['spot', 'private'], 'GET', {'cost': 0.2})
    spot_private_get_v1_account_history = spotPrivateGetV1AccountHistory = Entry[_Dict]('v1/account/history', ['spot', 'private'], 'GET', {'cost': 4})
    spot_private_get_v2_account_ledger = spotPrivateGetV2AccountLedger = Entry[_Dict]('v2/account/ledger', ['spot', 'private'], 'GET', {'cost': 1})
    spot_private_get_v2_point_account = spotPrivateGetV2PointAccount = Entry[_Dict]('v2/point/account', ['spot', 'private'], 'GET', {'cost': 5})
    spot_private_get_v2_account_deposit_address = spotPrivateGetV2AccountDepositAddress = Entry[_Dict]('v2/account/deposit/address', ['spot', 'private'], 'GET', {'cost': 1})
    spot_private_get_v2_account_withdraw_quota = spotPrivateGetV2AccountWithdrawQuota = Entry[_Dict]('v2/account/withdraw/quota', ['spot', 'private'], 'GET', {'cost': 1})
    spot_private_get_v2_account_withdraw_address = spotPrivateGetV2AccountWithdrawAddress = Entry[_Dict]('v2/account/withdraw/address', ['spot', 'private'], 'GET', {'cost': 1})
    spot_private_get_v2_reference_currencies = spotPrivateGetV2ReferenceCurrencies = Entry[_Dict]('v2/reference/currencies', ['spot', 'private'], 'GET', {'cost': 1})
    spot_private_get_v1_query_deposit_withdraw = spotPrivateGetV1QueryDepositWithdraw = Entry[_Dict]('v1/query/deposit-withdraw', ['spot', 'private'], 'GET', {'cost': 1})
    spot_private_get_v1_query_withdraw_client_order_id = spotPrivateGetV1QueryWithdrawClientOrderId = Entry[_Dict]('v1/query/withdraw/client-order-id', ['spot', 'private'], 'GET', {'cost': 1})
    spot_private_get_v2_user_api_key = spotPrivateGetV2UserApiKey = Entry[_Dict]('v2/user/api-key', ['spot', 'private'], 'GET', {'cost': 1})
    spot_private_get_v2_user_uid = spotPrivateGetV2UserUid = Entry[_Dict]('v2/user/uid', ['spot', 'private'], 'GET', {'cost': 1})
    spot_private_get_v2_sub_user_user_list = spotPrivateGetV2SubUserUserList = Entry[_Dict]('v2/sub-user/user-list', ['spot', 'private'], 'GET', {'cost': 1})
    spot_private_get_v2_sub_user_user_state = spotPrivateGetV2SubUserUserState = Entry[_Dict]('v2/sub-user/user-state', ['spot', 'private'], 'GET', {'cost': 1})
    spot_private_get_v2_sub_user_account_list = spotPrivateGetV2SubUserAccountList = Entry[_Dict]('v2/sub-user/account-list', ['spot', 'private'], 'GET', {'cost': 1})
    spot_private_get_v2_sub_user_deposit_address = spotPrivateGetV2SubUserDepositAddress = Entry[_Dict]('v2/sub-user/deposit-address', ['spot', 'private'], 'GET', {'cost': 1})
    spot_private_get_v2_sub_user_query_deposit = spotPrivateGetV2SubUserQueryDeposit = Entry[_Dict]('v2/sub-user/query-deposit', ['spot', 'private'], 'GET', {'cost': 1})
    spot_private_get_v1_subuser_aggregate_balance = spotPrivateGetV1SubuserAggregateBalance = Entry[_Dict]('v1/subuser/aggregate-balance', ['spot', 'private'], 'GET', {'cost': 10})
    spot_private_get_v1_account_accounts_sub_uid = spotPrivateGetV1AccountAccountsSubUid = Entry[_Dict]('v1/account/accounts/{sub-uid}', ['spot', 'private'], 'GET', {'cost': 1})
    spot_private_get_v1_order_openorders = spotPrivateGetV1OrderOpenOrders = Entry[_Dict]('v1/order/openOrders', ['spot', 'private'], 'GET', {'cost': 0.4})
    spot_private_get_v1_order_orders_order_id = spotPrivateGetV1OrderOrdersOrderId = Entry[_Dict]('v1/order/orders/{order-id}', ['spot', 'private'], 'GET', {'cost': 0.4})
    spot_private_get_v1_order_orders_getclientorder = spotPrivateGetV1OrderOrdersGetClientOrder = Entry[_Dict]('v1/order/orders/getClientOrder', ['spot', 'private'], 'GET', {'cost': 0.4})
    spot_private_get_v1_order_orders_order_id_matchresult = spotPrivateGetV1OrderOrdersOrderIdMatchresult = Entry[_Dict]('v1/order/orders/{order-id}/matchresult', ['spot', 'private'], 'GET', {'cost': 0.4})
    spot_private_get_v1_order_orders_order_id_matchresults = spotPrivateGetV1OrderOrdersOrderIdMatchresults = Entry[_Dict]('v1/order/orders/{order-id}/matchresults', ['spot', 'private'], 'GET', {'cost': 0.4})
    spot_private_get_v1_order_orders = spotPrivateGetV1OrderOrders = Entry[_Dict]('v1/order/orders', ['spot', 'private'], 'GET', {'cost': 0.4})
    spot_private_get_v1_order_history = spotPrivateGetV1OrderHistory = Entry[_Dict]('v1/order/history', ['spot', 'private'], 'GET', {'cost': 1})
    spot_private_get_v1_order_matchresults = spotPrivateGetV1OrderMatchresults = Entry[_Dict]('v1/order/matchresults', ['spot', 'private'], 'GET', {'cost': 1})
    spot_private_get_v2_reference_transact_fee_rate = spotPrivateGetV2ReferenceTransactFeeRate = Entry[_Dict]('v2/reference/transact-fee-rate', ['spot', 'private'], 'GET', {'cost': 1})
    spot_private_get_v2_algo_orders_opening = spotPrivateGetV2AlgoOrdersOpening = Entry[_Dict]('v2/algo-orders/opening', ['spot', 'private'], 'GET', {'cost': 1})
    spot_private_get_v2_algo_orders_history = spotPrivateGetV2AlgoOrdersHistory = Entry[_Dict]('v2/algo-orders/history', ['spot', 'private'], 'GET', {'cost': 1})
    spot_private_get_v2_algo_orders_specific = spotPrivateGetV2AlgoOrdersSpecific = Entry[_Dict]('v2/algo-orders/specific', ['spot', 'private'], 'GET', {'cost': 1})
    spot_private_get_v1_margin_loan_info = spotPrivateGetV1MarginLoanInfo = Entry[_Dict]('v1/margin/loan-info', ['spot', 'private'], 'GET', {'cost': 1})
    spot_private_get_v1_margin_loan_orders = spotPrivateGetV1MarginLoanOrders = Entry[_Dict]('v1/margin/loan-orders', ['spot', 'private'], 'GET', {'cost': 0.2})
    spot_private_get_v1_margin_accounts_balance = spotPrivateGetV1MarginAccountsBalance = Entry[_Dict]('v1/margin/accounts/balance', ['spot', 'private'], 'GET', {'cost': 0.2})
    spot_private_get_v1_cross_margin_loan_info = spotPrivateGetV1CrossMarginLoanInfo = Entry[_Dict]('v1/cross-margin/loan-info', ['spot', 'private'], 'GET', {'cost': 1})
    spot_private_get_v1_cross_margin_loan_orders = spotPrivateGetV1CrossMarginLoanOrders = Entry[_Dict]('v1/cross-margin/loan-orders', ['spot', 'private'], 'GET', {'cost': 1})
    spot_private_get_v1_cross_margin_accounts_balance = spotPrivateGetV1CrossMarginAccountsBalance = Entry[_Dict]('v1/cross-margin/accounts/balance', ['spot', 'private'], 'GET', {'cost': 1})
    spot_private_get_v2_account_repayment = spotPrivateGetV2AccountRepayment = Entry[_Dict]('v2/account/repayment', ['spot', 'private'], 'GET', {'cost': 5})
    spot_private_get_v5_account_universal_transfer_records = spotPrivateGetV5AccountUniversalTransferRecords = Entry[_Dict]('v5/account/universal_transfer_records', ['spot', 'private'], 'GET', {'cost': 4})
    spot_private_get_v1_stable_coin_quote = spotPrivateGetV1StableCoinQuote = Entry[_Dict]('v1/stable-coin/quote', ['spot', 'private'], 'GET', {'cost': 1})
    spot_private_get_v1_stable_coin_exchange_rate = spotPrivateGetV1StableCoinExchangeRate = Entry[_Dict]('v1/stable_coin/exchange_rate', ['spot', 'private'], 'GET', {'cost': 1})
    spot_private_get_v2_etp_transactions = spotPrivateGetV2EtpTransactions = Entry[_Dict]('v2/etp/transactions', ['spot', 'private'], 'GET', {'cost': 5})
    spot_private_get_v2_etp_transaction = spotPrivateGetV2EtpTransaction = Entry[_Dict]('v2/etp/transaction', ['spot', 'private'], 'GET', {'cost': 5})
    spot_private_get_v2_etp_limit = spotPrivateGetV2EtpLimit = Entry[_Dict]('v2/etp/limit', ['spot', 'private'], 'GET', {'cost': 1})
    spot_private_post_v1_account_transfer = spotPrivatePostV1AccountTransfer = Entry[_Dict]('v1/account/transfer', ['spot', 'private'], 'POST', {'cost': 1})
    spot_private_post_v1_futures_transfer = spotPrivatePostV1FuturesTransfer = Entry[_Dict]('v1/futures/transfer', ['spot', 'private'], 'POST', {'cost': 1})
    spot_private_post_v2_point_transfer = spotPrivatePostV2PointTransfer = Entry[_Dict]('v2/point/transfer', ['spot', 'private'], 'POST', {'cost': 5})
    spot_private_post_v2_account_transfer = spotPrivatePostV2AccountTransfer = Entry[_Dict]('v2/account/transfer', ['spot', 'private'], 'POST', {'cost': 1})
    spot_private_post_v1_dw_withdraw_api_create = spotPrivatePostV1DwWithdrawApiCreate = Entry[_Dict]('v1/dw/withdraw/api/create', ['spot', 'private'], 'POST', {'cost': 1})
    spot_private_post_v1_dw_withdraw_virtual_withdraw_id_cancel = spotPrivatePostV1DwWithdrawVirtualWithdrawIdCancel = Entry[_Dict]('v1/dw/withdraw-virtual/{withdraw-id}/cancel', ['spot', 'private'], 'POST', {'cost': 1})
    spot_private_post_v2_sub_user_deduct_mode = spotPrivatePostV2SubUserDeductMode = Entry[_Dict]('v2/sub-user/deduct-mode', ['spot', 'private'], 'POST', {'cost': 1})
    spot_private_post_v2_sub_user_creation = spotPrivatePostV2SubUserCreation = Entry[_Dict]('v2/sub-user/creation', ['spot', 'private'], 'POST', {'cost': 1})
    spot_private_post_v2_sub_user_management = spotPrivatePostV2SubUserManagement = Entry[_Dict]('v2/sub-user/management', ['spot', 'private'], 'POST', {'cost': 1})
    spot_private_post_v2_sub_user_tradable_market = spotPrivatePostV2SubUserTradableMarket = Entry[_Dict]('v2/sub-user/tradable-market', ['spot', 'private'], 'POST', {'cost': 1})
    spot_private_post_v2_sub_user_transferability = spotPrivatePostV2SubUserTransferability = Entry[_Dict]('v2/sub-user/transferability', ['spot', 'private'], 'POST', {'cost': 1})
    spot_private_post_v2_sub_user_api_key_generation = spotPrivatePostV2SubUserApiKeyGeneration = Entry[_Dict]('v2/sub-user/api-key-generation', ['spot', 'private'], 'POST', {'cost': 1})
    spot_private_post_v2_sub_user_api_key_modification = spotPrivatePostV2SubUserApiKeyModification = Entry[_Dict]('v2/sub-user/api-key-modification', ['spot', 'private'], 'POST', {'cost': 1})
    spot_private_post_v2_sub_user_api_key_deletion = spotPrivatePostV2SubUserApiKeyDeletion = Entry[_Dict]('v2/sub-user/api-key-deletion', ['spot', 'private'], 'POST', {'cost': 1})
    spot_private_post_v1_subuser_transfer = spotPrivatePostV1SubuserTransfer = Entry[_Dict]('v1/subuser/transfer', ['spot', 'private'], 'POST', {'cost': 10})
    spot_private_post_v1_trust_user_active_credit = spotPrivatePostV1TrustUserActiveCredit = Entry[_Dict]('v1/trust/user/active/credit', ['spot', 'private'], 'POST', {'cost': 10})
    spot_private_post_v1_order_orders_place = spotPrivatePostV1OrderOrdersPlace = Entry[_Dict]('v1/order/orders/place', ['spot', 'private'], 'POST', {'cost': 0.2})
    spot_private_post_v1_order_batch_orders = spotPrivatePostV1OrderBatchOrders = Entry[_Dict]('v1/order/batch-orders', ['spot', 'private'], 'POST', {'cost': 0.4})
    spot_private_post_v1_order_auto_place = spotPrivatePostV1OrderAutoPlace = Entry[_Dict]('v1/order/auto/place', ['spot', 'private'], 'POST', {'cost': 0.2})
    spot_private_post_v1_order_orders_order_id_submitcancel = spotPrivatePostV1OrderOrdersOrderIdSubmitcancel = Entry[_Dict]('v1/order/orders/{order-id}/submitcancel', ['spot', 'private'], 'POST', {'cost': 0.2})
    spot_private_post_v1_order_orders_submitcancelclientorder = spotPrivatePostV1OrderOrdersSubmitCancelClientOrder = Entry[_Dict]('v1/order/orders/submitCancelClientOrder', ['spot', 'private'], 'POST', {'cost': 0.2})
    spot_private_post_v1_order_orders_batchcancelopenorders = spotPrivatePostV1OrderOrdersBatchCancelOpenOrders = Entry[_Dict]('v1/order/orders/batchCancelOpenOrders', ['spot', 'private'], 'POST', {'cost': 0.4})
    spot_private_post_v1_order_orders_batchcancel = spotPrivatePostV1OrderOrdersBatchcancel = Entry[_Dict]('v1/order/orders/batchcancel', ['spot', 'private'], 'POST', {'cost': 0.4})
    spot_private_post_v2_algo_orders_cancel_all_after = spotPrivatePostV2AlgoOrdersCancelAllAfter = Entry[_Dict]('v2/algo-orders/cancel-all-after', ['spot', 'private'], 'POST', {'cost': 1})
    spot_private_post_v2_algo_orders = spotPrivatePostV2AlgoOrders = Entry[_Dict]('v2/algo-orders', ['spot', 'private'], 'POST', {'cost': 1})
    spot_private_post_v2_algo_orders_cancellation = spotPrivatePostV2AlgoOrdersCancellation = Entry[_Dict]('v2/algo-orders/cancellation', ['spot', 'private'], 'POST', {'cost': 1})
    spot_private_post_v2_account_repayment = spotPrivatePostV2AccountRepayment = Entry[_Dict]('v2/account/repayment', ['spot', 'private'], 'POST', {'cost': 5})
    spot_private_post_v1_dw_transfer_in_margin = spotPrivatePostV1DwTransferInMargin = Entry[_Dict]('v1/dw/transfer-in/margin', ['spot', 'private'], 'POST', {'cost': 10})
    spot_private_post_v1_dw_transfer_out_margin = spotPrivatePostV1DwTransferOutMargin = Entry[_Dict]('v1/dw/transfer-out/margin', ['spot', 'private'], 'POST', {'cost': 10})
    spot_private_post_v1_margin_orders = spotPrivatePostV1MarginOrders = Entry[_Dict]('v1/margin/orders', ['spot', 'private'], 'POST', {'cost': 10})
    spot_private_post_v1_margin_orders_order_id_repay = spotPrivatePostV1MarginOrdersOrderIdRepay = Entry[_Dict]('v1/margin/orders/{order-id}/repay', ['spot', 'private'], 'POST', {'cost': 10})
    spot_private_post_v1_cross_margin_transfer_in = spotPrivatePostV1CrossMarginTransferIn = Entry[_Dict]('v1/cross-margin/transfer-in', ['spot', 'private'], 'POST', {'cost': 1})
    spot_private_post_v1_cross_margin_transfer_out = spotPrivatePostV1CrossMarginTransferOut = Entry[_Dict]('v1/cross-margin/transfer-out', ['spot', 'private'], 'POST', {'cost': 1})
    spot_private_post_v1_cross_margin_orders = spotPrivatePostV1CrossMarginOrders = Entry[_Dict]('v1/cross-margin/orders', ['spot', 'private'], 'POST', {'cost': 1})
    spot_private_post_v1_cross_margin_orders_order_id_repay = spotPrivatePostV1CrossMarginOrdersOrderIdRepay = Entry[_Dict]('v1/cross-margin/orders/{order-id}/repay', ['spot', 'private'], 'POST', {'cost': 1})
    spot_private_post_v1_stable_coin_exchange = spotPrivatePostV1StableCoinExchange = Entry[_Dict]('v1/stable-coin/exchange', ['spot', 'private'], 'POST', {'cost': 1})
    spot_private_post_v2_etp_creation = spotPrivatePostV2EtpCreation = Entry[_Dict]('v2/etp/creation', ['spot', 'private'], 'POST', {'cost': 5})
    spot_private_post_v2_etp_redemption = spotPrivatePostV2EtpRedemption = Entry[_Dict]('v2/etp/redemption', ['spot', 'private'], 'POST', {'cost': 5})
    spot_private_post_v2_etp_transactid_cancel = spotPrivatePostV2EtpTransactIdCancel = Entry[_Dict]('v2/etp/{transactId}/cancel', ['spot', 'private'], 'POST', {'cost': 10})
    spot_private_post_v2_etp_batch_cancel = spotPrivatePostV2EtpBatchCancel = Entry[_Dict]('v2/etp/batch-cancel', ['spot', 'private'], 'POST', {'cost': 50})
    contract_public_get_api_v1_timestamp = contractPublicGetApiV1Timestamp = Entry[_Dict]('api/v1/timestamp', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_heartbeat = contractPublicGetHeartbeat = Entry[_Dict]('heartbeat/', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_api_v1_contract_contract_info = contractPublicGetApiV1ContractContractInfo = Entry[_Dict]('api/v1/contract_contract_info', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_api_v1_contract_index = contractPublicGetApiV1ContractIndex = Entry[_Dict]('api/v1/contract_index', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_api_v1_contract_query_elements = contractPublicGetApiV1ContractQueryElements = Entry[_Dict]('api/v1/contract_query_elements', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_api_v1_contract_price_limit = contractPublicGetApiV1ContractPriceLimit = Entry[_Dict]('api/v1/contract_price_limit', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_api_v1_contract_open_interest = contractPublicGetApiV1ContractOpenInterest = Entry[_Dict]('api/v1/contract_open_interest', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_api_v1_contract_delivery_price = contractPublicGetApiV1ContractDeliveryPrice = Entry[_Dict]('api/v1/contract_delivery_price', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_market_depth = contractPublicGetMarketDepth = Entry[_Dict]('market/depth', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_market_bbo = contractPublicGetMarketBbo = Entry[_Dict]('market/bbo', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_market_history_kline = contractPublicGetMarketHistoryKline = Entry[_Dict]('market/history/kline', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_index_market_history_mark_price_kline = contractPublicGetIndexMarketHistoryMarkPriceKline = Entry[_Dict]('index/market/history/mark_price_kline', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_market_detail_merged = contractPublicGetMarketDetailMerged = Entry[_Dict]('market/detail/merged', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_market_detail_batch_merged = contractPublicGetMarketDetailBatchMerged = Entry[_Dict]('market/detail/batch_merged', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_v2_market_detail_batch_merged = contractPublicGetV2MarketDetailBatchMerged = Entry[_Dict]('v2/market/detail/batch_merged', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_market_trade = contractPublicGetMarketTrade = Entry[_Dict]('market/trade', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_market_history_trade = contractPublicGetMarketHistoryTrade = Entry[_Dict]('market/history/trade', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_api_v1_contract_risk_info = contractPublicGetApiV1ContractRiskInfo = Entry[_Dict]('api/v1/contract_risk_info', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_api_v1_contract_insurance_fund = contractPublicGetApiV1ContractInsuranceFund = Entry[_Dict]('api/v1/contract_insurance_fund', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_api_v1_contract_adjustfactor = contractPublicGetApiV1ContractAdjustfactor = Entry[_Dict]('api/v1/contract_adjustfactor', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_api_v1_contract_his_open_interest = contractPublicGetApiV1ContractHisOpenInterest = Entry[_Dict]('api/v1/contract_his_open_interest', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_api_v1_contract_ladder_margin = contractPublicGetApiV1ContractLadderMargin = Entry[_Dict]('api/v1/contract_ladder_margin', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_api_v1_contract_api_state = contractPublicGetApiV1ContractApiState = Entry[_Dict]('api/v1/contract_api_state', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_api_v1_contract_elite_account_ratio = contractPublicGetApiV1ContractEliteAccountRatio = Entry[_Dict]('api/v1/contract_elite_account_ratio', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_api_v1_contract_elite_position_ratio = contractPublicGetApiV1ContractElitePositionRatio = Entry[_Dict]('api/v1/contract_elite_position_ratio', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_api_v1_contract_liquidation_orders = contractPublicGetApiV1ContractLiquidationOrders = Entry[_Dict]('api/v1/contract_liquidation_orders', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_api_v1_contract_settlement_records = contractPublicGetApiV1ContractSettlementRecords = Entry[_Dict]('api/v1/contract_settlement_records', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_index_market_history_index = contractPublicGetIndexMarketHistoryIndex = Entry[_Dict]('index/market/history/index', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_index_market_history_basis = contractPublicGetIndexMarketHistoryBasis = Entry[_Dict]('index/market/history/basis', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_api_v1_contract_estimated_settlement_price = contractPublicGetApiV1ContractEstimatedSettlementPrice = Entry[_Dict]('api/v1/contract_estimated_settlement_price', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_api_v3_contract_liquidation_orders = contractPublicGetApiV3ContractLiquidationOrders = Entry[_Dict]('api/v3/contract_liquidation_orders', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_swap_api_v1_swap_contract_info = contractPublicGetSwapApiV1SwapContractInfo = Entry[_Dict]('swap-api/v1/swap_contract_info', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_swap_api_v1_swap_index = contractPublicGetSwapApiV1SwapIndex = Entry[_Dict]('swap-api/v1/swap_index', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_swap_api_v1_swap_query_elements = contractPublicGetSwapApiV1SwapQueryElements = Entry[_Dict]('swap-api/v1/swap_query_elements', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_swap_api_v1_swap_price_limit = contractPublicGetSwapApiV1SwapPriceLimit = Entry[_Dict]('swap-api/v1/swap_price_limit', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_swap_api_v1_swap_open_interest = contractPublicGetSwapApiV1SwapOpenInterest = Entry[_Dict]('swap-api/v1/swap_open_interest', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_swap_ex_market_depth = contractPublicGetSwapExMarketDepth = Entry[_Dict]('swap-ex/market/depth', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_swap_ex_market_bbo = contractPublicGetSwapExMarketBbo = Entry[_Dict]('swap-ex/market/bbo', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_swap_ex_market_history_kline = contractPublicGetSwapExMarketHistoryKline = Entry[_Dict]('swap-ex/market/history/kline', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_index_market_history_swap_mark_price_kline = contractPublicGetIndexMarketHistorySwapMarkPriceKline = Entry[_Dict]('index/market/history/swap_mark_price_kline', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_swap_ex_market_detail_merged = contractPublicGetSwapExMarketDetailMerged = Entry[_Dict]('swap-ex/market/detail/merged', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_v2_swap_ex_market_detail_batch_merged = contractPublicGetV2SwapExMarketDetailBatchMerged = Entry[_Dict]('v2/swap-ex/market/detail/batch_merged', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_index_market_history_swap_premium_index_kline = contractPublicGetIndexMarketHistorySwapPremiumIndexKline = Entry[_Dict]('index/market/history/swap_premium_index_kline', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_swap_ex_market_detail_batch_merged = contractPublicGetSwapExMarketDetailBatchMerged = Entry[_Dict]('swap-ex/market/detail/batch_merged', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_swap_ex_market_trade = contractPublicGetSwapExMarketTrade = Entry[_Dict]('swap-ex/market/trade', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_swap_ex_market_history_trade = contractPublicGetSwapExMarketHistoryTrade = Entry[_Dict]('swap-ex/market/history/trade', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_swap_api_v1_swap_risk_info = contractPublicGetSwapApiV1SwapRiskInfo = Entry[_Dict]('swap-api/v1/swap_risk_info', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_swap_api_v1_swap_insurance_fund = contractPublicGetSwapApiV1SwapInsuranceFund = Entry[_Dict]('swap-api/v1/swap_insurance_fund', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_swap_api_v1_swap_adjustfactor = contractPublicGetSwapApiV1SwapAdjustfactor = Entry[_Dict]('swap-api/v1/swap_adjustfactor', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_swap_api_v1_swap_his_open_interest = contractPublicGetSwapApiV1SwapHisOpenInterest = Entry[_Dict]('swap-api/v1/swap_his_open_interest', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_swap_api_v1_swap_ladder_margin = contractPublicGetSwapApiV1SwapLadderMargin = Entry[_Dict]('swap-api/v1/swap_ladder_margin', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_swap_api_v1_swap_api_state = contractPublicGetSwapApiV1SwapApiState = Entry[_Dict]('swap-api/v1/swap_api_state', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_swap_api_v1_swap_elite_account_ratio = contractPublicGetSwapApiV1SwapEliteAccountRatio = Entry[_Dict]('swap-api/v1/swap_elite_account_ratio', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_swap_api_v1_swap_elite_position_ratio = contractPublicGetSwapApiV1SwapElitePositionRatio = Entry[_Dict]('swap-api/v1/swap_elite_position_ratio', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_swap_api_v1_swap_estimated_settlement_price = contractPublicGetSwapApiV1SwapEstimatedSettlementPrice = Entry[_Dict]('swap-api/v1/swap_estimated_settlement_price', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_swap_api_v1_swap_liquidation_orders = contractPublicGetSwapApiV1SwapLiquidationOrders = Entry[_Dict]('swap-api/v1/swap_liquidation_orders', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_swap_api_v1_swap_settlement_records = contractPublicGetSwapApiV1SwapSettlementRecords = Entry[_Dict]('swap-api/v1/swap_settlement_records', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_swap_api_v1_swap_funding_rate = contractPublicGetSwapApiV1SwapFundingRate = Entry[_Dict]('swap-api/v1/swap_funding_rate', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_swap_api_v1_swap_batch_funding_rate = contractPublicGetSwapApiV1SwapBatchFundingRate = Entry[_Dict]('swap-api/v1/swap_batch_funding_rate', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_swap_api_v1_swap_historical_funding_rate = contractPublicGetSwapApiV1SwapHistoricalFundingRate = Entry[_Dict]('swap-api/v1/swap_historical_funding_rate', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_swap_api_v3_swap_liquidation_orders = contractPublicGetSwapApiV3SwapLiquidationOrders = Entry[_Dict]('swap-api/v3/swap_liquidation_orders', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_index_market_history_swap_estimated_rate_kline = contractPublicGetIndexMarketHistorySwapEstimatedRateKline = Entry[_Dict]('index/market/history/swap_estimated_rate_kline', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_index_market_history_swap_basis = contractPublicGetIndexMarketHistorySwapBasis = Entry[_Dict]('index/market/history/swap_basis', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_linear_swap_api_v1_swap_contract_info = contractPublicGetLinearSwapApiV1SwapContractInfo = Entry[_Dict]('linear-swap-api/v1/swap_contract_info', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_linear_swap_api_v1_swap_index = contractPublicGetLinearSwapApiV1SwapIndex = Entry[_Dict]('linear-swap-api/v1/swap_index', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_linear_swap_api_v1_swap_query_elements = contractPublicGetLinearSwapApiV1SwapQueryElements = Entry[_Dict]('linear-swap-api/v1/swap_query_elements', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_linear_swap_api_v1_swap_price_limit = contractPublicGetLinearSwapApiV1SwapPriceLimit = Entry[_Dict]('linear-swap-api/v1/swap_price_limit', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_linear_swap_ex_market_depth = contractPublicGetLinearSwapExMarketDepth = Entry[_Dict]('linear-swap-ex/market/depth', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_linear_swap_ex_market_bbo = contractPublicGetLinearSwapExMarketBbo = Entry[_Dict]('linear-swap-ex/market/bbo', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_linear_swap_ex_market_history_kline = contractPublicGetLinearSwapExMarketHistoryKline = Entry[_Dict]('linear-swap-ex/market/history/kline', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_index_market_history_linear_swap_mark_price_kline = contractPublicGetIndexMarketHistoryLinearSwapMarkPriceKline = Entry[_Dict]('index/market/history/linear_swap_mark_price_kline', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_linear_swap_ex_market_detail_merged = contractPublicGetLinearSwapExMarketDetailMerged = Entry[_Dict]('linear-swap-ex/market/detail/merged', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_linear_swap_ex_market_detail_batch_merged = contractPublicGetLinearSwapExMarketDetailBatchMerged = Entry[_Dict]('linear-swap-ex/market/detail/batch_merged', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_v2_linear_swap_ex_market_detail_batch_merged = contractPublicGetV2LinearSwapExMarketDetailBatchMerged = Entry[_Dict]('v2/linear-swap-ex/market/detail/batch_merged', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_linear_swap_ex_market_trade = contractPublicGetLinearSwapExMarketTrade = Entry[_Dict]('linear-swap-ex/market/trade', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_linear_swap_ex_market_history_trade = contractPublicGetLinearSwapExMarketHistoryTrade = Entry[_Dict]('linear-swap-ex/market/history/trade', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_swap_api_v1_linear_swap_api_v1_swap_insurance_fund = contractPublicGetSwapApiV1LinearSwapApiV1SwapInsuranceFund = Entry[_Dict]('swap-api/v1/linear-swap-api/v1/swap_insurance_fund', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_linear_swap_api_v1_swap_adjustfactor = contractPublicGetLinearSwapApiV1SwapAdjustfactor = Entry[_Dict]('linear-swap-api/v1/swap_adjustfactor', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_linear_swap_api_v1_swap_cross_adjustfactor = contractPublicGetLinearSwapApiV1SwapCrossAdjustfactor = Entry[_Dict]('linear-swap-api/v1/swap_cross_adjustfactor', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_linear_swap_api_v1_swap_his_open_interest = contractPublicGetLinearSwapApiV1SwapHisOpenInterest = Entry[_Dict]('linear-swap-api/v1/swap_his_open_interest', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_linear_swap_api_v1_swap_ladder_margin = contractPublicGetLinearSwapApiV1SwapLadderMargin = Entry[_Dict]('linear-swap-api/v1/swap_ladder_margin', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_linear_swap_api_v1_swap_cross_ladder_margin = contractPublicGetLinearSwapApiV1SwapCrossLadderMargin = Entry[_Dict]('linear-swap-api/v1/swap_cross_ladder_margin', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_linear_swap_api_v1_swap_api_state = contractPublicGetLinearSwapApiV1SwapApiState = Entry[_Dict]('linear-swap-api/v1/swap_api_state', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_linear_swap_api_v1_swap_elite_account_ratio = contractPublicGetLinearSwapApiV1SwapEliteAccountRatio = Entry[_Dict]('linear-swap-api/v1/swap_elite_account_ratio', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_linear_swap_api_v1_swap_elite_position_ratio = contractPublicGetLinearSwapApiV1SwapElitePositionRatio = Entry[_Dict]('linear-swap-api/v1/swap_elite_position_ratio', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_linear_swap_api_v1_swap_settlement_records = contractPublicGetLinearSwapApiV1SwapSettlementRecords = Entry[_Dict]('linear-swap-api/v1/swap_settlement_records', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_linear_swap_api_v3_swap_liquidation_orders = contractPublicGetLinearSwapApiV3SwapLiquidationOrders = Entry[_Dict]('linear-swap-api/v3/swap_liquidation_orders', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_index_market_history_linear_swap_premium_index_kline = contractPublicGetIndexMarketHistoryLinearSwapPremiumIndexKline = Entry[_Dict]('index/market/history/linear_swap_premium_index_kline', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_index_market_history_linear_swap_estimated_rate_kline = contractPublicGetIndexMarketHistoryLinearSwapEstimatedRateKline = Entry[_Dict]('index/market/history/linear_swap_estimated_rate_kline', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_index_market_history_linear_swap_basis = contractPublicGetIndexMarketHistoryLinearSwapBasis = Entry[_Dict]('index/market/history/linear_swap_basis', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_linear_swap_api_v1_swap_estimated_settlement_price = contractPublicGetLinearSwapApiV1SwapEstimatedSettlementPrice = Entry[_Dict]('linear-swap-api/v1/swap_estimated_settlement_price', ['contract', 'public'], 'GET', {'cost': 1})
    contract_public_get_v5_market_funding_rate = contractPublicGetV5MarketFundingRate = Entry[_Dict]('v5/market/funding_rate', ['contract', 'public'], 'GET', {'cost': 0.125})
    contract_public_get_v5_market_funding_rate_history = contractPublicGetV5MarketFundingRateHistory = Entry[_Dict]('v5/market/funding_rate_history', ['contract', 'public'], 'GET', {'cost': 0.125})
    contract_public_get_v5_market_open_interest = contractPublicGetV5MarketOpenInterest = Entry[_Dict]('v5/market/open_interest', ['contract', 'public'], 'GET', {'cost': 0.125})
    contract_public_get_v5_market_liquidation_orders = contractPublicGetV5MarketLiquidationOrders = Entry[_Dict]('v5/market/liquidation_orders', ['contract', 'public'], 'GET', {'cost': 0.125})
    contract_public_get_v5_market_settlement_history = contractPublicGetV5MarketSettlementHistory = Entry[_Dict]('v5/market/settlement_history', ['contract', 'public'], 'GET', {'cost': 0.125})
    contract_public_get_v5_market_elite_account_ratio = contractPublicGetV5MarketEliteAccountRatio = Entry[_Dict]('v5/market/elite_account_ratio', ['contract', 'public'], 'GET', {'cost': 0.125})
    contract_public_get_v5_market_elite_position_ratio = contractPublicGetV5MarketElitePositionRatio = Entry[_Dict]('v5/market/elite_position_ratio', ['contract', 'public'], 'GET', {'cost': 0.125})
    contract_public_get_v5_market_estimated_settlement_price = contractPublicGetV5MarketEstimatedSettlementPrice = Entry[_Dict]('v5/market/estimated_settlement_price', ['contract', 'public'], 'GET', {'cost': 0.125})
    contract_public_get_v5_market_price_limit = contractPublicGetV5MarketPriceLimit = Entry[_Dict]('v5/market/price_limit', ['contract', 'public'], 'GET', {'cost': 0.125})
    contract_private_get_api_v1_contract_sub_auth_list = contractPrivateGetApiV1ContractSubAuthList = Entry[_Dict]('api/v1/contract_sub_auth_list', ['contract', 'private'], 'GET', {'cost': 1})
    contract_private_get_api_v1_contract_api_trading_status = contractPrivateGetApiV1ContractApiTradingStatus = Entry[_Dict]('api/v1/contract_api_trading_status', ['contract', 'private'], 'GET', {'cost': 1})
    contract_private_get_swap_api_v1_swap_sub_auth_list = contractPrivateGetSwapApiV1SwapSubAuthList = Entry[_Dict]('swap-api/v1/swap_sub_auth_list', ['contract', 'private'], 'GET', {'cost': 1})
    contract_private_get_swap_api_v1_swap_api_trading_status = contractPrivateGetSwapApiV1SwapApiTradingStatus = Entry[_Dict]('swap-api/v1/swap_api_trading_status', ['contract', 'private'], 'GET', {'cost': 1})
    contract_private_get_v5_account_asset_mode = contractPrivateGetV5AccountAssetMode = Entry[_Dict]('v5/account/asset_mode', ['contract', 'private'], 'GET', {'cost': 0.20834})
    contract_private_get_v5_account_balance = contractPrivateGetV5AccountBalance = Entry[_Dict]('v5/account/balance', ['contract', 'private'], 'GET', {'cost': 0.20834})
    contract_private_get_v5_account_bills = contractPrivateGetV5AccountBills = Entry[_Dict]('v5/account/bills', ['contract', 'private'], 'GET', {'cost': 0.20834})
    contract_private_get_v5_account_fee_deduction_currency = contractPrivateGetV5AccountFeeDeductionCurrency = Entry[_Dict]('v5/account/fee_deduction_currency', ['contract', 'private'], 'GET', {'cost': 0.20834})
    contract_private_get_v5_trade_position_opens = contractPrivateGetV5TradePositionOpens = Entry[_Dict]('v5/trade/position/opens', ['contract', 'private'], 'GET', {'cost': 0.41679})
    contract_private_get_v5_trade_order_opens = contractPrivateGetV5TradeOrderOpens = Entry[_Dict]('v5/trade/order/opens', ['contract', 'private'], 'GET', {'cost': 0.41679})
    contract_private_get_v5_trade_order_details = contractPrivateGetV5TradeOrderDetails = Entry[_Dict]('v5/trade/order/details', ['contract', 'private'], 'GET', {'cost': 0.41679})
    contract_private_get_v5_trade_order_history = contractPrivateGetV5TradeOrderHistory = Entry[_Dict]('v5/trade/order/history', ['contract', 'private'], 'GET', {'cost': 0.41679})
    contract_private_get_v5_trade_order = contractPrivateGetV5TradeOrder = Entry[_Dict]('v5/trade/order', ['contract', 'private'], 'GET', {'cost': 0.41679})
    contract_private_get_v5_position_lever = contractPrivateGetV5PositionLever = Entry[_Dict]('v5/position/lever', ['contract', 'private'], 'GET', {'cost': 0.20834})
    contract_private_get_v5_position_mode = contractPrivateGetV5PositionMode = Entry[_Dict]('v5/position/mode', ['contract', 'private'], 'GET', {'cost': 0.20834})
    contract_private_get_v5_position_risk_limit = contractPrivateGetV5PositionRiskLimit = Entry[_Dict]('v5/position/risk/limit', ['contract', 'private'], 'GET', {'cost': 0.20834})
    contract_private_get_v5_position_risk_limit_tier = contractPrivateGetV5PositionRiskLimitTier = Entry[_Dict]('v5/position/risk/limit_tier', ['contract', 'private'], 'GET', {'cost': 0.20834})
    contract_private_get_v5_market_risk_limit = contractPrivateGetV5MarketRiskLimit = Entry[_Dict]('v5/market/risk/limit', ['contract', 'private'], 'GET', {'cost': 0.125})
    contract_private_get_v5_market_assets_deduction_currency = contractPrivateGetV5MarketAssetsDeductionCurrency = Entry[_Dict]('v5/market/assets_deduction_currency', ['contract', 'private'], 'GET', {'cost': 0.125})
    contract_private_get_v5_market_multi_assets_margin = contractPrivateGetV5MarketMultiAssetsMargin = Entry[_Dict]('v5/market/multi_assets_margin', ['contract', 'private'], 'GET', {'cost': 0.125})
    contract_private_get_v5_algo_order_opens = contractPrivateGetV5AlgoOrderOpens = Entry[_Dict]('v5/algo/order/opens', ['contract', 'private'], 'GET', {'cost': 0.41679})
    contract_private_get_v5_algo_order = contractPrivateGetV5AlgoOrder = Entry[_Dict]('v5/algo/order', ['contract', 'private'], 'GET', {'cost': 0.41679})
    contract_private_get_v5_algo_order_history = contractPrivateGetV5AlgoOrderHistory = Entry[_Dict]('v5/algo/order/history', ['contract', 'private'], 'GET', {'cost': 0.41679})
    contract_private_post_api_v1_contract_balance_valuation = contractPrivatePostApiV1ContractBalanceValuation = Entry[_Dict]('api/v1/contract_balance_valuation', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_account_info = contractPrivatePostApiV1ContractAccountInfo = Entry[_Dict]('api/v1/contract_account_info', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_position_info = contractPrivatePostApiV1ContractPositionInfo = Entry[_Dict]('api/v1/contract_position_info', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_sub_auth = contractPrivatePostApiV1ContractSubAuth = Entry[_Dict]('api/v1/contract_sub_auth', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_sub_account_list = contractPrivatePostApiV1ContractSubAccountList = Entry[_Dict]('api/v1/contract_sub_account_list', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_sub_account_info_list = contractPrivatePostApiV1ContractSubAccountInfoList = Entry[_Dict]('api/v1/contract_sub_account_info_list', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_sub_account_info = contractPrivatePostApiV1ContractSubAccountInfo = Entry[_Dict]('api/v1/contract_sub_account_info', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_sub_position_info = contractPrivatePostApiV1ContractSubPositionInfo = Entry[_Dict]('api/v1/contract_sub_position_info', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_financial_record = contractPrivatePostApiV1ContractFinancialRecord = Entry[_Dict]('api/v1/contract_financial_record', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_financial_record_exact = contractPrivatePostApiV1ContractFinancialRecordExact = Entry[_Dict]('api/v1/contract_financial_record_exact', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_user_settlement_records = contractPrivatePostApiV1ContractUserSettlementRecords = Entry[_Dict]('api/v1/contract_user_settlement_records', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_order_limit = contractPrivatePostApiV1ContractOrderLimit = Entry[_Dict]('api/v1/contract_order_limit', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_fee = contractPrivatePostApiV1ContractFee = Entry[_Dict]('api/v1/contract_fee', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_transfer_limit = contractPrivatePostApiV1ContractTransferLimit = Entry[_Dict]('api/v1/contract_transfer_limit', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_position_limit = contractPrivatePostApiV1ContractPositionLimit = Entry[_Dict]('api/v1/contract_position_limit', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_account_position_info = contractPrivatePostApiV1ContractAccountPositionInfo = Entry[_Dict]('api/v1/contract_account_position_info', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_master_sub_transfer = contractPrivatePostApiV1ContractMasterSubTransfer = Entry[_Dict]('api/v1/contract_master_sub_transfer', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_master_sub_transfer_record = contractPrivatePostApiV1ContractMasterSubTransferRecord = Entry[_Dict]('api/v1/contract_master_sub_transfer_record', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_available_level_rate = contractPrivatePostApiV1ContractAvailableLevelRate = Entry[_Dict]('api/v1/contract_available_level_rate', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v3_contract_financial_record = contractPrivatePostApiV3ContractFinancialRecord = Entry[_Dict]('api/v3/contract_financial_record', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v3_contract_financial_record_exact = contractPrivatePostApiV3ContractFinancialRecordExact = Entry[_Dict]('api/v3/contract_financial_record_exact', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_cancel_after = contractPrivatePostApiV1ContractCancelAfter = Entry[_Dict]('api/v1/contract-cancel-after', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_order = contractPrivatePostApiV1ContractOrder = Entry[_Dict]('api/v1/contract_order', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_batchorder = contractPrivatePostApiV1ContractBatchorder = Entry[_Dict]('api/v1/contract_batchorder', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_cancel = contractPrivatePostApiV1ContractCancel = Entry[_Dict]('api/v1/contract_cancel', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_cancelall = contractPrivatePostApiV1ContractCancelall = Entry[_Dict]('api/v1/contract_cancelall', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_switch_lever_rate = contractPrivatePostApiV1ContractSwitchLeverRate = Entry[_Dict]('api/v1/contract_switch_lever_rate', ['contract', 'private'], 'POST', {'cost': 30})
    contract_private_post_api_v1_lightning_close_position = contractPrivatePostApiV1LightningClosePosition = Entry[_Dict]('api/v1/lightning_close_position', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_order_info = contractPrivatePostApiV1ContractOrderInfo = Entry[_Dict]('api/v1/contract_order_info', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_order_detail = contractPrivatePostApiV1ContractOrderDetail = Entry[_Dict]('api/v1/contract_order_detail', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_openorders = contractPrivatePostApiV1ContractOpenorders = Entry[_Dict]('api/v1/contract_openorders', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_hisorders = contractPrivatePostApiV1ContractHisorders = Entry[_Dict]('api/v1/contract_hisorders', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_hisorders_exact = contractPrivatePostApiV1ContractHisordersExact = Entry[_Dict]('api/v1/contract_hisorders_exact', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_matchresults = contractPrivatePostApiV1ContractMatchresults = Entry[_Dict]('api/v1/contract_matchresults', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_matchresults_exact = contractPrivatePostApiV1ContractMatchresultsExact = Entry[_Dict]('api/v1/contract_matchresults_exact', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v3_contract_hisorders = contractPrivatePostApiV3ContractHisorders = Entry[_Dict]('api/v3/contract_hisorders', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v3_contract_hisorders_exact = contractPrivatePostApiV3ContractHisordersExact = Entry[_Dict]('api/v3/contract_hisorders_exact', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v3_contract_matchresults = contractPrivatePostApiV3ContractMatchresults = Entry[_Dict]('api/v3/contract_matchresults', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v3_contract_matchresults_exact = contractPrivatePostApiV3ContractMatchresultsExact = Entry[_Dict]('api/v3/contract_matchresults_exact', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_trigger_order = contractPrivatePostApiV1ContractTriggerOrder = Entry[_Dict]('api/v1/contract_trigger_order', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_trigger_cancel = contractPrivatePostApiV1ContractTriggerCancel = Entry[_Dict]('api/v1/contract_trigger_cancel', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_trigger_cancelall = contractPrivatePostApiV1ContractTriggerCancelall = Entry[_Dict]('api/v1/contract_trigger_cancelall', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_trigger_openorders = contractPrivatePostApiV1ContractTriggerOpenorders = Entry[_Dict]('api/v1/contract_trigger_openorders', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_trigger_hisorders = contractPrivatePostApiV1ContractTriggerHisorders = Entry[_Dict]('api/v1/contract_trigger_hisorders', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_tpsl_order = contractPrivatePostApiV1ContractTpslOrder = Entry[_Dict]('api/v1/contract_tpsl_order', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_tpsl_cancel = contractPrivatePostApiV1ContractTpslCancel = Entry[_Dict]('api/v1/contract_tpsl_cancel', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_tpsl_cancelall = contractPrivatePostApiV1ContractTpslCancelall = Entry[_Dict]('api/v1/contract_tpsl_cancelall', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_tpsl_openorders = contractPrivatePostApiV1ContractTpslOpenorders = Entry[_Dict]('api/v1/contract_tpsl_openorders', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_tpsl_hisorders = contractPrivatePostApiV1ContractTpslHisorders = Entry[_Dict]('api/v1/contract_tpsl_hisorders', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_relation_tpsl_order = contractPrivatePostApiV1ContractRelationTpslOrder = Entry[_Dict]('api/v1/contract_relation_tpsl_order', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_track_order = contractPrivatePostApiV1ContractTrackOrder = Entry[_Dict]('api/v1/contract_track_order', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_track_cancel = contractPrivatePostApiV1ContractTrackCancel = Entry[_Dict]('api/v1/contract_track_cancel', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_track_cancelall = contractPrivatePostApiV1ContractTrackCancelall = Entry[_Dict]('api/v1/contract_track_cancelall', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_track_openorders = contractPrivatePostApiV1ContractTrackOpenorders = Entry[_Dict]('api/v1/contract_track_openorders', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_api_v1_contract_track_hisorders = contractPrivatePostApiV1ContractTrackHisorders = Entry[_Dict]('api/v1/contract_track_hisorders', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_balance_valuation = contractPrivatePostSwapApiV1SwapBalanceValuation = Entry[_Dict]('swap-api/v1/swap_balance_valuation', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_account_info = contractPrivatePostSwapApiV1SwapAccountInfo = Entry[_Dict]('swap-api/v1/swap_account_info', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_position_info = contractPrivatePostSwapApiV1SwapPositionInfo = Entry[_Dict]('swap-api/v1/swap_position_info', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_account_position_info = contractPrivatePostSwapApiV1SwapAccountPositionInfo = Entry[_Dict]('swap-api/v1/swap_account_position_info', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_sub_auth = contractPrivatePostSwapApiV1SwapSubAuth = Entry[_Dict]('swap-api/v1/swap_sub_auth', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_sub_account_list = contractPrivatePostSwapApiV1SwapSubAccountList = Entry[_Dict]('swap-api/v1/swap_sub_account_list', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_sub_account_info_list = contractPrivatePostSwapApiV1SwapSubAccountInfoList = Entry[_Dict]('swap-api/v1/swap_sub_account_info_list', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_sub_account_info = contractPrivatePostSwapApiV1SwapSubAccountInfo = Entry[_Dict]('swap-api/v1/swap_sub_account_info', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_sub_position_info = contractPrivatePostSwapApiV1SwapSubPositionInfo = Entry[_Dict]('swap-api/v1/swap_sub_position_info', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_financial_record = contractPrivatePostSwapApiV1SwapFinancialRecord = Entry[_Dict]('swap-api/v1/swap_financial_record', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_financial_record_exact = contractPrivatePostSwapApiV1SwapFinancialRecordExact = Entry[_Dict]('swap-api/v1/swap_financial_record_exact', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_user_settlement_records = contractPrivatePostSwapApiV1SwapUserSettlementRecords = Entry[_Dict]('swap-api/v1/swap_user_settlement_records', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_available_level_rate = contractPrivatePostSwapApiV1SwapAvailableLevelRate = Entry[_Dict]('swap-api/v1/swap_available_level_rate', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_order_limit = contractPrivatePostSwapApiV1SwapOrderLimit = Entry[_Dict]('swap-api/v1/swap_order_limit', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_fee = contractPrivatePostSwapApiV1SwapFee = Entry[_Dict]('swap-api/v1/swap_fee', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_transfer_limit = contractPrivatePostSwapApiV1SwapTransferLimit = Entry[_Dict]('swap-api/v1/swap_transfer_limit', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_position_limit = contractPrivatePostSwapApiV1SwapPositionLimit = Entry[_Dict]('swap-api/v1/swap_position_limit', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_master_sub_transfer = contractPrivatePostSwapApiV1SwapMasterSubTransfer = Entry[_Dict]('swap-api/v1/swap_master_sub_transfer', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_master_sub_transfer_record = contractPrivatePostSwapApiV1SwapMasterSubTransferRecord = Entry[_Dict]('swap-api/v1/swap_master_sub_transfer_record', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v3_swap_financial_record = contractPrivatePostSwapApiV3SwapFinancialRecord = Entry[_Dict]('swap-api/v3/swap_financial_record', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v3_swap_financial_record_exact = contractPrivatePostSwapApiV3SwapFinancialRecordExact = Entry[_Dict]('swap-api/v3/swap_financial_record_exact', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_cancel_after = contractPrivatePostSwapApiV1SwapCancelAfter = Entry[_Dict]('swap-api/v1/swap-cancel-after', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_order = contractPrivatePostSwapApiV1SwapOrder = Entry[_Dict]('swap-api/v1/swap_order', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_batchorder = contractPrivatePostSwapApiV1SwapBatchorder = Entry[_Dict]('swap-api/v1/swap_batchorder', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_cancel = contractPrivatePostSwapApiV1SwapCancel = Entry[_Dict]('swap-api/v1/swap_cancel', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_cancelall = contractPrivatePostSwapApiV1SwapCancelall = Entry[_Dict]('swap-api/v1/swap_cancelall', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_lightning_close_position = contractPrivatePostSwapApiV1SwapLightningClosePosition = Entry[_Dict]('swap-api/v1/swap_lightning_close_position', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_switch_lever_rate = contractPrivatePostSwapApiV1SwapSwitchLeverRate = Entry[_Dict]('swap-api/v1/swap_switch_lever_rate', ['contract', 'private'], 'POST', {'cost': 30})
    contract_private_post_swap_api_v1_swap_order_info = contractPrivatePostSwapApiV1SwapOrderInfo = Entry[_Dict]('swap-api/v1/swap_order_info', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_order_detail = contractPrivatePostSwapApiV1SwapOrderDetail = Entry[_Dict]('swap-api/v1/swap_order_detail', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_openorders = contractPrivatePostSwapApiV1SwapOpenorders = Entry[_Dict]('swap-api/v1/swap_openorders', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_hisorders = contractPrivatePostSwapApiV1SwapHisorders = Entry[_Dict]('swap-api/v1/swap_hisorders', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_hisorders_exact = contractPrivatePostSwapApiV1SwapHisordersExact = Entry[_Dict]('swap-api/v1/swap_hisorders_exact', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_matchresults = contractPrivatePostSwapApiV1SwapMatchresults = Entry[_Dict]('swap-api/v1/swap_matchresults', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_matchresults_exact = contractPrivatePostSwapApiV1SwapMatchresultsExact = Entry[_Dict]('swap-api/v1/swap_matchresults_exact', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v3_swap_matchresults = contractPrivatePostSwapApiV3SwapMatchresults = Entry[_Dict]('swap-api/v3/swap_matchresults', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v3_swap_matchresults_exact = contractPrivatePostSwapApiV3SwapMatchresultsExact = Entry[_Dict]('swap-api/v3/swap_matchresults_exact', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v3_swap_hisorders = contractPrivatePostSwapApiV3SwapHisorders = Entry[_Dict]('swap-api/v3/swap_hisorders', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v3_swap_hisorders_exact = contractPrivatePostSwapApiV3SwapHisordersExact = Entry[_Dict]('swap-api/v3/swap_hisorders_exact', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_trigger_order = contractPrivatePostSwapApiV1SwapTriggerOrder = Entry[_Dict]('swap-api/v1/swap_trigger_order', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_trigger_cancel = contractPrivatePostSwapApiV1SwapTriggerCancel = Entry[_Dict]('swap-api/v1/swap_trigger_cancel', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_trigger_cancelall = contractPrivatePostSwapApiV1SwapTriggerCancelall = Entry[_Dict]('swap-api/v1/swap_trigger_cancelall', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_trigger_openorders = contractPrivatePostSwapApiV1SwapTriggerOpenorders = Entry[_Dict]('swap-api/v1/swap_trigger_openorders', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_trigger_hisorders = contractPrivatePostSwapApiV1SwapTriggerHisorders = Entry[_Dict]('swap-api/v1/swap_trigger_hisorders', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_tpsl_order = contractPrivatePostSwapApiV1SwapTpslOrder = Entry[_Dict]('swap-api/v1/swap_tpsl_order', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_tpsl_cancel = contractPrivatePostSwapApiV1SwapTpslCancel = Entry[_Dict]('swap-api/v1/swap_tpsl_cancel', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_tpsl_cancelall = contractPrivatePostSwapApiV1SwapTpslCancelall = Entry[_Dict]('swap-api/v1/swap_tpsl_cancelall', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_tpsl_openorders = contractPrivatePostSwapApiV1SwapTpslOpenorders = Entry[_Dict]('swap-api/v1/swap_tpsl_openorders', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_tpsl_hisorders = contractPrivatePostSwapApiV1SwapTpslHisorders = Entry[_Dict]('swap-api/v1/swap_tpsl_hisorders', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_relation_tpsl_order = contractPrivatePostSwapApiV1SwapRelationTpslOrder = Entry[_Dict]('swap-api/v1/swap_relation_tpsl_order', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_track_order = contractPrivatePostSwapApiV1SwapTrackOrder = Entry[_Dict]('swap-api/v1/swap_track_order', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_track_cancel = contractPrivatePostSwapApiV1SwapTrackCancel = Entry[_Dict]('swap-api/v1/swap_track_cancel', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_track_cancelall = contractPrivatePostSwapApiV1SwapTrackCancelall = Entry[_Dict]('swap-api/v1/swap_track_cancelall', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_track_openorders = contractPrivatePostSwapApiV1SwapTrackOpenorders = Entry[_Dict]('swap-api/v1/swap_track_openorders', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_swap_api_v1_swap_track_hisorders = contractPrivatePostSwapApiV1SwapTrackHisorders = Entry[_Dict]('swap-api/v1/swap_track_hisorders', ['contract', 'private'], 'POST', {'cost': 1})
    contract_private_post_v5_account_asset_mode = contractPrivatePostV5AccountAssetMode = Entry[_Dict]('v5/account/asset_mode', ['contract', 'private'], 'POST', {'cost': 100})
    contract_private_post_v5_trade_order = contractPrivatePostV5TradeOrder = Entry[_Dict]('v5/trade/order', ['contract', 'private'], 'POST', {'cost': 0.41679})
    contract_private_post_v5_trade_batch_orders = contractPrivatePostV5TradeBatchOrders = Entry[_Dict]('v5/trade/batch_orders', ['contract', 'private'], 'POST', {'cost': 0.41679})
    contract_private_post_v5_trade_cancel_order = contractPrivatePostV5TradeCancelOrder = Entry[_Dict]('v5/trade/cancel_order', ['contract', 'private'], 'POST', {'cost': 0.41679})
    contract_private_post_v5_trade_cancel_batch_orders = contractPrivatePostV5TradeCancelBatchOrders = Entry[_Dict]('v5/trade/cancel_batch_orders', ['contract', 'private'], 'POST', {'cost': 0.41679})
    contract_private_post_v5_trade_cancel_all_orders = contractPrivatePostV5TradeCancelAllOrders = Entry[_Dict]('v5/trade/cancel_all_orders', ['contract', 'private'], 'POST', {'cost': 0.41679})
    contract_private_post_v5_trade_cancel_after = contractPrivatePostV5TradeCancelAfter = Entry[_Dict]('v5/trade/cancel-after', ['contract', 'private'], 'POST', {'cost': 0.41679})
    contract_private_post_v5_trade_position = contractPrivatePostV5TradePosition = Entry[_Dict]('v5/trade/position', ['contract', 'private'], 'POST', {'cost': 0.41679})
    contract_private_post_v5_trade_position_all = contractPrivatePostV5TradePositionAll = Entry[_Dict]('v5/trade/position_all', ['contract', 'private'], 'POST', {'cost': 0.41679})
    contract_private_post_v5_position_lever = contractPrivatePostV5PositionLever = Entry[_Dict]('v5/position/lever', ['contract', 'private'], 'POST', {'cost': 0.20834})
    contract_private_post_v5_position_mode = contractPrivatePostV5PositionMode = Entry[_Dict]('v5/position/mode', ['contract', 'private'], 'POST', {'cost': 0.20834})
    contract_private_post_v5_position_margin = contractPrivatePostV5PositionMargin = Entry[_Dict]('v5/position/margin', ['contract', 'private'], 'POST', {'cost': 0.20834})
    contract_private_post_v5_account_fee_deduction_currency = contractPrivatePostV5AccountFeeDeductionCurrency = Entry[_Dict]('v5/account/fee_deduction_currency', ['contract', 'private'], 'POST', {'cost': 0.20834})
    contract_private_post_v5_algo_order = contractPrivatePostV5AlgoOrder = Entry[_Dict]('v5/algo/order', ['contract', 'private'], 'POST', {'cost': 0.41679})
    contract_private_post_v5_algo_cancel_orders = contractPrivatePostV5AlgoCancelOrders = Entry[_Dict]('v5/algo/cancel_orders', ['contract', 'private'], 'POST', {'cost': 0.41679})
