from ccxt.base.types import Entry


class ImplicitAPI:
    public_get_getvalidprimarycurrencycodes = publicGetGetValidPrimaryCurrencyCodes = Entry('GetValidPrimaryCurrencyCodes', 'public', 'GET', {'cost': 1})
    public_get_getvalidsecondarycurrencycodes = publicGetGetValidSecondaryCurrencyCodes = Entry('GetValidSecondaryCurrencyCodes', 'public', 'GET', {'cost': 1})
    public_get_getvalidlimitordertypes = publicGetGetValidLimitOrderTypes = Entry('GetValidLimitOrderTypes', 'public', 'GET', {'cost': 1})
    public_get_getvalidmarketordertypes = publicGetGetValidMarketOrderTypes = Entry('GetValidMarketOrderTypes', 'public', 'GET', {'cost': 1})
    public_get_getvalidordertypes = publicGetGetValidOrderTypes = Entry('GetValidOrderTypes', 'public', 'GET', {'cost': 1})
    public_get_getvalidtransactiontypes = publicGetGetValidTransactionTypes = Entry('GetValidTransactionTypes', 'public', 'GET', {'cost': 1})
    public_get_getmarketsummary = publicGetGetMarketSummary = Entry('GetMarketSummary', 'public', 'GET', {'cost': 1})
    public_get_getorderbook = publicGetGetOrderBook = Entry('GetOrderBook', 'public', 'GET', {'cost': 1})
    public_get_getallorders = publicGetGetAllOrders = Entry('GetAllOrders', 'public', 'GET', {'cost': 1})
    public_get_gettradehistorysummary = publicGetGetTradeHistorySummary = Entry('GetTradeHistorySummary', 'public', 'GET', {'cost': 1})
    public_get_getrecenttrades = publicGetGetRecentTrades = Entry('GetRecentTrades', 'public', 'GET', {'cost': 1})
    public_get_getfxrates = publicGetGetFxRates = Entry('GetFxRates', 'public', 'GET', {'cost': 1})
    public_get_getorderminimumvolumes = publicGetGetOrderMinimumVolumes = Entry('GetOrderMinimumVolumes', 'public', 'GET', {'cost': 1})
    public_get_getcryptowithdrawalfees = publicGetGetCryptoWithdrawalFees = Entry('GetCryptoWithdrawalFees', 'public', 'GET', {'cost': 1})
    public_get_getcryptowithdrawalfees2 = publicGetGetCryptoWithdrawalFees2 = Entry('GetCryptoWithdrawalFees2', 'public', 'GET', {'cost': 1})
    public_get_getnetworks = publicGetGetNetworks = Entry('GetNetworks', 'public', 'GET', {'cost': 1})
    public_get_getprimarycurrencyconfig2 = publicGetGetPrimaryCurrencyConfig2 = Entry('GetPrimaryCurrencyConfig2', 'public', 'GET', {'cost': 1})
    private_post_getopenorders = privatePostGetOpenOrders = Entry('GetOpenOrders', 'private', 'POST', {'cost': 1})
    private_post_getclosedorders = privatePostGetClosedOrders = Entry('GetClosedOrders', 'private', 'POST', {'cost': 1})
    private_post_getclosedfilledorders = privatePostGetClosedFilledOrders = Entry('GetClosedFilledOrders', 'private', 'POST', {'cost': 1})
    private_post_getorderdetails = privatePostGetOrderDetails = Entry('GetOrderDetails', 'private', 'POST', {'cost': 1})
    private_post_getaccounts = privatePostGetAccounts = Entry('GetAccounts', 'private', 'POST', {'cost': 1})
    private_post_gettransactions = privatePostGetTransactions = Entry('GetTransactions', 'private', 'POST', {'cost': 1})
    private_post_getfiatbankaccounts = privatePostGetFiatBankAccounts = Entry('GetFiatBankAccounts', 'private', 'POST', {'cost': 1})
    private_post_getdigitalcurrencydepositaddress = privatePostGetDigitalCurrencyDepositAddress = Entry('GetDigitalCurrencyDepositAddress', 'private', 'POST', {'cost': 1})
    private_post_getdigitalcurrencydepositaddress2 = privatePostGetDigitalCurrencyDepositAddress2 = Entry('GetDigitalCurrencyDepositAddress2', 'private', 'POST', {'cost': 1})
    private_post_getdigitalcurrencydepositaddresses = privatePostGetDigitalCurrencyDepositAddresses = Entry('GetDigitalCurrencyDepositAddresses', 'private', 'POST', {'cost': 1})
    private_post_getdigitalcurrencydepositaddresses2 = privatePostGetDigitalCurrencyDepositAddresses2 = Entry('GetDigitalCurrencyDepositAddresses2', 'private', 'POST', {'cost': 1})
    private_post_gettrades = privatePostGetTrades = Entry('GetTrades', 'private', 'POST', {'cost': 1})
    private_post_getbrokeragefees = privatePostGetBrokerageFees = Entry('GetBrokerageFees', 'private', 'POST', {'cost': 1})
    private_post_getdigitalcurrencywithdrawal = privatePostGetDigitalCurrencyWithdrawal = Entry('GetDigitalCurrencyWithdrawal', 'private', 'POST', {'cost': 1})
    private_post_placelimitorder = privatePostPlaceLimitOrder = Entry('PlaceLimitOrder', 'private', 'POST', {'cost': 1})
    private_post_placemarketorder = privatePostPlaceMarketOrder = Entry('PlaceMarketOrder', 'private', 'POST', {'cost': 1})
    private_post_cancelorder = privatePostCancelOrder = Entry('CancelOrder', 'private', 'POST', {'cost': 1})
    private_post_synchdigitalcurrencydepositaddresswithblockchain = privatePostSynchDigitalCurrencyDepositAddressWithBlockchain = Entry('SynchDigitalCurrencyDepositAddressWithBlockchain', 'private', 'POST', {'cost': 1})
    private_post_requestfiatwithdrawal = privatePostRequestFiatWithdrawal = Entry('RequestFiatWithdrawal', 'private', 'POST', {'cost': 1})
    private_post_withdrawfiatcurrency = privatePostWithdrawFiatCurrency = Entry('WithdrawFiatCurrency', 'private', 'POST', {'cost': 1})
    private_post_withdrawdigitalcurrency = privatePostWithdrawDigitalCurrency = Entry('WithdrawDigitalCurrency', 'private', 'POST', {'cost': 1})
    private_post_withdrawcrypto = privatePostWithdrawCrypto = Entry('WithdrawCrypto', 'private', 'POST', {'cost': 1})
