from ccxt.base.types import Entry
from typing import Any as PythonAny, Dict, List

_Dict = Dict[str, PythonAny]
_List = List[PythonAny]

class ImplicitAPI:
    public_get_feeschedules = publicGetFeeschedules = Entry[_Dict]('feeschedules', 'public', 'GET', {'cost': 1})
    public_get_instruments = publicGetInstruments = Entry[_Dict]('instruments', 'public', 'GET', {'cost': 1})
    public_get_orderbook = publicGetOrderbook = Entry[_Dict]('orderbook', 'public', 'GET', {'cost': 1})
    public_get_tickers = publicGetTickers = Entry[_Dict]('tickers', 'public', 'GET', {'cost': 1})
    public_get_history = publicGetHistory = Entry[_Dict]('history', 'public', 'GET', {'cost': 1})
    public_get_historicalfundingrates = publicGetHistoricalfundingrates = Entry[_Dict]('historicalfundingrates', 'public', 'GET', {'cost': 1})
    private_get_feeschedules_volumes = privateGetFeeschedulesVolumes = Entry[_Dict]('feeschedules/volumes', 'private', 'GET', {'cost': 1})
    private_get_openpositions = privateGetOpenpositions = Entry[_List]('openpositions', 'private', 'GET', {'cost': 1})
    private_get_notifications = privateGetNotifications = Entry[_Dict]('notifications', 'private', 'GET', {'cost': 1})
    private_get_accounts = privateGetAccounts = Entry[_Dict]('accounts', 'private', 'GET', {'cost': 1})
    private_get_openorders = privateGetOpenorders = Entry[_Dict]('openorders', 'private', 'GET', {'cost': 1})
    private_get_recentorders = privateGetRecentorders = Entry[_Dict]('recentorders', 'private', 'GET', {'cost': 1})
    private_get_fills = privateGetFills = Entry[_Dict]('fills', 'private', 'GET', {'cost': 1})
    private_get_transfers = privateGetTransfers = Entry[_Dict]('transfers', 'private', 'GET', {'cost': 1})
    private_get_leveragepreferences = privateGetLeveragepreferences = Entry[_Dict]('leveragepreferences', 'private', 'GET', {'cost': 1})
    private_get_pnlpreferences = privateGetPnlpreferences = Entry[_Dict]('pnlpreferences', 'private', 'GET', {'cost': 1})
    private_get_assignmentprogram_current = privateGetAssignmentprogramCurrent = Entry[_Dict]('assignmentprogram/current', 'private', 'GET', {'cost': 1})
    private_get_assignmentprogram_history = privateGetAssignmentprogramHistory = Entry[_Dict]('assignmentprogram/history', 'private', 'GET', {'cost': 1})
    private_get_orders_status = privateGetOrdersStatus = Entry[_Dict]('orders/status', 'private', 'GET', {'cost': 1})
    private_post_sendorder = privatePostSendorder = Entry[_Dict]('sendorder', 'private', 'POST', {'cost': 1})
    private_post_editorder = privatePostEditorder = Entry[_Dict]('editorder', 'private', 'POST', {'cost': 1})
    private_post_cancelorder = privatePostCancelorder = Entry[_Dict]('cancelorder', 'private', 'POST', {'cost': 1})
    private_post_transfer = privatePostTransfer = Entry[_Dict]('transfer', 'private', 'POST', {'cost': 1})
    private_post_batchorder = privatePostBatchorder = Entry[_Dict]('batchorder', 'private', 'POST', {'cost': 1})
    private_post_cancelallorders = privatePostCancelallorders = Entry[_Dict]('cancelallorders', 'private', 'POST', {'cost': 1})
    private_post_cancelallordersafter = privatePostCancelallordersafter = Entry[_Dict]('cancelallordersafter', 'private', 'POST', {'cost': 1})
    private_post_withdrawal = privatePostWithdrawal = Entry[_Dict]('withdrawal', 'private', 'POST', {'cost': 1})
    private_post_assignmentprogram_add = privatePostAssignmentprogramAdd = Entry[_Dict]('assignmentprogram/add', 'private', 'POST', {'cost': 1})
    private_post_assignmentprogram_delete = privatePostAssignmentprogramDelete = Entry[_Dict]('assignmentprogram/delete', 'private', 'POST', {'cost': 1})
    private_put_leveragepreferences = privatePutLeveragepreferences = Entry[_Dict]('leveragepreferences', 'private', 'PUT', {'cost': 1})
    private_put_pnlpreferences = privatePutPnlpreferences = Entry[_Dict]('pnlpreferences', 'private', 'PUT', {'cost': 1})
    charts_get_price_type_symbol_interval = chartsGetPriceTypeSymbolInterval = Entry[_Dict]('{price_type}/{symbol}/{interval}', 'charts', 'GET', {'cost': 1})
    history_get_orders = historyGetOrders = Entry[_Dict]('orders', 'history', 'GET', {'cost': 1})
    history_get_executions = historyGetExecutions = Entry[_Dict]('executions', 'history', 'GET', {'cost': 1})
    history_get_triggers = historyGetTriggers = Entry[_Dict]('triggers', 'history', 'GET', {'cost': 1})
    history_get_accountlogcsv = historyGetAccountlogcsv = Entry[str]('accountlogcsv', 'history', 'GET', {'cost': 1})
    history_get_account_log = historyGetAccountLog = Entry[_Dict]('account-log', 'history', 'GET', {'cost': 1})
    history_get_market_symbol_orders = historyGetMarketSymbolOrders = Entry[_Dict]('market/{symbol}/orders', 'history', 'GET', {'cost': 1})
    history_get_market_symbol_executions = historyGetMarketSymbolExecutions = Entry[_Dict]('market/{symbol}/executions', 'history', 'GET', {'cost': 1})
