from ccxt.base.types import Entry
from typing import Any as PythonAny, Dict, List

_Dict = Dict[str, PythonAny]
_List = List[PythonAny]

class ImplicitAPI:
    public_get_book_currency_quote = publicGetBookCurrencyQuote = Entry[_Dict]('book/{currency}/{quote}', 'public', 'GET', {'cost': 1})
    public_get_chart_week = publicGetChartWeek = Entry[_Dict]('chart/week', 'public', 'GET', {'cost': 1})
    public_get_chart_week_currency_quote = publicGetChartWeekCurrencyQuote = Entry[_Dict]('chart/week/{currency}/{quote}', 'public', 'GET', {'cost': 1})
    public_get_currency = publicGetCurrency = Entry[_List]('currency', 'public', 'GET', {'cost': 1})
    public_get_currency_available = publicGetCurrencyAvailable = Entry[_List]('currency/available', 'public', 'GET', {'cost': 1})
    public_get_currency_quotes = publicGetCurrencyQuotes = Entry[_List]('currency/quotes', 'public', 'GET', {'cost': 1})
    public_get_currency_currency = publicGetCurrencyCurrency = Entry[_Dict]('currency/{currency}', 'public', 'GET', {'cost': 1})
    public_get_pair = publicGetPair = Entry[_List]('pair', 'public', 'GET', {'cost': 1})
    public_get_pair_available = publicGetPairAvailable = Entry[_List]('pair/available', 'public', 'GET', {'cost': 1})
    public_get_ticker = publicGetTicker = Entry[_List]('ticker', 'public', 'GET', {'cost': 1})
    public_get_ticker_base_quote = publicGetTickerBaseQuote = Entry[_Dict]('ticker/{base}/{quote}', 'public', 'GET', {'cost': 1})
    public_get_time = publicGetTime = Entry[_Dict]('time', 'public', 'GET', {'cost': 1})
    public_get_trade_history_currency_quote = publicGetTradeHistoryCurrencyQuote = Entry[_List]('trade/history/{currency}/{quote}', 'public', 'GET', {'cost': 1})
    public_get_trade_fee_currency_quote = publicGetTradeFeeCurrencyQuote = Entry[_Dict]('trade/fee/{currency}/{quote}', 'public', 'GET', {'cost': 1})
    public_get_trade_feelevels = publicGetTradeFeeLevels = Entry[_List]('trade/feeLevels', 'public', 'GET', {'cost': 1})
    public_get_transaction_bindings = publicGetTransactionBindings = Entry[_List]('transaction/bindings', 'public', 'GET', {'cost': 1})
    private_get_auth_account = privateGetAuthAccount = Entry[_List]('auth/account', 'private', 'GET', {'cost': 1})
    private_get_auth_account_currency_currency_type = privateGetAuthAccountCurrencyCurrencyType = Entry[_List]('auth/account/currency/{currency}/{type}', 'private', 'GET', {'cost': 1})
    private_get_auth_order = privateGetAuthOrder = Entry[_List]('auth/order', 'private', 'GET', {'cost': 1})
    private_get_auth_order_getorder_id = privateGetAuthOrderGetOrderId = Entry[_Dict]('auth/order/getOrder/{id}', 'private', 'GET', {'cost': 1})
    private_get_auth_order_pair_currency_quote = privateGetAuthOrderPairCurrencyQuote = Entry[_List]('auth/order/pair/{currency}/{quote}', 'private', 'GET', {'cost': 1})
    private_get_auth_order_pair_currency_quote_active = privateGetAuthOrderPairCurrencyQuoteActive = Entry[_List]('auth/order/pair/{currency}/{quote}/active', 'private', 'GET', {'cost': 1})
    private_get_auth_stoporder = privateGetAuthStopOrder = Entry[_List]('auth/stopOrder', 'private', 'GET', {'cost': 1})
    private_get_auth_stoporder_getorder_id = privateGetAuthStopOrderGetOrderId = Entry[_Dict]('auth/stopOrder/getOrder/{id}', 'private', 'GET', {'cost': 1})
    private_get_auth_stoporder_pair_currency_quote = privateGetAuthStopOrderPairCurrencyQuote = Entry[_List]('auth/stopOrder/pair/{currency}/{quote}', 'private', 'GET', {'cost': 1})
    private_get_auth_stoporder_pair_currency_quote_active = privateGetAuthStopOrderPairCurrencyQuoteActive = Entry[_List]('auth/stopOrder/pair/{currency}/{quote}/active', 'private', 'GET', {'cost': 1})
    private_get_auth_trade = privateGetAuthTrade = Entry[_List]('auth/trade', 'private', 'GET', {'cost': 1})
    private_get_auth_trade_pair_currency_quote = privateGetAuthTradePairCurrencyQuote = Entry[_List]('auth/trade/pair/{currency}/{quote}', 'private', 'GET', {'cost': 1})
    private_get_auth_trade_fee_currency_quote = privateGetAuthTradeFeeCurrencyQuote = Entry[_Dict]('auth/trade/fee/{currency}/{quote}', 'private', 'GET', {'cost': 1})
    private_get_auth_transaction = privateGetAuthTransaction = Entry[_Dict]('auth/transaction', 'private', 'GET', {'cost': 1})
    private_get_auth_transaction_bindings = privateGetAuthTransactionBindings = Entry[_Dict]('auth/transaction/bindings', 'private', 'GET', {'cost': 1})
    private_get_auth_transaction_bindings_currency = privateGetAuthTransactionBindingsCurrency = Entry[_List]('auth/transaction/bindings/{currency}', 'private', 'GET', {'cost': 1})
    private_get_auth_transaction_id = privateGetAuthTransactionId = Entry[_Dict]('auth/transaction/{id}', 'private', 'GET', {'cost': 1})
    private_get_auth_transfer = privateGetAuthTransfer = Entry[_Dict]('auth/transfer', 'private', 'GET', {'cost': 1})
    private_post_auth_order_cancel = privatePostAuthOrderCancel = Entry[_Dict]('auth/order/cancel', 'private', 'POST', {'cost': 1})
    private_post_auth_order_cancelall = privatePostAuthOrderCancelAll = Entry[_Dict]('auth/order/cancelAll', 'private', 'POST', {'cost': 1})
    private_post_auth_order_cancelall_currency_quote = privatePostAuthOrderCancelAllCurrencyQuote = Entry[_Dict]('auth/order/cancelAll/{currency}/{quote}', 'private', 'POST', {'cost': 1})
    private_post_auth_order_place = privatePostAuthOrderPlace = Entry[_Dict]('auth/order/place', 'private', 'POST', {'cost': 1})
    private_post_auth_spot_deposit = privatePostAuthSpotDeposit = Entry[_Dict]('auth/spot/deposit', 'private', 'POST', {'cost': 1})
    private_post_auth_spot_withdraw = privatePostAuthSpotWithdraw = Entry[_Dict]('auth/spot/withdraw', 'private', 'POST', {'cost': 1})
    private_post_auth_stoporder_cancel = privatePostAuthStopOrderCancel = Entry[_Dict]('auth/stopOrder/cancel', 'private', 'POST', {'cost': 1})
    private_post_auth_stoporder_cancelall = privatePostAuthStopOrderCancelAll = Entry[_Dict]('auth/stopOrder/cancelAll', 'private', 'POST', {'cost': 1})
    private_post_auth_stoporder_cancelall_currency_quote = privatePostAuthStopOrderCancelAllCurrencyQuote = Entry[_Dict]('auth/stopOrder/cancelAll/{currency}/{quote}', 'private', 'POST', {'cost': 1})
    private_post_auth_stoporder_place = privatePostAuthStopOrderPlace = Entry[_Dict]('auth/stopOrder/place', 'private', 'POST', {'cost': 1})
    private_post_auth_transaction_depositaddress = privatePostAuthTransactionDepositAddress = Entry[_Dict]('auth/transaction/depositAddress', 'private', 'POST', {'cost': 1})
    private_post_auth_transaction_withdraw = privatePostAuthTransactionWithdraw = Entry[_Dict]('auth/transaction/withdraw', 'private', 'POST', {'cost': 1})
    private_post_auth_transaction_withdraw_cancel = privatePostAuthTransactionWithdrawCancel = Entry[_Dict]('auth/transaction/withdraw/cancel', 'private', 'POST', {'cost': 1})
    private_post_auth_transaction_withdraw_confirm = privatePostAuthTransactionWithdrawConfirm = Entry[_Dict]('auth/transaction/withdraw/confirm', 'private', 'POST', {'cost': 1})
    private_post_auth_transaction_withdraw_resendcode = privatePostAuthTransactionWithdrawResendCode = Entry[_Dict]('auth/transaction/withdraw/resendCode', 'private', 'POST', {'cost': 1})
    private_post_auth_transfer_email = privatePostAuthTransferEmail = Entry[_Dict]('auth/transfer/email', 'private', 'POST', {'cost': 1})
    private_post_auth_transfer_id = privatePostAuthTransferId = Entry[_Dict]('auth/transfer/id', 'private', 'POST', {'cost': 1})
    private_post_auth_transfer_phone = privatePostAuthTransferPhone = Entry[_Dict]('auth/transfer/phone', 'private', 'POST', {'cost': 1})
