from ccxt.base.types import Entry
from typing import Any as PythonAny, Dict

_Dict = Dict[str, PythonAny]

class ImplicitAPI:
    spot_public_get_currencypairs = spotPublicGetCurrencyPairs = Entry[_Dict]('currencyPairs', ['spot', 'public'], 'GET', {'cost': 2.5})
    spot_public_get_accuracy = spotPublicGetAccuracy = Entry[_Dict]('accuracy', ['spot', 'public'], 'GET', {'cost': 2.5})
    spot_public_get_usdtocny = spotPublicGetUsdToCny = Entry[_Dict]('usdToCny', ['spot', 'public'], 'GET', {'cost': 2.5})
    spot_public_get_assetconfigs = spotPublicGetAssetConfigs = Entry[_Dict]('assetConfigs', ['spot', 'public'], 'GET', {'cost': 2.5})
    spot_public_get_withdrawconfigs = spotPublicGetWithdrawConfigs = Entry[_Dict]('withdrawConfigs', ['spot', 'public'], 'GET', {'cost': 3.75})
    spot_public_get_timestamp = spotPublicGetTimestamp = Entry[_Dict]('timestamp', ['spot', 'public'], 'GET', {'cost': 2.5})
    spot_public_get_ticker_24hr = spotPublicGetTicker24hr = Entry[_Dict]('ticker/24hr', ['spot', 'public'], 'GET', {'cost': 2.5})
    spot_public_get_ticker = spotPublicGetTicker = Entry[_Dict]('ticker', ['spot', 'public'], 'GET', {'cost': 2.5})
    spot_public_get_depth = spotPublicGetDepth = Entry[_Dict]('depth', ['spot', 'public'], 'GET', {'cost': 2.5})
    spot_public_get_incrdepth = spotPublicGetIncrDepth = Entry[_Dict]('incrDepth', ['spot', 'public'], 'GET', {'cost': 2.5})
    spot_public_get_trades = spotPublicGetTrades = Entry[_Dict]('trades', ['spot', 'public'], 'GET', {'cost': 2.5})
    spot_public_get_kline = spotPublicGetKline = Entry[_Dict]('kline', ['spot', 'public'], 'GET', {'cost': 2.5})
    spot_public_get_supplement_system_ping = spotPublicGetSupplementSystemPing = Entry[_Dict]('supplement/system_ping', ['spot', 'public'], 'GET', {'cost': 2.5})
    spot_public_get_supplement_incrdepth = spotPublicGetSupplementIncrDepth = Entry[_Dict]('supplement/incrDepth', ['spot', 'public'], 'GET', {'cost': 2.5})
    spot_public_get_supplement_trades = spotPublicGetSupplementTrades = Entry[_Dict]('supplement/trades', ['spot', 'public'], 'GET', {'cost': 2.5})
    spot_public_get_supplement_ticker_price = spotPublicGetSupplementTickerPrice = Entry[_Dict]('supplement/ticker/price', ['spot', 'public'], 'GET', {'cost': 2.5})
    spot_public_get_supplement_ticker_bookticker = spotPublicGetSupplementTickerBookTicker = Entry[_Dict]('supplement/ticker/bookTicker', ['spot', 'public'], 'GET', {'cost': 2.5})
    spot_public_post_supplement_system_status = spotPublicPostSupplementSystemStatus = Entry[_Dict]('supplement/system_status', ['spot', 'public'], 'POST', {'cost': 2.5})
    spot_private_post_user_info = spotPrivatePostUserInfo = Entry[_Dict]('user_info', ['spot', 'private'], 'POST', {'cost': 2.5})
    spot_private_post_subscribe_get_key = spotPrivatePostSubscribeGetKey = Entry[_Dict]('subscribe/get_key', ['spot', 'private'], 'POST', {'cost': 2.5})
    spot_private_post_subscribe_refresh_key = spotPrivatePostSubscribeRefreshKey = Entry[_Dict]('subscribe/refresh_key', ['spot', 'private'], 'POST', {'cost': 2.5})
    spot_private_post_subscribe_destroy_key = spotPrivatePostSubscribeDestroyKey = Entry[_Dict]('subscribe/destroy_key', ['spot', 'private'], 'POST', {'cost': 2.5})
    spot_private_post_get_deposit_address = spotPrivatePostGetDepositAddress = Entry[_Dict]('get_deposit_address', ['spot', 'private'], 'POST', {'cost': 2.5})
    spot_private_post_deposit_history = spotPrivatePostDepositHistory = Entry[_Dict]('deposit_history', ['spot', 'private'], 'POST', {'cost': 2.5})
    spot_private_post_create_order = spotPrivatePostCreateOrder = Entry[_Dict]('create_order', ['spot', 'private'], 'POST', {'cost': 1})
    spot_private_post_batch_create_order = spotPrivatePostBatchCreateOrder = Entry[_Dict]('batch_create_order', ['spot', 'private'], 'POST', {'cost': 1})
    spot_private_post_cancel_order = spotPrivatePostCancelOrder = Entry[_Dict]('cancel_order', ['spot', 'private'], 'POST', {'cost': 1})
    spot_private_post_cancel_clientorders = spotPrivatePostCancelClientOrders = Entry[_Dict]('cancel_clientOrders', ['spot', 'private'], 'POST', {'cost': 1})
    spot_private_post_orders_info = spotPrivatePostOrdersInfo = Entry[_Dict]('orders_info', ['spot', 'private'], 'POST', {'cost': 2.5})
    spot_private_post_orders_info_history = spotPrivatePostOrdersInfoHistory = Entry[_Dict]('orders_info_history', ['spot', 'private'], 'POST', {'cost': 2.5})
    spot_private_post_order_transaction_detail = spotPrivatePostOrderTransactionDetail = Entry[_Dict]('order_transaction_detail', ['spot', 'private'], 'POST', {'cost': 2.5})
    spot_private_post_transaction_history = spotPrivatePostTransactionHistory = Entry[_Dict]('transaction_history', ['spot', 'private'], 'POST', {'cost': 2.5})
    spot_private_post_orders_info_no_deal = spotPrivatePostOrdersInfoNoDeal = Entry[_Dict]('orders_info_no_deal', ['spot', 'private'], 'POST', {'cost': 2.5})
    spot_private_post_withdraw = spotPrivatePostWithdraw = Entry[_Dict]('withdraw', ['spot', 'private'], 'POST', {'cost': 2.5})
    spot_private_post_withdrawcancel = spotPrivatePostWithdrawCancel = Entry[_Dict]('withdrawCancel', ['spot', 'private'], 'POST', {'cost': 2.5})
    spot_private_post_withdraws = spotPrivatePostWithdraws = Entry[_Dict]('withdraws', ['spot', 'private'], 'POST', {'cost': 2.5})
    spot_private_post_supplement_user_info = spotPrivatePostSupplementUserInfo = Entry[_Dict]('supplement/user_info', ['spot', 'private'], 'POST', {'cost': 2.5})
    spot_private_post_supplement_withdraw = spotPrivatePostSupplementWithdraw = Entry[_Dict]('supplement/withdraw', ['spot', 'private'], 'POST', {'cost': 2.5})
    spot_private_post_supplement_deposit_history = spotPrivatePostSupplementDepositHistory = Entry[_Dict]('supplement/deposit_history', ['spot', 'private'], 'POST', {'cost': 2.5})
    spot_private_post_supplement_withdraws = spotPrivatePostSupplementWithdraws = Entry[_Dict]('supplement/withdraws', ['spot', 'private'], 'POST', {'cost': 2.5})
    spot_private_post_supplement_get_deposit_address = spotPrivatePostSupplementGetDepositAddress = Entry[_Dict]('supplement/get_deposit_address', ['spot', 'private'], 'POST', {'cost': 2.5})
    spot_private_post_supplement_asset_detail = spotPrivatePostSupplementAssetDetail = Entry[_Dict]('supplement/asset_detail', ['spot', 'private'], 'POST', {'cost': 2.5})
    spot_private_post_supplement_customer_trade_fee = spotPrivatePostSupplementCustomerTradeFee = Entry[_Dict]('supplement/customer_trade_fee', ['spot', 'private'], 'POST', {'cost': 2.5})
    spot_private_post_supplement_api_restrictions = spotPrivatePostSupplementApiRestrictions = Entry[_Dict]('supplement/api_Restrictions', ['spot', 'private'], 'POST', {'cost': 2.5})
    spot_private_post_supplement_system_ping = spotPrivatePostSupplementSystemPing = Entry[_Dict]('supplement/system_ping', ['spot', 'private'], 'POST', {'cost': 2.5})
    spot_private_post_supplement_create_order_test = spotPrivatePostSupplementCreateOrderTest = Entry[_Dict]('supplement/create_order_test', ['spot', 'private'], 'POST', {'cost': 1})
    spot_private_post_supplement_create_order = spotPrivatePostSupplementCreateOrder = Entry[_Dict]('supplement/create_order', ['spot', 'private'], 'POST', {'cost': 1})
    spot_private_post_supplement_cancel_order = spotPrivatePostSupplementCancelOrder = Entry[_Dict]('supplement/cancel_order', ['spot', 'private'], 'POST', {'cost': 1})
    spot_private_post_supplement_cancel_order_by_symbol = spotPrivatePostSupplementCancelOrderBySymbol = Entry[_Dict]('supplement/cancel_order_by_symbol', ['spot', 'private'], 'POST', {'cost': 1})
    spot_private_post_supplement_orders_info = spotPrivatePostSupplementOrdersInfo = Entry[_Dict]('supplement/orders_info', ['spot', 'private'], 'POST', {'cost': 2.5})
    spot_private_post_supplement_orders_info_no_deal = spotPrivatePostSupplementOrdersInfoNoDeal = Entry[_Dict]('supplement/orders_info_no_deal', ['spot', 'private'], 'POST', {'cost': 2.5})
    spot_private_post_supplement_orders_info_history = spotPrivatePostSupplementOrdersInfoHistory = Entry[_Dict]('supplement/orders_info_history', ['spot', 'private'], 'POST', {'cost': 2.5})
    spot_private_post_supplement_user_info_account = spotPrivatePostSupplementUserInfoAccount = Entry[_Dict]('supplement/user_info_account', ['spot', 'private'], 'POST', {'cost': 2.5})
    spot_private_post_supplement_transaction_history = spotPrivatePostSupplementTransactionHistory = Entry[_Dict]('supplement/transaction_history', ['spot', 'private'], 'POST', {'cost': 2.5})
    contract_public_get_cfd_openapi_v1_pub_gettime = contractPublicGetCfdOpenApiV1PubGetTime = Entry[_Dict]('cfd/openApi/v1/pub/getTime', ['contract', 'public'], 'GET', {'cost': 2.5})
    contract_public_get_cfd_openapi_v1_pub_instrument = contractPublicGetCfdOpenApiV1PubInstrument = Entry[_Dict]('cfd/openApi/v1/pub/instrument', ['contract', 'public'], 'GET', {'cost': 2.5})
    contract_public_get_cfd_openapi_v1_pub_marketdata = contractPublicGetCfdOpenApiV1PubMarketData = Entry[_Dict]('cfd/openApi/v1/pub/marketData', ['contract', 'public'], 'GET', {'cost': 2.5})
    contract_public_get_cfd_openapi_v1_pub_marketorder = contractPublicGetCfdOpenApiV1PubMarketOrder = Entry[_Dict]('cfd/openApi/v1/pub/marketOrder', ['contract', 'public'], 'GET', {'cost': 2.5})
