from ccxt.base.types import Entry
from typing import Any as PythonAny, Dict, List

_Dict = Dict[str, PythonAny]
_List = List[PythonAny]

class ImplicitAPI:
    root_get = rootGet = Entry[_Dict]('', 'root', 'GET', {'cost': 1})
    root_get_info = rootGetInfo = Entry[_Dict]('info', 'root', 'GET', {'cost': 1})
    public_get_account = publicGetAccount = Entry[_Dict]('account', 'public', 'GET', {'cost': 1})
    public_get_accountsbyl1address = publicGetAccountsByL1Address = Entry[_Dict]('accountsByL1Address', 'public', 'GET', {'cost': 1})
    public_get_apikeys = publicGetApikeys = Entry[_Dict]('apikeys', 'public', 'GET', {'cost': 1})
    public_get_exchangestats = publicGetExchangeStats = Entry[_Dict]('exchangeStats', 'public', 'GET', {'cost': 1})
    public_get_assetdetails = publicGetAssetDetails = Entry[_Dict]('assetDetails', 'public', 'GET', {'cost': 1})
    public_get_orderbookdetails = publicGetOrderBookDetails = Entry[_Dict]('orderBookDetails', 'public', 'GET', {'cost': 1})
    public_get_orderbookorders = publicGetOrderBookOrders = Entry[_Dict]('orderBookOrders', 'public', 'GET', {'cost': 1})
    public_get_orderbooks = publicGetOrderBooks = Entry[_Dict]('orderBooks', 'public', 'GET', {'cost': 1})
    public_get_recenttrades = publicGetRecentTrades = Entry[_Dict]('recentTrades', 'public', 'GET', {'cost': 1})
    public_get_blocktxs = publicGetBlockTxs = Entry[_Dict]('blockTxs', 'public', 'GET', {'cost': 1})
    public_get_nextnonce = publicGetNextNonce = Entry[_Dict]('nextNonce', 'public', 'GET', {'cost': 1})
    public_get_tx = publicGetTx = Entry[_Dict]('tx', 'public', 'GET', {'cost': 1})
    public_get_txfroml1txhash = publicGetTxFromL1TxHash = Entry[_Dict]('txFromL1TxHash', 'public', 'GET', {'cost': 1})
    public_get_txs = publicGetTxs = Entry[_Dict]('txs', 'public', 'GET', {'cost': 1})
    public_get_announcement = publicGetAnnouncement = Entry[_Dict]('announcement', 'public', 'GET', {'cost': 1})
    public_get_block = publicGetBlock = Entry[_Dict]('block', 'public', 'GET', {'cost': 1})
    public_get_blocks = publicGetBlocks = Entry[_List]('blocks', 'public', 'GET', {'cost': 1})
    public_get_currentheight = publicGetCurrentHeight = Entry[_Dict]('currentHeight', 'public', 'GET', {'cost': 1})
    public_get_candles = publicGetCandles = Entry[_Dict]('candles', 'public', 'GET', {'cost': 1})
    public_get_fundings = publicGetFundings = Entry[_Dict]('fundings', 'public', 'GET', {'cost': 1})
    public_get_fastbridge_info = publicGetFastbridgeInfo = Entry[_Dict]('fastbridge/info', 'public', 'GET', {'cost': 1})
    public_get_funding_rates = publicGetFundingRates = Entry[_Dict]('funding-rates', 'public', 'GET', {'cost': 1})
    public_get_withdrawaldelay = publicGetWithdrawalDelay = Entry[_Dict]('withdrawalDelay', 'public', 'GET', {'cost': 1})
    public_post_sendtx = publicPostSendTx = Entry[_Dict]('sendTx', 'public', 'POST', {'cost': 1})
    public_post_sendtxbatch = publicPostSendTxBatch = Entry[_Dict]('sendTxBatch', 'public', 'POST', {'cost': 1})
    private_get_accountlimits = privateGetAccountLimits = Entry[_Dict]('accountLimits', 'private', 'GET', {'cost': 1})
    private_get_accountmetadata = privateGetAccountMetadata = Entry[_Dict]('accountMetadata', 'private', 'GET', {'cost': 1})
    private_get_pnl = privateGetPnl = Entry[_Dict]('pnl', 'private', 'GET', {'cost': 1})
    private_get_l1metadata = privateGetL1Metadata = Entry[_Dict]('l1Metadata', 'private', 'GET', {'cost': 1})
    private_get_liquidations = privateGetLiquidations = Entry[_Dict]('liquidations', 'private', 'GET', {'cost': 1})
    private_get_positionfunding = privateGetPositionFunding = Entry[_Dict]('positionFunding', 'private', 'GET', {'cost': 1})
    private_get_publicpoolsmetadata = privateGetPublicPoolsMetadata = Entry[_Dict]('publicPoolsMetadata', 'private', 'GET', {'cost': 1})
    private_get_accountactiveorders = privateGetAccountActiveOrders = Entry[_Dict]('accountActiveOrders', 'private', 'GET', {'cost': 1})
    private_get_accountinactiveorders = privateGetAccountInactiveOrders = Entry[_Dict]('accountInactiveOrders', 'private', 'GET', {'cost': 1})
    private_get_export = privateGetExport = Entry[_Dict]('export', 'private', 'GET', {'cost': 1})
    private_get_trades = privateGetTrades = Entry[_Dict]('trades', 'private', 'GET', {'cost': 1})
    private_get_accounttxs = privateGetAccountTxs = Entry[_Dict]('accountTxs', 'private', 'GET', {'cost': 1})
    private_get_deposit_history = privateGetDepositHistory = Entry[_Dict]('deposit/history', 'private', 'GET', {'cost': 1})
    private_get_transfer_history = privateGetTransferHistory = Entry[_Dict]('transfer/history', 'private', 'GET', {'cost': 1})
    private_get_withdraw_history = privateGetWithdrawHistory = Entry[_Dict]('withdraw/history', 'private', 'GET', {'cost': 1})
    private_get_referral_points = privateGetReferralPoints = Entry[_Dict]('referral/points', 'private', 'GET', {'cost': 1})
    private_get_transferfeeinfo = privateGetTransferFeeInfo = Entry[_Dict]('transferFeeInfo', 'private', 'GET', {'cost': 1})
    private_post_changeaccounttier = privatePostChangeAccountTier = Entry[_Dict]('changeAccountTier', 'private', 'POST', {'cost': 1})
    private_post_notification_ack = privatePostNotificationAck = Entry[_Dict]('notification/ack', 'private', 'POST', {'cost': 1})
