from ccxt.base.types import Entry


class ImplicitAPI:
    public_get_coins = publicGetCoins = Entry('coins', 'public', 'GET', {'cost': 1})
    public_get_coin_orderbook = publicGetCoinOrderbook = Entry('{coin}/orderbook/', 'public', 'GET', {'cost': 1})
    public_get_coin_ticker = publicGetCoinTicker = Entry('{coin}/ticker/', 'public', 'GET', {'cost': 1})
    public_get_coin_trades = publicGetCoinTrades = Entry('{coin}/trades/', 'public', 'GET', {'cost': 1})
    public_get_coin_trades_from = publicGetCoinTradesFrom = Entry('{coin}/trades/{from}/', 'public', 'GET', {'cost': 1})
    public_get_coin_trades_from_to = publicGetCoinTradesFromTo = Entry('{coin}/trades/{from}/{to}', 'public', 'GET', {'cost': 1})
    public_get_coin_day_summary_year_month_day = publicGetCoinDaySummaryYearMonthDay = Entry('{coin}/day-summary/{year}/{month}/{day}/', 'public', 'GET', {'cost': 1})
    private_post_cancel_order = privatePostCancelOrder = Entry('cancel_order', 'private', 'POST', {'cost': 1})
    private_post_get_account_info = privatePostGetAccountInfo = Entry('get_account_info', 'private', 'POST', {'cost': 1})
    private_post_get_order = privatePostGetOrder = Entry('get_order', 'private', 'POST', {'cost': 1})
    private_post_get_withdrawal = privatePostGetWithdrawal = Entry('get_withdrawal', 'private', 'POST', {'cost': 1})
    private_post_list_system_messages = privatePostListSystemMessages = Entry('list_system_messages', 'private', 'POST', {'cost': 1})
    private_post_list_orders = privatePostListOrders = Entry('list_orders', 'private', 'POST', {'cost': 1})
    private_post_list_orderbook = privatePostListOrderbook = Entry('list_orderbook', 'private', 'POST', {'cost': 1})
    private_post_place_buy_order = privatePostPlaceBuyOrder = Entry('place_buy_order', 'private', 'POST', {'cost': 1})
    private_post_place_sell_order = privatePostPlaceSellOrder = Entry('place_sell_order', 'private', 'POST', {'cost': 1})
    private_post_place_market_buy_order = privatePostPlaceMarketBuyOrder = Entry('place_market_buy_order', 'private', 'POST', {'cost': 1})
    private_post_place_market_sell_order = privatePostPlaceMarketSellOrder = Entry('place_market_sell_order', 'private', 'POST', {'cost': 1})
    private_post_withdraw_coin = privatePostWithdrawCoin = Entry('withdraw_coin', 'private', 'POST', {'cost': 1})
    v4public_get_coin_candle = v4PublicGetCoinCandle = Entry('{coin}/candle/', 'v4Public', 'GET', {'cost': 1})
    v4publicnet_get_candles = v4PublicNetGetCandles = Entry('candles', 'v4PublicNet', 'GET', {'cost': 1})
