from ccxt.base.types import Entry
from typing import Any as PythonAny, Dict, List

_Dict = Dict[str, PythonAny]
_List = List[PythonAny]

class ImplicitAPI:
    public_get_info = publicGetInfo = Entry[_Dict]('info', 'public', 'GET', {'cost': 1})
    public_get_info_fees = publicGetInfoFees = Entry[_Dict]('info/fees', 'public', 'GET', {'cost': 1})
    public_get_info_prices = publicGetInfoPrices = Entry[_Dict]('info/prices', 'public', 'GET', {'cost': 1})
    public_get_kline = publicGetKline = Entry[_Dict]('kline', 'public', 'GET', {'cost': 12})
    public_get_kline_mark = publicGetKlineMark = Entry[_Dict]('kline/mark', 'public', 'GET', {'cost': 12})
    public_get_book = publicGetBook = Entry[_Dict]('book', 'public', 'GET', {'cost': 1})
    public_get_trades = publicGetTrades = Entry[_Dict]('trades', 'public', 'GET', {'cost': 1})
    public_get_funding_rate_history = publicGetFundingRateHistory = Entry[_Dict]('funding_rate/history', 'public', 'GET', {'cost': 1})
    public_get_loan_pool = publicGetLoanPool = Entry[_Dict]('loan_pool', 'public', 'GET', {'cost': 1})
    public_get_account = publicGetAccount = Entry[_Dict]('account', 'public', 'GET', {'cost': 1})
    public_get_account_loan = publicGetAccountLoan = Entry[_Dict]('account/loan', 'public', 'GET', {'cost': 1})
    public_get_account_settings = publicGetAccountSettings = Entry[_Dict]('account/settings', 'public', 'GET', {'cost': 1})
    public_get_positions = publicGetPositions = Entry[_Dict]('positions', 'public', 'GET', {'cost': 1})
    public_get_trades_history = publicGetTradesHistory = Entry[_Dict]('trades/history', 'public', 'GET', {'cost': 12})
    public_get_funding_history = publicGetFundingHistory = Entry[_Dict]('funding/history', 'public', 'GET', {'cost': 1})
    public_get_portfolio = publicGetPortfolio = Entry[_Dict]('portfolio', 'public', 'GET', {'cost': 1})
    public_get_account_balance_history = publicGetAccountBalanceHistory = Entry[_Dict]('account/balance/history', 'public', 'GET', {'cost': 12})
    public_get_account_spot_balance_history = publicGetAccountSpotBalanceHistory = Entry[_Dict]('account/spot_balance/history', 'public', 'GET', {'cost': 1})
    public_get_account_spot_asset_deposit_history = publicGetAccountSpotAssetDepositHistory = Entry[_Dict]('account/spot_asset/deposit/history', 'public', 'GET', {'cost': 1})
    public_get_account_spot_asset_withdraw_history = publicGetAccountSpotAssetWithdrawHistory = Entry[_Dict]('account/spot_asset/withdraw/history', 'public', 'GET', {'cost': 1})
    public_get_account_spot_asset_withdraw_pending = publicGetAccountSpotAssetWithdrawPending = Entry[_Dict]('account/spot_asset/withdraw/pending', 'public', 'GET', {'cost': 1})
    public_get_orders = publicGetOrders = Entry[_Dict]('orders', 'public', 'GET', {'cost': 1})
    public_get_orders_history = publicGetOrdersHistory = Entry[_Dict]('orders/history', 'public', 'GET', {'cost': 12})
    public_get_orders_history_by_id = publicGetOrdersHistoryById = Entry[_Dict]('orders/history_by_id', 'public', 'GET', {'cost': 1})
    public_get_spot_assets = publicGetSpotAssets = Entry[_Dict]('spot_assets', 'public', 'GET', {'cost': 1})
    public_get_spot_assets_bridge_info = publicGetSpotAssetsBridgeInfo = Entry[_Dict]('spot_assets/bridge/info', 'public', 'GET', {'cost': 1})
    public_get_spot_assets_bridge_parameters_symbol = publicGetSpotAssetsBridgeParametersSymbol = Entry[_Dict]('spot_assets/bridge/parameters/{symbol}', 'public', 'GET', {'cost': 1})
    public_get_lake_list = publicGetLakeList = Entry[_Dict]('lake/list', 'public', 'GET', {'cost': 1})
    public_get_account_builder_codes_approvals = publicGetAccountBuilderCodesApprovals = Entry[_List]('account/builder_codes/approvals', 'public', 'GET', {'cost': 1})
    private_post_account_leverage = privatePostAccountLeverage = Entry[_Dict]('account/leverage', 'private', 'POST', {'cost': 1})
    private_post_account_margin = privatePostAccountMargin = Entry[_Dict]('account/margin', 'private', 'POST', {'cost': 1})
    private_post_account_withdraw = privatePostAccountWithdraw = Entry[_Dict]('account/withdraw', 'private', 'POST', {'cost': 1})
    private_post_account_settings_auto_lend_disabled = privatePostAccountSettingsAutoLendDisabled = Entry[_Dict]('account/settings/auto_lend_disabled', 'private', 'POST', {'cost': 1})
    private_post_account_settings_spot = privatePostAccountSettingsSpot = Entry[_Dict]('account/settings/spot', 'private', 'POST', {'cost': 1})
    private_post_account_spot_asset_withdraw = privatePostAccountSpotAssetWithdraw = Entry[_Dict]('account/spot_asset/withdraw', 'private', 'POST', {'cost': 1})
    private_post_account_subaccount_create = privatePostAccountSubaccountCreate = Entry[_Dict]('account/subaccount/create', 'private', 'POST', {'cost': 1})
    private_post_account_subaccount_list = privatePostAccountSubaccountList = Entry[_Dict]('account/subaccount/list', 'private', 'POST', {'cost': 1})
    private_post_account_subaccount_transfer = privatePostAccountSubaccountTransfer = Entry[_Dict]('account/subaccount/transfer', 'private', 'POST', {'cost': 1})
    private_post_account_subaccount_spot_asset_transfer = privatePostAccountSubaccountSpotAssetTransfer = Entry[_Dict]('account/subaccount/spot_asset/transfer', 'private', 'POST', {'cost': 1})
    private_post_positions_add_isolated_margin = privatePostPositionsAddIsolatedMargin = Entry[_Dict]('positions/add_isolated_margin', 'private', 'POST', {'cost': 1})
    private_post_orders_create = privatePostOrdersCreate = Entry[_Dict]('orders/create', 'private', 'POST', {'cost': 1})
    private_post_orders_create_market = privatePostOrdersCreateMarket = Entry[_Dict]('orders/create_market', 'private', 'POST', {'cost': 1})
    private_post_orders_stop_create = privatePostOrdersStopCreate = Entry[_Dict]('orders/stop/create', 'private', 'POST', {'cost': 1})
    private_post_positions_tpsl = privatePostPositionsTpsl = Entry[_Dict]('positions/tpsl', 'private', 'POST', {'cost': 1})
    private_post_orders_cancel = privatePostOrdersCancel = Entry[_Dict]('orders/cancel', 'private', 'POST', {'cost': 0.5})
    private_post_orders_cancel_all = privatePostOrdersCancelAll = Entry[_Dict]('orders/cancel_all', 'private', 'POST', {'cost': 0.5})
    private_post_orders_stop_cancel = privatePostOrdersStopCancel = Entry[_Dict]('orders/stop/cancel', 'private', 'POST', {'cost': 0.5})
    private_post_orders_edit = privatePostOrdersEdit = Entry[_Dict]('orders/edit', 'private', 'POST', {'cost': 1})
    private_post_orders_batch = privatePostOrdersBatch = Entry[_Dict]('orders/batch', 'private', 'POST', {'cost': 1})
    private_post_account_builder_codes_approve = privatePostAccountBuilderCodesApprove = Entry[_Dict]('account/builder_codes/approve', 'private', 'POST', {'cost': 1})
    private_post_account_builder_codes_revoke = privatePostAccountBuilderCodesRevoke = Entry[_Dict]('account/builder_codes/revoke', 'private', 'POST', {'cost': 1})
    private_post_agent_bind = privatePostAgentBind = Entry[_Dict]('agent/bind', 'private', 'POST', {'cost': 1})
    private_post_account_api_keys_create = privatePostAccountApiKeysCreate = Entry[_Dict]('account/api_keys/create', 'private', 'POST', {'cost': 1})
    private_post_account_api_keys_revoke = privatePostAccountApiKeysRevoke = Entry[_Dict]('account/api_keys/revoke', 'private', 'POST', {'cost': 1})
    private_post_account_api_keys = privatePostAccountApiKeys = Entry[_Dict]('account/api_keys', 'private', 'POST', {'cost': 1})
    private_post_lake_add_blacklist = privatePostLakeAddBlacklist = Entry[_Dict]('lake/add_blacklist', 'private', 'POST', {'cost': 1})
    private_post_lake_add_max_leverage = privatePostLakeAddMaxLeverage = Entry[_Dict]('lake/add_max_leverage', 'private', 'POST', {'cost': 1})
    private_post_lake_add_whitelist = privatePostLakeAddWhitelist = Entry[_Dict]('lake/add_whitelist', 'private', 'POST', {'cost': 1})
    private_post_lake_claim_manager = privatePostLakeClaimManager = Entry[_Dict]('lake/claim_manager', 'private', 'POST', {'cost': 1})
    private_post_lake_claim_referral_code = privatePostLakeClaimReferralCode = Entry[_Dict]('lake/claim_referral_code', 'private', 'POST', {'cost': 1})
    private_post_lake_create = privatePostLakeCreate = Entry[_Dict]('lake/create', 'private', 'POST', {'cost': 1})
    private_post_lake_deposit = privatePostLakeDeposit = Entry[_Dict]('lake/deposit', 'private', 'POST', {'cost': 1})
    private_post_lake_remove_blacklist = privatePostLakeRemoveBlacklist = Entry[_Dict]('lake/remove_blacklist', 'private', 'POST', {'cost': 1})
    private_post_lake_remove_max_leverage = privatePostLakeRemoveMaxLeverage = Entry[_Dict]('lake/remove_max_leverage', 'private', 'POST', {'cost': 1})
    private_post_lake_remove_whitelist = privatePostLakeRemoveWhitelist = Entry[_Dict]('lake/remove_whitelist', 'private', 'POST', {'cost': 1})
    private_post_lake_update_deposit_cap = privatePostLakeUpdateDepositCap = Entry[_Dict]('lake/update_deposit_cap', 'private', 'POST', {'cost': 1})
    private_post_lake_withdraw = privatePostLakeWithdraw = Entry[_Dict]('lake/withdraw', 'private', 'POST', {'cost': 1})
