from ccxt.base.types import Entry
from typing import Any as PythonAny, Dict, List

_List = List[PythonAny]
_Dict = Dict[str, PythonAny]

class ImplicitAPI:
    public_get_market_all = publicGetMarketAll = Entry[_List]('market/all', 'public', 'GET', {'cost': 2})
    public_get_candles_timeframe = publicGetCandlesTimeframe = Entry[_List]('candles/{timeframe}', 'public', 'GET', {'cost': 2})
    public_get_candles_timeframe_unit = publicGetCandlesTimeframeUnit = Entry[_List]('candles/{timeframe}/{unit}', 'public', 'GET', {'cost': 2})
    public_get_candles_seconds = publicGetCandlesSeconds = Entry[_List]('candles/seconds', 'public', 'GET', {'cost': 2})
    public_get_candles_minutes_unit = publicGetCandlesMinutesUnit = Entry[_List]('candles/minutes/{unit}', 'public', 'GET', {'cost': 2})
    public_get_candles_minutes_1 = publicGetCandlesMinutes1 = Entry[_List]('candles/minutes/1', 'public', 'GET', {'cost': 2})
    public_get_candles_minutes_3 = publicGetCandlesMinutes3 = Entry[_List]('candles/minutes/3', 'public', 'GET', {'cost': 2})
    public_get_candles_minutes_5 = publicGetCandlesMinutes5 = Entry[_List]('candles/minutes/5', 'public', 'GET', {'cost': 2})
    public_get_candles_minutes_10 = publicGetCandlesMinutes10 = Entry[_List]('candles/minutes/10', 'public', 'GET', {'cost': 2})
    public_get_candles_minutes_15 = publicGetCandlesMinutes15 = Entry[_List]('candles/minutes/15', 'public', 'GET', {'cost': 2})
    public_get_candles_minutes_30 = publicGetCandlesMinutes30 = Entry[_List]('candles/minutes/30', 'public', 'GET', {'cost': 2})
    public_get_candles_minutes_60 = publicGetCandlesMinutes60 = Entry[_List]('candles/minutes/60', 'public', 'GET', {'cost': 2})
    public_get_candles_minutes_240 = publicGetCandlesMinutes240 = Entry[_List]('candles/minutes/240', 'public', 'GET', {'cost': 2})
    public_get_candles_days = publicGetCandlesDays = Entry[_List]('candles/days', 'public', 'GET', {'cost': 2})
    public_get_candles_weeks = publicGetCandlesWeeks = Entry[_List]('candles/weeks', 'public', 'GET', {'cost': 2})
    public_get_candles_months = publicGetCandlesMonths = Entry[_List]('candles/months', 'public', 'GET', {'cost': 2})
    public_get_candles_years = publicGetCandlesYears = Entry[_List]('candles/years', 'public', 'GET', {'cost': 2})
    public_get_trades_ticks = publicGetTradesTicks = Entry[_List]('trades/ticks', 'public', 'GET', {'cost': 2})
    public_get_ticker = publicGetTicker = Entry[_List]('ticker', 'public', 'GET', {'cost': 2})
    public_get_ticker_all = publicGetTickerAll = Entry[_Dict]('ticker/all', 'public', 'GET', {'cost': 2})
    public_get_orderbook = publicGetOrderbook = Entry[_List]('orderbook', 'public', 'GET', {'cost': 2})
    public_get_orderbook_instruments = publicGetOrderbookInstruments = Entry[_List]('orderbook/instruments', 'public', 'GET', {'cost': 2})
    private_get_accounts = privateGetAccounts = Entry[_Dict]('accounts', 'private', 'GET', {'cost': 0.67})
    private_get_orders_chance = privateGetOrdersChance = Entry[_Dict]('orders/chance', 'private', 'GET', {'cost': 0.67})
    private_get_order = privateGetOrder = Entry[_Dict]('order', 'private', 'GET', {'cost': 0.67})
    private_get_orders_closed = privateGetOrdersClosed = Entry[_List]('orders/closed', 'private', 'GET', {'cost': 0.67})
    private_get_orders_open = privateGetOrdersOpen = Entry[_List]('orders/open', 'private', 'GET', {'cost': 0.67})
    private_get_orders_uuids = privateGetOrdersUuids = Entry[_List]('orders/uuids', 'private', 'GET', {'cost': 0.67})
    private_get_withdraws = privateGetWithdraws = Entry[_List]('withdraws', 'private', 'GET', {'cost': 0.67})
    private_get_withdraw = privateGetWithdraw = Entry[_Dict]('withdraw', 'private', 'GET', {'cost': 0.67})
    private_get_withdraws_chance = privateGetWithdrawsChance = Entry[_Dict]('withdraws/chance', 'private', 'GET', {'cost': 0.67})
    private_get_withdraws_coin_addresses = privateGetWithdrawsCoinAddresses = Entry[_List]('withdraws/coin_addresses', 'private', 'GET', {'cost': 0.67})
    private_get_deposits = privateGetDeposits = Entry[_List]('deposits', 'private', 'GET', {'cost': 0.67})
    private_get_deposits_chance_coin = privateGetDepositsChanceCoin = Entry[_Dict]('deposits/chance/coin', 'private', 'GET', {'cost': 0.67})
    private_get_deposit = privateGetDeposit = Entry[_Dict]('deposit', 'private', 'GET', {'cost': 0.67})
    private_get_deposits_coin_addresses = privateGetDepositsCoinAddresses = Entry[_List]('deposits/coin_addresses', 'private', 'GET', {'cost': 0.67})
    private_get_deposits_coin_address = privateGetDepositsCoinAddress = Entry[_Dict]('deposits/coin_address', 'private', 'GET', {'cost': 0.67})
    private_get_travel_rule_vasps = privateGetTravelRuleVasps = Entry[_List]('travel_rule/vasps', 'private', 'GET', {'cost': 0.67})
    private_get_status_wallet = privateGetStatusWallet = Entry[_List]('status/wallet', 'private', 'GET', {'cost': 0.67})
    private_get_api_keys = privateGetApiKeys = Entry[_List]('api_keys', 'private', 'GET', {'cost': 0.67})
    private_post_orders = privatePostOrders = Entry[_Dict]('orders', 'private', 'POST', {'cost': 2.5})
    private_post_orders_test = privatePostOrdersTest = Entry[_Dict]('orders/test', 'private', 'POST', {'cost': 2.5})
    private_post_orders_cancel_and_new = privatePostOrdersCancelAndNew = Entry[_Dict]('orders/cancel_and_new', 'private', 'POST', {'cost': 2.5})
    private_post_withdraws_coin = privatePostWithdrawsCoin = Entry[_Dict]('withdraws/coin', 'private', 'POST', {'cost': 0.67})
    private_post_withdraws_krw = privatePostWithdrawsKrw = Entry[_Dict]('withdraws/krw', 'private', 'POST', {'cost': 0.67})
    private_post_deposits_krw = privatePostDepositsKrw = Entry[_Dict]('deposits/krw', 'private', 'POST', {'cost': 0.67})
    private_post_deposits_generate_coin_address = privatePostDepositsGenerateCoinAddress = Entry[_Dict]('deposits/generate_coin_address', 'private', 'POST', {'cost': 0.67})
    private_post_travel_rule_deposit_uuid = privatePostTravelRuleDepositUuid = Entry[_Dict]('travel_rule/deposit/uuid', 'private', 'POST', {'cost': 0.67})
    private_post_travel_rule_deposit_txid = privatePostTravelRuleDepositTxid = Entry[_Dict]('travel_rule/deposit/txid', 'private', 'POST', {'cost': 0.67})
    private_delete_order = privateDeleteOrder = Entry[_Dict]('order', 'private', 'DELETE', {'cost': 0.67})
    private_delete_orders_open = privateDeleteOrdersOpen = Entry[_Dict]('orders/open', 'private', 'DELETE', {'cost': 40})
    private_delete_orders_uuids = privateDeleteOrdersUuids = Entry[_Dict]('orders/uuids', 'private', 'DELETE', {'cost': 0.67})
    private_delete_withdraws_coin = privateDeleteWithdrawsCoin = Entry[_Dict]('withdraws/coin', 'private', 'DELETE', {'cost': 0.67})
