from ccxt.base.types import Entry


class ImplicitAPI:
    public_get_openapi_market_symbols = publicGetOpenApiMarketSymbols = Entry('openApi/market/symbols', 'public', 'GET', {'cost': 1})
    public_get_openapi_market_currencies = publicGetOpenApiMarketCurrencies = Entry('openApi/market/currencies', 'public', 'GET', {'cost': 1})
    public_get_openapi_market_trade = publicGetOpenApiMarketTrade = Entry('openApi/market/trade', 'public', 'GET', {'cost': 1})
    public_get_openapi_market_depth = publicGetOpenApiMarketDepth = Entry('openApi/market/depth', 'public', 'GET', {'cost': 1})
    public_get_openapi_market_orderbook = publicGetOpenApiMarketOrderbook = Entry('openApi/market/orderbook', 'public', 'GET', {'cost': 1})
    public_get_openapi_market_kline = publicGetOpenApiMarketKline = Entry('openApi/market/kline', 'public', 'GET', {'cost': 1})
    public_get_openapi_market_24kline = publicGetOpenApiMarket24kline = Entry('openApi/market/24kline', 'public', 'GET', {'cost': 1})
    public_get_openapi_market_24kline_list = publicGetOpenApiMarket24klineList = Entry('openApi/market/24kline-list', 'public', 'GET', {'cost': 1})
    public_get_openapi_market_precision = publicGetOpenApiMarketPrecision = Entry('openApi/market/precision', 'public', 'GET', {'cost': 1})
    contract_get_openapi_contract_symbols = contractGetOpenApiContractSymbols = Entry('openApi/contract/symbols', 'contract', 'GET', {'cost': 1})
    contract_get_openapi_contract_trade = contractGetOpenApiContractTrade = Entry('openApi/contract/trade', 'contract', 'GET', {'cost': 1})
    contract_get_openapi_contract_depth = contractGetOpenApiContractDepth = Entry('openApi/contract/depth', 'contract', 'GET', {'cost': 1})
    contract_get_openapi_contract_kline = contractGetOpenApiContractKline = Entry('openApi/contract/kline', 'contract', 'GET', {'cost': 1})
    contract_get_openapi_contract_24kline = contractGetOpenApiContract24kline = Entry('openApi/contract/24kline', 'contract', 'GET', {'cost': 1})
    contract_get_openapi_contract_currentlist = contractGetOpenApiContractCurrentList = Entry('openApi/contract/currentList', 'contract', 'GET', {'cost': 1})
    private_get_openapi_wallet_list = privateGetOpenApiWalletList = Entry('openApi/wallet/list', 'private', 'GET', {'cost': 1})
    private_get_openapi_entrust_historylist = privateGetOpenApiEntrustHistoryList = Entry('openApi/entrust/historyList', 'private', 'GET', {'cost': 1})
    private_get_openapi_entrust_currentlist = privateGetOpenApiEntrustCurrentList = Entry('openApi/entrust/currentList', 'private', 'GET', {'cost': 1})
    private_get_openapi_futures_entrust_orderlist = privateGetOpenApiFuturesEntrustOrderList = Entry('openApi/futures/entrust/orderList', 'private', 'GET', {'cost': 1})
    private_get_openapi_futures_position_list = privateGetOpenApiFuturesPositionList = Entry('openApi/futures/position/list', 'private', 'GET', {'cost': 1})
    private_get_openapi_contract_walletlist_full = privateGetOpenApiContractWalletListFull = Entry('openApi/contract/walletList/full', 'private', 'GET', {'cost': 1})
    private_post_openapi_entrust_add = privatePostOpenApiEntrustAdd = Entry('openApi/entrust/add', 'private', 'POST', {'cost': 1})
    private_post_openapi_entrust_cancel = privatePostOpenApiEntrustCancel = Entry('openApi/entrust/cancel', 'private', 'POST', {'cost': 1})
    private_post_openapi_entrust_orderdetail = privatePostOpenApiEntrustOrderDetail = Entry('openApi/entrust/orderDetail', 'private', 'POST', {'cost': 1})
    private_post_openapi_entrust_ordertrade = privatePostOpenApiEntrustOrderTrade = Entry('openApi/entrust/orderTrade', 'private', 'POST', {'cost': 1})
    private_post_openapi_entrust_historydetail = privatePostOpenApiEntrustHistoryDetail = Entry('openApi/entrust/historyDetail', 'private', 'POST', {'cost': 1})
    private_post_openapi_wallet_detail = privatePostOpenApiWalletDetail = Entry('openApi/wallet/detail', 'private', 'POST', {'cost': 1})
    private_post_openapi_futures_entrust_add = privatePostOpenApiFuturesEntrustAdd = Entry('openApi/futures/entrust/add', 'private', 'POST', {'cost': 1})
    private_post_openapi_futures_entrust_cancel = privatePostOpenApiFuturesEntrustCancel = Entry('openApi/futures/entrust/cancel', 'private', 'POST', {'cost': 1})
    private_post_openapi_futures_entrust_orderdetail = privatePostOpenApiFuturesEntrustOrderDetail = Entry('openApi/futures/entrust/orderDetail', 'private', 'POST', {'cost': 1})
    private_post_openapi_futures_position_detail = privatePostOpenApiFuturesPositionDetail = Entry('openApi/futures/position/detail', 'private', 'POST', {'cost': 1})
    private_post_openapi_futures_position_setleverage = privatePostOpenApiFuturesPositionSetLeverage = Entry('openApi/futures/position/setLeverage', 'private', 'POST', {'cost': 1})
