from ccxt.base.types import Entry


class ImplicitAPI:
    public_get_openapi_market_symbols = publicGetOpenApiMarketSymbols = Entry('openApi/market/symbols', 'public', 'GET', {'cost': 1})
    public_get_openapi_market_currencies = publicGetOpenApiMarketCurrencies = Entry('openApi/market/currencies', 'public', 'GET', {'cost': 1})
    public_get_openapi_market_trade = publicGetOpenApiMarketTrade = Entry('openApi/market/trade', 'public', 'GET', {'cost': 1})
    public_get_openapi_market_depth = publicGetOpenApiMarketDepth = Entry('openApi/market/depth', 'public', 'GET', {'cost': 1})
    public_get_openapi_market_orderbook = publicGetOpenApiMarketOrderbook = Entry('openApi/market/orderbook', 'public', 'GET', {'cost': 1})
    public_get_openapi_market_kline = publicGetOpenApiMarketKline = Entry('openApi/market/kline', 'public', 'GET', {'cost': 1})
    public_get_openapi_market_24kline = publicGetOpenApiMarket24kline = Entry('openApi/market/24kline', 'public', 'GET', {'cost': 1})
    public_get_openapi_market_24kline_list = publicGetOpenApiMarket24klineList = Entry('openApi/market/24kline-list', 'public', 'GET', {'cost': 1})
    public_get_openapi_market_precision = publicGetOpenApiMarketPrecision = Entry('openApi/market/precision', 'public', 'GET', {'cost': 1})
    public_get_openapi_contract_symbols = publicGetOpenApiContractSymbols = Entry('openApi/contract/symbols', 'public', 'GET', {'cost': 1})
    public_get_openapi_contract_precision = publicGetOpenApiContractPrecision = Entry('openApi/contract/precision', 'public', 'GET', {'cost': 1})
    public_get_openapi_contract_trade = publicGetOpenApiContractTrade = Entry('openApi/contract/trade', 'public', 'GET', {'cost': 1})
    public_get_openapi_contract_depth = publicGetOpenApiContractDepth = Entry('openApi/contract/depth', 'public', 'GET', {'cost': 1})
    public_get_openapi_contract_kline = publicGetOpenApiContractKline = Entry('openApi/contract/kline', 'public', 'GET', {'cost': 1})
    public_get_openapi_contract_24kline = publicGetOpenApiContract24kline = Entry('openApi/contract/24kline', 'public', 'GET', {'cost': 1})
    private_get_openapi_wallet_list = privateGetOpenApiWalletList = Entry('openApi/wallet/list', 'private', 'GET', {'cost': 1})
    private_get_openapi_entrust_historylist = privateGetOpenApiEntrustHistoryList = Entry('openApi/entrust/historyList', 'private', 'GET', {'cost': 1})
    private_get_openapi_entrust_currentlist = privateGetOpenApiEntrustCurrentList = Entry('openApi/entrust/currentList', 'private', 'GET', {'cost': 1})
    private_get_openapi_entrust_status = privateGetOpenApiEntrustStatus = Entry('openApi/entrust/status', 'private', 'GET', {'cost': 1})
    private_get_openapi_contract_walletlist_full = privateGetOpenApiContractWalletListFull = Entry('openApi/contract/walletList/full', 'private', 'GET', {'cost': 1})
    private_get_openapi_contract_position = privateGetOpenApiContractPosition = Entry('openApi/contract/position', 'private', 'GET', {'cost': 1})
    private_get_openapi_contract_currentlist = privateGetOpenApiContractCurrentList = Entry('openApi/contract/currentList', 'private', 'GET', {'cost': 1})
    private_get_openapi_contract_getorderdetail = privateGetOpenApiContractGetOrderDetail = Entry('openApi/contract/getOrderDetail', 'private', 'GET', {'cost': 1})
    private_post_openapi_entrust_add = privatePostOpenApiEntrustAdd = Entry('openApi/entrust/add', 'private', 'POST', {'cost': 1})
    private_post_openapi_entrust_cancel = privatePostOpenApiEntrustCancel = Entry('openApi/entrust/cancel', 'private', 'POST', {'cost': 1})
    private_post_openapi_entrust_orderdetail = privatePostOpenApiEntrustOrderDetail = Entry('openApi/entrust/orderDetail', 'private', 'POST', {'cost': 1})
    private_post_openapi_entrust_ordertrade = privatePostOpenApiEntrustOrderTrade = Entry('openApi/entrust/orderTrade', 'private', 'POST', {'cost': 1})
    private_post_openapi_entrust_historydetail = privatePostOpenApiEntrustHistoryDetail = Entry('openApi/entrust/historyDetail', 'private', 'POST', {'cost': 1})
    private_post_openapi_wallet_detail = privatePostOpenApiWalletDetail = Entry('openApi/wallet/detail', 'private', 'POST', {'cost': 1})
    private_post_openapi_contract_cancel = privatePostOpenApiContractCancel = Entry('openApi/contract/cancel', 'private', 'POST', {'cost': 1})
    private_post_openapi_contract_add = privatePostOpenApiContractAdd = Entry('openApi/contract/add', 'private', 'POST', {'cost': 1})
