from ccxt.base.types import Entry
from typing import Any as PythonAny, Dict, List

_Dict = Dict[str, PythonAny]
_List = List[PythonAny]

class ImplicitAPI:
    public_get_depth_pair = publicGetDepthPair = Entry[_Dict]('depth/{pair}', 'public', 'GET', {'cost': 1})
    public_get_currencies_pair = publicGetCurrenciesPair = Entry[_List]('currencies/{pair}', 'public', 'GET', {'cost': 1})
    public_get_currencies_all = publicGetCurrenciesAll = Entry[_List]('currencies/all', 'public', 'GET', {'cost': 1})
    public_get_currency_pairs_pair = publicGetCurrencyPairsPair = Entry[_List]('currency_pairs/{pair}', 'public', 'GET', {'cost': 1})
    public_get_currency_pairs_all = publicGetCurrencyPairsAll = Entry[_List]('currency_pairs/all', 'public', 'GET', {'cost': 1})
    public_get_last_price_pair = publicGetLastPricePair = Entry[_Dict]('last_price/{pair}', 'public', 'GET', {'cost': 1})
    public_get_ticker_pair = publicGetTickerPair = Entry[_Dict]('ticker/{pair}', 'public', 'GET', {'cost': 1})
    public_get_trades_pair = publicGetTradesPair = Entry[_List]('trades/{pair}', 'public', 'GET', {'cost': 1})
    private_post_active_orders = privatePostActiveOrders = Entry[_Dict]('active_orders', 'private', 'POST', {'cost': 5})
    private_post_cancel_order = privatePostCancelOrder = Entry[_Dict]('cancel_order', 'private', 'POST', {'cost': 5})
    private_post_deposit_history = privatePostDepositHistory = Entry[_Dict]('deposit_history', 'private', 'POST', {'cost': 5})
    private_post_get_id_info = privatePostGetIdInfo = Entry[_Dict]('get_id_info', 'private', 'POST', {'cost': 5})
    private_post_get_info = privatePostGetInfo = Entry[_Dict]('get_info', 'private', 'POST', {'cost': 10})
    private_post_get_info2 = privatePostGetInfo2 = Entry[_Dict]('get_info2', 'private', 'POST', {'cost': 5})
    private_post_get_personal_info = privatePostGetPersonalInfo = Entry[_Dict]('get_personal_info', 'private', 'POST', {'cost': 5})
    private_post_trade = privatePostTrade = Entry[_Dict]('trade', 'private', 'POST', {'cost': 5})
    private_post_trade_history = privatePostTradeHistory = Entry[_Dict]('trade_history', 'private', 'POST', {'cost': 50})
    private_post_withdraw = privatePostWithdraw = Entry[_Dict]('withdraw', 'private', 'POST', {'cost': 5})
    private_post_withdraw_history = privatePostWithdrawHistory = Entry[_Dict]('withdraw_history', 'private', 'POST', {'cost': 5})
    ecapi_post_createinvoice = ecapiPostCreateInvoice = Entry[_Dict]('createInvoice', 'ecapi', 'POST', {'cost': 1})
    ecapi_post_getinvoice = ecapiPostGetInvoice = Entry[_Dict]('getInvoice', 'ecapi', 'POST', {'cost': 1})
    ecapi_post_getinvoiceidsbyordernumber = ecapiPostGetInvoiceIdsByOrderNumber = Entry[_Dict]('getInvoiceIdsByOrderNumber', 'ecapi', 'POST', {'cost': 1})
    ecapi_post_cancelinvoice = ecapiPostCancelInvoice = Entry[_Dict]('cancelInvoice', 'ecapi', 'POST', {'cost': 1})
    tlapi_post_get_positions = tlapiPostGetPositions = Entry[_Dict]('get_positions', 'tlapi', 'POST', {'cost': 66})
    tlapi_post_position_history = tlapiPostPositionHistory = Entry[_Dict]('position_history', 'tlapi', 'POST', {'cost': 66})
    tlapi_post_active_positions = tlapiPostActivePositions = Entry[_Dict]('active_positions', 'tlapi', 'POST', {'cost': 5})
    tlapi_post_create_position = tlapiPostCreatePosition = Entry[_Dict]('create_position', 'tlapi', 'POST', {'cost': 33})
    tlapi_post_change_position = tlapiPostChangePosition = Entry[_Dict]('change_position', 'tlapi', 'POST', {'cost': 33})
    tlapi_post_cancel_position = tlapiPostCancelPosition = Entry[_Dict]('cancel_position', 'tlapi', 'POST', {'cost': 33})
    fapi_get_groups_group_id = fapiGetGroupsGroupId = Entry[_List]('groups/{group_id}', 'fapi', 'GET', {'cost': 1})
    fapi_get_last_price_group_id_pair = fapiGetLastPriceGroupIdPair = Entry[_Dict]('last_price/{group_id}/{pair}', 'fapi', 'GET', {'cost': 1})
    fapi_get_ticker_group_id_pair = fapiGetTickerGroupIdPair = Entry[_Dict]('ticker/{group_id}/{pair}', 'fapi', 'GET', {'cost': 1})
    fapi_get_trades_group_id_pair = fapiGetTradesGroupIdPair = Entry[_List]('trades/{group_id}/{pair}', 'fapi', 'GET', {'cost': 1})
    fapi_get_depth_group_id_pair = fapiGetDepthGroupIdPair = Entry[_Dict]('depth/{group_id}/{pair}', 'fapi', 'GET', {'cost': 1})
