# -*- coding: utf-8 -*-

"""CCXT: CryptoCurrency eXchange Trading Library (Async)"""

# -----------------------------------------------------------------------------


# CCXT Pro exchanges (now this is mainly used for importing exchanged in WS tests)

from ccxt.ws.aax import aax                                               # noqa: F401
from ccxt.ws.ascendex import ascendex                                     # noqa: F401
from ccxt.ws.bequant import bequant                                       # noqa: F401
from ccxt.ws.bibox import bibox                                           # noqa: F401
from ccxt.ws.bigone import bigone                                         # noqa: F401
from ccxt.ws.binance import binance                                       # noqa: F401
from ccxt.ws.binancecoinm import binancecoinm                             # noqa: F401
from ccxt.ws.binanceus import binanceus                                   # noqa: F401
from ccxt.ws.binanceusdm import binanceusdm                               # noqa: F401
from ccxt.ws.bit2c import bit2c                                           # noqa: F401
from ccxt.ws.bitbank import bitbank                                       # noqa: F401
from ccxt.ws.bitbay import bitbay                                         # noqa: F401
from ccxt.ws.bitbns import bitbns                                         # noqa: F401
from ccxt.ws.bitcoincom import bitcoincom                                 # noqa: F401
from ccxt.ws.bitfinex import bitfinex                                     # noqa: F401
from ccxt.ws.bitfinex2 import bitfinex2                                   # noqa: F401
from ccxt.ws.bitflyer import bitflyer                                     # noqa: F401
from ccxt.ws.bitforex import bitforex                                     # noqa: F401
from ccxt.ws.bitget import bitget                                         # noqa: F401
from ccxt.ws.bithumb import bithumb                                       # noqa: F401
from ccxt.ws.bitmart import bitmart                                       # noqa: F401
from ccxt.ws.bitmex import bitmex                                         # noqa: F401
from ccxt.ws.bitopro import bitopro                                       # noqa: F401
from ccxt.ws.bitpanda import bitpanda                                     # noqa: F401
from ccxt.ws.bitrue import bitrue                                         # noqa: F401
from ccxt.ws.bitso import bitso                                           # noqa: F401
from ccxt.ws.bitstamp import bitstamp                                     # noqa: F401
from ccxt.ws.bitstamp1 import bitstamp1                                   # noqa: F401
from ccxt.ws.bittrex import bittrex                                       # noqa: F401
from ccxt.ws.bitvavo import bitvavo                                       # noqa: F401
from ccxt.ws.bkex import bkex                                             # noqa: F401
from ccxt.ws.bl3p import bl3p                                             # noqa: F401
from ccxt.ws.blockchaincom import blockchaincom                           # noqa: F401
from ccxt.ws.btcalpha import btcalpha                                     # noqa: F401
from ccxt.ws.btcbox import btcbox                                         # noqa: F401
from ccxt.ws.btcex import btcex                                           # noqa: F401
from ccxt.ws.btcmarkets import btcmarkets                                 # noqa: F401
from ccxt.ws.btctradeua import btctradeua                                 # noqa: F401
from ccxt.ws.btcturk import btcturk                                       # noqa: F401
from ccxt.ws.buda import buda                                             # noqa: F401
from ccxt.ws.bw import bw                                                 # noqa: F401
from ccxt.ws.bybit import bybit                                           # noqa: F401
from ccxt.ws.bytetrade import bytetrade                                   # noqa: F401
from ccxt.ws.cdax import cdax                                             # noqa: F401
from ccxt.ws.cex import cex                                               # noqa: F401
from ccxt.ws.coinbase import coinbase                                     # noqa: F401
from ccxt.ws.coinbaseprime import coinbaseprime                           # noqa: F401
from ccxt.ws.coinbasepro import coinbasepro                               # noqa: F401
from ccxt.ws.coincheck import coincheck                                   # noqa: F401
from ccxt.ws.coinex import coinex                                         # noqa: F401
from ccxt.ws.coinfalcon import coinfalcon                                 # noqa: F401
from ccxt.ws.coinmate import coinmate                                     # noqa: F401
from ccxt.ws.coinone import coinone                                       # noqa: F401
from ccxt.ws.coinspot import coinspot                                     # noqa: F401
from ccxt.ws.crex24 import crex24                                         # noqa: F401
from ccxt.ws.cryptocom import cryptocom                                   # noqa: F401
from ccxt.ws.currencycom import currencycom                               # noqa: F401
from ccxt.ws.delta import delta                                           # noqa: F401
from ccxt.ws.deribit import deribit                                       # noqa: F401
from ccxt.ws.digifinex import digifinex                                   # noqa: F401
from ccxt.ws.eqonex import eqonex                                         # noqa: F401
from ccxt.ws.exmo import exmo                                             # noqa: F401
from ccxt.ws.flowbtc import flowbtc                                       # noqa: F401
from ccxt.ws.fmfwio import fmfwio                                         # noqa: F401
from ccxt.ws.ftx import ftx                                               # noqa: F401
from ccxt.ws.ftxus import ftxus                                           # noqa: F401
from ccxt.ws.gate import gate                                             # noqa: F401
from ccxt.ws.gateio import gateio                                         # noqa: F401
from ccxt.ws.gemini import gemini                                         # noqa: F401
from ccxt.ws.hitbtc import hitbtc                                         # noqa: F401
from ccxt.ws.hitbtc3 import hitbtc3                                       # noqa: F401
from ccxt.ws.hollaex import hollaex                                       # noqa: F401
from ccxt.ws.huobi import huobi                                           # noqa: F401
from ccxt.ws.huobijp import huobijp                                       # noqa: F401
from ccxt.ws.huobipro import huobipro                                     # noqa: F401
from ccxt.ws.idex import idex                                             # noqa: F401
from ccxt.ws.independentreserve import independentreserve                 # noqa: F401
from ccxt.ws.indodax import indodax                                       # noqa: F401
from ccxt.ws.itbit import itbit                                           # noqa: F401
from ccxt.ws.kraken import kraken                                         # noqa: F401
from ccxt.ws.kucoin import kucoin                                         # noqa: F401
from ccxt.ws.kucoinfutures import kucoinfutures                           # noqa: F401
from ccxt.ws.kuna import kuna                                             # noqa: F401
from ccxt.ws.latoken import latoken                                       # noqa: F401
from ccxt.ws.lbank import lbank                                           # noqa: F401
from ccxt.ws.lbank2 import lbank2                                         # noqa: F401
from ccxt.ws.liquid import liquid                                         # noqa: F401
from ccxt.ws.luno import luno                                             # noqa: F401
from ccxt.ws.lykke import lykke                                           # noqa: F401
from ccxt.ws.mercado import mercado                                       # noqa: F401
from ccxt.ws.mexc import mexc                                             # noqa: F401
from ccxt.ws.mexc3 import mexc3                                           # noqa: F401
from ccxt.ws.ndax import ndax                                             # noqa: F401
from ccxt.ws.novadax import novadax                                       # noqa: F401
from ccxt.ws.oceanex import oceanex                                       # noqa: F401
from ccxt.ws.okcoin import okcoin                                         # noqa: F401
from ccxt.ws.okex import okex                                             # noqa: F401
from ccxt.ws.okex5 import okex5                                           # noqa: F401
from ccxt.ws.okx import okx                                               # noqa: F401
from ccxt.ws.paymium import paymium                                       # noqa: F401
from ccxt.ws.phemex import phemex                                         # noqa: F401
from ccxt.ws.poloniex import poloniex                                     # noqa: F401
from ccxt.ws.probit import probit                                         # noqa: F401
from ccxt.ws.qtrade import qtrade                                         # noqa: F401
from ccxt.ws.ripio import ripio                                           # noqa: F401
from ccxt.ws.stex import stex                                             # noqa: F401
from ccxt.ws.therock import therock                                       # noqa: F401
from ccxt.ws.tidebit import tidebit                                       # noqa: F401
from ccxt.ws.tidex import tidex                                           # noqa: F401
from ccxt.ws.timex import timex                                           # noqa: F401
from ccxt.ws.upbit import upbit                                           # noqa: F401
from ccxt.ws.wavesexchange import wavesexchange                           # noqa: F401
from ccxt.ws.wazirx import wazirx                                         # noqa: F401
from ccxt.ws.whitebit import whitebit                                     # noqa: F401
from ccxt.ws.woo import woo                                               # noqa: F401
from ccxt.ws.xena import xena                                             # noqa: F401
from ccxt.ws.yobit import yobit                                           # noqa: F401
from ccxt.ws.zaif import zaif                                             # noqa: F401
from ccxt.ws.zb import zb                                                 # noqa: F401
from ccxt.ws.zipmex import zipmex                                         # noqa: F401
from ccxt.ws.zonda import zonda                                           # noqa: F401

