[tox]
envlist = py{310,311,312,313,314}
skipsdist = True
skip_missing_interpreters = False
ignore_basepython_conflict = True

[testenv]
basepython = python3
sitepackages = True
setenv =
    PYTHONPATH = {toxinidir}:{toxinidir}
deps =
    pip
    setuptools
    wheel
    aiohttp
    cryptography
    requests
    coincurve
commands =
    pip install -e {toxinidir}/..
    python ccxt/test/tests_init.py --idTests
    python ccxt/test/tests_init.py --sync --idTests

[testenv:qa]
allowlist_externals = ruff
changedir = {toxinidir}
commands = ruff ./ccxt/
deps = {toxinidir}/..[qa]

[testenv:type]
allowlist_externals = mypy
changedir = {toxinidir}
commands = mypy ./ccxt/
deps = {toxinidir}/..[type]
