#!/bin/bash

# Check if changes are relevant
CHECK_DIRECTORIES="ts/ python/ccxt/ php/ build/"

MODIFIED_FILES=$(git diff --name-only upstream/master)
HAS_RELEVANT_CHANGES=false

for DIR in $CHECK_DIRECTORIES; do
    if echo "$MODIFIED_FILES" | grep -qE "^$DIR"; then
        HAS_RELEVANT_CHANGES=true
        break
    fi
done

function check_exit_status() {
    if [ $1 -ne 0 ]; then
        echo "$2 : Linting failed, check the files..."
        exit 1
    fi
}

if [ "$HAS_RELEVANT_CHANGES" = "false" ]; then
    echo "No relevant changes, skipping checks..."
    exit 0
fi

# Lint TS files
MODIFIED_TS_FILES=$(git diff --name-only upstream/master -- 'ts/**/*.ts')

ESLINT_EXIT_CODE=0
# Run eslint on the modified files
if [ "$MODIFIED_TS_FILES" != "" ]; then
    eslint $MODIFIED_TS_FILES
    ESLINT_EXIT_CODE=$?
fi
check_exit_status $ESLINT_EXIT_CODE "ESLint"

# Run python linting
npm run check-python-ruff
check_exit_status $? "Python"

# Run PHP linting
npm run check-php-syntax
check_exit_status $? "PHP"

echo "All checks passed, pushing..."
exit 0