import alpacaRest from '../alpaca.js';
import { Int } from '../base/types.js';
import Client from '../base/ws/Client.js';
export default class alpaca extends alpacaRest {
    describe(): any;
    watchTicker(symbol: string, params?: {}): Promise<any>;
    handleTicker(client: Client, message: any): void;
    parseTicker(ticker: any, market?: any): import("../base/types.js").Ticker;
    watchOHLCV(symbol: string, timeframe?: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    handleOHLCV(client: Client, message: any): void;
    watchOrderBook(symbol: string, limit?: Int, params?: {}): Promise<any>;
    handleOrderBook(client: Client, message: any): void;
    handleDelta(bookside: any, delta: any): void;
    handleDeltas(bookside: any, deltas: any): void;
    watchTrades(symbol: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    handleTrades(client: Client, message: any): void;
    watchMyTrades(symbol?: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    watchOrders(symbol?: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    handleTradeUpdate(client: Client, message: any): void;
    handleOrder(client: Client, message: any): void;
    handleMyTrade(client: Client, message: any): void;
    parseMyTrade(trade: any, market?: any): import("../base/types.js").Trade;
    authenticate(url: any, params?: {}): Promise<any>;
    handleErrorMessage(client: Client, message: any): void;
    handleConnected(client: Client, message: any): any;
    handleCryptoMessage(client: Client, message: any): any;
    handleTradingMessage(client: Client, message: any): void;
    handleMessage(client: Client, message: any): any;
    handleAuthenticate(client: Client, message: any): void;
    handleSubscription(client: Client, message: any): any;
}
