import bitmartRest from '../bitmart.js';
import { Int, Market, Str, Strings } from '../base/types.js';
import Client from '../base/ws/Client.js';
export default class bitmart extends bitmartRest {
    describe(): any;
    subscribe(channel: any, symbol: any, type: any, params?: {}): Promise<any>;
    watchBalance(params?: {}): Promise<any>;
    setBalanceCache(client: Client, type: any): any;
    loadBalanceSnapshot(client: any, messageHash: any, type: any): Promise<void>;
    handleBalance(client: Client, message: any): void;
    watchTrades(symbol: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    watchTicker(symbol: string, params?: {}): Promise<any>;
    watchTickers(symbols?: Strings, params?: {}): Promise<any>;
    watchOrders(symbol?: Str, since?: Int, limit?: Int, params?: {}): Promise<any>;
    handleOrders(client: Client, message: any): void;
    parseWsOrder(order: any, market?: Market): import("../base/types.js").Order;
    parseWsOrderStatus(statusId: any): string;
    parseWsOrderSide(sideId: any): string;
    watchPositions(symbols?: Strings, since?: Int, limit?: Int, params?: {}): Promise<any>;
    handlePositions(client: Client, message: any): void;
    parseWsPosition(position: any, market?: Market): import("../base/types.js").Position;
    handleTrade(client: Client, message: any): any;
    parseWsTrade(trade: any, market?: Market): import("../base/types.js").Trade;
    handleTicker(client: Client, message: any): any;
    parseWsSwapTicker(ticker: any, market?: Market): import("../base/types.js").Ticker;
    watchOHLCV(symbol: string, timeframe?: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    handleOHLCV(client: Client, message: any): void;
    watchOrderBook(symbol: string, limit?: Int, params?: {}): Promise<any>;
    handleDelta(bookside: any, delta: any): void;
    handleDeltas(bookside: any, deltas: any): void;
    handleOrderBookMessage(client: Client, message: any, orderbook: any): any;
    handleOrderBook(client: Client, message: any): void;
    authenticate(type: any, params?: {}): Promise<any>;
    handleSubscriptionStatus(client: Client, message: any): any;
    handleAuthenticate(client: Client, message: any): void;
    handleErrorMessage(client: Client, message: any): boolean;
    handleMessage(client: Client, message: any): any;
}
