import coinbaseproRest from '../coinbasepro.js';
export default class coinbasepro extends coinbaseproRest {
    describe(): any;
    authenticate(): {
        timestamp: number;
        key: string;
        signature: any;
        passphrase: any;
    };
    subscribe(name: any, symbol: any, messageHashStart: any, params?: {}): Promise<any>;
    watchTicker(symbol: any, params?: {}): Promise<any>;
    watchTrades(symbol: any, since?: any, limit?: any, params?: {}): Promise<any>;
    watchMyTrades(symbol?: string, since?: any, limit?: any, params?: {}): Promise<any>;
    watchOrders(symbol?: string, since?: any, limit?: any, params?: {}): Promise<any>;
    watchOrderBook(symbol: any, limit?: any, params?: {}): Promise<any>;
    handleTrade(client: any, message: any): any;
    handleMyTrade(client: any, message: any): any;
    parseWsTrade(trade: any): import("../base/types.js").Trade;
    parseWsOrderStatus(status: any): string;
    handleOrder(client: any, message: any): void;
    parseWsOrder(order: any): {
        info: any;
        symbol: any;
        id: string;
        clientOrderId: string;
        timestamp: number;
        datetime: string;
        lastTradeTimestamp: any;
        type: string;
        timeInForce: any;
        postOnly: any;
        side: string;
        price: number;
        stopPrice: any;
        triggerPrice: any;
        amount: number;
        cost: any;
        average: any;
        filled: any;
        remaining: number;
        status: string;
        fee: any;
        trades: any;
    };
    handleTicker(client: any, message: any): any;
    parseTicker(ticker: any, market?: any): import("../base/types.js").Ticker | {
        symbol: any;
        timestamp: number;
        datetime: string;
        high: number;
        low: number;
        bid: number;
        bidVolume: number;
        ask: number;
        askVolume: number;
        vwap: any;
        open: number;
        close: number;
        last: number;
        previousClose: any;
        change: any;
        percentage: any;
        average: any;
        baseVolume: number;
        quoteVolume: any;
        info: any;
    };
    handleDelta(bookside: any, delta: any): void;
    handleDeltas(bookside: any, deltas: any): void;
    handleOrderBook(client: any, message: any): void;
    handleSubscriptionStatus(client: any, message: any): any;
    handleMessage(client: any, message: any): any;
}
