import hitbtcRest from '../hitbtc.js';
import { Int, OHLCV, OrderSide, OrderType, Strings } from '../base/types.js';
import Client from '../base/ws/Client.js';
import { Str, Trade } from '../base/types';
export default class hitbtc extends hitbtcRest {
    describe(): any;
    authenticate(): Promise<any>;
    subscribePublic(name: string, symbols?: Strings, params?: {}): Promise<any>;
    subscribePrivate(name: string, symbol?: Str, params?: {}): Promise<any>;
    tradeRequest(name: string, params?: {}): Promise<any>;
    watchOrderBook(symbol: string, limit?: Int, params?: {}): Promise<any>;
    handleOrderBook(client: Client, message: any): void;
    handleDelta(bookside: any, delta: any): void;
    handleDeltas(bookside: any, deltas: any): void;
    watchTicker(symbol: string, params?: {}): Promise<any>;
    watchTickers(symbols?: any, params?: {}): Promise<any>;
    handleTicker(client: Client, message: any): any;
    parseWsTicker(ticker: any, market?: any): import("../base/types.js").Ticker;
    watchTrades(symbol: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    handleTrades(client: Client, message: any): any;
    parseWsTrades(trades: any, market?: object, since?: Int, limit?: Int, params?: {}): Trade[];
    parseWsTrade(trade: any, market?: any): Trade;
    watchOHLCV(symbol: string, timeframe?: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    handleOHLCV(client: Client, message: any): any;
    parseWsOHLCV(ohlcv: any, market?: any): OHLCV;
    watchOrders(symbol?: Str, since?: Int, limit?: Int, params?: {}): Promise<any>;
    handleOrder(client: Client, message: any): any;
    handleOrderHelper(client: Client, message: any, order: any): void;
    parseWsOrderTrade(trade: any, market?: any): Trade;
    parseWsOrder(order: any, market?: any): import("../base/types.js").Order;
    watchBalance(params?: {}): Promise<any>;
    createOrderWs(symbol: string, type: OrderType, side: OrderSide, amount: any, price?: any, params?: {}): Promise<any>;
    cancelOrderWs(id: string, symbol?: Str, params?: {}): Promise<any>;
    cancelAllOrdersWs(symbol?: Str, params?: {}): Promise<any>;
    fetchOpenOrdersWs(symbol?: Str, since?: Int, limit?: Int, params?: {}): Promise<any>;
    handleBalance(client: Client, message: any): void;
    handleNotification(client: Client, message: any): any;
    handleOrderRequest(client: Client, message: any): any;
    handleMessage(client: Client, message: any): void;
    handleAuthenticate(client: Client, message: any): any;
    handleError(client: Client, message: any): any;
}
