import huobiRest from '../huobi.js';
export default class huobi extends huobiRest {
    describe(): any;
    requestId(): any;
    watchTicker(symbol: any, params?: {}): Promise<any>;
    handleTicker(client: any, message: any): any;
    watchTrades(symbol: any, since?: any, limit?: any, params?: {}): Promise<any>;
    handleTrades(client: any, message: any): any;
    watchOHLCV(symbol: any, timeframe?: string, since?: any, limit?: any, params?: {}): Promise<any>;
    handleOHLCV(client: any, message: any): void;
    watchOrderBook(symbol: any, limit?: any, params?: {}): Promise<any>;
    handleOrderBookSnapshot(client: any, message: any, subscription: any): void;
    watchOrderBookSnapshot(client: any, message: any, subscription: any): Promise<any>;
    handleDelta(bookside: any, delta: any): void;
    handleDeltas(bookside: any, deltas: any): void;
    handleOrderBookMessage(client: any, message: any, orderbook: any): any;
    handleOrderBook(client: any, message: any): void;
    handleOrderBookSubscription(client: any, message: any, subscription: any): void;
    watchMyTrades(symbol?: string, since?: any, limit?: any, params?: {}): Promise<any>;
    getOrderChannelAndMessageHash(type: any, subType: any, market?: any, params?: {}): any[];
    watchOrders(symbol?: string, since?: any, limit?: any, params?: {}): Promise<any>;
    handleOrder(client: any, message: any): void;
    parseWsOrder(order: any, market?: any): any;
    parseOrderTrade(trade: any, market?: any): import("../base/types.js").Trade;
    watchBalance(params?: {}): Promise<any>;
    handleBalance(client: any, message: any): void;
    handleSubscriptionStatus(client: any, message: any): any;
    handleSystemStatus(client: any, message: any): any;
    handleSubject(client: any, message: any): any;
    pong(client: any, message: any): Promise<void>;
    handlePing(client: any, message: any): void;
    handleAuthenticate(client: any, message: any): any;
    handleErrorMessage(client: any, message: any): any;
    handleMessage(client: any, message: any): void;
    handleMyTrade(client: any, message: any, extendParams?: {}): void;
    parseWsTrade(trade: any): import("../base/types.js").Trade;
    getUrlByMarketType(type: any, isLinear?: boolean, isPrivate?: boolean): any;
    subscribePublic(url: any, symbol: any, messageHash: any, method?: any, params?: {}): Promise<any>;
    subscribePrivate(channel: any, messageHash: any, type: any, subtype: any, params?: {}, subscriptionParams?: {}): Promise<any>;
    authenticate(params?: {}): Promise<any>;
}
