import mexcRest from '../mexc.js';
import { Int } from '../base/types.js';
export default class mexc extends mexcRest {
    describe(): any;
    watchTicker(symbol: string, params?: {}): Promise<any>;
    handleTicker(client: any, message: any): void;
    parseWsTicker(ticker: any, market?: any): import("../base/types.js").Ticker;
    watchSpotPublic(channel: any, messageHash: any, params?: {}): Promise<any>;
    watchSpotPrivate(channel: any, messageHash: any, params?: {}): Promise<any>;
    watchSwapPublic(channel: any, messageHash: any, requestParams: any, params?: {}): Promise<any>;
    watchSwapPrivate(messageHash: any, params?: {}): Promise<any>;
    watchOHLCV(symbol: string, timeframe?: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    handleOHLCV(client: any, message: any): void;
    parseWsOHLCV(ohlcv: any, market?: any): number[];
    watchOrderBook(symbol: string, limit?: Int, params?: {}): Promise<any>;
    handleOrderBookSubscription(client: any, message: any): void;
    getCacheIndex(orderbook: any, cache: any): any;
    handleOrderBook(client: any, message: any): void;
    handleBooksideDelta(bookside: any, bidasks: any): void;
    handleDelta(orderbook: any, delta: any): void;
    watchTrades(symbol: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    handleTrades(client: any, message: any): void;
    watchMyTrades(symbol?: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    handleMyTrade(client: any, message: any, subscription?: any): void;
    parseWsTrade(trade: any, market?: any): import("../base/types.js").Trade;
    watchOrders(symbol?: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    handleOrder(client: any, message: any): void;
    parseWsOrder(order: any, market?: any): any;
    parseWsOrderStatus(status: any, market?: any): string;
    parseWsOrderType(type: any): string;
    parseWsTimeInForce(timeInForce: any): string;
    watchBalance(params?: {}): Promise<any>;
    handleBalance(client: any, message: any): void;
    authenticate(subscriptionHash: any, params?: {}): Promise<string>;
    keepAliveListenKey(listenKey: any, params?: {}): Promise<void>;
    handlePong(client: any, message: any): any;
    handleSubscriptionStatus(client: any, message: any): any;
    handleMessage(client: any, message: any): any;
    ping(client: any): {
        method: string;
    };
}
