import phemexRest from '../phemex.js';
import { Int, Str } from '../base/types.js';
import Client from '../base/ws/Client.js';
export default class phemex extends phemexRest {
    describe(): undefined;
    fromEn(en: any, scale: any): string | undefined;
    fromEp(ep: any, market?: undefined): any;
    fromEv(ev: any, market?: undefined): any;
    fromEr(er: any, market?: undefined): any;
    requestId(): any;
    parseSwapTicker(ticker: any, market?: undefined): {
        symbol: any;
        timestamp: Int;
        datetime: string | undefined;
        high: number;
        low: number;
        bid: undefined;
        bidVolume: undefined;
        ask: undefined;
        askVolume: undefined;
        vwap: undefined;
        open: number;
        close: number;
        last: number;
        previousClose: undefined;
        change: undefined;
        percentage: undefined;
        average: undefined;
        baseVolume: number;
        quoteVolume: number;
        info: any;
    };
    parsePerpetualTicker(ticker: any, market?: undefined): {
        symbol: any;
        timestamp: undefined;
        datetime: undefined;
        high: number;
        low: number;
        bid: undefined;
        bidVolume: undefined;
        ask: undefined;
        askVolume: undefined;
        vwap: undefined;
        open: number;
        close: number;
        last: number;
        previousClose: undefined;
        change: undefined;
        percentage: undefined;
        average: undefined;
        baseVolume: number;
        quoteVolume: number;
        info: any;
    };
    handleTicker(client: Client, message: any): void;
    watchBalance(params?: {}): Promise<any>;
    handleBalance(type: any, client: any, message: any): void;
    handleTrades(client: Client, message: any): void;
    handleOHLCV(client: Client, message: any): void;
    watchTicker(symbol: string, params?: {}): Promise<any>;
    watchTrades(symbol: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    watchOrderBook(symbol: string, limit?: Int, params?: {}): Promise<any>;
    watchOHLCV(symbol: string, timeframe?: string, since?: Int, limit?: Int, params?: {}): Promise<any>;
    handleDelta(bookside: any, delta: any, market?: undefined): void;
    handleDeltas(bookside: any, deltas: any, market?: undefined): void;
    handleOrderBook(client: Client, message: any): void;
    watchMyTrades(symbol?: Str, since?: Int, limit?: Int, params?: {}): Promise<any>;
    handleMyTrades(client: Client, message: any): void;
    watchOrders(symbol?: Str, since?: Int, limit?: Int, params?: {}): Promise<any>;
    handleOrders(client: Client, message: any): void;
    parseWSSwapOrder(order: any, market?: undefined): import("../base/types.js").Order;
    handleMessage(client: Client, message: any): any;
    handleAuthenticate(client: Client, message: any): void;
    subscribePrivate(type: any, messageHash: any, params?: {}): Promise<any>;
    authenticate(params?: {}): Promise<any>;
}
