import poloniexfuturesRest from '../poloniexfutures.js';
import type { Int, Str, OrderBook, Order, Trade, Ticker, Balances } from '../base/types.js';
import Client from '../base/ws/Client.js';
export default class poloniexfutures extends poloniexfuturesRest {
    describe(): any;
    negotiate(privateChannel: any, params?: {}): Promise<any>;
    negotiateHelper(privateChannel: any, params?: {}): Promise<string>;
    requestId(): any;
    subscribe(name: string, isPrivate: boolean, symbol?: Str, subscription?: any, params?: {}): Promise<any>;
    onClose(client: any, error: any): void;
    stream(url: any, subscriptionHash: any): Promise<string>;
    handleOrderBookSubscription(client: Client, message: any, subscription: any): void;
    handleSubscriptionStatus(client: Client, message: any): any;
    handleNewStream(client: Client, message: any, subscription: any): void;
    watchTicker(symbol: string, params?: {}): Promise<Ticker>;
    watchTrades(symbol: string, since?: Int, limit?: Int, params?: {}): Promise<Trade[]>;
    watchOrderBook(symbol: string, limit?: Int, params?: {}): Promise<OrderBook>;
    watchOrders(symbol?: Str, since?: Int, limit?: Int, params?: {}): Promise<Order[]>;
    watchBalance(params?: {}): Promise<Balances>;
    handleTrade(client: Client, message: any): any;
    parseWsTrade(trade: any, market?: any): Trade;
    parseWsOrderTrade(trade: any, market?: any): Trade;
    handleOrder(client: Client, message: any): any;
    parseOrderStatus(status: string, type: string): string;
    parseWsOrder(order: any, market?: any): Order;
    handleTicker(client: Client, message: any): any;
    handleL3OrderBook(client: Client, message: any): void;
    handleLevel2(client: Client, message: any): void;
    handleL2OrderBook(client: Client, message: any): void;
    handeL2Snapshot(client: Client, message: any): void;
    getSymbolFromTopic(topic: string): string;
    getCacheIndex(orderbook: any, cache: any): any;
    handleDelta(orderbook: any, delta: any): void;
    handleBalance(client: Client, message: any): any;
    parseWsBalance(response: any): Balances;
    handleSystemStatus(client: Client, message: any): any;
    handleSubject(client: Client, message: any): void;
    ping(client: Client): {
        id: any;
        type: string;
    };
    handlePong(client: Client, message: any): any;
    handleErrorMessage(client: Client, message: any): void;
    handleMessage(client: Client, message: any): void;
    handleAuthenticate(client: any, message: any): any;
}
