package models

import (
	"time"
)

// Instrument Tradeable Contracts, Indices, and History
type Instrument struct {
	AskPrice                       float64   `json:"askPrice,omitempty"`
	BankruptLimitDownPrice         float64   `json:"bankruptLimitDownPrice,omitempty"`
	BankruptLimitUpPrice           float64   `json:"bankruptLimitUpPrice,omitempty"`
	BidPrice                       float64   `json:"bidPrice,omitempty"`
	BuyLeg                         string    `json:"buyLeg,omitempty"`
	CalcInterval                   time.Time `json:"calcInterval,omitempty"`
	Capped                         bool      `json:"capped,omitempty"`
	ClosingTimestamp               time.Time `json:"closingTimestamp,omitempty"`
	Deleverage                     bool      `json:"deleverage,omitempty"`
	Expiry                         time.Time `json:"expiry,omitempty"`
	FairBasis                      float64   `json:"fairBasis,omitempty"`
	FairBasisRate                  float64   `json:"fairBasisRate,omitempty"`
	FairMethod                     string    `json:"fairMethod,omitempty"`
	FairPrice                      float64   `json:"fairPrice,omitempty"`
	ForeignNotional24h             float64   `json:"foreignNotional24h,omitempty"`
	Front                          time.Time `json:"front,omitempty"`
	FundingBaseSymbol              string    `json:"fundingBaseSymbol,omitempty"`
	FundingInterval                time.Time `json:"fundingInterval,omitempty"`
	FundingPremiumSymbol           string    `json:"fundingPremiumSymbol,omitempty"`
	FundingQuoteSymbol             string    `json:"fundingQuoteSymbol,omitempty"`
	FundingRate                    float64   `json:"fundingRate,omitempty"`
	FundingTimestamp               time.Time `json:"fundingTimestamp,omitempty"`
	HasLiquidity                   bool      `json:"hasLiquidity,omitempty"`
	HighPrice                      float64   `json:"highPrice,omitempty"`
	HomeNotional24h                float64   `json:"homeNotional24h,omitempty"`
	ImpactAskPrice                 float64   `json:"impactAskPrice,omitempty"`
	ImpactBidPrice                 float64   `json:"impactBidPrice,omitempty"`
	ImpactMidPrice                 float64   `json:"impactMidPrice,omitempty"`
	IndicativeFundingRate          float64   `json:"indicativeFundingRate,omitempty"`
	IndicativeSettlePrice          float64   `json:"indicativeSettlePrice,omitempty"`
	IndicativeTaxRate              float64   `json:"indicativeTaxRate,omitempty"`
	InitMargin                     float64   `json:"initMargin,omitempty"`
	InsuranceFee                   float64   `json:"insuranceFee,omitempty"`
	InverseLeg                     string    `json:"inverseLeg,omitempty"`
	IsInverse                      bool      `json:"isInverse,omitempty"`
	IsQuanto                       bool      `json:"isQuanto,omitempty"`
	LastChangePcnt                 float64   `json:"lastChangePcnt,omitempty"`
	LastPrice                      float64   `json:"lastPrice,omitempty"`
	LastPriceProtected             float64   `json:"lastPriceProtected,omitempty"`
	LastTickDirection              string    `json:"lastTickDirection,omitempty"`
	Limit                          float64   `json:"limit,omitempty"`
	LimitDownPrice                 float64   `json:"limitDownPrice,omitempty"`
	LimitUpPrice                   float64   `json:"limitUpPrice,omitempty"`
	Listing                        time.Time `json:"listing,omitempty"`
	LotSize                        int64     `json:"lotSize,omitempty"`
	LowPrice                       float64   `json:"lowPrice,omitempty"`
	MaintMargin                    float64   `json:"maintMargin,omitempty"`
	MakerFee                       float64   `json:"makerFee,omitempty"`
	MarkMethod                     string    `json:"markMethod,omitempty"`
	MarkPrice                      float64   `json:"markPrice,omitempty"`
	MaxOrderQty                    int64     `json:"maxOrderQty,omitempty"`
	MaxPrice                       float64   `json:"maxPrice,omitempty"`
	MidPrice                       float64   `json:"midPrice,omitempty"`
	Multiplier                     int64     `json:"multiplier,omitempty"`
	OpenInterest                   int64     `json:"openInterest,omitempty"`
	OpenValue                      int64     `json:"openValue,omitempty"`
	OpeningTimestamp               time.Time `json:"openingTimestamp,omitempty"`
	OptionMultiplier               float64   `json:"optionMultiplier,omitempty"`
	OptionStrikePcnt               float64   `json:"optionStrikePcnt,omitempty"`
	OptionStrikePrice              float64   `json:"optionStrikePrice,omitempty"`
	OptionStrikeRound              float64   `json:"optionStrikeRound,omitempty"`
	OptionUnderlyingPrice          float64   `json:"optionUnderlyingPrice,omitempty"`
	PositionCurrency               string    `json:"positionCurrency,omitempty"`
	PrevClosePrice                 float64   `json:"prevClosePrice,omitempty"`
	PrevPrice24h                   float64   `json:"prevPrice24h,omitempty"`
	PrevTotalTurnover              int64     `json:"prevTotalTurnover,omitempty"`
	PrevTotalVolume                int64     `json:"prevTotalVolume,omitempty"`
	PublishInterval                time.Time `json:"publishInterval,omitempty"`
	PublishTime                    time.Time `json:"publishTime,omitempty"`
	QuoteCurrency                  string    `json:"quoteCurrency,omitempty"`
	QuoteToSettleMultiplier        int64     `json:"quoteToSettleMultiplier,omitempty"`
	RebalanceInterval              time.Time `json:"rebalanceInterval,omitempty"`
	RebalanceTimestamp             time.Time `json:"rebalanceTimestamp,omitempty"`
	Reference                      string    `json:"reference,omitempty"`
	ReferenceSymbol                string    `json:"referenceSymbol,omitempty"`
	RelistInterval                 time.Time `json:"relistInterval,omitempty"`
	RiskLimit                      int64     `json:"riskLimit,omitempty"`
	RiskStep                       int64     `json:"riskStep,omitempty"`
	RootSymbol                     string    `json:"rootSymbol,omitempty"`
	SellLeg                        string    `json:"sellLeg,omitempty"`
	SessionInterval                time.Time `json:"sessionInterval,omitempty"`
	SettlCurrency                  string    `json:"settlCurrency,omitempty"`
	Settle                         time.Time `json:"settle,omitempty"`
	SettledPrice                   float64   `json:"settledPrice,omitempty"`
	SettlementFee                  float64   `json:"settlementFee,omitempty"`
	State                          string    `json:"state,omitempty"`
	Symbol                         string    `json:"symbol"`
	TakerFee                       float64   `json:"takerFee,omitempty"`
	Taxed                          bool      `json:"taxed,omitempty"`
	TickSize                       float64   `json:"tickSize,omitempty"`
	Timestamp                      time.Time `json:"timestamp,omitempty"`
	TotalTurnover                  int64     `json:"totalTurnover,omitempty"`
	TotalVolume                    int64     `json:"totalVolume,omitempty"`
	Turnover                       int64     `json:"turnover,omitempty"`
	Turnover24h                    int64     `json:"turnover24h,omitempty"`
	Typ                            string    `json:"typ,omitempty"`
	Underlying                     string    `json:"underlying,omitempty"`
	UnderlyingSymbol               string    `json:"underlyingSymbol,omitempty"`
	UnderlyingToPositionMultiplier int64     `json:"underlyingToPositionMultiplier,omitempty"`
	UnderlyingToSettleMultiplier   int64     `json:"underlyingToSettleMultiplier,omitempty"`
	Volume                         int64     `json:"volume,omitempty"`
	Volume24h                      int64     `json:"volume24h,omitempty"`
	Vwap                           float64   `json:"vwap,omitempty"`
}
