package models

import "time"

// Position Summary of Open and Closed Positions
type Position struct {
	Account              int64     `json:"account"`
	AvgCostPrice         float64   `json:"avgCostPrice,omitempty"`
	AvgEntryPrice        float64   `json:"avgEntryPrice,omitempty"`
	BankruptPrice        float64   `json:"bankruptPrice,omitempty"`
	BreakEvenPrice       float64   `json:"breakEvenPrice,omitempty"`
	Commission           float64   `json:"commission,omitempty"`
	CrossMargin          bool      `json:"crossMargin,omitempty"`
	Currency             string    `json:"currency"`
	CurrentComm          int64     `json:"currentComm,omitempty"`
	CurrentCost          int64     `json:"currentCost,omitempty"`
	CurrentQty           int64     `json:"currentQty,omitempty"`
	CurrentTimestamp     time.Time `json:"currentTimestamp,omitempty"`
	DeleveragePercentile float64   `json:"deleveragePercentile,omitempty"`
	ExecBuyCost          int64     `json:"execBuyCost,omitempty"`
	ExecBuyQty           int64     `json:"execBuyQty,omitempty"`
	ExecComm             int64     `json:"execComm,omitempty"`
	ExecCost             int64     `json:"execCost,omitempty"`
	ExecQty              int64     `json:"execQty,omitempty"`
	ExecSellCost         int64     `json:"execSellCost,omitempty"`
	ExecSellQty          int64     `json:"execSellQty,omitempty"`
	ForeignNotional      float64   `json:"foreignNotional,omitempty"`
	GrossExecCost        int64     `json:"grossExecCost,omitempty"`
	GrossOpenCost        int64     `json:"grossOpenCost,omitempty"`
	GrossOpenPremium     int64     `json:"grossOpenPremium,omitempty"`
	HomeNotional         float64   `json:"homeNotional,omitempty"`
	IndicativeTax        int64     `json:"indicativeTax,omitempty"`
	IndicativeTaxRate    float64   `json:"indicativeTaxRate,omitempty"`
	InitMargin           int64     `json:"initMargin,omitempty"`
	InitMarginReq        float64   `json:"initMarginReq,omitempty"`
	IsOpen               bool      `json:"isOpen,omitempty"`
	LastPrice            float64   `json:"lastPrice,omitempty"`
	LastValue            int64     `json:"lastValue,omitempty"`
	Leverage             float64   `json:"leverage,omitempty"`
	LiquidationPrice     float64   `json:"liquidationPrice,omitempty"`
	LongBankrupt         int64     `json:"longBankrupt,omitempty"`
	MaintMargin          int64     `json:"maintMargin,omitempty"`
	MaintMarginReq       float64   `json:"maintMarginReq,omitempty"`
	MarginCallPrice      float64   `json:"marginCallPrice,omitempty"`
	MarkPrice            float64   `json:"markPrice,omitempty"`
	MarkValue            int64     `json:"markValue,omitempty"`
	OpenOrderBuyCost     int64     `json:"openOrderBuyCost,omitempty"`
	OpenOrderBuyPremium  int64     `json:"openOrderBuyPremium,omitempty"`
	OpenOrderBuyQty      int64     `json:"openOrderBuyQty,omitempty"`
	OpenOrderSellCost    int64     `json:"openOrderSellCost,omitempty"`
	OpenOrderSellPremium int64     `json:"openOrderSellPremium,omitempty"`
	OpenOrderSellQty     int64     `json:"openOrderSellQty,omitempty"`
	OpeningComm          int64     `json:"openingComm,omitempty"`
	OpeningCost          int64     `json:"openingCost,omitempty"`
	OpeningQty           int64     `json:"openingQty,omitempty"`
	OpeningTimestamp     time.Time `json:"openingTimestamp,omitempty"`
	PosAllowance         int64     `json:"posAllowance,omitempty"`
	PosComm              int64     `json:"posComm,omitempty"`
	PosCost              int64     `json:"posCost,omitempty"`
	PosCost2             int64     `json:"posCost2,omitempty"`
	PosCross             int64     `json:"posCross,omitempty"`
	PosInit              int64     `json:"posInit,omitempty"`
	PosLoss              int64     `json:"posLoss,omitempty"`
	PosMaint             int64     `json:"posMaint,omitempty"`
	PosMargin            int64     `json:"posMargin,omitempty"`
	PosState             string    `json:"posState,omitempty"`
	PrevClosePrice       float64   `json:"prevClosePrice,omitempty"`
	PrevRealisedPnl      int64     `json:"prevRealisedPnl,omitempty"`
	PrevUnrealisedPnl    int64     `json:"prevUnrealisedPnl,omitempty"`
	QuoteCurrency        string    `json:"quoteCurrency,omitempty"`
	RealisedCost         int64     `json:"realisedCost,omitempty"`
	RealisedGrossPnl     int64     `json:"realisedGrossPnl,omitempty"`
	RealisedPnl          int64     `json:"realisedPnl,omitempty"`
	RealisedTax          int64     `json:"realisedTax,omitempty"`
	RebalancedPnl        int64     `json:"rebalancedPnl,omitempty"`
	RiskLimit            int64     `json:"riskLimit,omitempty"`
	RiskValue            int64     `json:"riskValue,omitempty"`
	SessionMargin        int64     `json:"sessionMargin,omitempty"`
	ShortBankrupt        int64     `json:"shortBankrupt,omitempty"`
	SimpleCost           float64   `json:"simpleCost,omitempty"`
	SimplePnl            float64   `json:"simplePnl,omitempty"`
	SimplePnlPcnt        float64   `json:"simplePnlPcnt,omitempty"`
	SimpleQty            float64   `json:"simpleQty,omitempty"`
	SimpleValue          float64   `json:"simpleValue,omitempty"`
	Symbol               string    `json:"symbol"`
	TargetExcessMargin   int64     `json:"targetExcessMargin,omitempty"`
	TaxBase              int64     `json:"taxBase,omitempty"`
	TaxableMargin        int64     `json:"taxableMargin,omitempty"`
	Timestamp            time.Time `json:"timestamp,omitempty"`
	Underlying           string    `json:"underlying,omitempty"`
	UnrealisedCost       int64     `json:"unrealisedCost,omitempty"`
	UnrealisedGrossPnl   int64     `json:"unrealisedGrossPnl,omitempty"`
	UnrealisedPnl        int64     `json:"unrealisedPnl,omitempty"`
	UnrealisedPnlPcnt    float64   `json:"unrealisedPnlPcnt,omitempty"`
	UnrealisedRoePcnt    float64   `json:"unrealisedRoePcnt,omitempty"`
	UnrealisedTax        int64     `json:"unrealisedTax,omitempty"`
	VarMargin            int64     `json:"varMargin,omitempty"`
}
