import { safeInputType, Int, Str, NullableIndexType, Num } from '../types.js';
declare const isNumber: (number: unknown) => boolean;
declare const isInteger: (number: unknown) => boolean;
declare const isArray: (arg: any) => arg is any[];
declare const hasProps: (o: any) => boolean;
declare const isString: (s: any) => s is string;
declare const isObject: (o: any) => boolean;
declare const isDictionary: (o: any) => boolean;
declare const isStringCoercible: (x: any) => any;
declare const prop: (o: any, k: NullableIndexType) => any;
declare const asFloat: (x: any) => number | typeof NaN;
declare const asInteger: (x: any) => number | typeof NaN;
declare function safeFloat(o: safeInputType, k: NullableIndexType, $default?: number): Num;
declare function safeInteger(o: safeInputType, k: NullableIndexType, $default: number): number;
declare function safeInteger(o: safeInputType, k: NullableIndexType, $default?: number): Int;
declare function safeIntegerProduct(o: safeInputType, k: NullableIndexType, $factor: number, $default?: number): Int;
declare function safeTimestamp(o: safeInputType, k: NullableIndexType, $default?: number): Int;
declare function safeValue(o: safeInputType, k: NullableIndexType, $default?: any): any;
declare function safeString(o: safeInputType, k: NullableIndexType, $default: string): string;
declare function safeString(o: safeInputType, k: NullableIndexType, $default?: string): Str;
declare function safeStringLower(o: safeInputType, k: NullableIndexType, $default?: string): Str;
declare function safeStringUpper(o: safeInputType, k: NullableIndexType, $default?: string): Str;
declare function safeFloat2(o: safeInputType, k1: NullableIndexType, k2: NullableIndexType, $default?: number): Num;
declare function safeInteger2(o: safeInputType, k1: NullableIndexType, k2: NullableIndexType, $default: number): number;
declare function safeInteger2(o: safeInputType, k1: NullableIndexType, k2: NullableIndexType, $default?: number): Int;
declare function safeIntegerProduct2(o: safeInputType, k1: NullableIndexType, k2: NullableIndexType, $factor: number, $default?: number): Int;
declare function safeTimestamp2(o: safeInputType, k1: NullableIndexType, k2: NullableIndexType, $default?: Int): Int;
declare function safeValue2(o: safeInputType, k1: NullableIndexType, k2: NullableIndexType, $default?: any): any;
declare function safeString2(o: safeInputType, k1: NullableIndexType, k2: NullableIndexType, $default: string): string;
declare function safeString2(o: safeInputType, k1: NullableIndexType, k2: NullableIndexType, $default?: string): Str;
declare function safeStringLower2(o: safeInputType, k1: NullableIndexType, k2: NullableIndexType, $default?: string): Str;
declare function safeStringUpper2(o: safeInputType, k1: NullableIndexType, k2: NullableIndexType, $default?: string): Str;
declare function safeFloatN(o: safeInputType, k: (NullableIndexType)[], $default?: number): Num;
declare function safeIntegerN(o: safeInputType, k: (NullableIndexType)[], $default: number): number;
declare function safeIntegerN(o: safeInputType, k: (NullableIndexType)[], $default?: number): Int;
declare function safeIntegerProductN(o: safeInputType, k: (NullableIndexType)[], $factor: number, $default?: number): Int;
declare function safeTimestampN(o: safeInputType, k: (NullableIndexType)[], $default?: number): Int;
declare function safeValueN(o: safeInputType, k: (NullableIndexType)[], $default?: any): any;
declare function safeStringN(o: safeInputType, k: (NullableIndexType)[], $default: string): string;
declare function safeStringN(o: safeInputType, k: (NullableIndexType)[], $default?: string): Str;
declare function safeStringLowerN(o: safeInputType, k: (NullableIndexType)[], $default?: string): Str;
declare function safeStringUpperN(o: safeInputType, k: (NullableIndexType)[], $default?: string): Str;
export { isNumber, isInteger, isArray, isObject, isString, isStringCoercible, isDictionary as isDict, hasProps, prop, asFloat, asInteger, safeFloat, safeInteger, safeIntegerProduct, safeTimestamp, safeValue, safeString, safeStringLower, safeStringUpper, safeFloat2, safeInteger2, safeIntegerProduct2, safeTimestamp2, safeValue2, safeString2, safeStringLower2, safeStringUpper2, safeFloatN, safeIntegerN, safeIntegerProductN, safeTimestampN, safeValueN, safeStringN, safeStringLowerN, safeStringUpperN, };
