import { implicitReturnType, Int, Str, MaybeIndexType, Num } from '../types.js';
declare const isNumber: (number: unknown) => boolean;
declare const isInteger: (number: unknown) => boolean;
declare const isArray: (arg: any) => arg is any[];
declare const hasProps: (o: any) => boolean;
declare const isString: (s: any) => s is string;
declare const isObject: (o: any) => boolean;
declare const isDictionary: (o: any) => boolean;
declare const isStringCoercible: (x: any) => any;
declare const prop: (o: any, k: MaybeIndexType) => any;
declare const asFloat: (x: any) => number | typeof NaN;
declare const asInteger: (x: any) => number | typeof NaN;
declare const safeFloat: (o: implicitReturnType, k: MaybeIndexType, $default?: number) => Num;
declare function safeInteger(o: implicitReturnType, k: MaybeIndexType, $default: number): number;
declare function safeInteger(o: implicitReturnType, k: MaybeIndexType, $default?: number): Int;
declare const safeIntegerProduct: (o: implicitReturnType, k: MaybeIndexType, $factor: number, $default?: number) => Int;
declare const safeTimestamp: (o: implicitReturnType, k: MaybeIndexType, $default?: number) => Int;
declare const safeValue: (o: implicitReturnType, k: MaybeIndexType, $default?: any) => any;
declare function safeString(o: implicitReturnType, k: MaybeIndexType, $default: string): string;
declare function safeString(o: implicitReturnType, k: MaybeIndexType, $default?: string): Str;
declare function safeStringLower(o: implicitReturnType, k: MaybeIndexType, $default: string): string;
declare function safeStringLower(o: implicitReturnType, k: MaybeIndexType, $default?: string): Str;
declare function safeStringUpper(o: implicitReturnType, k: MaybeIndexType, $default: string): string;
declare function safeStringUpper(o: implicitReturnType, k: MaybeIndexType, $default?: string): Str;
declare const safeFloat2: (o: implicitReturnType, k1: MaybeIndexType, k2: MaybeIndexType, $default?: number) => Num;
declare function safeInteger2(o: implicitReturnType, k1: MaybeIndexType, k2: MaybeIndexType, $default: number): number;
declare function safeInteger2(o: implicitReturnType, k1: MaybeIndexType, k2: MaybeIndexType, $default?: number): Int;
declare const safeIntegerProduct2: (o: implicitReturnType, k1: MaybeIndexType, k2: MaybeIndexType, $factor: number, $default?: number) => Int;
declare const safeTimestamp2: (o: implicitReturnType, k1: MaybeIndexType, k2: MaybeIndexType, $default?: Int) => Int;
declare const safeValue2: (o: implicitReturnType, k1: MaybeIndexType, k2: MaybeIndexType, $default?: any) => any;
declare function safeString2(o: implicitReturnType, k1: MaybeIndexType, k2: MaybeIndexType, $default: string): string;
declare function safeString2(o: implicitReturnType, k1: MaybeIndexType, k2: MaybeIndexType, $default?: string): Str;
declare function safeStringLower2(o: implicitReturnType, k1: MaybeIndexType, k2: MaybeIndexType, $default: string): string;
declare function safeStringLower2(o: implicitReturnType, k1: MaybeIndexType, k2: MaybeIndexType, $default?: string): Str;
declare function safeStringUpper2(o: implicitReturnType, k1: MaybeIndexType, k2: MaybeIndexType, $default: string): string;
declare function safeStringUpper2(o: implicitReturnType, k1: MaybeIndexType, k2: MaybeIndexType, $default?: string): Str;
declare const safeFloatN: (o: implicitReturnType, k: (MaybeIndexType)[], $default?: number) => Num;
declare function safeIntegerN(o: implicitReturnType, k: (MaybeIndexType)[], $default: number): number;
declare function safeIntegerN(o: implicitReturnType, k: (MaybeIndexType)[], $default?: number): Int;
declare const safeIntegerProductN: (o: implicitReturnType, k: (MaybeIndexType)[], $factor: number, $default?: number) => Int;
declare const safeTimestampN: (o: implicitReturnType, k: (MaybeIndexType)[], $default?: number) => Int;
declare const safeValueN: (o: implicitReturnType, k: (MaybeIndexType)[], $default?: any) => any;
declare function safeStringN(o: implicitReturnType, k: (MaybeIndexType)[], $default: string): string;
declare function safeStringN(o: implicitReturnType, k: (MaybeIndexType)[], $default?: string): Str;
declare function safeStringLowerN(o: implicitReturnType, k: (MaybeIndexType)[], $default: string): string;
declare function safeStringLowerN(o: implicitReturnType, k: (MaybeIndexType)[], $default?: string): Str;
declare function safeStringUpperN(o: implicitReturnType, k: (MaybeIndexType)[], $default: string): string;
declare function safeStringUpperN(o: implicitReturnType, k: (MaybeIndexType)[], $default?: string): Str;
export { isNumber, isInteger, isArray, isObject, isString, isStringCoercible, isDictionary as isDict, hasProps, prop, asFloat, asInteger, safeFloat, safeInteger, safeIntegerProduct, safeTimestamp, safeValue, safeString, safeStringLower, safeStringUpper, safeFloat2, safeInteger2, safeIntegerProduct2, safeTimestamp2, safeValue2, safeString2, safeStringLower2, safeStringUpper2, safeFloatN, safeIntegerN, safeIntegerProductN, safeTimestampN, safeValueN, safeStringN, safeStringLowerN, safeStringUpperN, };
