// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

package io.github.ccxt.exchanges.pro;
import io.github.ccxt.base.Precise;
import io.github.ccxt.errors.*;
import io.github.ccxt.Helpers;
import io.github.ccxt.BaseExchange;
import io.github.ccxt.ws.*;
import io.github.ccxt.Client;
import io.github.ccxt.types.OHLCV;
import io.github.ccxt.types.Order;
import io.github.ccxt.types.OrderBook;
import io.github.ccxt.types.Position;
import io.github.ccxt.types.Ticker;
import io.github.ccxt.types.Tickers;
import io.github.ccxt.types.Trade;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.util.stream.Collectors;

public class Backpack extends io.github.ccxt.exchanges.Backpack
{
   public Backpack () {
       super();
   }

   public Backpack (Object options) {
       super(options);
   }

    public Object describe()
    {
        return this.deepExtend(super.describe(), new HashMap<String, Object>() {{
            put( "has", new HashMap<String, Object>() {{
                put( "ws", true );
                put( "watchBalance", false );
                put( "watchBidsAsks", true );
                put( "watchMyTrades", false );
                put( "watchOHLCV", true );
                put( "watchOHLCVForSymbols", true );
                put( "watchOrderBook", true );
                put( "watchOrderBookForSymbols", true );
                put( "watchOrders", true );
                put( "watchPositions", true );
                put( "watchTicker", true );
                put( "watchTickers", true );
                put( "watchTrades", true );
                put( "watchTradesForSymbols", true );
                put( "unwatchBidsAsks", true );
                put( "unwatchOHLCV", true );
                put( "unwatchOHLCVForSymbols", true );
                put( "unwatchOrderBook", true );
                put( "unwatchOrderBookForSymbols", true );
                put( "unwatchTicker", true );
                put( "unwatchTickers", true );
                put( "unWatchTrades", true );
                put( "unWatchTradesForSymbols", true );
                put( "unWatchOrders", true );
                put( "unWatchPositions", true );
            }} );
            put( "urls", new HashMap<String, Object>() {{
                put( "api", new HashMap<String, Object>() {{
                    put( "ws", new HashMap<String, Object>() {{
                        put( "public", "wss://ws.backpack.exchange" );
                        put( "private", "wss://ws.backpack.exchange" );
                    }} );
                }} );
            }} );
            put( "options", new HashMap<String, Object>() {{
                put( "timeframes", new HashMap<String, Object>() {{}} );
            }} );
            put( "streaming", new HashMap<String, Object>() {{
                put( "ping", "ping");
                put( "keepAlive", 119000 );
            }} );
        }});
    }

    public CompletableFuture<Object> watchPublic(Object topics, Object messageHashes, Object... optionalArgs)
    {

        return BaseExchange.supplyAsync(() -> {

            Object parameters = optionalArgs != null && optionalArgs.length > 0 ? optionalArgs[0] : new HashMap<String, Object>() {{}};
            Object unwatch = optionalArgs != null && optionalArgs.length > 1 ? optionalArgs[1] : false;
            if (java.util.Objects.equals(this.markets, null))
            {
                (this.loadMarkets()).join();
            }
            Object url = Helpers.GetValue(((Map<String, Object>)((Map<String, Object>)this.urls).get("api")).get("ws"), "public");
            String method = ((Helpers.isTrue(unwatch))) ? "UNSUBSCRIBE" : "SUBSCRIBE";
            Map<String, Object> request = new HashMap<String, Object>() {{
                put( "method", method );
                put( "params", topics );
            }};
            Map<String, Object> message = this.deepExtend(request, parameters);
            if (Helpers.isTrue(unwatch))
            {
                this.handleUnsubscriptions(url, messageHashes, message);
                return null;
            }
            return (this.watchMultiple(url, messageHashes, message, messageHashes, null)).join();
        });

    }

    public CompletableFuture<Object> watchPrivate(Object topics, Object messageHashes, Object... optionalArgs)
    {

        return BaseExchange.supplyAsync(() -> {

            Object parameters = optionalArgs != null && optionalArgs.length > 0 ? optionalArgs[0] : new HashMap<String, Object>() {{}};
            Object unwatch = optionalArgs != null && optionalArgs.length > 1 ? optionalArgs[1] : false;
            this.checkRequiredCredentials();
            Object url = Helpers.GetValue(((Map<String, Object>)((Map<String, Object>)this.urls).get("api")).get("ws"), "private");
            String instruction = "subscribe";
            Object ts = String.valueOf(this.nonce());
            String method = ((Helpers.isTrue(unwatch))) ? "UNSUBSCRIBE" : "SUBSCRIBE";
            String recvWindow = this.safeString2(this.options, "recvWindow", "X-Window", "5000");
            Object payload = (((((("instruction=" + instruction) + "&") + "timestamp=") + ts) + "&window=") + recvWindow);
            Object secretBytes = this.base64ToBinary(this.secret);
            Object seed = this.arraySlice(secretBytes, 0, 32);
            Object signature = eddsa(this.encode(payload), seed, ed25519());
            Map<String, Object> request = new HashMap<String, Object>() {{
                put( "method", method );
                put( "params", topics );
                put( "signature", new ArrayList<Object>(Arrays.asList(Backpack.this.apiKey, signature, ts, recvWindow)) );
            }};
            Map<String, Object> message = this.deepExtend(request, parameters);
            if (Helpers.isTrue(unwatch))
            {
                this.handleUnsubscriptions(url, messageHashes, message);
                return null;
            }
            return (this.watchMultiple(url, messageHashes, message, messageHashes, null)).join();
        });

    }

    public void handleUnsubscriptions(Object url, Object messageHashes, Object message)
    {
        Client client = this.client(url);
        this.watchMultiple(url, messageHashes, message, messageHashes, null);
        for (var i = 0; i < ((List<?>)messageHashes).size(); i++)
        {
            Object messageHash = Helpers.GetValue(messageHashes, i);
            Object subMessageHash = Helpers.replace(((String)messageHash), "unsubscribe:", "");
            this.cleanUnsubscription(client, subMessageHash, messageHash);
            if (Helpers.isGreaterThanOrEqual(Helpers.getIndexOf(messageHash, "ticker"), 0))
            {
                Object symbol = Helpers.replace(((String)messageHash), "unsubscribe:ticker:", "");
                if (((Map<?, ?>)this.tickers).containsKey(symbol))
                {
                    ((Map<String,Object>)this.tickers).remove((String)symbol);
                }
            } else if (Helpers.isGreaterThanOrEqual(Helpers.getIndexOf(messageHash, "bidask"), 0))
            {
                Object symbol = Helpers.replace(((String)messageHash), "unsubscribe:bidask:", "");
                if (((Map<?, ?>)this.bidsasks).containsKey(symbol))
                {
                    ((Map<String,Object>)this.bidsasks).remove((String)symbol);
                }
            } else if (Helpers.isGreaterThanOrEqual(Helpers.getIndexOf(messageHash, "candles"), 0))
            {
                Object splitHashes = Helpers.split(messageHash, ":");
                String symbol = this.safeString(splitHashes, 2);
                String timeframe = this.safeString(splitHashes, 3);
                if ((!java.util.Objects.equals(symbol, null)) && (!java.util.Objects.equals(timeframe, null)) && (((Map<?, ?>)this.ohlcvs).containsKey(symbol)))
                {
                    if (((Map<?, ?>)Helpers.GetValue(this.ohlcvs, symbol)).containsKey(timeframe))
                    {
                        ((Map<String,Object>)Helpers.GetValue(this.ohlcvs, symbol)).remove((String)timeframe);
                    }
                }
            } else if (Helpers.isGreaterThanOrEqual(Helpers.getIndexOf(messageHash, "orderbook"), 0))
            {
                Object symbol = Helpers.replace(((String)messageHash), "unsubscribe:orderbook:", "");
                if (((Map<?, ?>)this.orderbooks).containsKey(symbol))
                {
                    ((Map<String,Object>)this.orderbooks).remove((String)symbol);
                }
            } else if (Helpers.isGreaterThanOrEqual(Helpers.getIndexOf(messageHash, "trades"), 0))
            {
                Object symbol = Helpers.replace(((String)messageHash), "unsubscribe:trades:", "");
                if (((Map<?, ?>)this.trades).containsKey(symbol))
                {
                    ((Map<String,Object>)this.trades).remove((String)symbol);
                }
            } else if (Helpers.isGreaterThanOrEqual(Helpers.getIndexOf(messageHash, "orders"), 0))
            {
                if (java.util.Objects.equals(messageHash, "unsubscribe:orders"))
                {
                    Object cache = this.orders;
                    if (!java.util.Objects.equals(cache, null))
                    {
                        Object keys = Helpers.objectKeys(cache);
                        for (var j = 0; j < ((List<?>)keys).size(); j++)
                        {
                            Object symbol = Helpers.GetValue(keys, j);
                            ((Map<String,Object>)cache).remove((String)symbol);
                        }
                    }
                } else
                {
                    Object symbol = Helpers.replace(((String)messageHash), "unsubscribe:orders:", "");
                    Object cache = this.orders;
                    if ((!java.util.Objects.equals(cache, null)) && (((Map<?, ?>)cache).containsKey(symbol)))
                    {
                        ((Map<String,Object>)cache).remove((String)symbol);
                    }
                }
            } else if (Helpers.isGreaterThanOrEqual(Helpers.getIndexOf(messageHash, "positions"), 0))
            {
                if (java.util.Objects.equals(messageHash, "unsubscribe:positions"))
                {
                    Object cache = this.positions;
                    Object keys = Helpers.objectKeys(cache);
                    for (var j = 0; j < ((List<?>)keys).size(); j++)
                    {
                        Object symbol = Helpers.GetValue(keys, j);
                        ((Map<String,Object>)this.positions).remove((String)symbol);
                    }
                } else
                {
                    Object symbol = Helpers.replace(((String)messageHash), "unsubscribe:positions:", "");
                    if (Helpers.inOp(this.positions, symbol))
                    {
                        ((Map<String,Object>)this.positions).remove((String)symbol);
                    }
                }
            }
        }
    }

    /**
     * @method
     * @name backpack#watchTicker
     * @description watches a price ticker, a statistical calculation with the information calculated over the past 24 hours for a specific market
     * @see https://docs.backpack.exchange/#tag/Streams/Public/Ticker
     * @param {string} symbol unified symbol of the market to fetch the ticker for
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} a [ticker structure]{@link https://docs.ccxt.com/?id=ticker-structure}
     */
    public CompletableFuture<Ticker> watchTicker(String symbol2, Object... optionalArgs)
    {
        final Object symbol3 = symbol2;
        return BaseExchange.supplyAsync(() -> {
            Object symbol = symbol3;
            Object parameters = optionalArgs != null && optionalArgs.length > 0 ? optionalArgs[0] : new HashMap<String, Object>() {{}};
            if (java.util.Objects.equals(this.markets, null))
            {
                (this.loadMarkets()).join();
            }
            Map<String, Object> market = (Map<String, Object>) this.market(symbol);
            symbol = ((Map<String, Object>)market).get("symbol");
            Object topic = Helpers.add(("ticker" + "."), ((Map<String, Object>)market).get("id"));
            String messageHash = (("ticker" + ":") + symbol);
            return (this.watchPublic(new ArrayList<Object>(Arrays.asList(topic)), new ArrayList<Object>(Arrays.asList(messageHash)), parameters)).join();
        }).thenApply(Ticker::new);

    }

    /**
     * @method
     * @name backpack#unWatchTicker
     * @description unWatches a price ticker, a statistical calculation with the information calculated over the past 24 hours for a specific market
     * @see https://docs.backpack.exchange/#tag/Streams/Public/Ticker
     * @param {string} symbol unified symbol of the market to fetch the ticker for
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} a [ticker structure]{@link https://docs.ccxt.com/?id=ticker-structure}
     */
    public CompletableFuture<Object> unWatchTicker(String symbol, Object... optionalArgs)
    {

        return BaseExchange.supplyAsync(() -> {

            Object parameters = optionalArgs != null && optionalArgs.length > 0 ? optionalArgs[0] : new HashMap<String, Object>() {{}};
            return (this.unWatchTickers(new ArrayList<Object>(Arrays.asList(symbol)), parameters)).join();
        });

    }

    /**
     * @method
     * @name backpack#watchTickers
     * @description watches a price ticker, a statistical calculation with the information calculated over the past 24 hours for all markets of a specific list
     * @see https://docs.backpack.exchange/#tag/Streams/Public/Ticker
     * @param {string[]} symbols unified symbol of the market to fetch the ticker for
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} a [ticker structure]{@link https://docs.ccxt.com/?id=ticker-structure}
     */
    public CompletableFuture<Tickers> watchTickers(Object... optionalArgs)
    {

        return BaseExchange.supplyAsync(() -> {

            Object symbols = optionalArgs != null && optionalArgs.length > 0 ? optionalArgs[0] : null;
            Object parameters = optionalArgs != null && optionalArgs.length > 1 ? optionalArgs[1] : new HashMap<String, Object>() {{}};
            if (java.util.Objects.equals(this.markets, null))
            {
                (this.loadMarkets()).join();
            }
            symbols = this.marketSymbols(symbols, null, false);
            Object messageHashes = new ArrayList<Object>(Arrays.asList());
            Object topics = new ArrayList<Object>(Arrays.asList());
            for (var i = 0; i < ((List<?>)symbols).size(); i++)
            {
                Object symbol = Helpers.GetValue(symbols, i);
                Object marketId = this.marketId(symbol);
                ((List<Object>)messageHashes).add(("ticker:" + symbol));
                ((List<Object>)topics).add(Helpers.add("ticker.", marketId));
            }
            (this.watchPublic(topics, messageHashes, parameters)).join();
            return this.filterByArray(this.tickers, "symbol", symbols);
        }).thenApply(Tickers::new);

    }

    /**
     * @method
     * @name backpack#unWatchTickers
     * @description watches a price ticker, a statistical calculation with the information calculated over the past 24 hours for all markets of a specific list
     * @see https://docs.backpack.exchange/#tag/Streams/Public/Ticker
     * @param {string[]} symbols unified symbol of the market to fetch the ticker for
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} a [ticker structure]{@link https://docs.ccxt.com/?id=ticker-structure}
     */
    public CompletableFuture<Object> unWatchTickers(Object... optionalArgs)
    {

        return BaseExchange.supplyAsync(() -> {

            Object symbols = optionalArgs != null && optionalArgs.length > 0 ? optionalArgs[0] : null;
            Object parameters = optionalArgs != null && optionalArgs.length > 1 ? optionalArgs[1] : new HashMap<String, Object>() {{}};
            if (java.util.Objects.equals(this.markets, null))
            {
                (this.loadMarkets()).join();
            }
            symbols = this.marketSymbols(symbols, null, false);
            Object topics = new ArrayList<Object>(Arrays.asList());
            Object messageHashes = new ArrayList<Object>(Arrays.asList());
            for (var i = 0; i < ((List<?>)symbols).size(); i++)
            {
                Object symbol = Helpers.GetValue(symbols, i);
                Object marketId = this.marketId(symbol);
                ((List<Object>)topics).add(Helpers.add("ticker.", marketId));
                ((List<Object>)messageHashes).add(("unsubscribe:ticker:" + symbol));
            }
            return (this.watchPublic(topics, messageHashes, parameters, true)).join();
        });

    }

    public void handleTicker(Client client, Object message)
    {
        //
        //     {
        //         data: {
        //             E: '1754176123312507',
        //             V: '19419526.742584',
        //             c: '3398.57',
        //             e: 'ticker',
        //             h: '3536.65',
        //             l: '3371.8',
        //             n: 17152,
        //             o: '3475.45',
        //             s: 'ETH_USDC',
        //             v: '5573.5827'
        //         },
        //         stream: 'bookTicker.ETH_USDC'
        //     }
        //
        Object ticker = this.safeDict(message, "data", new HashMap<String, Object>() {{}});
        String marketId = this.safeString(ticker, "s");
        Map<String, Object> market = (Map<String, Object>) this.safeMarket(marketId);
        String symbol = this.safeSymbol(marketId, market);
        Object parsedTicker = this.parseWsTicker(ticker, market);
        String messageHash = (("ticker" + ":") + symbol);
        Helpers.addElementToObject(this.tickers, symbol, parsedTicker);
        client.resolve(parsedTicker, messageHash);
    }

    public Object parseWsTicker(Object ticker, Object... optionalArgs)
    {
        //
        //     {
        //         E: '1754178406415232',
        //         V: '19303818.6923',
        //         c: '3407.54',
        //         e: 'ticker',
        //         h: '3536.65',
        //         l: '3369.18',
        //         n: 17272,
        //         o: '3481.71',
        //         s: 'ETH_USDC',
        //         v: '5542.3911'
        //     }
        //
        Object market = optionalArgs != null && optionalArgs.length > 0 ? optionalArgs[0] : null;
        Long microseconds = this.safeInteger(ticker, "E", 0);
        Long timestamp = this.parseToInt(Helpers.divide(microseconds, 1000));
        String marketId = this.safeString(ticker, "s");
        market = this.safeMarket(marketId, market);
        String symbol = this.safeSymbol(marketId, market);
        String last = this.safeString(ticker, "c");
        String open = this.safeString(ticker, "o");
        return this.safeTicker(new HashMap<String, Object>() {{
            put( "symbol", symbol );
            put( "timestamp", timestamp );
            put( "datetime", Backpack.this.iso8601(timestamp) );
            put( "high", Backpack.this.safeNumber(ticker, "h") );
            put( "low", Backpack.this.safeNumber(ticker, "l") );
            put( "bid", null );
            put( "bidVolume", null );
            put( "ask", null );
            put( "askVolume", null );
            put( "vwap", null );
            put( "open", open );
            put( "close", last );
            put( "last", last );
            put( "previousClose", null );
            put( "change", null );
            put( "percentage", null );
            put( "average", null );
            put( "baseVolume", Backpack.this.safeString(ticker, "v") );
            put( "quoteVolume", Backpack.this.safeString(ticker, "V") );
            put( "info", ticker );
        }}, market);
    }

    /**
     * @method
     * @name backpack#watchBidsAsks
     * @description watches best bid & ask for symbols
     * @see https://docs.backpack.exchange/#tag/Streams/Public/Book-ticker
     * @param {string[]} symbols unified symbol of the market to fetch the ticker for
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} a [ticker structure]{@link https://docs.ccxt.com/?id=ticker-structure}
     */
    public CompletableFuture<Tickers> watchBidsAsks(Object... optionalArgs)
    {

        return BaseExchange.supplyAsync(() -> {

            Object symbols = optionalArgs != null && optionalArgs.length > 0 ? optionalArgs[0] : null;
            Object parameters = optionalArgs != null && optionalArgs.length > 1 ? optionalArgs[1] : new HashMap<String, Object>() {{}};
            if (java.util.Objects.equals(this.markets, null))
            {
                (this.loadMarkets()).join();
            }
            symbols = this.marketSymbols(symbols, null, false);
            Object topics = new ArrayList<Object>(Arrays.asList());
            Object messageHashes = new ArrayList<Object>(Arrays.asList());
            for (var i = 0; i < ((List<?>)symbols).size(); i++)
            {
                Object symbol = Helpers.GetValue(symbols, i);
                Object marketId = this.marketId(symbol);
                ((List<Object>)topics).add(Helpers.add("bookTicker.", marketId));
                ((List<Object>)messageHashes).add(("bidask:" + symbol));
            }
            (this.watchPublic(topics, messageHashes, parameters)).join();
            return this.filterByArray(this.bidsasks, "symbol", symbols);
        }).thenApply(Tickers::new);

    }

    /**
     * @method
     * @name backpack#unWatchBidsAsks
     * @description unWatches best bid & ask for symbols
     * @param {string[]} symbols unified symbol of the market to fetch the ticker for
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} a [ticker structure]{@link https://docs.ccxt.com/?id=ticker-structure}
     */
    public CompletableFuture<Object> unWatchBidsAsks(Object... optionalArgs)
    {

        return BaseExchange.supplyAsync(() -> {

            Object symbols = optionalArgs != null && optionalArgs.length > 0 ? optionalArgs[0] : null;
            Object parameters = optionalArgs != null && optionalArgs.length > 1 ? optionalArgs[1] : new HashMap<String, Object>() {{}};
            if (java.util.Objects.equals(this.markets, null))
            {
                (this.loadMarkets()).join();
            }
            symbols = this.marketSymbols(symbols, null, false);
            Object topics = new ArrayList<Object>(Arrays.asList());
            Object messageHashes = new ArrayList<Object>(Arrays.asList());
            for (var i = 0; i < ((List<?>)symbols).size(); i++)
            {
                Object symbol = Helpers.GetValue(symbols, i);
                Object marketId = this.marketId(symbol);
                ((List<Object>)topics).add(Helpers.add("bookTicker.", marketId));
                ((List<Object>)messageHashes).add(("unsubscribe:bidask:" + symbol));
            }
            return (this.watchPublic(topics, messageHashes, parameters, true)).join();
        });

    }

    public void handleBidAsk(Client client, Object message)
    {
        //
        //     {
        //         data: {
        //             A: '0.4087',
        //             B: '0.0020',
        //             E: '1754517402450016',
        //             T: '1754517402449064',
        //             a: '3667.50',
        //             b: '3667.49',
        //             e: 'bookTicker',
        //             s: 'ETH_USDC',
        //             u: 1328288557
        //         },
        //         stream: 'bookTicker.ETH_USDC'
        //     }
        Object data = this.safeDict(message, "data", new HashMap<String, Object>() {{}});
        String marketId = this.safeString(data, "s");
        Map<String, Object> market = (Map<String, Object>) this.safeMarket(marketId);
        String symbol = this.safeSymbol(marketId, market);
        Object parsedBidAsk = this.parseWsBidAsk(data, market);
        String messageHash = (("bidask" + ":") + symbol);
        Helpers.addElementToObject(this.bidsasks, symbol, parsedBidAsk);
        client.resolve(parsedBidAsk, messageHash);
    }

    public Object parseWsBidAsk(Object ticker, Object... optionalArgs)
    {
        //
        //     {
        //         A: '0.4087',
        //         B: '0.0020',
        //         E: '1754517402450016',
        //         T: '1754517402449064',
        //         a: '3667.50',
        //         b: '3667.49',
        //         e: 'bookTicker',
        //         s: 'ETH_USDC',
        //         u: 1328288557
        //     }
        //
        Object market = optionalArgs != null && optionalArgs.length > 0 ? optionalArgs[0] : null;
        String marketId = this.safeString(ticker, "s");
        market = this.safeMarket(marketId, market);
        String symbol = this.safeString(market, "symbol");
        Long microseconds = this.safeInteger(ticker, "E", 0);
        Long timestamp = this.parseToInt(Helpers.divide(microseconds, 1000));
        String ask = this.safeString(ticker, "a");
        String askVolume = this.safeString(ticker, "A");
        String bid = this.safeString(ticker, "b");
        String bidVolume = this.safeString(ticker, "B");
        return this.safeTicker(new HashMap<String, Object>() {{
            put( "symbol", symbol );
            put( "timestamp", timestamp );
            put( "datetime", Backpack.this.iso8601(timestamp) );
            put( "ask", ask );
            put( "askVolume", askVolume );
            put( "bid", bid );
            put( "bidVolume", bidVolume );
            put( "info", ticker );
        }}, market);
    }

    /**
     * @method
     * @name backpack#watchOHLCV
     * @description watches historical candlestick data containing the open, high, low, close price, and the volume of a market
     * @see https://docs.backpack.exchange/#tag/Streams/Public/K-Line
     * @param {string} symbol unified symbol of the market to fetch OHLCV data for
     * @param {string} timeframe the length of time each candle represents
     * @param {int} [since] timestamp in ms of the earliest candle to fetch
     * @param {int} [limit] the maximum amount of candles to fetch
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {int[][]} A list of candles ordered as timestamp, open, high, low, close, volume
     */
    public CompletableFuture<List<OHLCV>> watchOHLCV(String symbol, Object... optionalArgs)
    {

        return BaseExchange.supplyAsync(() -> {

            Object timeframe = optionalArgs != null && optionalArgs.length > 0 ? optionalArgs[0] : "1m";
            Object since = optionalArgs != null && optionalArgs.length > 1 ? optionalArgs[1] : null;
            Object limit = optionalArgs != null && optionalArgs.length > 2 ? optionalArgs[2] : null;
            Object parameters = optionalArgs != null && optionalArgs.length > 3 ? optionalArgs[3] : new HashMap<String, Object>() {{}};
            Object result = (this.watchOHLCVForSymbols(new ArrayList<Object>(Arrays.asList(new ArrayList<Object>(Arrays.asList(symbol, timeframe)))), since, limit, parameters)).join();
            return Helpers.GetValue(Helpers.GetValue(result, symbol), timeframe);
        }).thenApply(res -> ((List<?>) res).stream().map(OHLCV::new).collect(Collectors.toList()));

    }

    /**
     * @method
     * @name backpack#unWatchOHLCV
     * @description watches historical candlestick data containing the open, high, low, and close price, and the volume of a market
     * @see https://docs.backpack.exchange/#tag/Streams/Public/K-Line
     * @param {string} symbol unified symbol of the market to fetch OHLCV data for
     * @param {string} timeframe the length of time each candle represents
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {int[][]} A list of candles ordered as timestamp, open, high, low, close, volume
     */
    public CompletableFuture<Object> unWatchOHLCV(String symbol, Object... optionalArgs)
    {

        return BaseExchange.supplyAsync(() -> {

            Object timeframe = optionalArgs != null && optionalArgs.length > 0 ? optionalArgs[0] : "1m";
            Object parameters = optionalArgs != null && optionalArgs.length > 1 ? optionalArgs[1] : new HashMap<String, Object>() {{}};
            return (this.unWatchOHLCVForSymbols(new ArrayList<Object>(Arrays.asList(new ArrayList<Object>(Arrays.asList(symbol, timeframe)))), parameters)).join();
        });

    }

    /**
     * @method
     * @name backpack#watchOHLCVForSymbols
     * @description watches historical candlestick data containing the open, high, low, close price, and the volume of a market
     * @see https://docs.backpack.exchange/#tag/Streams/Public/K-Line
     * @param {string[][]} symbolsAndTimeframes array of arrays containing unified symbols and timeframes to fetch OHLCV data for, example [['BTC/USDT', '1m'], ['LTC/USDT', '5m']]
     * @param {int} [since] timestamp in ms of the earliest candle to fetch
     * @param {int} [limit] the maximum amount of candles to fetch
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {int[][]} A list of candles ordered as timestamp, open, high, low, close, volume
     */
    public CompletableFuture<Object> watchOHLCVForSymbols(Object symbolsAndTimeframes, Object... optionalArgs)
    {

        return BaseExchange.supplyAsync(() -> {

            Object since = optionalArgs != null && optionalArgs.length > 0 ? optionalArgs[0] : null;
            Object limit = optionalArgs != null && optionalArgs.length > 1 ? optionalArgs[1] : null;
            Object parameters = optionalArgs != null && optionalArgs.length > 2 ? optionalArgs[2] : new HashMap<String, Object>() {{}};
            Object symbolsLength = ((List<?>)symbolsAndTimeframes).size();
            if (Helpers.isEqual(symbolsLength, 0) || !Helpers.isTrue(Helpers.isArray(Helpers.GetValue(symbolsAndTimeframes, 0))))
            {
                throw new ArgumentsRequired((this.id + " watchOHLCVForSymbols() requires a an array of symbols and timeframes, like  ['ETH/USDC', '1m']")) ;
            }
            if (java.util.Objects.equals(this.markets, null))
            {
                (this.loadMarkets()).join();
            }
            Object topics = new ArrayList<Object>(Arrays.asList());
            Object messageHashes = new ArrayList<Object>(Arrays.asList());
            for (var i = 0; i < ((List<?>)symbolsAndTimeframes).size(); i++)
            {
                Object symbolAndTimeframe = Helpers.GetValue(symbolsAndTimeframes, i);
                String marketId = this.safeString(symbolAndTimeframe, 0);
                Map<String, Object> market = (Map<String, Object>) this.market(marketId);
                String tf = this.safeString(symbolAndTimeframe, 1);
                String interval = this.safeString(this.timeframes, tf, tf);
                ((List<Object>)topics).add(Helpers.add((Helpers.add("kline.", interval) + "."), ((Map<String, Object>)market).get("id")));
                ((List<Object>)messageHashes).add(Helpers.add((("candles:" + ((Map<String, Object>)market).get("symbol")) + ":"), interval));
            }
            var symboltimeframecandlesVariable = (this.watchPublic(topics, messageHashes, parameters)).join();
            var symbol = ((List<Object>) symboltimeframecandlesVariable).get(0);
            var timeframe = ((List<Object>) symboltimeframecandlesVariable).get(1);
            var candles = ((List<Object>) symboltimeframecandlesVariable).get(2);
            if (Helpers.isTrue(this.newUpdates))
            {
                limit = Helpers.callDynamically(candles, "getLimit", new Object[]{symbol, limit});
            }
            List<Object> filtered = this.filterBySinceLimit(candles, since, limit, 0, true);
            return this.createOHLCVObject(symbol, timeframe, filtered);
        });

    }

    /**
     * @method
     * @name backpack#unWatchOHLCVForSymbols
     * @description unWatches historical candlestick data containing the open, high, low, and close price, and the volume of a market
     * @see https://docs.backpack.exchange/#tag/Streams/Public/K-Line
     * @param {string[][]} symbolsAndTimeframes array of arrays containing unified symbols and timeframes to fetch OHLCV data for, example [['BTC/USDT', '1m'], ['LTC/USDT', '5m']]
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {int[][]} A list of candles ordered as timestamp, open, high, low, close, volume
     */
    public CompletableFuture<Object> unWatchOHLCVForSymbols(Object symbolsAndTimeframes, Object... optionalArgs)
    {

        return BaseExchange.supplyAsync(() -> {

            Object parameters = optionalArgs != null && optionalArgs.length > 0 ? optionalArgs[0] : new HashMap<String, Object>() {{}};
            Object symbolsLength = ((List<?>)symbolsAndTimeframes).size();
            if (Helpers.isEqual(symbolsLength, 0) || !Helpers.isTrue(Helpers.isArray(Helpers.GetValue(symbolsAndTimeframes, 0))))
            {
                throw new ArgumentsRequired((this.id + " unWatchOHLCVForSymbols() requires a an array of symbols and timeframes, like  ['ETH/USDC', '1m']")) ;
            }
            if (java.util.Objects.equals(this.markets, null))
            {
                (this.loadMarkets()).join();
            }
            Object topics = new ArrayList<Object>(Arrays.asList());
            Object messageHashes = new ArrayList<Object>(Arrays.asList());
            for (var i = 0; i < ((List<?>)symbolsAndTimeframes).size(); i++)
            {
                Object symbolAndTimeframe = Helpers.GetValue(symbolsAndTimeframes, i);
                String marketId = this.safeString(symbolAndTimeframe, 0);
                Map<String, Object> market = (Map<String, Object>) this.market(marketId);
                String tf = this.safeString(symbolAndTimeframe, 1);
                String interval = this.safeString(this.timeframes, tf, tf);
                ((List<Object>)topics).add(Helpers.add((Helpers.add("kline.", interval) + "."), ((Map<String, Object>)market).get("id")));
                ((List<Object>)messageHashes).add(Helpers.add((("unsubscribe:candles:" + ((Map<String, Object>)market).get("symbol")) + ":"), interval));
            }
            return (this.watchPublic(topics, messageHashes, parameters, true)).join();
        });

    }

    public void handleOHLCV(Client client, Object message)
    {
        //
        //     {
        //         data: {
        //             E: '1754519557526056',
        //             T: '2025-08-07T00:00:00',
        //             X: false,
        //             c: '3680.520000000',
        //             e: 'kline',
        //             h: '3681.370000000',
        //             l: '3667.650000000',
        //             n: 255,
        //             o: '3670.150000000',
        //             s: 'ETH_USDC',
        //             t: '2025-08-06T22:00:00',
        //             v: '62.2621000'
        //         },
        //         stream: 'kline.2h.ETH_USDC'
        //     }
        //
        Object data = this.safeDict(message, "data", new HashMap<String, Object>() {{}});
        String marketId = this.safeString(data, "s");
        Map<String, Object> market = (Map<String, Object>) this.market(marketId);
        Object symbol = ((Map<String, Object>)market).get("symbol");
        String stream = this.safeString(message, "stream", "");
        Object parts = Helpers.split(stream, ".");
        String timeframe = this.safeString(parts, 1, "");
        if (!(((Map<?, ?>)this.ohlcvs).containsKey(symbol)))
        {
            Helpers.addElementToObject(this.ohlcvs, symbol, new HashMap<String, Object>() {{}});
        }
        if (!(((Map<?, ?>)Helpers.GetValue(this.ohlcvs, symbol)).containsKey(timeframe)))
        {
            Long limit = this.safeInteger(this.options, "OHLCVLimit", 1000);
            var stored = new ArrayCache.ArrayCacheByTimestamp(((Number)limit).intValue());
            Helpers.addElementToObject(Helpers.GetValue(this.ohlcvs, symbol), timeframe, stored);
        }
        Object ohlcv = Helpers.GetValue(Helpers.GetValue(this.ohlcvs, symbol), timeframe);
        Object parsed = this.parseWsOHLCV(data);
        Helpers.callDynamically(ohlcv, "append", new Object[]{parsed});
        String messageHash = ((("candles:" + symbol) + ":") + timeframe);
        client.resolve(new ArrayList<Object>(Arrays.asList(symbol, timeframe, ohlcv)), messageHash);
    }

    public Object parseWsOHLCV(Object ohlcv, Object... optionalArgs)
    {
        //
        //     {
        //         E: '1754519557526056',
        //         T: '2025-08-07T00:00:00',
        //         X: false,
        //         c: '3680.520000000',
        //         e: 'kline',
        //         h: '3681.370000000',
        //         l: '3667.650000000',
        //         n: 255,
        //         o: '3670.150000000',
        //         s: 'ETH_USDC',
        //         t: '2025-08-06T22:00:00',
        //         v: '62.2621000'
        //     },
        //
        Object market = optionalArgs != null && optionalArgs.length > 0 ? optionalArgs[0] : null;
        return new ArrayList<Object>(Arrays.asList(this.parse8601(this.safeString(ohlcv, "T")), this.safeNumber(ohlcv, "o"), this.safeNumber(ohlcv, "h"), this.safeNumber(ohlcv, "l"), this.safeNumber(ohlcv, "c"), this.safeNumber(ohlcv, "v")));
    }

    /**
     * @method
     * @name backpack#watchTrades
     * @description watches information on multiple trades made in a market
     * @see https://docs.backpack.exchange/#tag/Streams/Public/Trade
     * @param {string} symbol unified symbol of the market to fetch the ticker for
     * @param {int} [since] the earliest time in ms to fetch trades for
     * @param {int} [limit] the maximum number of trade structures to retrieve
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} a [ticker structure]{@link https://docs.ccxt.com/?id=ticker-structure}
     */
    public CompletableFuture<List<Trade>> watchTrades(String symbol, Object... optionalArgs)
    {

        return BaseExchange.supplyAsync(() -> {

            Object since = optionalArgs != null && optionalArgs.length > 0 ? optionalArgs[0] : null;
            Object limit = optionalArgs != null && optionalArgs.length > 1 ? optionalArgs[1] : null;
            Object parameters = optionalArgs != null && optionalArgs.length > 2 ? optionalArgs[2] : new HashMap<String, Object>() {{}};
            return (this.watchTradesForSymbols((Object)(new ArrayList<Object>(Arrays.asList(symbol))), (Object)(since), (Object)(limit), (Object)(parameters))).join();
        }).thenApply(res -> ((List<?>) res).stream().map(Trade::new).collect(Collectors.toList()));

    }

    /**
     * @method
     * @name backpack#unWatchTrades
     * @description unWatches from the stream channel
     * @see https://docs.backpack.exchange/#tag/Streams/Public/Trade
     * @param {string} symbol unified symbol of the market to fetch trades for
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object[]} a list of [trade structures]{@link https://docs.ccxt.com/?id=public-trades}
     */
    public CompletableFuture<Object> unWatchTrades(String symbol, Object... optionalArgs)
    {

        return BaseExchange.supplyAsync(() -> {

            Object parameters = optionalArgs != null && optionalArgs.length > 0 ? optionalArgs[0] : new HashMap<String, Object>() {{}};
            return (this.unWatchTradesForSymbols(new ArrayList<Object>(Arrays.asList(symbol)), parameters)).join();
        });

    }

    /**
     * @method
     * @name backpack#watchTradesForSymbols
     * @description watches information on multiple trades made in a market
     * @see https://docs.backpack.exchange/#tag/Streams/Public/Trade
     * @param {string[]} symbols unified symbol of the market to fetch trades for
     * @param {int} [since] the earliest time in ms to fetch trades for
     * @param {int} [limit] the maximum number of trade structures to retrieve
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} a [ticker structure]{@link https://docs.ccxt.com/?id=ticker-structure}
     */
    public CompletableFuture<List<Trade>> watchTradesForSymbols(Object symbols2, Object... optionalArgs)
    {
        final Object symbols3 = symbols2;
        return BaseExchange.supplyAsync(() -> {
            Object symbols = symbols3;
            Object since = optionalArgs != null && optionalArgs.length > 0 ? optionalArgs[0] : null;
            Object limit = optionalArgs != null && optionalArgs.length > 1 ? optionalArgs[1] : null;
            Object parameters = optionalArgs != null && optionalArgs.length > 2 ? optionalArgs[2] : new HashMap<String, Object>() {{}};
            if (java.util.Objects.equals(this.markets, null))
            {
                (this.loadMarkets()).join();
            }
            symbols = this.marketSymbols(symbols);
            Object symbolsLength = ((List<?>)symbols).size();
            if (Helpers.isEqual(symbolsLength, 0))
            {
                throw new ArgumentsRequired((this.id + " watchTradesForSymbols() requires a non-empty array of symbols")) ;
            }
            Object topics = new ArrayList<Object>(Arrays.asList());
            Object messageHashes = new ArrayList<Object>(Arrays.asList());
            for (var i = 0; i < ((List<?>)symbols).size(); i++)
            {
                Object symbol = Helpers.GetValue(symbols, i);
                Object marketId = this.marketId(symbol);
                ((List<Object>)topics).add(Helpers.add("trade.", marketId));
                ((List<Object>)messageHashes).add(("trades:" + symbol));
            }
            Object trades = (this.watchPublic(topics, messageHashes, parameters)).join();
            if (Helpers.isTrue(this.newUpdates))
            {
                Object first = this.safeValue(trades, 0);
                String tradeSymbol = this.safeString(first, "symbol");
                limit = Helpers.callDynamically(trades, "getLimit", new Object[]{tradeSymbol, limit});
            }
            List<Object> result = this.filterBySinceLimit(trades, since, limit, "timestamp", true);
            return this.sortBy(result, "timestamp");  // needed bcz of https://github.com/ccxt/ccxt/actions/runs/20755599389/job/59597208008?pr=27624#step:10:537
        }).thenApply(res -> ((List<?>) res).stream().map(Trade::new).collect(Collectors.toList()));

    }

    /**
     * @method
     * @name backpack#unWatchTradesForSymbols
     * @description unWatches from the stream channel
     * @see https://docs.backpack.exchange/#tag/Streams/Public/Trade
     * @param {string[]} symbols unified symbol of the market to fetch trades for
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object[]} a list of [trade structures]{@link https://docs.ccxt.com/?id=public-trades}
     */
    public CompletableFuture<Object> unWatchTradesForSymbols(Object symbols2, Object... optionalArgs)
    {
        final Object symbols3 = symbols2;
        return BaseExchange.supplyAsync(() -> {
            Object symbols = symbols3;
            Object parameters = optionalArgs != null && optionalArgs.length > 0 ? optionalArgs[0] : new HashMap<String, Object>() {{}};
            if (java.util.Objects.equals(this.markets, null))
            {
                (this.loadMarkets()).join();
            }
            symbols = this.marketSymbols(symbols);
            Object symbolsLength = ((List<?>)symbols).size();
            if (Helpers.isEqual(symbolsLength, 0))
            {
                throw new ArgumentsRequired((this.id + " unWatchTradesForSymbols() requires a non-empty array of symbols")) ;
            }
            Object topics = new ArrayList<Object>(Arrays.asList());
            Object messageHashes = new ArrayList<Object>(Arrays.asList());
            for (var i = 0; i < ((List<?>)symbols).size(); i++)
            {
                Object symbol = Helpers.GetValue(symbols, i);
                Object marketId = this.marketId(symbol);
                ((List<Object>)topics).add(Helpers.add("trade.", marketId));
                ((List<Object>)messageHashes).add(("unsubscribe:trades:" + symbol));
            }
            return (this.watchPublic(topics, messageHashes, parameters, true)).join();
        });

    }

    public void handleTrades(Client client, Object message)
    {
        //
        //     {
        //         data: {
        //             E: '1754601477746429',
        //             T: '1754601477744000',
        //             a: '5121860761',
        //             b: '5121861755',
        //             e: 'trade',
        //             m: false,
        //             p: '3870.25',
        //             q: '0.0008',
        //             s: 'ETH_USDC_PERP',
        //             t: 10782547
        //         },
        //         stream: 'trade.ETH_USDC_PERP'
        //     }
        //
        Object data = this.safeDict(message, "data", new HashMap<String, Object>() {{}});
        String marketId = this.safeString(data, "s");
        Map<String, Object> market = (Map<String, Object>) this.market(marketId);
        Object symbol = ((Map<String, Object>)market).get("symbol");
        if (!(((Map<?, ?>)this.trades).containsKey(symbol)))
        {
            Long limit = this.safeInteger(this.options, "tradesLimit", 1000);
            var stored = new ArrayCache(((Number)limit).intValue());
            Helpers.addElementToObject(this.trades, symbol, stored);
        }
        io.github.ccxt.ws.ArrayCache cache = (io.github.ccxt.ws.ArrayCache) Helpers.GetValue(this.trades, symbol);
        Object trade = this.parseWsTrade(data, market);
        Helpers.callDynamically(cache, "append", new Object[]{trade});
        String messageHash = ("trades:" + symbol);
        client.resolve(cache, messageHash);
        client.resolve(cache, "trades");
    }

    public Object parseWsTrade(Object trade, Object... optionalArgs)
    {
        //
        //     {
        //         E: '1754601477746429',
        //         T: '1754601477744000',
        //         a: '5121860761',
        //         b: '5121861755',
        //         e: 'trade',
        //         m: false,
        //         p: '3870.25',
        //         q: '0.0008',
        //         s: 'ETH_USDC_PERP',
        //         t: 10782547
        //     }
        //
        Object market = optionalArgs != null && optionalArgs.length > 0 ? optionalArgs[0] : null;
        Long microseconds = this.safeInteger(trade, "E", 0);
        Long timestamp = this.parseToInt(Helpers.divide(microseconds, 1000));
        String id = this.safeString(trade, "t");
        String marketId = this.safeString(trade, "s");
        market = this.safeMarket(marketId, market);
        Object isBuyerMaker = this.safeBool(trade, "m");
        String side = null;
        String takerOrMaker = null;
        if (!java.util.Objects.equals(isBuyerMaker, null))
        {
            takerOrMaker = "taker";
            if (Helpers.isTrue(isBuyerMaker))
            {
                side = "sell";
            } else
            {
                side = "buy";
            }
        }
        String price = this.safeString(trade, "p");
        String amount = this.safeString(trade, "q");
        String orderId = null;
        if (java.util.Objects.equals(side, "buy"))
        {
            orderId = this.safeString(trade, "b");
        } else
        {
            orderId = this.safeString(trade, "a");
        }
        final Object finalMarket = market;
        final Object finalOrderId = orderId;
        final Object finalSide = side;
        final Object finalTakerOrMaker = takerOrMaker;
        return this.safeTrade(new HashMap<String, Object>() {{
            put( "info", trade );
            put( "id", id );
            put( "timestamp", timestamp );
            put( "datetime", Backpack.this.iso8601(timestamp) );
            put( "symbol", ((Map<String, Object>)finalMarket).get("symbol") );
            put( "order", finalOrderId );
            put( "type", null );
            put( "side", finalSide );
            put( "takerOrMaker", finalTakerOrMaker );
            put( "price", price );
            put( "amount", amount );
            put( "cost", null );
            put( "fee", new HashMap<String, Object>() {{
                put( "currency", null );
                put( "cost", null );
            }} );
        }}, market);
    }

    /**
     * @method
     * @name backpack#watchOrderBook
     * @description watches information on open orders with bid (buy) and ask (sell) prices, volumes and other data
     * @see https://docs.backpack.exchange/#tag/Streams/Public/Depth
     * @param {string} symbol unified symbol of the market to fetch the order book for
     * @param {int} [limit] the maximum amount of order book entries to return
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} A dictionary of [order book structures]{@link https://docs.ccxt.com/?id=order-book-structure}
     */
    public CompletableFuture<OrderBook> watchOrderBook(String symbol, Object... optionalArgs)
    {

        return BaseExchange.supplyAsync(() -> {

            Object limit = optionalArgs != null && optionalArgs.length > 0 ? optionalArgs[0] : null;
            Object parameters = optionalArgs != null && optionalArgs.length > 1 ? optionalArgs[1] : new HashMap<String, Object>() {{}};
            return (this.watchOrderBookForSymbols((Object)(new ArrayList<Object>(Arrays.asList(symbol))), (Object)(limit), (Object)(parameters))).join();
        }).thenApply(OrderBook::new);

    }

    /**
     * @method
     * @name backpack#watchOrderBookForSymbols
     * @see https://docs.backpack.exchange/#tag/Streams/Public/Depth
     * @description watches information on open orders with bid (buy) and ask (sell) prices, volumes and other data
     * @param {string[]} symbols unified array of symbols
     * @param {int} [limit] the maximum amount of order book entries to return
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @param {string} [params.method] either '/market/level2' or '/spotMarket/level2Depth5' or '/spotMarket/level2Depth50' default is '/market/level2'
     * @returns {object} an [order book structure]{@link https://docs.ccxt.com/?id=order-book-structure}
     */
    public CompletableFuture<OrderBook> watchOrderBookForSymbols(Object symbols2, Object... optionalArgs)
    {
        final Object symbols3 = symbols2;
        return BaseExchange.supplyAsync(() -> {
            Object symbols = symbols3;
            Object limit = optionalArgs != null && optionalArgs.length > 0 ? optionalArgs[0] : null;
            Object parameters = optionalArgs != null && optionalArgs.length > 1 ? optionalArgs[1] : new HashMap<String, Object>() {{}};
            if (java.util.Objects.equals(this.markets, null))
            {
                (this.loadMarkets()).join();
            }
            symbols = this.marketSymbols(symbols, null, false);
            Object marketIds = this.marketIds(symbols);
            Object messageHashes = new ArrayList<Object>(Arrays.asList());
            Object topics = new ArrayList<Object>(Arrays.asList());
            for (var i = 0; i < ((List<?>)symbols).size(); i++)
            {
                Object symbol = Helpers.GetValue(symbols, i);
                ((List<Object>)messageHashes).add(("orderbook:" + symbol));
                Object marketId = Helpers.GetValue(marketIds, i);
                String topic = ("depth." + marketId);
                ((List<Object>)topics).add(topic);
            }
            Object orderbook = (this.watchPublic(topics, messageHashes, parameters)).join();
            return Helpers.callDynamically(orderbook, "limit", new Object[]{});  // todo check if limit is needed
        }).thenApply(OrderBook::new);

    }

    /**
     * @method
     * @name backpack#unWatchOrderBook
     * @description unWatches information on open orders with bid (buy) and ask (sell) prices, volumes and other data
     * @param {string} symbol unified array of symbols
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} A dictionary of [order book structures]{@link https://docs.ccxt.com/?id=order-book-structure}
     */
    public CompletableFuture<Object> unWatchOrderBook(Object symbol, Object... optionalArgs)
    {

        return BaseExchange.supplyAsync(() -> {

            Object parameters = optionalArgs != null && optionalArgs.length > 0 ? optionalArgs[0] : new HashMap<String, Object>() {{}};
            return (this.unWatchOrderBookForSymbols(new ArrayList<Object>(Arrays.asList(symbol)), parameters)).join();
        });

    }

    /**
     * @method
     * @name backpack#unWatchOrderBookForSymbols
     * @description unWatches information on open orders with bid (buy) and ask (sell) prices, volumes and other data
     * @param {string[]} symbols unified array of symbols
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @param {string} [params.method] either '/market/level2' or '/spotMarket/level2Depth5' or '/spotMarket/level2Depth50' default is '/market/level2'
     * @returns {object} A dictionary of [order book structures]{@link https://docs.ccxt.com/?id=order-book-structure}
     */
    public CompletableFuture<Object> unWatchOrderBookForSymbols(Object symbols2, Object... optionalArgs)
    {
        final Object symbols3 = symbols2;
        return BaseExchange.supplyAsync(() -> {
            Object symbols = symbols3;
            Object parameters = optionalArgs != null && optionalArgs.length > 0 ? optionalArgs[0] : new HashMap<String, Object>() {{}};
            if (java.util.Objects.equals(this.markets, null))
            {
                (this.loadMarkets()).join();
            }
            symbols = this.marketSymbols(symbols, null, false);
            Object marketIds = this.marketIds(symbols);
            Object messageHashes = new ArrayList<Object>(Arrays.asList());
            Object topics = new ArrayList<Object>(Arrays.asList());
            for (var i = 0; i < ((List<?>)symbols).size(); i++)
            {
                Object symbol = Helpers.GetValue(symbols, i);
                ((List<Object>)messageHashes).add(("unsubscribe:orderbook:" + symbol));
                Object marketId = Helpers.GetValue(marketIds, i);
                String topic = ("depth." + marketId);
                ((List<Object>)topics).add(topic);
            }
            return (this.watchPublic(topics, messageHashes, parameters, true)).join();
        });

    }

    public void handleOrderBook(Client client, Object message)
    {
        //
        // initial snapshot is fetched with ccxt's fetchOrderBook
        // the feed does not include a snapshot, just the deltas
        //
        //     {
        //         "data": {
        //             "E": "1754903057555305",
        //             "T": "1754903057554352",
        //             "U": 1345937436,
        //             "a": [],
        //             "b": [],
        //             "e": "depth",
        //             "s": "ETH_USDC",
        //             "u": 1345937436
        //         },
        //         "stream": "depth.ETH_USDC"
        //     }
        //
        Object data = this.safeDict(message, "data", new HashMap<String, Object>() {{}});
        String marketId = this.safeString(data, "s");
        String symbol = this.safeSymbol(marketId);
        if (!(((Map<?, ?>)this.orderbooks).containsKey(symbol)))
        {
            Helpers.addElementToObject(this.orderbooks, symbol, this.orderBook());
        }
        io.github.ccxt.ws.WsOrderBook storedOrderBook = (io.github.ccxt.ws.WsOrderBook) Helpers.GetValue(this.orderbooks, symbol);
        Long nonce = this.safeInteger(storedOrderBook, "nonce");
        Long deltaNonce = this.safeInteger(data, "u");
        String messageHash = ("orderbook:" + symbol);
        if (java.util.Objects.equals(nonce, null))
        {
            Object cacheLength = ((List<?>)((List<Object>)Helpers.GetValue(storedOrderBook, "cache"))).size();
            // the rest API is very delayed
            // usually it takes at least 9 deltas to resolve
            Object snapshotDelay = this.handleOption("watchOrderBook", "snapshotDelay", 10);
            if (Helpers.isEqual(cacheLength, snapshotDelay))
            {
                this.spawn(() -> { try { this.loadOrderBook(client, messageHash, symbol, null, new HashMap<String, Object>() {{}}); } catch(Exception _e) { throw new RuntimeException(_e); } });
            }
            ((List<Object>)((List<Object>)Helpers.GetValue(storedOrderBook, "cache"))).add(data);
            return;
        } else if ((!java.util.Objects.equals(deltaNonce, null)) && (Helpers.isGreaterThan(nonce, deltaNonce)))
        {
            return;
        }
        this.handleDelta(storedOrderBook, data);
        client.resolve(storedOrderBook, messageHash);
    }

    public void handleDelta(Object orderbook, Object delta)
    {
        Long timestamp = this.parseToInt(Helpers.divide(this.safeInteger(delta, "T", 0), 1000));
        Helpers.addElementToObject(orderbook, "timestamp", timestamp);
        Helpers.addElementToObject(orderbook, "datetime", this.iso8601(timestamp));
        Helpers.addElementToObject(orderbook, "nonce", this.safeInteger(delta, "u"));
        List<Object> bids = (List<Object>) this.safeList(delta, "b", new ArrayList<Object>(Arrays.asList()));
        List<Object> asks = (List<Object>) this.safeList(delta, "a", new ArrayList<Object>(Arrays.asList()));
        Object storedBids = Helpers.GetValue(orderbook, "bids");
        Object storedAsks = Helpers.GetValue(orderbook, "asks");
        this.handleBidAsks(storedBids, bids);
        this.handleBidAsks(storedAsks, asks);
    }

    public void handleBidAsks(Object bookSide, Object bidAsks)
    {
        for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(bidAsks)); i++)
        {
            Object bidAsk = this.parseOrderBookBidAsk(Helpers.GetValue(bidAsks, i));
            Helpers.callDynamically(bookSide, "storeArray", new Object[]{bidAsk});
        }
    }

    public Object getCacheIndex(Object orderbook, Object cache)
    {
        //
        // {"E":"1759338824897386","T":"1759338824895616","U":1662976171,"a":[],"b":[["117357.0","0.00000"]],"e":"depth","s":"BTC_USDC_PERP","u":1662976171}
        Object firstDelta = this.safeDict(cache, 0);
        Long nonce = this.safeInteger(orderbook, "nonce");
        Long firstDeltaStart = this.safeInteger(firstDelta, "U");
        if (java.util.Objects.equals(nonce, null))
        {
            return Helpers.getArrayLength(cache);
        }
        if (java.util.Objects.equals(firstDeltaStart, null))
        {
            return Helpers.opNeg(1);
        }
        if (Helpers.isLessThan(nonce, Helpers.subtract(firstDeltaStart, 1)))
        {
            return Helpers.opNeg(1);
        }
        for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(cache)); i++)
        {
            Object delta = Helpers.GetValue(cache, i);
            Long deltaStart = this.safeInteger(delta, "U");
            Long deltaEnd = this.safeInteger(delta, "u");
            if ((java.util.Objects.equals(deltaStart, null)) || (java.util.Objects.equals(deltaEnd, null)))
            {
                return Helpers.getArrayLength(cache);
            }
            if ((Helpers.isGreaterThanOrEqual(nonce, Helpers.subtract(deltaStart, 1))) && (Helpers.isLessThan(nonce, deltaEnd)))
            {
                return i;
            }
        }
        return Helpers.getArrayLength(cache);
    }

    /**
     * @method
     * @name backpack#watchOrders
     * @description watches information on multiple orders made by the user
     * @see https://docs.backpack.exchange/#tag/Streams/Private/Order-update
     * @param {string} [symbol] unified market symbol of the market orders were made in
     * @param {int} [since] the earliest time in ms to fetch orders for
     * @param {int} [limit] the maximum number of order structures to retrieve
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object[]} a list of [order structures]{@link https://docs.ccxt.com/?id=order-structure}
     */
    public CompletableFuture<List<Order>> watchOrders(Object... optionalArgs)
    {

        return BaseExchange.supplyAsync(() -> {

            Object symbol = optionalArgs != null && optionalArgs.length > 0 ? optionalArgs[0] : null;
            Object since = optionalArgs != null && optionalArgs.length > 1 ? optionalArgs[1] : null;
            Object limit = optionalArgs != null && optionalArgs.length > 2 ? optionalArgs[2] : null;
            Object parameters = optionalArgs != null && optionalArgs.length > 3 ? optionalArgs[3] : new HashMap<String, Object>() {{}};
            if (java.util.Objects.equals(this.markets, null))
            {
                (this.loadMarkets()).join();
            }
            Object market = null;
            if (!java.util.Objects.equals(symbol, null))
            {
                market = this.market(symbol);
                symbol = ((Map<String, Object>)market).get("symbol");
            }
            String topic = "account.orderUpdate";
            String messageHash = "orders";
            if (!java.util.Objects.equals(market, null))
            {
                topic = Helpers.add("account.orderUpdate.", ((Map<String, Object>)market).get("id"));
                messageHash = Helpers.add("orders:", symbol);
            }
            Object orders = (this.watchPrivate(new ArrayList<Object>(Arrays.asList(topic)), new ArrayList<Object>(Arrays.asList(messageHash)), parameters)).join();
            if (Helpers.isTrue(this.newUpdates))
            {
                limit = Helpers.callDynamically(orders, "getLimit", new Object[]{symbol, limit});
            }
            return this.filterBySymbolSinceLimit(orders, symbol, since, limit, true);
        }).thenApply(res -> ((List<?>) res).stream().map(Order::new).collect(Collectors.toList()));

    }

    /**
     * @method
     * @name backpack#unWatchOrders
     * @description unWatches information on multiple orders made by the user
     * @see https://docs.backpack.exchange/#tag/Streams/Private/Order-update
     * @param {string} [symbol] unified market symbol of the market orders were made in
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object[]} a list of [order structures]{@link https://docs.ccxt.com/?id=order-structure}
     */
    public CompletableFuture<Object> unWatchOrders(Object... optionalArgs)
    {

        return BaseExchange.supplyAsync(() -> {

            Object symbol = optionalArgs != null && optionalArgs.length > 0 ? optionalArgs[0] : null;
            Object parameters = optionalArgs != null && optionalArgs.length > 1 ? optionalArgs[1] : new HashMap<String, Object>() {{}};
            if (java.util.Objects.equals(this.markets, null))
            {
                (this.loadMarkets()).join();
            }
            Object market = null;
            if (!java.util.Objects.equals(symbol, null))
            {
                market = this.market(symbol);
                symbol = ((Map<String, Object>)market).get("symbol");
            }
            String topic = "account.orderUpdate";
            String messageHash = "unsubscribe:orders";
            if (!java.util.Objects.equals(market, null))
            {
                topic = Helpers.add("account.orderUpdate.", ((Map<String, Object>)market).get("id"));
                messageHash = Helpers.add("unsubscribe:orders:", symbol);
            }
            return (this.watchPrivate(new ArrayList<Object>(Arrays.asList(topic)), new ArrayList<Object>(Arrays.asList(messageHash)), parameters, true)).join();
        });

    }

    public void handleOrder(Client client, Object message)
    {
        //
        //     {
        //         data: {
        //             E: '1754939110175843',
        //             O: 'USER',
        //             Q: '4.30',
        //             S: 'Bid',
        //             T: '1754939110174703',
        //             V: 'RejectTaker',
        //             X: 'New',
        //             Z: '0',
        //             e: 'orderAccepted',
        //             f: 'GTC',
        //             i: '5406825793',
        //             o: 'MARKET',
        //             q: '0.0010',
        //             r: false,
        //             s: 'ETH_USDC',
        //             t: null,
        //             z: '0'
        //         },
        //         stream: 'account.orderUpdate.ETH_USDC'
        //     }
        //
        String messageHash = "orders";
        Object data = this.safeDict(message, "data", new HashMap<String, Object>() {{}});
        String marketId = this.safeString(data, "s");
        Map<String, Object> market = (Map<String, Object>) this.safeMarket(marketId);
        Object symbol = ((Map<String, Object>)market).get("symbol");
        Object parsed = this.parseWsOrder(data, market);
        Object orders = this.orders;
        if (java.util.Objects.equals(orders, null))
        {
            Long limit = this.safeInteger(this.options, "ordersLimit", 1000);
            orders = new ArrayCache.ArrayCacheBySymbolById(((Number)limit).intValue());
            this.orders = orders;
        }
        Helpers.callDynamically(orders, "append", new Object[]{parsed});
        client.resolve(orders, messageHash);
        Object symbolSpecificMessageHash = ((messageHash + ":") + symbol);
        client.resolve(orders, symbolSpecificMessageHash);
    }

    public Object parseWsOrder(Object order, Object... optionalArgs)
    {
        //
        //     {
        //         E: '1754939110175879',
        //         L: '4299.16',
        //         N: 'ETH',
        //         O: 'USER',
        //         Q: '4.30',
        //         S: 'Bid',
        //         T: '1754939110174705',
        //         V: 'RejectTaker',
        //         X: 'Filled',
        //         Z: '4.299160',
        //         e: 'orderFill',
        //         f: 'GTC',
        //         i: '5406825793',
        //         l: '0.0010',
        //         m: false,
        //         n: '0.000001',
        //         o: 'MARKET',
        //         q: '0.0010',
        //         r: false,
        //         s: 'ETH_USDC',
        //         t: 2888471,
        //         z: '0.0010'
        //     },
        //
        Object market = optionalArgs != null && optionalArgs.length > 0 ? optionalArgs[0] : null;
        String id = this.safeString(order, "i");
        String clientOrderId = this.safeString(order, "c");
        Long microseconds = this.safeInteger(order, "E", 0);
        Long timestamp = this.parseToInt(Helpers.divide(microseconds, 1000));
        String status = this.parseWsOrderStatus(this.safeString(order, "X"), market);
        String marketId = this.safeString(order, "s");
        market = this.safeMarket(marketId, market);
        Object symbol = ((Map<String, Object>)market).get("symbol");
        String type = this.safeStringLower(order, "o");
        String timeInForce = this.safeString(order, "f");
        String side = this.parseWsOrderSide(this.safeString(order, "S"));
        String price = this.safeString(order, "p");
        Double triggerPrice = this.safeNumber(order, "P");
        String amount = this.safeString(order, "q");
        String cost = this.safeString(order, "Z");
        String filled = this.safeString(order, "l");
        Object fee = null;
        String feeCurrency = this.safeString(order, "N");
        if (!java.util.Objects.equals(feeCurrency, null))
        {
            final Object finalFeeCurrency = feeCurrency;
            fee = new HashMap<String, Object>() {{
                put( "currency", finalFeeCurrency );
                put( "cost", null );
            }};
        }
        final Object finalFee = fee;
        return this.safeOrder(new HashMap<String, Object>() {{
            put( "id", id );
            put( "clientOrderId", clientOrderId );
            put( "timestamp", timestamp );
            put( "datetime", Backpack.this.iso8601(timestamp) );
            put( "lastTradeTimestamp", null );
            put( "status", status );
            put( "symbol", symbol );
            put( "type", type );
            put( "timeInForce", timeInForce );
            put( "side", side );
            put( "price", price );
            put( "stopPrice", null );
            put( "triggerPrice", triggerPrice );
            put( "average", null );
            put( "amount", amount );
            put( "cost", cost );
            put( "filled", filled );
            put( "remaining", null );
            put( "fee", finalFee );
            put( "trades", null );
            put( "info", order );
        }}, market);
    }

    public String parseWsOrderStatus(Object status, Object... optionalArgs)
    {
        Object market = optionalArgs != null && optionalArgs.length > 0 ? optionalArgs[0] : null;
        Map<String, Object> statuses = new HashMap<String, Object>() {{
            put( "New", "open" );
            put( "Filled", "closed" );
            put( "Cancelled", "canceled" );
            put( "Expired", "canceled" );
            put( "PartiallyFilled", "open" );
            put( "TriggerPending", "open" );
            put( "TriggerFailed", "rejected" );
        }};
        return this.safeString(statuses, status, status);
    }

    public String parseWsOrderSide(Object side)
    {
        Map<String, Object> sides = new HashMap<String, Object>() {{
            put( "Bid", "buy" );
            put( "Ask", "sell" );
        }};
        return this.safeString(sides, side, side);
    }

    /**
     * @method
     * @name backpack#watchPositions
     * @description watch all open positions
     * @see https://docs.backpack.exchange/#tag/Streams/Private/Position-update
     * @param {string[]} [symbols] list of unified market symbols to watch positions for
     * @param {int} [since] the earliest time in ms to fetch positions for
     * @param {int} [limit] the maximum number of positions to retrieve
     * @param {object} params extra parameters specific to the exchange API endpoint
     * @returns {object[]} a list of [position structure]{@link https://docs.ccxt.com/en/latest/manual.html#position-structure}
     */
    public CompletableFuture<List<Position>> watchPositions(Object... optionalArgs)
    {

        return BaseExchange.supplyAsync(() -> {

            Object symbols = optionalArgs != null && optionalArgs.length > 0 ? optionalArgs[0] : null;
            Object since = optionalArgs != null && optionalArgs.length > 1 ? optionalArgs[1] : null;
            Object limit = optionalArgs != null && optionalArgs.length > 2 ? optionalArgs[2] : null;
            Object parameters = optionalArgs != null && optionalArgs.length > 3 ? optionalArgs[3] : new HashMap<String, Object>() {{}};
            if (java.util.Objects.equals(this.markets, null))
            {
                (this.loadMarkets()).join();
            }
            symbols = this.marketSymbols(symbols);
            Object messageHashes = new ArrayList<Object>(Arrays.asList());
            Object topics = new ArrayList<Object>(Arrays.asList());
            if (!java.util.Objects.equals(symbols, null))
            {
                for (var i = 0; i < ((List<?>)symbols).size(); i++)
                {
                    Object symbol = Helpers.GetValue(symbols, i);
                    ((List<Object>)messageHashes).add((("positions" + ":") + symbol));
                    ((List<Object>)topics).add(Helpers.add("account.positionUpdate.", this.marketId(symbol)));
                }
            } else
            {
                ((List<Object>)messageHashes).add("positions");
                ((List<Object>)topics).add("account.positionUpdate");
            }
            Object positions = (this.watchPrivate(topics, messageHashes, parameters)).join();
            if (Helpers.isTrue(this.newUpdates))
            {
                return positions;
            }
            return this.filterBySymbolsSinceLimit(this.positions, symbols, since, limit, true);
        }).thenApply(res -> ((List<?>) res).stream().map(Position::new).collect(Collectors.toList()));

    }

    /**
     * @method
     * @name backpack#unWatchPositions
     * @description unWatches from the stream channel
     * @see https://docs.backpack.exchange/#tag/Streams/Private/Position-update
     * @param {string[]} [symbols] list of unified market symbols to watch positions for
     * @param {object} params extra parameters specific to the exchange API endpoint
     * @returns {object[]} a list of [position structure]{@link https://docs.ccxt.com/en/latest/manual.html#position-structure}
     */
    public CompletableFuture<Object> unWatchPositions(Object... optionalArgs)
    {

        return BaseExchange.supplyAsync(() -> {

            Object symbols = optionalArgs != null && optionalArgs.length > 0 ? optionalArgs[0] : null;
            Object parameters = optionalArgs != null && optionalArgs.length > 1 ? optionalArgs[1] : new HashMap<String, Object>() {{}};
            if (java.util.Objects.equals(this.markets, null))
            {
                (this.loadMarkets()).join();
            }
            symbols = this.marketSymbols(symbols);
            Object messageHashes = new ArrayList<Object>(Arrays.asList());
            Object topics = new ArrayList<Object>(Arrays.asList());
            if (!java.util.Objects.equals(symbols, null))
            {
                for (var i = 0; i < ((List<?>)symbols).size(); i++)
                {
                    Object symbol = Helpers.GetValue(symbols, i);
                    ((List<Object>)messageHashes).add((("unsubscribe:positions" + ":") + symbol));
                    ((List<Object>)topics).add(Helpers.add("account.positionUpdate.", this.marketId(symbol)));
                }
            } else
            {
                ((List<Object>)messageHashes).add("unsubscribe:positions");
                ((List<Object>)topics).add("account.positionUpdate");
            }
            return (this.watchPrivate(topics, messageHashes, parameters, true)).join();
        });

    }

    public void handlePositions(Client client, Object message)
    {
        //
        //     {
        //         data: {
        //             B: '4236.36',
        //             E: '1754943862040486',
        //             M: '4235.88650933',
        //             P: '-0.000473',
        //             Q: '0.0010',
        //             T: '1754943862040487',
        //             b: '4238.479',
        //             e: 'positionOpened',
        //             f: '0.02',
        //             i: 5411399049,
        //             l: '0',
        //             m: '0.0125',
        //             n: '4.23588650933',
        //             p: '0',
        //             q: '0.0010',
        //             s: 'ETH_USDC_PERP'
        //         },
        //         stream: 'account.positionUpdate'
        //     }
        //
        String messageHash = "positions";
        Object data = this.safeDict(message, "data", new HashMap<String, Object>() {{}});
        if (java.util.Objects.equals(this.positions, null))
        {
            this.positions = new ArrayCache.ArrayCacheBySymbolById();
        }
        Object cache = this.positions;
        Object parsedPosition = this.parseWsPosition(data);
        Long microseconds = this.safeInteger(data, "E", 0);
        Long timestamp = this.parseToInt(Helpers.divide(microseconds, 1000));
        Helpers.addElementToObject(parsedPosition, "timestamp", timestamp);
        Helpers.addElementToObject(parsedPosition, "datetime", this.iso8601(timestamp));
        Helpers.callDynamically(cache, "append", new Object[]{parsedPosition});
        Object symbolSpecificMessageHash = Helpers.add((messageHash + ":"), ((Map<String, Object>)parsedPosition).get("symbol"));
        client.resolve(new ArrayList<Object>(Arrays.asList(parsedPosition)), messageHash);
        client.resolve(new ArrayList<Object>(Arrays.asList(parsedPosition)), symbolSpecificMessageHash);
    }

    public Object parseWsPosition(Object position, Object... optionalArgs)
    {
        //
        //     {
        //         B: '4236.36',
        //         E: '1754943862040486',
        //         M: '4235.88650933',
        //         P: '-0.000473',
        //         Q: '0.0010',
        //         T: '1754943862040487',
        //         b: '4238.479',
        //         e: 'positionOpened',
        //         f: '0.02',
        //         i: 5411399049,
        //         l: '0',
        //         m: '0.0125',
        //         n: '4.23588650933',
        //         p: '0',
        //         q: '0.0010',
        //         s: 'ETH_USDC_PERP'
        //     }
        //
        Object market = optionalArgs != null && optionalArgs.length > 0 ? optionalArgs[0] : null;
        String id = this.safeString(position, "i");
        String marketId = this.safeString(position, "s");
        Map<String, Object> marketResolved = (Map<String, Object>) this.safeMarket(marketId, market);
        market = marketResolved;
        Object symbol = ((Map<String, Object>)marketResolved).get("symbol");
        String notional = this.safeString(position, "n");
        String liquidationPrice = this.safeString(position, "l");
        String entryPrice = this.safeString(position, "b");
        String realizedPnl = this.safeString(position, "p");
        String unrealisedPnl = this.safeString(position, "P");
        String contracts = this.safeString(position, "Q");
        String markPrice = this.safeString(position, "M");
        Double netQuantity = this.safeNumber(position, "q");
        Boolean hedged = false;
        String side = "long";
        if (!java.util.Objects.equals(netQuantity, null))
        {
            if (Helpers.isLessThan(netQuantity, 0))
            {
                side = "short";
            }
        } else
        {
            hedged = null;
            side = null;
        }
        Long microseconds = this.safeInteger(position, "E", 0);
        Long timestamp = this.parseToInt(Helpers.divide(microseconds, 1000));
        Double maintenanceMarginPercentage = this.safeNumber(position, "m");
        Double initialMarginPercentage = this.safeNumber(position, "f");
        final Object finalSide = side;
        final Object finalHedged = hedged;
        return this.safePosition(new HashMap<String, Object>() {{
            put( "info", position );
            put( "id", id );
            put( "symbol", symbol );
            put( "notional", notional );
            put( "marginMode", null );
            put( "liquidationPrice", liquidationPrice );
            put( "entryPrice", entryPrice );
            put( "realizedPnl", realizedPnl );
            put( "unrealizedPnl", unrealisedPnl );
            put( "percentage", null );
            put( "contracts", contracts );
            put( "contractSize", null );
            put( "markPrice", markPrice );
            put( "side", finalSide );
            put( "hedged", finalHedged );
            put( "timestamp", timestamp );
            put( "datetime", Backpack.this.iso8601(timestamp) );
            put( "maintenanceMargin", null );
            put( "maintenanceMarginPercentage", maintenanceMarginPercentage );
            put( "collateral", null );
            put( "initialMargin", null );
            put( "initialMarginPercentage", initialMarginPercentage );
            put( "leverage", null );
            put( "marginRatio", null );
        }});
    }

    public void handleMessage(Client client, Object message)
    {
        if (!java.util.Objects.equals(this.handleErrorMessage(client, message), true))
        {
            return;
        }
        Object data = this.safeDict(message, "data");
        String eventVar = this.safeString(data, "e");
        if (java.util.Objects.equals(eventVar, "ticker"))
        {
            this.handleTicker(client, message);
        } else if (java.util.Objects.equals(eventVar, "bookTicker"))
        {
            this.handleBidAsk(client, message);
        } else if (java.util.Objects.equals(eventVar, "kline"))
        {
            this.handleOHLCV(client, message);
        } else if (java.util.Objects.equals(eventVar, "trade"))
        {
            this.handleTrades(client, message);
        } else if (java.util.Objects.equals(eventVar, "depth"))
        {
            this.handleOrderBook(client, message);
        } else if (java.util.Objects.equals(eventVar, "orderAccepted") || java.util.Objects.equals(eventVar, "orderUpdate") || java.util.Objects.equals(eventVar, "orderFill") || java.util.Objects.equals(eventVar, "orderCancelled") || java.util.Objects.equals(eventVar, "orderExpired") || java.util.Objects.equals(eventVar, "orderModified") || java.util.Objects.equals(eventVar, "triggerPlaced") || java.util.Objects.equals(eventVar, "triggerFailed"))
        {
            this.handleOrder(client, message);
        } else if (java.util.Objects.equals(eventVar, "positionAdjusted") || java.util.Objects.equals(eventVar, "positionOpened") || java.util.Objects.equals(eventVar, "positionClosed") || java.util.Objects.equals(eventVar, "positionUpdated"))
        {
            this.handlePositions(client, message);
        }
    }

    public Object handleErrorMessage(Client client, Object message)
    {
        //
        //     {
        //         id: null,
        //         error: {
        //             code: 4006,
        //             message: 'Invalid stream'
        //         }
        //     }
        //
        Object error = this.safeDict(message, "error", new HashMap<String, Object>() {{}});
        Long code = this.safeInteger(error, "code");
        try
        {
            if (!java.util.Objects.equals(code, null))
            {
                String msg = this.safeString(error, "message");
                throw new ExchangeError((String)Helpers.add((this.id + " "), msg)) ;
            }
            return true;
        } catch(Exception e)
        {
            client.reject(e);
        }
        return true;
    }
}
