<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>ccxtbench</AssemblyName>
    <RootNamespace>ccxtbench</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ccxt/ccxt.csproj" />
  </ItemGroup>
</Project>
