name: Test application

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Install npm dependencies
      run: npm ci --include=dev
    - name: Determine modified files
      run: ./utils/init_actions.sh
    - name: Debug output
      run: |
        echo "Important files modified: ${{ env.important_modified }}"
        echo "REST files: ${{ env.rest_files }}"
        echo "WS files: ${{ env.ws_files }}"
    - name: Run only if "Important files modified" is true
      if: env.important_modified == 'true'
      run: echo "This step runs only for PRs targeting the main branch"