name: Test application

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Determine modified files
      run: |
       ./utils/check_modified_files.sh
       OUTPUT=$(./utils/check_modified_files.sh | tr -d '\n')
       echo "after output"
       IMPORTANT_MODIFIED=$(echo "$OUTPUT" | jq -r '.important_modified')
       echo "after important modified"
       REST_FILES=$(echo "$OUTPUT" | jq -r '.rest_exchanges')
       WS_FILES=$(echo "$OUTPUT" | jq -r '.ws_exchanges')
       echo "important_modified=$IMPORTANT_MODIFIED" >> $GITHUB_ENV
       echo "rest_files=$REST_FILES" >> $GITHUB_ENV
       echo "ws_files=$WS_FILES" >> $GITHUB_ENV
    - name: Debug output
      run: |
        echo "Important files modified: ${{ env.important_modified }}"
        echo "REST files: ${{ env.rest_files }}"
        echo "WS files: ${{ env.ws_files }}"
