name: Js Live Tests # ignore this file for now
on:
  workflow_run:
    workflows: ["Js"]
    types:
      - completed
permissions:
  contents: read
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
      - name: Download JS Files
        uses: actions/download-artifact@v4
        with:
          name: js-files
          path: js/
      - name: Live tests
        run: ./run-tests-simul.sh --js
