name: linux

on: 
  push:
  pull_request:
    types: [ opened, synchronize, closed, ready_for_review, review_requested ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        cxx: [g++-11]
        build_type: [Debug, Release]
        std: [20]
        
    steps:
    - uses: actions/checkout@v3

    - name: Add ubuntu mirrors
      run: |
        # Github Actions caching proxy is at times unreliable
        # see https://github.com/actions/runner-images/issues/7048
        printf 'http://azure.archive.ubuntu.com/ubuntu\tpriority:1\n' | sudo tee /etc/apt/mirrors.txt
        curl http://mirrors.ubuntu.com/mirrors.txt | sudo tee --append /etc/apt/mirrors.txt
        sudo sed -i 's~http://azure.archive.ubuntu.com/ubuntu/~mirror+file:/etc/apt/mirrors.txt~' /etc/apt/sources.list

    - name: Create Build Environment
      run: |
        sudo apt update
        ${{matrix.install}}
        sudo apt install -y cmake ninja-build libspdlog-dev libfmt-dev libhowardhinnant-date-dev nlohmann-json3-dev libboost-all-dev libssl-dev
        cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure
      working-directory: ${{runner.workspace}}/build
      env:
        CXX: ${{matrix.cxx}}
        CXXFLAGS: ${{matrix.cxxflags}}
      run: |
        cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} ${{matrix.shared}} \
              -DCMAKE_CXX_STANDARD=${{matrix.std}} \
              -GNinja \
              $GITHUB_WORKSPACE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: |        
        cmake --build . --config ${{matrix.build_type}}

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: |
        cpp/test/unit/base/test-base
        cpp/test/unit/tests
