name: Push Generated [test]

on:
  workflow_run:
    workflows:
      - "Js"
      - "Python"
      - "PHP"
      - "C#"
    types:
      - completed

jobs:
  run-on-master:
    if: github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run your script
        run: echo "All workflows succeeded. Running on master branch."
